### ISSUE TITLE
Packer crash when I deploy to azure arm - windows

### ISSUE THREAD

**Issue by CasewiseTest** [mitchellh/packer#4000] opened 2016-10-13 13:40 UTC
Packer crash when I try to deploy a VM to Azure ARM. I'm using the windows. JSON example template

- Packer version from `packer version`  packer_0.10.1_windows
 
- Debug log output  https://gist.github.com/CasewiseTest/974cb462880f1af2727a0faa78bab17f

- Template - https://gist.github.com/CasewiseTest/94cb9b30062d00ddb7e0f3ed88dfd7fc

**Comment by boumenot** [comment] 2016-10-13 16:23
This is a known issue, and has been fixed in master for quite some time.  Unfortunately, there has not been a new release of Packer containing the fix.

1. You can rebuild master, and pick up the fix.
1. I made a private build available for another user, see #3766 for details.
1. Wait for next official Packer release. I do not have an ETA on when that will be.

Dupe of #3766

**Closed by boumenot** 2016-10-13 16:23 UTC
Labels: builder/azure, crash, duplicate
