### ISSUE TITLE
Emty files with openstack builder

### ISSUE THREAD

**Issue by ldejager** [mitchellh/packer#2773] opened 2015-09-24 09:32 UTC
Noticed few key files for services came up empty when spinning up a new instance from a packer created image.

For example, calling a simple script through the provisioners to install bind and then do a systemctl status named.service.

```shell
    openstack: ::: SYSTEMCTL :::
    openstack: named.service - Berkeley Internet Name Domain (DNS)
    openstack: Loaded: loaded (/usr/lib/systemd/system/named.service; disabled)
    openstack: Active: inactive (dead)
```
As above, during the image creation it works OK, however after launching a new instance that same service is marked as masked due to an empty service file as below;

```shell
[root@test1 ~]# systemctl status named.service
named.service
   Loaded: masked (/usr/lib/systemd/system/named.service; masked)
   Active: inactive (dead)
```

```shell
[root@test1 ~]# file /usr/lib/systemd/system/named.service;
/usr/lib/systemd/system/named.service: empty
```

As a workaround, I've added a sync() call in a cleanup/validation script to flush to disk before the image creation instance is killed off. Can ensuring all files are flushed to disk perhaps be handled by packer itself?

**Comment by timbunce** [comment] 2015-10-19 15:26
I'm noticing something similar happening occasionally with amazon-ebs.

**Comment by cbednarski** [comment] 2016-01-26 04:40
Thanks for the report. I agree it would be great for packer to do this automatically.

I will need to find a creative place to put this since I don't think we ever ask you what type of OS you're using. For instance you could use openssh on windows and I'm not sure if sync does anything there (I suppose we could just call it anyway and ignore the failure).

**Comment by rickard-von-essen** [comment] 2016-01-26 10:18
This seems a bit fishy to me. When OpenStack (or EC2) shutdown the instance it will invoke an OS shutdown which will do an sync(). So this points to that your instances did not properly stop. Could you share your template you used when this happened?

**Comment by ldejager** [comment] 2016-01-26 10:29
Sure, it's been a while but I still have the template used. The version of packer used back then was `Packer v0.8.2`.

*consul.json*
```
{
  "_comment": "Consul DNS Server",

  "builders": [
    {
      "type": "openstack",
      "ssh_username": "centos",
      "ssh_pty": "true",
      "image_name": "consul_dns_centos-7_x86_64",
      "source_image": "",
      "flavor": "",
      "security_groups": "",
      "networks": ""
}
  ],
  "provisioners": [
    {
      "type": "shell",
      "scripts": [
        "scripts/bind.sh",
        "scripts/consul.sh",
        "scripts/netenv.sh",
        "scripts/validate.sh",
        "scripts/cleanup.sh"
      ],
      "execute_command": "sudo -S sh '{{ .Path }}'"
    }
  ]
}
```

*cleanup.sh*
```
#!/bin/bash

yum -y clean all
sync
```

**Comment by rickard-von-essen** [comment] 2016-01-27 22:21
@ldejager How often do this occur? I fail to reproduce this on DevStack. It would be interesting to see a debug log from when this happens and see if there is some problem with shutting down the instance etc.

**Comment by ldejager** [comment] 2016-01-28 08:27
I could reproduce this behavior pretty much on demand back in September last year, however I've just tried it again using the above template and am unable to reproduce as well.

I'll spend some time and see if I can trigger the issue.

**Comment by ldejager** [comment] 2016-02-01 08:48
I've not been able to re-produce, the problem seen may have been caused by an OpenStack specific issue back then.

Feel free to close this issue unless others are affected and can reproduce the issue to give the requested debug logs.

**Comment by rickard-von-essen** [comment] 2016-02-01 11:44
I think we close this and reopen if anyone sees it again. Most likely there where some thing outside of packer.

**Closed by rickard-von-essen** 2016-02-01 11:44 UTC
Labels: core, enhancement

**Comment by melon-babak** [comment] 2016-02-24 10:45
I'm having this issue with Rackspace.

I notice packer says `openstack: OpenStack cluster doesn't support stop, skipping...`.

Related: #1462

**Comment by rickard-von-essen** [comment] 2016-02-24 11:06
@melon-babak Could you run:
```
nova list-extensions
```
against Rackspace and gist the output.

**Comment by melon-babak** [comment] 2016-02-24 12:06
I ran `nova list-extensions` here's ouptut:

```
➜  rackspace-server-images nova list-extensions
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for identity.api.rackspacecloud.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
+--------------------------+-------------------------------------------------------------+---------------------------------+----------------------+
| Name                     | Summary                                                     | Alias                           | Updated              |
+--------------------------+-------------------------------------------------------------+---------------------------------+----------------------+
| DiskConfig               | Disk Management Extension.                                  | OS-DCF                          | 2011-09-27T00:00:00Z |
| ImageSize                | Adds image size to image listings.                          | OS-EXT-IMG-SIZE                 | 2013-02-19T00:00:00Z |
| ExtendedStatus           | Extended Status support.                                    | OS-EXT-STS                      | 2011-11-03T00:00:00Z |
| FlavorExtraData          | Provide additional data for flavors.                        | OS-FLV-EXT-DATA                 | 2011-09-14T00:00:00Z |
| FlavorWithExtraSpecs     | Provide extra specs along with flavor data.                 | OS-FLV-WITH-EXT-SPECS           | 2013-08-01T00:00:00Z |
| SchedulerHints           | Pass arbitrary key/value pairs to the scheduler.            | OS-SCH-HNT                      | 2011-07-19T00:00:00Z |
| PublicIPZoneID           | Adds public_ip_zone_id on Servers.                          | RAX-PUBLIC-IP-ZONE-ID           | 2013-04-29T00:00:00Z |
| IPAssociations           | IP associations on an instance.                             | ip_associations                 | 2015-05-08T00:00:00Z |
| AdminActions             | Enable admin-only server actions...                         | os-admin-actions                | 2011-09-20T00:00:00Z |
| BlockDeviceMappingV2Boot | Allow boot with the new BDM data format.                    | os-block-device-mapping-v2-boot | 2013-07-08T00:00:00Z |
| ConfigDrive              | Config Drive Extension.                                     | os-config-drive                 | 2012-07-16T00:00:00Z |
| Consoles                 | Interactive Console support.                                | os-consoles                     | 2011-12-23T00:00:00Z |
| ExtendedRescueWithImage  | Allow the user to specify the image to use for rescue.      | os-extended-rescue-with-image   | 2014-01-04T00:00:00Z |
| FlavorExtraSpecs         | Instance type (flavor) extra specs.                         | os-flavor-extra-specs           | 2011-06-23T00:00:00Z |
| FlavorRxtx               | Support to show the rxtx status of a flavor.                | os-flavor-rxtx                  | 2012-08-29T00:00:00Z |
| FlavorSwap               | Support to show the swap status of a flavor.                | os-flavor-swap                  | 2012-08-29T00:00:00Z |
| InstanceActions          | View a log of actions and events taken on an instance.      | os-instance-actions             | 2013-02-08T00:00:00Z |
| Keypairs                 | Keypair Support.                                            | os-keypairs                     | 2011-08-08T00:00:00Z |
| OSNetworksV2             | Admin-only Network Management Extension.                    | os-networksv2                   | 2012-03-07T14:46:43Z |
| Quotas                   | Quotas management support.                                  | os-quota-sets                   | 2011-08-08T00:00:00Z |
| Rescue                   | Instance rescue mode.                                       | os-rescue                       | 2011-08-18T00:00:00Z |
| UsedLimits               | Provide data on limited resources that are being used.      | os-used-limits                  | 2012-07-13T00:00:00Z |
| UserData                 | Add user_data to the Create Server v1.1 API.                | os-user-data                    | 2012-08-07T00:00:00Z |
| VirtualInterfacesV2      | Virtual interface support.                                  | os-virtual-interfacesv2         | 2011-08-17T00:00:00Z |
| Volumes                  | Volumes support.                                            | os-volumes                      | 2011-03-25T00:00:00Z |
| ScheduledImages          | Enables automatic scheduled images to be taken of a server. | rax-si-image-schedule           | 2013-03-20T00:00:00Z |
+--------------------------+-------------------------------------------------------------+---------------------------------+----------------------+
```

Openstack environment variables:

```
OS_USERNAME=[redacted]
OS_PASSWORD=[redacted]
OS_IDENTITY_API_VERSION=2.0
OS_AUTH_URL=https://identity.api.rackspacecloud.com/v2.0/
OS_TENANT_ID=[redacted]
OS_REGION_NAME=DFW
OS_NO_CACHE=1
```

**Comment by DavidGoodwin** [comment] 2017-02-01 06:25
I think I experienced this issue with Rackspace yesterday. Using packer 0.12.2 generating an Ubuntu Trusty image (ext4).

Specifically, files recently added by ansible would appear corrupt on a new VM based off the generated image. The files would _appear_ present within the VM - right size and permissions  however they were empty and if you cat -v'ed them you'd just see a lot of ^@^@^@^@...

I even added a sha1 check within the ansible playbook to check the file was copied correctly - which passed. 

Anyway, the fix was seemingly either chance or from adding a shell provisioner which called sync to run after the normal rackspace one.

```
      .....
    {
      "only": [ "rackspace" ],
      "inline" : [ "echo 'Running shell provisioner'", "sudo sync" ],
      "type": "shell"
    }, ....
```

Hopefully this helps someone else experiencing this 'feature' on rackspace in the future.
