### ISSUE TITLE
chef client for windows host

### ISSUE THREAD

**Issue by kenny-opennix** [mitchellh/packer#3879] opened 2016-09-12 18:05 UTC
Hi,everyone.
I try to configure chef client provisioner for windows box.
My config

```
 {
      "type": "chef-client",
      "server_url": "https://ex.com:443",
      "prevent_sudo": true,
      "guest_os_type":"windows",
      "staging_directory":"c:/windows/temp/packer-chef-client",
      "validation_key_path" : "config/chef-validator.pem",
      "validation_client_name" : "chef-validator",
      "run_list" : "recipe[ex::windows]"
    },
```

When i try to build box, i get

```
  virtualbox-iso: Installing Chef...
    virtualbox-iso: powershell.exe -Command "(New-Object System.Net.WebClient).DownloadFile('http://chef.io/chef/install.msi', 'C:\Windows\Temp\chef.msi');Start-Process 'msiexec' -ArgumentList '/qb /i C:\Windows\Temp\chef.msi' -NoNewWindow -Wait"
    virtualbox-iso: sh: -c: line 0: syntax error near unexpected token `('
    virtualbox-iso: sh: -c: line 0: `/bin/sh.exe -c "powershell.exe -Command "(New-Object System.Net.WebClient).DownloadFile('http://chef.io/chef/install.msi', 'C:\Windows\Temp\chef.msi');Start-Process 'msiexec' -ArgumentList '/qb /i C:\Windows\Temp\chef.msi' -NoNewWindow -Wait"'
    virtualbox-iso: Creating directory: c:/windows/temp/packer-chef-client
```

And building box doesn't finish
What i do wrong?
I build vagrant box and archive.

**Comment by rickard-von-essen** [comment] 2016-09-12 19:30
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

**Comment by kenny-opennix** [comment] 2016-09-12 19:33
```
D:\project\windows\packer\packer-prepod>packer -v
0.10.1
```
I try to build box on Windows 10, in debug mode i doesn't see any error.

**Comment by rickard-von-essen** [comment] 2016-09-13 20:38
Closing until you provide the [information requested in the comment above](https://github.com/mitchellh/packer/issues/3879#issuecomment-246463597).

**Comment by kenny-opennix** [comment] 2016-09-14 08:09
My template https://gist.github.com/kenny-opennix/aff674b8711fa24a28ee13689d8d5ecf
My log https://gist.github.com/kenny-opennix/1571d038377f46c6c8a91c0d81ba5d67
Packer version 0.10.1
Os 

> D:\>ver
> 
> Microsoft Windows [Version 10.0.10586]

**Comment by rickard-von-essen** [comment] 2016-09-14 19:31
I think this is a bug with using `"communicator": "ssh"` and `"guest_os_type": "windows"` in the chef-server provisioner. There are several similar bugs and some debate on how to resolve them. 

I think a workaround is to switch to `"communicator": "winrm"` or try `"guest_os_type": "unix"`.

PR's or suggestions how to fix this are welcome.

**Comment by kenny-opennix** [comment] 2016-09-14 20:15
If i set "communicator": "winrm" all work fine, and one moment on osx that's problem does not reproduce.

On windows os i try reproduce problem with winrm.

**Comment by kenny-opennix** [comment] 2016-09-16 09:00
Update: on Windows platform, i do next steps:
1) Switch communicator to winrm
2) Installation successful complete, and i see running chef client command windows like

>   virtualbox-iso: Executing Chef: c:/opscode/chef/bin/chef-client.bat --no-color -c C:/Windows/Temp/packer-chef-client/client.rb -j C:/Windows/Temp/packer-chef-client/first-boot.json

, but cleanup command unix-like 

> [INFO] command 'knife node delete packer-57db90ef-2992-db3f-fa42-5ca7f27a6d29 -y -c C:/Windows/Temp/packer-chef-client/knife.rb'

I think if use chocolatey for installation chef client and "prevent_sudo": true options can help me.
example of install command
`     "install_command": "powershell.exe -Command \"Start-Process 'C:\\ProgramData\\chocolatey\\bin\\choco.exe' -ArgumentList 'install chef-client -f -y' -NoNewWindow -Wait\"",
`

**Comment by rickard-von-essen** [comment] 2016-09-16 09:11
I think that has been fixed in #3622 which is merged into master but unreleased. Try to build from master, it's easy, see CONTRIBUTE.md .

**Comment by kenny-opennix** [comment] 2016-09-16 10:16
I reproduce problem from master. 
We build master repos via jenkins every night.

**Comment by mwhooker** [comment] 2016-10-14 03:05
Closing on the assumption that this is fixed. please re-open if it's still an issue

**Comment by mwhooker** [comment] 2016-10-14 03:14
@kenny-opennix just to double check, you've built packer from master and cleanup still looks like `[INFO] command 'knife node delete packer-57db90ef-2992-db3f-fa42-5ca7f27a6d29 -y -c C:/Windows/Temp/packer-chef-client/knife.rb'`?

**Comment by kenny-opennix** [comment] 2016-10-14 09:03
On windows box, try execute command knife, without windows path, look like chef provisioner try execute unix like command.
But in source code command for windows system is 
`		knifeCommand:   "c:/opscode/chef/bin/knife.bat {{.Args}} {{.Flags}}",
`

**Comment by mwhooker** [comment] 2017-01-29 03:16
I think I see the problem

` C:\Users\Iurii_Medvedev\AppData\Roaming\packer.d\plugins\packer-builder-virtualbox-windows-ovf.exe`

I think you have an old version of packer installed. Follow this note from the download page and try again, please.

> Note: Packer now ships as a single binary. When upgrading from Packer < 0.9.0, you will need to remove the old packer-* plugins from your installation path.

Also, please open a new ticket if you continue to run in to this. Thanks!

**Closed by mwhooker** 2017-01-29 03:16 UTC
Labels: bug, provisioner/chef
