### ISSUE TITLE
Problems with creating OpenSUSE templates on virtual machine

### ISSUE THREAD

**Issue by mgluhic10** [mitchellh/packer#3577] opened 2016-05-26 08:28 UTC
Packer Version: 0.10.1, 0.8.6, 0.10.0 (i have tried multiple versions)
Host platform: ESXI, Ubuntu-14.04-server

HI,
I am currently building templates for OpenSUSE and I have some strange problems. When I build it on my Windows machine, everything works perfect. I am trying to build same configuration on Virtual linux Ubuntu-14.04 machine, wich is hosted on ESXI (building virtual machine on virtual machine) there is a problems. I have enabled everything what I could. Nested virtualization and everything else and I still get strange problems. Just to notify, I also have .json file for Ubuntu, and everything for Ubuntu works perfect(on same virtual machine, wich means that I don't  have a problem with nested virtualization and or something other). Creating virtualbox, vmware iso's and uploading on VCenter for Ubuntu is without problem, for OpenSUSE there is a lot of problems. Do you have any suggestions what I can do?

Also, I am using virtualbox-5.0 and vmware-worstation12.

I will post and logs and everything what I get from logs and etc.

https://gist.github.com/mgluhic10/3fc5bce3d147b56d17733cfd12cb47a1

PACKER_LOG=1 for Virtualbox: 

https://gist.github.com/mgluhic10/e2a4e227b5155e5909f6987dc57f4dbc

And after this at location : /VirtualBox VMs/packer-virtualbox-iso-1464247128/Logs#
I find this:

https://gist.github.com/mgluhic10/04ed1d46a9d3d29e184d3fa2030f6894

And for OpenSuse-vmware-iso also getting problems...This is PACKER_LOG=1 for vmware-iso - OpenSUSE

https://gist.github.com/mgluhic10/978541f938f2445815c3e502ad59d52d

and this is other log:

https://gist.github.com/mgluhic10/216bf50bcae38973c7ca3f49c97f58c2

And just to say once more, this configuration works perfect on my machine, but on Linux Virtual machine which is hosted on ESXI is not working.

Also, building Ubuntu on same machine works fine.

Do you have any suggestion, please help me?

If you need any additional info I will give it to you.

Thanks,

Milan

**Comment by cbednarski** [comment] 2016-05-26 21:53
There's a lot of info here! I'm not sure I can eyeball everything, but I did notice this looks a bit odd:

```
        "ethernet0.networkName": "VMnet8 ",
        "ethernet0.virtualDev": "vmxnet3",
```

Did you intend for this to be on two networks? It looks to me like it is trying to get a lease on `vmnet8` but this is failing for some reason. I wonder if the configuration above causes a conflict.

**Comment by mgluhic10** [comment] 2016-05-27 08:28
Hi,
Thank you for fast response! I really appreciate that!
Unfortunately that didn't help me. :(

My installation stucks at the moment when needs to read boot_command:

      "boot_command": [
        "<esc><enter><wait>",
        " linux netsetup=dhcp<wait>",
        " lang=en_US autoyast=floppy://http/preseed_opensuse.xml<wait>",
        " textmode=1<wait>",
        "<enter><wait>"
      ],
And something there is problem on both situations. And for example, sometimes when installation pass on virtualbox:
boot_command
"boot_command": [
        "<esc><enter><wait>",
        **"   linux netdevice=enp0s3 netsetup=dhcp<wait>",**
        " install=http://download.opensuse.org/distribution/13.2/repo/oss/ insecure=1<wait>",
        " lang=en_US autoyast=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed_opensuse.xml<wait>",
        " textmode=1<wait>",
        "<enter><wait>"
      ],
If you see I have puted 3 spaces before linux netdevice....

If I remove that spaces, then boot command starts to read:  inux netdevice=enp0...etc

Do you have any more suggestions?

Thanks!

**Comment by cbednarski** [comment] 2016-06-10 21:37
> If you see I have puted 3 spaces before linux netdevice....

Oh this is odd. Can you try running this interactively and see what happens? Maybe you need to add another `<wait>`, or perhaps there is a bug in the installer. I have run into several installer bugs in Ubuntu upgrades that required sending different boot commands.

The boot_command is very sensitive to timing issues caused by and high CPU or a slow network because it sends individual keyup / keydown events to the VM.

In VMware there is a 100ms delay between key events. In VirtualBox this works a bit differently. But in both cases if your host has very high CPU contention, or if you are running the build remotely over a high-latency network, it is possible for the boot command keypresses to be lost or timed improperly.

For the 3 spaces problem I would suggest trying another `<wait>` or two. Each time it will wait 1 second.

If there are other operations that may take longer (fetching from the network, checking fastest mirrors) you will need to add worst-case wait time so packer will wait for the longest duration that it might take. For example if there is a fastest mirror step that times out after 30 seconds, add 35 seconds worth of wait time. There are some other wait commands to help wit longer durations. IIRC there is also `<wait5>` and `<wait10>`.

**Comment by mwhooker** [comment] 2017-02-11 01:00
Going to close this since it looks like it was abandoned. feel free to comment here if this is still an issue and I'll reopen

**Closed by mwhooker** 2017-02-11 01:00 UTC
Labels: builder/vmware-esxi, question, waiting-reply
