### ISSUE TITLE
Provisioner, Builders (more) should have 'sudo_flags' settable item

### ISSUE THREAD

**Issue by tb3088** [mitchellh/packer#4457] opened 2017-01-25 23:25 UTC
Recently there was traffic about removing '-E' (#4088), a complication with sudo in CoreOS in Asure (#4245) and I'm sure there are many more. In my case I'm using the Puppet Masterless provisioner and wouldn't you know it '-E' is hard-coded into provisioner.go and it's set to '-i' in amazon/instance/builder.go.

This situation desperately cries out for a settable variable (call it sudo_flags) that is available across all provisioners, scripts, builders, pre/post processors, that if set within context replaces whatever the default might be. I shouldn't have to dig thru the source and resort to re-defining "execute_command" just to change a few characters.

I would have suggested using the variable .Sudo to represent the sudo command with all it's options but unfortunately that's been appropriated as a Boolean to inject the command into templates.

In my case I need it to be '-i' or '-iE' because the first provisioner (a script) installed Puppet from PuppetLabs which gets dropped into /opt/puppetlabs and also helpfully adds a file to /etc/profile.d for adding elements to PATH. But since the shell started by Packer over SSH precedes this activity only '-i' will remedy the situation.

Right now I'm hacking puppet_bin_dir to point to the installed binaries (which is again brittle, what if I had installed the RPM to a different PREFIX?) and I'm tempted to embed 'sudo <flags> /opt/puppetlabs/bin' as the value of "puppet_bin_dir" and turn off the built in sudo with "prevent_sudo". But at this point it's probably better to just redefine "execute_commend" even though it shouldn't be necessary to resort to a sledgehammer to do a tack hammer's job.

Additionally since the Puppet Provisioners lack "environment_vars" support (aside, why the heck isn't this available across all provisioners in the first place?!?!) things like HTTP_PROXY settings won't get picked up without "-i", which results in obvious connectivity problems during the run.

**Comment by cbednarski** [comment] 2017-02-10 22:01
Thanks for the report. It sounds like you are bumping into some frustrating rough edges. I'm sorry you are running into trouble here! I want to clear up a bit of background here because I have noticed a theme across several other issues. You are (I think):

1. Using a Windows host
2. Provisioning with Puppet
3. Provisioning CoreOS
4. Building on Azure

Each of these features is supported in packer but has some caveats. For example, Azure support is still quite new, puppet support is maintained by the community, and none of the maintainers develops packer on Windows / cygwin. As a result I think you're hitting a lot of snags in some areas that are not as well-exercised as other parts of packer, and, in puppet's case, not supported by our core maintainers.

Let me address this issue specifically. If I understand this correctly, there are several different things going on here:

1. You are requesting a global feature called `sudo_flags`.
2. You have mentioned`-E` is hard-coded into puppet (is this a bug report?)
3. You have mentioned `-i` is hard-coded into the EC2 instance builder (is this a bug report?)
4. You are requesting a specific fix for your puppet use-case (not sure what this is)
5. You have mentioned that you have applied _some_ workaround involving `puppet_bin_dir` but I don't understand what change you actually made or why
6. You have mentioned something about `environment_vars` (is this a duplicate of https://github.com/mitchellh/packer/issues/4458 ?)
7. You have mentioned something about `HTTP_PROXY` (is this a bug report?)
8. You have mentioned that there is an existing packer feature (`execute_command`) that can solve your problem, but you don't want to use it.

In response to the big picture view: If `execute_command` solves your problem, please use it -- that's why it's there! I used this feature last week to change sudo interaction in a build I am working on. Packer defaults to a happy path but given the variation in linux distros and environments we can't get it right every time. It's perfectly reasonable to set `execute_command` to a non-default value.

To broadly address the other items you mentioned, please keep issues specific to your use case(s) and refrain from hyperbole so we can focus on bugs that need to fixed, bugs that have workarounds, and features that are currently supported but maybe lack ergonomics. Also, please bear in mind that packer maintainers have to load in _a lot_ of context for the broad range of use-cases our users run into, and we may not be experts in your particular use-cases.

**Comment by mwhooker** [comment] 2017-02-21 19:09
We're going to stick with how it is for now, since it's complicated to support multiple OS's like the way the issue suggests.

**Closed by mwhooker** 2017-02-21 19:09 UTC
Labels: enhancement, provisioner/puppet, provisioner/shell, thinking

**Comment by tb3088** [comment] 2017-02-22 03:04
> Provisioning CoreOS
> Building on Azure

Nope to both.

> You are requesting a global feature called sudo_flags
I'm requesting that SUDO be re-thought (toss the Boolean and use it as the actual 'sudo with args' string. Currently it's a complete hodge podge depending on what a particular provisioner has been hard-coded to do. (points no. 2 and 3 just illustrate the lack of consistency)

Point 7 is just another common situation where one can need '-i' to Sudo to make the provisioner work.
Point 8, I shouldn't have to resort to rewriting a big, command to get the obvious execution flags to work. 

Having to rewrite 'execute_command' is the wrong answer. Every time. Unless you're doing something completely off the wall. It means the program was not fully thought through. Yes, I understand it has become the go-to solution, because the implementation is so narrow-minded it can't handle common-sense flexibility. The point is to fix the brittleness, not keep hand-waving it away.

Yes, I know this is closed. When I get some free time I'll work up some patches to apply features across ALL provisioners, ideally by using a suitable GoLang "inheritance" construct so we don't constantly run into this provisioner has this capability but these others don't, or the same exact thing has different names across provisioners, and for no good reason. Currently every provisioner does things a different way and there is rampant code copying instead of defining a 'parent class' that provides the same interfaces across the board and little/no duplication of code. If a new capability is introduced into the parent, then automatically all children inherit it instead of today's "let me remember to copy these 20 lines to 10 different provisioner.go files"

**Comment by tb3088** [comment] 2017-02-22 03:20
Since it's probably too late to undo the mistake that is .Sudo as boolean, I suggest Sudo_command as an analogue to Execute_command so that we arrive at:
`Execute_Command := {{if .Sudo}}.Sudo_Command{{end}} ... `
I think this merits not being closed, but considered for future build. I'm just going to open a PR against this anyway...

**Comment by kaladin-storm** [comment] 2017-02-27 23:31
I am having a similar issue. I am trying to build a CoreOS Azure VHD and provisioning with puppet. My template is as follows:

```
{
  "builders": [
    {
      "type": "azure-arm",
      "os_type": "Linux",
      "image_publisher": "OpenLogic",
      "image_offer": "CentOS",
      "image_sku": "7.2",
      "image_version": "latest",
       ....
      "ssh_timeout": "10000s",
      "ssh_pty": "true",
      "ssh_username": "centos",
      ....
    }
  ],
  "provisioners": [
    {
      "type": "puppet-masterless",
      "execute_command": "{{.FacterVars}} PATH=$PATH:/opt/puppetlabs/bin puppet apply --verbose --detailed-exitcodes --modulepath={{.ModulePath}} {{.ManifestFile}}",
      "facter": {
        "provisioner": "{{user `provisioner`}}"
      },
      "module_paths": [
        "manifests/modules",
        "vendor-modules"
      ],
      "manifest_file": "manifests/base.pp"
    },
    ....
  ]
}
```

But I am getting the following error from puppet provisioner: 
`Error: Failed to apply catalog: The yum provider can only be used as root`

@tb3088 How did you manage to run puppet as sudo?

**Comment by rickard-von-essen** [comment] 2017-02-28 05:29
@kaladin-storm Don't override [execute_command] (https://www.packer.io/docs/provisioners/puppet-masterless.html#execute_command)  or at least don't remove the parts that you need from the default.
