### ISSUE TITLE
Initialising instance on AWS with no keypair getting API error

### ISSUE THREAD

**Issue by m1keil** [mitchellh/packer#2754] opened 2015-09-18 15:28 UTC
I'm trying to start an instance in AWS with no `ssh_keypair_name` but **with** `ssh_key_path` defined.
(The scenario is that the AMI already has a pre-embedded key pair which is not part of the aws keystore).

Getting this:
```
Running Packer..
1442589607,,ui,say,nightly_virtualbox_build output will be in this color.
1442589607,,ui,say,
1442589607,,ui,say,==> nightly_virtualbox_build: Prevalidating AMI Name...
1442589608,,ui,say,==> nightly_virtualbox_build: Inspecting the source AMI...
1442589608,,ui,say,==> nightly_virtualbox_build: Creating temporary security group for this instance...
1442589609,,ui,say,==> nightly_virtualbox_build: Authorizing access to port 22 the temporary security group...
1442589609,,ui,say,==> nightly_virtualbox_build: Launching a source AWS instance...
1442589610,,ui,error,==> nightly_virtualbox_build: Error launching source instance: InvalidParameterValue: Invalid value '' for keyPairNames. It should not be blank\n==> nightly_virtualbox_build: 	status code: 400%!(PACKER_COMMA) request id: []
1442589610,,ui,say,==> nightly_virtualbox_build: No AMIs to cleanup
1442589610,,ui,say,==> nightly_virtualbox_build: Deleting temporary security group...
1442589610,,ui,error,Build 'nightly_virtualbox_build' errored: Error launching source instance: InvalidParameterValue: Invalid value '' for keyPairNames. It should not be blank\n	status code: 400%!(PACKER_COMMA) request id: []
1442589610,,error-count,1
1442589610,,ui,error,\n==> Some builds didn't complete successfully and had errors:
1442589610,nightly_virtualbox_build,error,Error launching source instance: InvalidParameterValue: Invalid value '' for keyPairNames. It should not be blank\n	status code: 400%!(PACKER_COMMA) request id: []
1442589610,,ui,error,--> nightly_virtualbox_build: Error launching source instance: InvalidParameterValue: Invalid value '' for keyPairNames. It should not be blank\n	status code: 400%!(PACKER_COMMA) request id: []
1442589610,,ui,say,\n==> Builds finished but no artifacts were created.
```

This started in 0.8.x branch. Works in 0.7.x without any problem.
This is similar to #2440

**Comment by jantman** [comment] 2015-10-06 03:01
I'm having this issue as well. I have ``ssh_username`` and ``ssh_private_key_file`` set in the builder config.

**Comment by dave2** [comment] 2015-11-16 00:43
Also getting this. The user being used inside the AMI to perform provisioning is already created with an authorized pubkey (and the AMI will not accept the externally-defined key anyway).

**Comment by cbednarski** [comment] 2016-01-26 04:17
Thanks for the report. I think this is a duplicate of https://github.com/mitchellh/packer/issues/2301

**Comment by m1keil** [comment] 2016-02-06 22:23
Yep. Sorry about that, couldn't find anything similar when I opened it but it seems like it is in fact a duplicate. You can close this one and use #2301.

**Closed** 2016-02-06 22:24 UTC
Labels: bug, builder/amazon
