### ISSUE TITLE
Packer skips part of my provisioner and continues on with the second provisioner

### ISSUE THREAD

**Issue by pporada-gl** [mitchellh/packer#3920] opened 2016-09-23 18:04 UTC
```
Packer v0.10.2
Linux laptappy 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I am building CentOS 7.2 AWS EC2 instances. I have a script that simply runs `yum update -y`. Part of this update includes a package, `microcode_ctl-2.1-12.el7_2.1.x86_64`. During this specific package update, the shell will hang for ~5 minutes on a t2.micro that Packer spins up. When this happens, yum will keep running, but Packer will continue on to the next provisioner. Notice below how the system is at 55/136 updates, but the next provisioner starts. Why?

```
    amazon-ebs:   Installing : kernel-3.10.0-327.36.1.el7.x86_64                         53/136
    amazon-ebs:   Updating   : systemd-sysv-219-19.el7_2.13.x86_64                       54/136
    amazon-ebs:   Updating   : 2:microcode_ctl-2.1-12.el7_2.1.x86_64                     55/136
==> amazon-ebs: Provisioning with shell script: scripts/install_packages.sh
    amazon-ebs: + echo '+) Updating system packages'
    amazon-ebs: +) Updating system packages
    amazon-ebs: + yum makecache
    amazon-ebs: Loaded plugins: fastestmirror
    amazon-ebs: Existing lock /var/run/yum.pid: another copy is running as pid 5758.
    amazon-ebs: Another app is currently holding the yum lock; waiting for it to exit...
    amazon-ebs: The other application is: yum
    amazon-ebs: Memory : 103 M RSS (421 MB VSZ)
    amazon-ebs: Started: Fri Sep 23 17:50:27 2016 - 03:05 ago
    amazon-ebs: State  : Sleeping, pid: 5758
    amazon-ebs: Another app is currently holding the yum lock; waiting for it to exit...
    amazon-ebs: The other application is: yum
```

**Comment by mwhooker** [comment] 2016-09-23 18:14
hi @pporada-gl 

thanks for the report. By any chance do you have a minimal packer file that will reproduce this? thanks!

**Comment by pporada-gl** [comment] 2016-09-23 18:27
Here you go. You'll need to fill in some of the variables at the bottom of the template.

https://gist.github.com/pporada-gl/d85789230657777636e9d9e39d549e4a

**Comment by rickard-von-essen** [comment] 2016-09-23 20:46
What if you add `-e` to your script?

**Comment by pporada-gl** [comment] 2016-09-25 22:20
@rickard-von-essen You mean like `set -e` to the top of the shell script?

**Comment by rickard-von-essen** [comment] 2016-09-26 04:06
Yes

**Comment by pporada-gl** [comment] 2016-09-26 14:07
A `set -e` will just cause the script to error out if something returns non-0. I'm not seeing how this will fix the problem I'm encountering.

I did run my build again with `set -e` at the top of my bash scripts but am encountering the same issue of Packer skipping the remainder of the first script.
```
    amazon-ebs:   Installing : kernel-3.10.0-327.36.1.el7.x86_64                         53/136
    amazon-ebs:   Updating   : systemd-sysv-219-19.el7_2.13.x86_64                       54/136
    amazon-ebs:   Updating   : 2:microcode_ctl-2.1-12.el7_2.1.x86_64                     55/136

==> amazon-ebs: Provisioning with shell script: scripts/install_packages.sh
    amazon-ebs: + set -e
    amazon-ebs: + echo '+) Updating system packages'
    amazon-ebs: +) Updating system packages
    amazon-ebs: + yum update -y
    amazon-ebs: Loaded plugins: fastestmirror
    amazon-ebs: Existing lock /var/run/yum.pid: another copy is running as pid 5617.
    amazon-ebs: Another app is currently holding the yum lock; waiting for it to exit...
    amazon-ebs: The other application is: yum
    amazon-ebs: Memory : 104 M RSS (423 MB VSZ)
    amazon-ebs: Started: Mon Sep 26 13:39:28 2016 - 03:17 ago
    amazon-ebs: State  : Sleeping, pid: 5617
    amazon-ebs: Another app is currently holding the yum lock; waiting for it to exit...
    amazon-ebs: The other application is: yum
    amazon-ebs: Memory : 104 M RSS (423 MB VSZ)
    amazon-ebs: Started: Mon Sep 26 13:39:28 2016 - 03:19 ago
    amazon-ebs: State  : Sleeping, pid: 5617
    amazon-ebs: Another app is currently holding the yum lock; waiting for it to exit...
    amazon-ebs: The other application is: yum
```

**Comment by rickard-von-essen** [comment] 2016-09-26 15:12
Please [gist](https://gist.github.com/) a full debug log from `PACKER_LOG=1 packer build template.json`.
I want to ensure that you have a correct install of Packer. We had some bugs around concurrency, but they should all be fixed. 

And my comment about `set - e` was maybe a bit premature but your script could partly silently fail. 

Do you have any info about the centos ami you are using, does it have any interest changes for reproducing this, such as auto yum update?

**Comment by rickard-von-essen** [comment] 2016-09-30 11:11
I've done some more testing and I have two conclusions:

1) I can reproduce this and there is something fishy going on here.
2) Adding `set -e` at the top of the script and the error goes away, so that is the solution to your problem. I'm not really sure how to explain way.

**Comment by rickard-von-essen** [comment] 2016-09-30 11:11
Actually this code here looks fishy
https://github.com/mitchellh/packer/blob/master/communicator/ssh/communicator.go#L121

**Comment by dfairhurst** [comment] 2016-09-30 15:27
In my case I use set -e and I still have the issue that the script seems to die/hang during a 'yum install' and packer assumes success and continues with the next script.

**Comment by rickard-von-essen** [comment] 2016-10-02 10:19
I have a hard time reproducing this reliably.

If you are comfortable building from source it would be awesome if you could build from master with the patch bellow applied.

Then run with `PACKER_LOG=1 packer ...` and report back if you get `SSH-DEBUG` in your log when you hit the problem.

---

```patch
diff --git a/communicator/ssh/communicator.go b/communicator/ssh/communicator.go
index faeb412..a0f5097 100644
--- a/communicator/ssh/communicator.go
+++ b/communicator/ssh/communicator.go
@@ -121,6 +121,8 @@ func (c *comm) Start(cmd *packer.RemoteCmd) (err error) {
 			exitErr, ok := err.(*ssh.ExitError)
 			if ok {
 				exitStatus = exitErr.ExitStatus()
+			} else {
+				log.Printf("SSH-DEBUG: got err: %s", err.Error())
 			}
 		}
```

**Comment by dfairhurst** [comment] 2016-10-03 14:51
I have compiled with this change and will wait for a reoccurrence of the issue

**Comment by rickard-von-essen** [comment] 2016-10-03 15:10
:+1: Looking forward to it!

**Comment by pporada-gl** [comment] 2016-10-04 14:25
@rickard-von-essen 
I've reproduced the issue with your added logging.
```
2016/10/04 10:21:57 ui:     amazon-ebs: Cleanup    : nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64              134/136
    amazon-ebs: Cleanup    : nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64              134/136
2016/10/04 10:21:57 ui:     amazon-ebs: Cleanup    : glibc-2.17-106.el7_2.4.x86_64                            135/136
    amazon-ebs: Cleanup    : glibc-2.17-106.el7_2.4.x86_64                            135/136
2016/10/04 10:21:57 ui:     amazon-ebs: Cleanup    : tzdata-2016a-1.el7.noarch                                136/136
    amazon-ebs: Cleanup    : tzdata-2016a-1.el7.noarch                                136/136
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 SSH-DEBUG: got err: wait: remote command exited without exit status or exit signal
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 remote command exited with '0': sudo -E -S sh '/tmp/script_834.sh'
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 [INFO] RPC endpoint: Communicator ended with: 0
2016/10/04 10:22:48 [INFO] 0 bytes written for 'stderr'
2016/10/04 10:22:48 [INFO] RPC client: Communicator ended with: 0
2016/10/04 10:22:48 [INFO] 136675 bytes written for 'stdout'
2016/10/04 10:22:48 [INFO] RPC endpoint: Communicator ended with: 0
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 [INFO] RPC client: Communicator ended with: 0
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 [INFO] 136675 bytes written for 'stdout'
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 [INFO] 0 bytes written for 'stderr'
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 opening new ssh session
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 ssh session open error: 'read tcp 10.11.13.42:42240->52.90.47.243:22: read: connection timed out', attempting reconnect
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 reconnecting to TCP connection for SSH
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 handshaking with SSH
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 handshake complete!
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 opening new ssh session
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 [INFO] agent forwarding enabled
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 starting remote command: rm -f /tmp/script_834.sh
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 remote command exited with '0': rm -f /tmp/script_834.sh
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 [INFO] RPC endpoint: Communicator ended with: 0
2016/10/04 10:22:48 [INFO] RPC client: Communicator ended with: 0
2016/10/04 10:22:48 [INFO] RPC endpoint: Communicator ended with: 0
2016/10/04 10:22:48 packer: 2016/10/04 10:22:48 [INFO] RPC client: Communicator ended with: 0
2016/10/04 10:22:48 ui: ==> amazon-ebs: Provisioning with shell script: scripts/updates.sh
==> amazon-ebs: Provisioning with shell script: scripts/updates.sh
```

**Comment by rickard-von-essen** [comment] 2016-10-04 15:06
That is great! That shows there is an failure case that we don't handle
properly. The ssh connection is closed without a proper disconnect, that
should result in an error and the build should be aborted.

I wonder why you get disconnected? Do you have unreliable connection
between the packer host and the EC2?

Ping @mwhooker this should be fixed before the next release, but the fix is
trivial unless there is any way of recover the connection.

**Comment by pporada-gl** [comment] 2016-10-04 15:08
The connection from my office to EC2 is stable. I'll do some work and put packer inside my vpc and report back if I hit the same issue. This will take me some time because of $BACKLOG. You know how that goes.

**Comment by mwhooker** [comment] 2016-10-05 19:12
It looks like the newest version of the ssh library behaves differently.

```
// If the remote server does not send an exit status, an error of type
// *ExitMissingError is returned. If the command completes
// unsuccessfully or is interrupted by a signal, the error is of type
// *ExitError. Other error types may be returned for I/O problems.
```
https://github.com/golang/crypto/blob/master/ssh/session.go#L285

If we update the library we can catch `ExitMissingError` errors and fix this, however it does still say that `Other error types may be returned for I/O problems.` so I think we should catch all types of errors regardless.

**Comment by dfairhurst** [comment] 2016-10-05 20:34
Seems to be a different issue I have.  Seems the ssh connection is lost during the script and the problem ignored.  The connection cannot be regained for 8 seconds afterwards, but no SSH-DEBUG log was logged.  Packer then continues with the next script.  I will continue looking around this code.  I fear it may be by design to handle 'reboot && sleep' scripts...

**Comment by rickard-von-essen** [comment] 2016-10-05 20:57
@dfairhurst That seems weird, if you have the patch above and gets disconnected there are only two options, either you get the debug print out or you get an exitcode back from ssh. Can you gist a log? And maybe a minimal config to reproduce the error with.

**Comment by mwhooker** [comment] 2016-10-06 01:23
@pporada-gl would you mind testing https://github.com/mitchellh/packer/pull/3966 to see if you get clearer error messages? I'm not sure we can seamlessly reestablish the connection with the remote server just yet, but this should at least prevent packer from stalling out, and clearly show what's going on.

**Comment by pporada-gl** [comment] 2016-10-06 14:02
@mwhooker 
Packer is not completing successfully on the sshupdate branch
```
Packer v0.11.0.dev (286b7836fada507be90b3dd5f66ec2362ecf2652)
```

It will run through most of my first script up until the point where it used to jump to the 2nd script.
```
    amazon-ebs:   Updating   : systemd-sysv-219-19.el7_2.13.x86_64                       54/136
2016/10/06 09:58:41 ui:     amazon-ebs:   Updating   : 2:microcode_ctl-2.1-12.el7_2.1.x86_64                     55/136
    amazon-ebs:   Updating   : 2:microcode_ctl-2.1-12.el7_2.1.x86_64                     55/136
2016/10/06 09:59:46 packer: 2016/10/06 09:59:46 wait: remote command exited without exit status or exit signal
2016/10/06 09:59:46 packer: 2016/10/06 09:59:46 [INFO] RPC endpoint: Communicator ended with: -1
2016/10/06 09:59:46 [INFO] 106570 bytes written for 'stdout'
2016/10/06 09:59:46 [INFO] 0 bytes written for 'stderr'
2016/10/06 09:59:46 [INFO] RPC client: Communicator ended with: -1
2016/10/06 09:59:46 [INFO] RPC endpoint: Communicator ended with: -1
2016/10/06 09:59:46 packer: 2016/10/06 09:59:46 [INFO] RPC client: Communicator ended with: -1
2016/10/06 09:59:46 packer: 2016/10/06 09:59:46 [INFO] 106570 bytes written for 'stdout'
2016/10/06 09:59:46 packer: 2016/10/06 09:59:46 [INFO] 0 bytes written for 'stderr'
2016/10/06 09:59:46 ui: ==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Terminating the source AWS instance...
2016/10/06 09:59:46 packer: 2016/10/06 09:59:46 Waiting for state to become: terminated
2016/10/06 09:59:46 packer: 2016/10/06 09:59:46 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
2016/10/06 10:00:53 ui: ==> amazon-ebs: No AMIs to cleanup
==> amazon-ebs: No AMIs to cleanup
2016/10/06 10:00:53 ui: ==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary security group...
2016/10/06 10:00:53 ui error: Build 'amazon-ebs' errored: Script exited with non-zero exit status: -1
2016/10/06 10:00:53 Builds completed. Waiting on interrupt barrier...
2016/10/06 10:00:53 machine readable: error-count []string{"1"}
2016/10/06 10:00:53 ui error: 
==> Some builds didn't complete successfully and had errors:
2016/10/06 10:00:53 machine readable: amazon-ebs,error []string{"Script exited with non-zero exit status: -1"}
2016/10/06 10:00:53 ui error: --> amazon-ebs: Script exited with non-zero exit status: -1
```

**Comment by rickard-von-essen** [comment] 2016-10-06 14:18
@pporada-gl That is the expected behavior since ssh gets ungracefully disconnected. Unfortunately it don't answer why that happens. It would be interesting to see if you can reproduce this with the null-builder connected to a EC2 in the same way, doing the same commands and also running a ssh client to the same EC2. 

As I see it there are three alternative explanaitions:
1) Go's ssh implementation is broken in some way.
2) The network connection is unstable. (Not very likely since you seems to reproduce this easily).
3) The CentOS 7.2 EC2 drops ssh when doing the upgrade (which it shouldn't).

I would be interesting to try to find out which of the above it is.

**Closed** 2016-10-06 19:27 UTC
Labels: bug, provisioner/shell

**Comment by mwhooker** [comment] 2016-10-06 19:47
I believe packer should have the correct behavior now. I'm also curious about why your connection is dropping. if you figure it out, it'd be great to hear why. This thread seems to say that `yum update` is known for dropping ssh connections http://centosfaq.org/centos/running-yum-update-on-remote-servers/

I think the idea that packer could notice that the connection dropped and attempt to reconnect is tricky. We don't know that the previous step completed successfully, so it seems risky to continue on like nothing happened (it seems like yum will exit when the ssh session dies). I'd be happy to discuss it more, but I think that should happen in another thread

**Comment by jcardinal** [comment] 2017-02-13 19:29
I started seeing a similar problem (a long-running provisioner using an AWS builder stops prematurely) around the same time this issue was originally posted. I'm using the latest Ubuntu 16.04 AMI as the source AMI. It seems ssh connections are dropped ~5-6 minutes after the instance first boots, including manual ssh sessions I initiate on the side when running packer in debug mode.

This behavior of ssh connections being interrupted ~5-6 minutes after a new EC2 instance boots has been very consistent for me in recent months.

I'm not sure what the root cause is, but an ugly workaround that's working for me right now is to add a `pause_before` of six minutes to my first provisioner for these AWS builders.

**Comment by fertapric** [comment] 2017-03-24 14:21
I'm experiencing the same behavior described by @jcardinal. In my case, ssh connections are dropped ~2-3 minutes after the instance boots. I'm also the latests Ubuntu 16.04 AMI.

**Comment by fertapric** [comment] 2017-03-24 16:42
**Update:**

I've made a few changes to make it work:

* I've configured SSH options `ClientAliveInterval` and `ClientAliveCountMax` on the Packer instance; and `ServerAliveInterval` and `ServerAliveCountMax` on the client (the one calling the `packer` command).
* I've also removed `reboot` from one of my scripts. It seems to be problematic https://github.com/mitchellh/packer/issues/4006

**Comment by rickard-von-essen** [comment] 2017-03-24 18:42
@fertapric FYI packer (on the client machine) ignores OpenSSH config since it uses a native go SSH implementation.

**Comment by necrolyte2** [comment] 2017-04-06 16:08
We are seeing this same issue(I think)
The timeout we are seeing seems to probably stem from `ClientAliveInterval` and `ClientAliveCountMax` being set inside the packer instance.

In our builds it is set to `300` and `0` meaning that at 5 minutes the ssh server is essentially disconnecting the client

Is there a way to pass the same setting as `ServerAliveInterval` or `ServerAliveCountMax` to to packer in the template?
