### ISSUE TITLE
why is vnc required for esxi vmware-iso ssh builder?

### ISSUE THREAD

**Issue by geoHeil** [mitchellh/packer#4514] opened 2017-02-07 18:48 UTC
Question: why is a vnc session 5900-6000 mandatory for packer to build the VM image when using the vmware-iso builder connected via SSH to an esxi server?

# edit
I am especially curious why this seems to be mandatory. Shouldn't a kickstart file work just for the purpose of installing / configuring the first basic settings?

**Comment by mwhooker** [comment] 2017-02-07 19:55
We want to make the vnc server optional, and will be happy to look at any PRs that come in for that. It's not something we're targeting for the 1.0 release, though. 

Marking this as a duplicate of https://github.com/mitchellh/packer/issues/3031

**Closed by mwhooker** 2017-02-07 19:55 UTC
Labels: builder/vmware-esxi, duplicate, question
