### ISSUE TITLE
Add virtualbox builder from a box existing in Atlas(VagrantCloud)

### ISSUE THREAD

**Issue by riywo** [mitchellh/packer#1775] opened 2014-12-17 02:57 UTC
I'd like to use Atlas public box for easy setup of vagrant on top of virtualbox.

I'm trying to use Atlas combining with development on this flow, but Packer builder for virtualbox supports only from iso or existing ovf. I don't want to consider the boot sequence etc., so I desire a builder from Atlas boxes like below:

````json
{
  "builders": [
    {
      "type": "virtualbox-atlas",
      "name": "ubuntu/trusty64"
    }
  ]
}
````

 cf. A little bit similar to #869 , but I'd like to use this builder on Atlas like type `amazon-ebs`.

----
Here is my POC for this. If this issue sounds good for you and the approach below looks fine, I'll try to write some code and make PR.

Once downloaded a box from Atlas, there is the ovf file under `~/.vagrant.d/boxes`: 

- ex.) `~/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-trusty64/14.04/virtualbox/box.ovf`

So, I tried `packer build` with a `template.json` like below and succeeded.

````json
{
  "post-processors": [
    {
      "type": "vagrant",
      "override": {
        "virtualbox": {
          "output": "my-ubuntu-trusty64-virtualbox.box"
        }
      }
    }
  ],
  "builders": [
    {
      "type": "virtualbox-ovf",
      "source_path": "~/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-trusty64/14.04/virtualbox/box.ovf",
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_wait_timeout": "30s",
      "shutdown_command": "echo 'packer' | sudo -S shutdown -P now",
      "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--memory", "512" ],
        [ "modifyvm", "{{.Name}}", "--cpus", "1" ]
      ]
    }
  ]
````

So, I guess the builder could be built by following steps:

- Download public box from Atlas
- Run build step as well as `virtualbox-ovf`

**Comment by aaronwalker** [comment] 2015-01-08 04:57
+1

**Comment by franklinkim** [comment] 2015-02-24 09:55
+1

**Comment by sethvargo** [comment] 2015-02-24 23:12
Hi there,

This is actually a duplicate of #1681. Please track that issue :smile:

**Closed by sethvargo** 2015-02-24 23:12 UTC

**Comment by cornfeedhobo** [comment] 2016-06-28 19:56
@riywo did you ever make a PR? If so, I can't find it. I would like to get this ball rolling.

p.s. I am responding here because #869 and #1681 are a mess of bad comments and +1.
