### ISSUE TITLE
Windows version of Packer can't find any builder

### ISSUE THREAD

**Issue by mheidenr** [mitchellh/packer#2315] opened 2015-06-25 13:19 UTC
When I run ```packer build minimal.json``` on my Windows 7 x64 machine it returns with
```
Failed to initialize build 'amazon-ebs': builder type not found: amazon-ebs
amazon-ebs output will be in this color.


==> Builds finished but no artifacts were created.
```

minimal.json taken from [test/fixtures/amazon-ebs/minimal.json](https://github.com/mitchellh/packer/blob/master/test/fixtures/amazon-ebs/minimal.json)

With other builders I have the same problem. (tested with windows_10.json from https://github.com/joefitzgerald/packer-windows)

Anyone who can confirm this?

**Comment by rickard-von-essen** [comment] 2015-06-25 15:22
Is the directory where you unzipped Packer on the path?

**Comment by mitchellh** [comment] 2015-06-25 15:46
Can you attach a debug log?

**Comment by daftpunk74** [comment] 2015-06-25 17:07
I was just about to file an issue on this -- I looked through the code, and it appears the windows-shell provisioner expands variables to: set "variable=value", which will not work. The syntax needs to be one of the following:
1. If the value contains spaces, it needs double quotations: set variable="some value"
2. If the value does not contain spaces, it should be: set variable=value
3. If the value contains double quotes, just use it verbatim #2 above: set variable=value

In Windows it seems if you double quote the value, you have to explicitly refer to the unquoted version %~VAR% otherwise it will include the quotes, so its probably best to distinguish whether or not quotes are necessary at all rather than to always include them.  If the user uses them, they most likely understand this, e.g. in the case of "Program Files" in a path statement.

**Comment by StefanScherer** [comment] 2015-06-26 06:06
You may install packer for Windows with Chocolatey: 

The package is going through approval, but you already can use it:

```
choco install -y packer -version 0.8.0
```

I've made a test in a vanilla Windows 7 box (ok, Chocolatey is preinstalled) with

```
choco install -y packer -version 0.8.0
choco install -y git
choco install -y virtualbox

# open a new cmd shell due to path changes for git and vboxmanage
# packer itself is already available in PATH

git clone https://github.com/joefitzgerald/packer-windows
cd packer-windows
packer build --only=virtualbox-iso windows_7.json
```

And packer starts a VirtualBox VM, so it finds all its builders etc.

**Comment by mheidenr** [comment] 2015-06-26 06:45
@rickard-von-essen I can run packer and all its modules directly from every folder
```
C:\Users\mheidenr>packer version
Packer v0.8.0

C:\Users\mheidenr>packer-builder-amazon-ebs.exe
panic: Please do not execute plugins directly. Packer will execute these for you.
[...]
```

@mitchellh debug log: https://gist.github.com/mheidenr/ec995e782fb7703b9b4d

@StefanScherer I think packer should work as expected, this workaround is not a solution

**Comment by StefanScherer** [comment] 2015-06-26 09:54
@mheidenr packer should work of course with and without the chocolatey package ;-) I just want to help.

Please provide some more information as described in https://www.packer.io/docs/other/debugging.html

```cmd
set PACKER_LOG=1
packer
```

This should output all discovered plugins. But this may not be sufficient as you reported that packer does not find any builder.

Please provide your installation, where do you have extracted the ZIP? Do you have extracted all files of the ZIP?

```cmd
where packer
where packer-builder-virtualbox-iso
```

The `packer.exe` looks for plugins side-by-side to the `packer.exe` and as well as the plugin directory %APPDATA%\packer.d.

**Comment by mheidenr** [comment] 2015-06-26 11:06
here is the packer log: https://gist.github.com/mheidenr/01d35264bede84cd3407
```
C:\>where packer
C:\Program Files\packer-0.8.0\packer.exe

C:\>where packer-builder-virtualbox-iso
C:\Program Files\packer-0.8.0\packer-builder-virtualbox-iso.exe
```

**Comment by StefanScherer** [comment] 2015-06-26 11:44
The installation directory `C:\Program Files\packer-0.8.0\` contains a space in the directory. Packer discovers all plugins in that directory. I've installed packer the same way into this directory and tried, but it also "works on my machine" ;-) So the space also isn't the problem.

Sorry, calling `packer` without args does not try to load a builder, so the gist only shows the discovering which looks promising.

Please try a packer build command eg. with the minimal.json file.

**Comment by rasa** [comment] 2015-06-28 14:59
Though packer 0.7.5 did, packer 0.8 on Windows does not respect symlinks, so
````
C:\>dir packer*
 Volume in drive C is kitsune_c
 Volume Serial Number is 5E35-563C

 Directory of C:\

06/28/2015  07:57 AM    <SYMLINKD>     packer [packer_0.8.0_windows_amd64]
````
returns `builder type not found` errors, but
````
C:\>dir packer*
 Volume in drive C is kitsune_c
 Volume Serial Number is 5E35-563C

 Directory of C:\

06/27/2015  03:29 PM    <DIR>          packer
````
doesn't.

**Comment by mitchellh** [comment] 2015-06-29 21:07
@rasa That sounds like a good bug, and might be related to this. I'm not sure.

As far as I can tell, we still don't know why some users can see plugins and some can't. Any ideas @StefanScherer? We want to fix this for 0.8.1 but it may have to wait if we can't repro it.

**Comment by cbednarski** [comment] 2015-06-29 21:15
Just a bit of speculation here: I think Program Files is a protected folder on Windows, and may have special permissions set. Does this work if you run packer from a command prompt with elevated permissions? Or does it work if you move packer to a different folder?

**Comment by StefanScherer** [comment] 2015-06-29 21:55
@mitchellh I have tried it in a Win7 box. Downloaded the packer.zip manually, extracted it into `C:\Users\vagrant\packer` directory, then created a symlink

```cmd
mklink /D "C:\Program Files\packer" C:\Users\vagrant\packer
set PATH=%PATH%;C:\Program Files\packer
```

Now it looks like the environment @rasa has:

```
C:\Users\vagrant>dir "c:\Program Files\packer*"
 Volume in drive C is Windows 7
 Volume Serial Number is B451-DD30

 Directory of c:\Program Files

29.06.2015  23:39    <SYMLINKD>     packer [C:\Users\vagrant\packer]
               0 File(s)              0 bytes
               1 Dir(s)  44.099.645.440 bytes free
```

Running packer without parameters with debug logs shows me that all plugins can be discovered:

```
C:\Users\vagrant>set PACKER_LOG=1

C:\Users\vagrant>packer
2015/06/29 23:40:40 [INFO] Packer version: 0.8.0  88e689faa22605759ee91c22bad9a5
f463fcf78a+CHANGES
2015/06/29 23:40:40 Packer Target OS/Arch: windows amd64
2015/06/29 23:40:40 Built with Go Version: go1.4.2
2015/06/29 23:40:40 [DEBUG] Discovered plugin: amazon-chroot = C:\Program Files\packer\packer-builder-amazon-chroot.exe
2015/06/29 23:40:40 [DEBUG] Discovered plugin: amazon-ebs = C:\Program Files\packer\packer-builder-amazon-ebs.exe
2015/06/29 23:40:40 [DEBUG] Discovered plugin: amazon-instance = C:\Program Files\packer\packer-builder-amazon-instance.exe
...
```

Now I took the minimal.json from https://github.com/mitchellh/packer/blob/master/test/fixtures/amazon-ebs/minimal.json and tried a `packer build minimal.json`

```
C:\Users\vagrant>packer build minimal.json
2015/06/29 23:50:15 [INFO] Packer version: 0.8.0  88e689faa22605759ee91c22bad9a5f463fcf78a+CHANGES
2015/06/29 23:50:15 Packer Target OS/Arch: windows amd64
2015/06/29 23:50:15 Built with Go Version: go1.4.2
2015/06/29 23:50:15 [DEBUG] Discovered plugin: amazon-chroot = C:\Program Files\packer\packer-builder-amazon-chroot.exe
2015/06/29 23:50:15 [DEBUG] Discovered plugin: amazon-ebs = C:\Program Files\packer\packer-builder-amazon-ebs.exe
...
2015/06/29 23:50:15 Setting cache directory: C:\Users\vagrant\packer_cache
2015/06/29 23:50:15 Loading builder: amazon-ebs
2015/06/29 23:50:15 Creating plugin client for path: C:\Program Files\packer\packer-builder-amazon-ebs.exe
2015/06/29 23:50:15 Starting plugin: C:\Program Files\packer\packer-builder-amazon-ebs.exe []string{"C:\\Program Files\\packer\\packer-builder-amazon-ebs.exe"}
2015/06/29 23:50:15 Waiting for RPC address for: C:\Program Files\packer\packer-builder-amazon-ebs.exe
2015/06/29 23:50:15 packer-builder-amazon-ebs.exe: 2015/06/29 23:50:15 Plugin minimum port: 10000
2015/06/29 23:50:15 packer-builder-amazon-ebs.exe: 2015/06/29 23:50:15 Plugin maximum port: 25000
...
==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error querying AMI: NoCredentialProviders: no valid providers in chain

==> Builds finished but no artifacts were created.
2015/06/29 23:50:15 C:\Program Files\packer\packer-builder-amazon-ebs.exe: plugin process exited
```

Of course, the build does not work as I do not provide further AWS credentials, but packer finds the builder which is in PATH in a symlinked directory.

Sorry, I can't reproduce the problem ;-)

**Comment by mitchellh** [comment] 2015-06-30 17:46
Thanks @StefanScherer. I'm going to close this since we can't get anyone to repro. I'm leaning towards what @cbednarski posited above.

**Closed by mitchellh** 2015-06-30 17:46 UTC
Labels: need-repro, waiting-reply

**Comment by lucifiel** [comment] 2015-07-25 16:08
packer doesn't work for me with the same error message.
https://gist.github.com/lucifiel/e5f139812405e4f5daed

Elevated command prompt produces same result. And i dont have any symlinks.

**Comment by cbednarski** [comment] 2015-07-30 23:45
@lucifiel I spent several hours looking into this when it was first reported and was not able to reproduce it. If you are able to provide repro sets please open a new ticket and link to this one. I understand this is frustrating, but I have to understand what's broken before I can fix it.

**Comment by lucifiel** [comment] 2015-08-11 13:37
The problem seems to be related to symbols '[' and ']' in the path. Everything worked fine when i used another dir. I will try to reproduce when i'll get to my windows machine.
