### ISSUE TITLE
azure-arm fails with InvalidApiVersionParameter: The api-version '2015-06-15' is invalid

### ISSUE THREAD

**Issue by bciceron** [mitchellh/packer#3454] opened 2016-04-19 20:42 UTC
Packer v0.10.0
azure --version
0.9.19 (node: 5.10.1)

- Host platform
MacOS X 10.11.4 

used https://github.com/mitchellh/packer/blob/master/examples/azure/ubuntu.json with my existing Azure config and credentials to bring up an Ubuntu 14.04 VM but packer build fails with:

2016/04/19 13:34:51 Starting build run: azure-arm
2016/04/19 13:34:51 Running builder: azure-arm
2016/04/19 13:34:51 ui: ==> azure-arm: Preparing builder ...
==> azure-arm: Preparing builder ...
2016/04/19 13:34:51 ui:     azure-arm: Creating Azure Resource Manager (ARM) client ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
2016/04/19 13:34:52 ui error: Build 'azure-arm' errored: storage/AccountsClient:ListKeys 400 Failure responding to request -- Original Error: azure: Service returned an error. Code="InvalidApiVersionParameter" Message="The api-version '2015-06-15' is invalid. The supported versions are '2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'." Status=400

see full listing at https://gist.github.com/bciceron/822d8b1820cce78eb5628491b2b563bf

**Comment by boumenot** [comment] 2016-04-19 20:47
I've seen this [error](https://github.com/Azure/packer-azure/issues/215) before.  It was root caused to be a user error. 

> This turned out to be a user error. The variable name specifying the storage group in the var-file did not match the variable name in the json file. Not a particularly useful error message.

Unfortunately, the error message is so vague that it makes it difficult to debug.  I have an open issue to 
try and detect this errors sooner, and give a better explanation.

Would you please verify if this is in fact the issue or not?

**Comment by bciceron** [comment] 2016-04-20 16:59
thanks @boumenot so since then i checked them and also ran with other storage group and made sure it also match what "azure storage account list" returns so i have a valid pair storage_account/resource_group_name.
But they all fail with the same error about: "The api-version '2015-06-15' is invalid".
What else should i check ?

**Comment by boumenot** [comment] 2016-04-20 17:55
Thanks for checking back.

The gist link returns a 404, but the next thing that interests me in this line.

2016/04/19 13:34:52 ui error: Build 'azure-arm' errored: storage/AccountsClient:ListKeys 400 Failure responding to request -- Original Error: azure: Service returned an error. 

The storage account must exist because that's where the builder will place Packer's output (.vhd).  Are you able to the the Azure CLI or Azure PowerShell to confirm access to the pre-existing storage account?

**Comment by bciceron** [comment] 2016-04-20 21:13
@boumenot I am able to do several things on that storage account (dev2db) from the azure cli:

$ azure storage account keys list dev2db
info:    Executing command storage account keys list
Resource group name: dev2
+ Getting storage account keys
data:    Primary: aaaaaaaaaaaaaaaaaaaaaaaa
data:    Secondary: bbbbbbbbbbbbbbbbbbbbbbb
info:    storage account keys list command OK

$ azure storage account connectionstring show dev2db
azure storage account connectionstring show dev2db
info:    Executing command storage account connectionstring show
Resource group name: dev2
+ Getting storage account keys
data:    connectionstring: XXXXXX
info:    storage account connectionstring show command OK

$ export AZURE_STORAGE_CONNECTION_STRING=XXXXXX

$ azure storage share list
info:    Executing command storage share list
+ Getting storage shares
info:    No share found
info:    storage share list command OK

**Comment by boumenot** [comment] 2016-04-20 21:56
Would you please update the gist with the error information.

Does the resource group of the storage correspond with the location specified in the packer template JSON?

**Comment by bciceron** [comment] 2016-04-20 22:16
@boumenot yes it is (dev2db in the resource dev2), see https://gist.github.com/bciceron/22ed2fba6bf53d9ba0ca735c492710cb

**Comment by boumenot** [comment] 2016-04-20 23:29
The template your using is simple, and I do not see anything glaring.  I'm going to use your template, and see if I can reproduce the error.  This is going to take me some time.

**Comment by bciceron** [comment] 2016-04-21 20:18
@boumenot thanks for looking into it

**Comment by bciceron** [comment] 2016-04-27 18:52
@boumenot  are you able to reproduce this ? is there any way i can help ?

**Comment by boumenot** [comment] 2016-04-27 20:03
I have not been able to reproduce this.  My attempts have all been based on the other error message we have for this whereby an argument was incorrect, and trying all of the permutations is time consuming.

I spoke with a colleague about your error, and he had some immediate insight into it.  He said if a URL parameter is empty the back end parses it differently (I don't know why), and throws the error above. The next steps are to walk through the **many** parameters passed to the Azure flavor of packer, and verify if any are empty.  Be on guard for a parameters where the parameter's name is transposed, e.g. client_id vs cleint_id.

Another way to verify this is to insert a proxy between packer and Azure, and record the traffic.  Scan the URLs exchanged, and see if any are empty.  It looks like you're running on a Mac.  I am not familiar with Mac, but others on my team have used mitmproxy to capture HTTP traffic.

I am going to log an issue against the azure-sdk-for-go to track this issue.  The SDK team should be able to catch these types of errors, and turn them into a more sensible message.

HTH, and let me know how it goes.

**Comment by bciceron** [comment] 2016-04-27 21:37
solved but hard to believe : 

instead of using the hard coded variables in the conf as documented in:https://www.packer.io/docs/builders/azure.html
i used the syntax from:
https://github.com/mitchellh/packer/blob/master/examples/azure/ubuntu.json#L3

so for example with ARM_CLIENT_ID in my ami/ansible.azure/ansible.azure.json, the diff between old/new is the following:
-    "client_id": "fe354398-d7sf-4dc9-87fd-c432cd8a7e09",
+    "client_id": "{{env `ARM_CLIENT_ID`}}",

(i did the same for all vars)

then of course:
export ARM_CLIENT_ID=fe354398-d7sf-4dc9-87fd-c432cd8a7e09

finally i can run successfully the same command as before:
time PACKER_LOG=1 ~/packer/packer build ami/ansible.azure/ansible.azure.json

**Comment by boumenot** [comment] 2016-04-27 21:43
I'm glad you're up and working again.

This is strange.

@cbednarski If you have time, could you weigh in on this.  It seems like a strange interaction concerning how *variables* are sourced by the builder.  I suspect the Azure builder is doing something wrong, but I am not sure what it is.

**Comment by cbednarski** [comment] 2016-04-27 22:01
@boumenot If I understand correctly, my guess is that somewhere in the Azure code path there is something reading the ENV directly, instead of reading the the value from the variable passed into the builder. Essentially, there is code in azure / azure-sdk that calls `os.Getenv()`.

In general, builders / provisioners / post-processors should never read from the environment. They should only use the variables that are passed in. In practice this is not _always_ the case, but we should be careful about breaking the guideline because it's very hard to identify and document side effects like this one without exhaustive debugging.

I may have misunderstood or missed some of the details above so possibly there is something else going on. I think it should be easy to test if you change the ENV name to something else and see if it still works. E.g. `ARM_CLIENT_ID` -> `SOME_CLIENT_ID`.

**Comment by boumenot** [comment] 2016-04-27 22:19
TBH, I'm still not sure that I understand the issue.

We follow those tenets too.  Everything flows through Config.  I can't find anywhere in the Azure code (packer, SDKs, etc.) where we are reading from environment variables to influence configuration.  The only places outside of test were environment variables are sucked in is for proxy settings.

That's the strange part.  It should be easy to test, and seeing @bciceron's report it makes it clear my testing was flawed.  I'll try to duplicate.

### My Testing
I was executing packer and explicitly passing -var parameters for each variable I wanted to define.  packer-azure was correctly rejecting missing/empty values.  I had to manually edit the code to excite this failure.  I'm running on Windows.

### Bug Report1
User used -var-file to inject variables, and reported a variable name mismatch.  I cannot reproduce this issue.  The code correctly rejects empty variables, but perhaps the version at the time did not.

### This Bug Report
User used environment variables to fix the issue vs. hard-coding them in the config file.  (This seems backwards.  Hard coded is more explicit than an environment variable.)  Running on MacOS.  I'm not sure how or if Ansible as any role in this, or that just happens to be the path.

My testing was subtly different from how variables were injected, and I cannot account for any OS differences.  This is what is strange to me.

**Comment by cbednarski** [comment] 2016-04-27 22:58
> User used -var-file to inject variables, and reported a variable name mismatch. I cannot reproduce this issue. The code correctly rejects empty variables, but perhaps the version at the time did not.

If using `-var-file` and `-var` these are ingested in order, so for example if you define something in `-var` but later `-var-file` has that value blank, it will not be resolved properly. The same goes for multiple uses of `-var` or `-var-file`. They are evaluated left to right and last write wins.

> User used environment variables to fix the issue vs. hard-coding them in the config file. (This seems backwards. ...)

Agreed, though there are some subtle cases where this comes up. For example when provisioning with Ansible we pass the current environment along to the Ansible invocation:

```
github.com/mitchellh/packer/provisioner/ansible/provisioner.go:
  310  	cmd := exec.Command(p.config.Command, args...)
  311  
  312: 	cmd.Env = os.Environ()
  313  	if len(envvars) > 0 {
  314  		cmd.Env = append(cmd.Env, envvars...)
```

I'm not sure how this could affect an API response from Azure, though.

If it's not already there, I think it would be expedient to add debug logging before the affected API calls to see what the state of the variables are that will be passed in. In combination with PACKER_LOG=1 we should be able to see what packer's internal state is and what is actually going into the API. Perhaps we can make the stack trace more informative by catching the error and logging the request/response details (similar to the way the Azure CLI works). We should also mask secrets before logging them (replace each char with * for example).

Since I tested and merged the PR on OS X I know that platform works and IIRC I tested using ENV, -var, and using the config file. However it's possible that the Azure API has changed or that something else is different between my setup and @bciceron's

@bciceron What shell are you using? ZSH or bash or something else? Do you use an HTTP proxy or anything along those lines?

**Comment by bciceron** [comment] 2016-04-27 23:21
@cbednarski using bash:

$ env | grep -i shell
SHELL=/bin/bash

$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.

Do you mean HTTP proxy in the context of my shell environment, infrastructure, ansible or packer ?
i don't set HTTP proxy in any of my configs.

**Comment by cbednarski** [comment] 2016-04-27 23:23
> Do you mean HTTP proxy in the context of my shell environment, infrastructure, ansible or packer ?
i don't set HTTP proxy in any of my configs.

Any of these? I think it's unlikely, just curious if there is some other application or system setting that could be tampering with the outbound HTTP request from Packer to Azure.

**Comment by boumenot** [comment] 2016-04-27 23:32
I'm don't think there's a platform issue.  I think there a subtle interaction that I am not accounting for, and I'm not sure where it is.  I'm still boggled that hard coded failed, but environment worked.  I'm going to follow your advice, and print out the variables in question to better help with bug reports.  We've identified a way to make the SDK more robust for these types of issues, so that should help too.

> I'm not sure how this could affect an API response from Azure, though.

Me either. :frowning: 

> The same goes for multiple uses of -var or -var-file. They are evaluated left to right and last write wins.

I was reviewing these documents as part of this bug.  The docs say -var trumps -var-file in all cases regardless of order.  I'm being over pedantic, but point taken.

See https://www.packer.io/docs/templates/user-variables.html
>And as mentioned above, no matter where a -var-file is specified, a -var flag on the command line will always override any variables from a file.

**Comment by cbednarski** [comment] 2016-04-27 23:34
> I was reviewing these documents as part of this bug. The docs say -var trumps -var-file in all cases regardless of order. I'm being over pedantic, but point taken.

Oops, thanks for the correction. Subtle points!

**Comment by cbednarski** [comment] 2016-05-07 07:43
@bciceron A patch has been merged in #3483 that should either resolve this or give you more information. Please give packer 0.10.1 a try and if you're still having a problem feel free to re-open.

**Closed by cbednarski** 2016-05-07 07:43 UTC
Labels: builder/azure
