### ISSUE TITLE
Build 'azure-arm' errored: unexpected EOF

### ISSUE THREAD

**Issue by ebrucucen** [mitchellh/packer#3886] opened 2016-09-14 15:11 UTC
- Packer version: 0.10.1
- Host platform : Windows 7
- Debug log output:
https://gist.github.com/ebrucucen/0279a7cf69143e4cfefd0c601edc3bed
- Scripts:
- Json template: 
https://gist.github.com/ebrucucen/e6d4e2b0f383ca38168d1f241546e3e7
- Command: 
packer build .\azure_packer_win2012r2.json

**Comment by boumenot** [comment] 2016-09-14 18:56
Thank you for logging and issue, and including all of the necessary details!  I am sorry that it did not work for you by default.

The error message you received when Packer tried to fetch the WinRM certificate from KeyVault is 403 (Forbidden).  This usually indicates that the object_id specified is incorrectly.

```json
{
    "error": {
        "code": "Forbidden",
        "message": "Operation 'get' is not allowed"
    }
}        
```
Please review the value.

```sh
azure ad sp show --spn <client_id>
```

Once you fix that issue you will encounter yet another issue with 0.10.1.  The issue is fixed in master, but a release with the fix has not been made. You have three solutions to the problem.

1. You can rebuild master, and pick up the fix.
1. I made a private build available for another user, see #3766 for details.
1. Wait for next official Packer release. I do not have an ETA on when that will be.

Dupe of #3766

**Closed by boumenot** 2016-09-14 18:56 UTC
Labels: bug, builder/azure, crash, duplicate
