### ISSUE TITLE
Error uploading script: Upload failed with non-zero exit status: 1

### ISSUE THREAD

**Issue by VEBERArnaud** [mitchellh/packer#4500] opened 2017-02-02 15:43 UTC
Hi packer team,

I'm trying to build a docker image with packer on gitlab-ci, but the build fails at the step
- `docker: Provisioning with shell script: provisionning/shell/setup.sh`
  - `Retryable error: Error uploading script: Upload failed with non-zero exit status: 1`

---

- Packer version: `0.12.2`
- Host Platform: 
  - packer bin runs in a [veberarnaud/gitlab-ci_packer](https://hub.docker.com/r/veberarnaud/gitlab-ci_packer/) container, based on [docker:1.13-dind](https://hub.docker.com/_/docker/)
  - the container host platform is `Ubuntu 16.04` with `Docker version 1.13.0, build 49bf474`
- Debug log output is available [here](https://gist.github.com/VEBERArnaud/013c02214620994ab850267bd911b4db)
- Template is available [here](https://gist.github.com/VEBERArnaud/c19edfca2425a388f3f53ee994f6c411)

---

Screen shot without `PACKER_LOG=1` for better readability

![screen shot 2017-02-02 at 4 02 47 pm](https://cloud.githubusercontent.com/assets/5168814/22557265/51046e8c-e96a-11e6-93cc-f8a819232c20.png)

**Comment by VEBERArnaud** [comment] 2017-02-02 15:46
looks related to https://github.com/mitchellh/packer/issues/1752#issuecomment-271614018

**Comment by mwhooker** [comment] 2017-02-02 20:50
I think this is a dupe of #2832 and which should be handled in #4186

**Closed by mwhooker** 2017-02-02 20:50 UTC

**Comment by fxfitz** [comment] 2017-06-14 02:06
@mwhooker We are currently seeing this as well on GitLab CI.

@VEBERArnaud Did you ever find a solution?

Packer v1.0.0

```shell
$ docker info
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.24-coreos
Operating System: Alpine Linux v3.5 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.958GiB
Name: e5f9c6b15d61
ID: 4KSV:QPAO:NBCY:LTVL:KAS7:GNTV:GMT3:H2D6:R7K3:WA3H:J3JS:MQK5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

```
{
  "builders": [{
    "type": "docker",
    "image": "ubuntu:16.04",
    "commit": true
  }],
  "provisioners": [{
    "type": "shell",
    "inline": [
        "apt-get update -y && apt-get install -y net-tools iproute2"
  ]}],
  "post-processors": [
    {
      "type": "docker-tag",
      "repository": "launchpad-base",
      "tag": "latest"
    }
  ]
}
```

Significant Output:
```
[...]
    docker: Digest: sha256:ea1d854d38be82f54d39efe2c67000bed1b03348bcc2f3dc094f260855dff368
    docker: Status: Downloaded newer image for ubuntu:16.04
==> docker: Starting docker container...
    docker: Run command: docker run -v /root/.packer.d/tmp/packer-docker349468636:/packer-files -d -i -t ubuntu:16.04 /bin/bash
    docker: Container ID: e4af2d72eb571f2ff18e1bf798fcb55a42383af4195f565c0f8e377469b78848
==> docker: Provisioning with shell script: /tmp/packer-shell674847360
==> docker: Killing the container: e4af2d72eb571f2ff18e1bf798fcb55a42383af4195f565c0f8e377469b78848
Build 'docker' errored: Retryable error: Error uploading script: Upload failed with non-zero exit status: 1
```
