### ISSUE TITLE
Puppet Masterless running with Role and Profiles structure

### ISSUE THREAD

**Issue by YamanduTellechea** [mitchellh/packer#3340] opened 2016-03-11 13:37 UTC
I want to use Puppet Masterless to provisioning machine with this plan:

role calls profiles -> profiles calls module --> module starts init.pp -> init.pp runs all classes in there

### Role module would be:
 
role/
├── Gemfile
├── manifests
│   ├── init.pp
│   └── jboss.pp
├── metadata.json
├── Rakefile
├── README.md
├── spec
│   ├── classes
│   │   └── init_spec.rb
│   └── spec_helper.rb
└── tests
    └── init.pp

Code jboss.pp--

**class role::jboss{ 
	include profiles::jboss
}**

### Profile Module would be...

profiles/
├── Gemfile
├── manifests
│   ├── init.pp
│   └── jboss.pp
├── metadata.json
├── Rakefile
├── README.md
├── spec
│   ├── classes
│   │   └── init_spec.rb
│   └── spec_helper.rb
└── tests
    └── init.pp

Code jboss.pp--

class profiles::jboss{

ALL VARIABLES                        

	class { '::jboss':
		namerepo        => $namerepo,
                enabledrepo     => $enabledrepo,
                baseurlrepo     => $baseurlrepo,
                gpgcheck        => $gpgcheck,
		product_tag     => $product_tag,
	        product_version => $product_version,
       	        ensure_install  => $ensure_install,
                product_tag2    => $product_tag2,
                product_version2=> $product_version2,
                product_tag3    => $product_tag3,
                product_version3=> $product_version3,
		software_vg     => $software_vg,
                jboss_path      => $jboss_path,
	}
}

Finally, call Jboss module.

On the other hand, this is my packer .json:

		        	
	{
            "type": "puppet-masterless",
            "manifest_file": "/usr/local/packer/puppetmodules/role/manifests/jboss.pp",
			"module_paths": ["/usr/local/packer/puppetmodules/jboss","/usr/local/packer/puppetmodules/profiles","/usr/local/packer/puppetmodules/role"],
			"staging_directory":"/etc/puppet/modules"
				    
              }

  

And this is the packer's log:

vmware-iso: Provisioning with Puppet...
    vmware-iso: Creating Puppet staging directory...
    vmware-iso: Uploading local modules from: /usr/local/packer/puppetmodules/jboss
    vmware-iso: Uploading local modules from: /usr/local/packer/puppetmodules/profiles
    vmware-iso: Uploading local modules from: /usr/local/packer/puppetmodules/role
    vmware-iso: Uploading manifests...
    vmware-iso: Uploading manifest file from: /usr/local/packer/puppetmodules/role/manifests/jboss.pp
    vmware-iso: Running Puppet: cd /etc/puppet/modules && FACTER_packer_build_name='vmware-iso' FACTER_packer_builder_type='vmware-iso'  sudo -E puppet apply --verbose --modulepath='/etc/puppet/modules/module-0:/etc/puppet/modules/module-1:/etc/puppet/modules/module-2' --detailed-exitcodes /etc/puppet/modules/manifests/jboss.pp
    vmware-iso: Notice: Compiled catalog for vmlbcatfl29.lvtc.gsnet.corp in environment production in 0.04 seconds
    vmware-iso: Info: Applying configuration version '1457697296'
    vmware-iso: Info: Creating state file /var/lib/puppet/state/state.yaml
    vmware-iso: Notice: Finished catalog run in 0.02 seconds

I hope that I am clear in this.

**Comment by cbednarski** [comment] 2016-03-11 19:41
Thanks for opening an issue. I am not a puppet expert so I am unable to debug your provisioning step. I do not see a packer bug or error in your logs. What is your question?

**Comment by YamanduTellechea** [comment] 2016-03-11 20:09
Thanks @cbednarski  .It's true,dont`exit any error, however, the problem is that puppet doesn`t apply these modules and no creates users,groups,installes rpms.

**Comment by rickard-von-essen** [comment] 2016-03-11 20:15
Your modules_path is wrong.

**Comment by YamanduTellechea** [comment] 2016-03-11 20:23
Thanks @rickard-von-essen , what should I put in 'module_paths'? My modules is in these paths

**Comment by rickard-von-essen** [comment] 2016-03-11 20:36
It should not include `profiles`and `role`since these are the name of your modules.

**Comment by YamanduTellechea** [comment] 2016-03-11 20:38
Thanks for soon answer, i will test on Monday.

**Comment by kikitux** [comment] 2016-03-12 01:01
@YamanduTellechea it seems this is more a question about puppet rather than a packer bug. Would you mind closing this issue and following up in the mailing list?

if you think this is a packer bug, and can share a zip file with a reproducible case we can have a look.

Thanks

**Closed by kikitux** 2016-03-12 01:01 UTC
Labels: provisioner/puppet, question
