### ISSUE TITLE
Packer push causes inconsitent behavior in atlas builds

### ISSUE THREAD

**Issue by udev** [mitchellh/packer#2607] opened 2015-08-16 17:18 UTC
I started with the [Atlas Packer Vagrant Tutorial](https://github.com/hashicorp/atlas-packer-vagrant-tutorial.git) template and successfully pushed to atlas and completed a build with no changes following the tutorial steps:

```
packer push -name udev/ceapi template.json
```

After the successful build I added a push section to the template to include a directory created in the project root:

``` json
"push": {
  "name": "udev/ceapi",
  "vcs": true,
  "include": [
    "directory"
  ]
}
```

The build fails with the following log:

```
---- Started new build at 2015-08-16 16:56:26.660917832 +0000 UTC ----
Packer v0.8.2

vmware-iso output will be in this color.

7 error(s) occurred:

* Bad script 'scripts/base.sh': stat scripts/base.sh: no such file or directory
* Bad script 'scripts/virtualbox.sh': stat scripts/virtualbox.sh: no such file or directory
* Bad script 'scripts/vmware.sh': stat scripts/vmware.sh: no such file or directory
* Bad script 'scripts/vagrant.sh': stat scripts/vagrant.sh: no such file or directory
* Bad script 'scripts/dep.sh': stat scripts/dep.sh: no such file or directory
* Bad script 'scripts/cleanup.sh': stat scripts/cleanup.sh: no such file or directory
* Bad script 'scripts/zerodisk.sh': stat scripts/zerodisk.sh: no such file or directory
```

expected: adding a push section with an array of included files/directories does not cause files in vcs to not be found.

This issue occurred on 0.8.5 and 0.8.2 (installed via brew)

**Comment by cbednarski** [comment] 2015-08-17 09:25
Thanks for the report! I'm actually not sure what the "correct" behavior is in this case, but after reading the docs this does seem to be working as intended.

[Here are the docs:](https://www.packer.io/docs/templates/push.html)

> `include` (array of strings) - Glob patterns to include relative to the base_dir. If this is specified, only files that match the include pattern are included.

> `vcs` (boolean) - If true, Packer will detect your VCS (if there is one) and only upload the files that are tracked by the VCS. This is useful for automatically excluding ignored files. This defaults to false.

The way I read this is that by default, packer will just push everything. When you add the `include` option, packer will now *only* push files that are globbed by the include options. Additionally, when you add `vcs` packer will *only* push files that are *both* globbed by include options *and* tracked by source control. Your config represents the most restrictive set.

I think since you have `scripts` that are missing you will need to customize your config to something like this:

```
"push": {
  "name": "udev/ceapi",
  "include": [
    "scripts"
  ]
}
```

You may be able to add the `vcs` option but it may be extraneous. From my understanding, the reason the `vcs` option is there is basically to take advantage of your `.gitignore` or `.hgignore` file and not accidentally push certs, keys, binaries, and other things you don't want to upload to Atlas. So if your `scripts` folder is checked in, you can probably use that option:

```
"push": {
  "name": "udev/ceapi",
  "vcs": true,
  "include": [
    "scripts"
  ]
}
```

If things are still busted, lemme know and we can figure out if there is a bug or if the docs are bad or both.

**Comment by udev** [comment] 2015-08-17 15:38
Gotcha. The documentation gave me the impression that the include array would add files on top of what was already in the build but your explanation does make sense. Since there is a corresponding exclude property I didn't expect include to operate exclusively on the listed files and directories.

**Comment by cbednarski** [comment] 2015-08-18 00:02
IIRC the order of precedence is default (all files), vcs, include, and then exclude. You can use exclude only and this will exclude files from the default set of all files. Otherwise, it is working with a more limited set based on vcs and include. Probably the easiest way to think about it is each set is smaller than the last.

I think the docs can be improved to clarify this behavior.

**Closed** 2017-02-10 02:26 UTC
Labels: docs, post-processor/atlas
