### ISSUE TITLE
SSH timeout error while running packer

### ISSUE THREAD

**Issue by RajatGoyal** [mitchellh/packer#4363] opened 2017-01-05 11:38 UTC
Getting SSH timeout error running packer, was working fine before

- Packer version 0.12
- Host platform OS X
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/RajatGoyal/c83f630c2aae5a71e29f8d6270df4f71

concerened part
```
2017/01/05 17:06:42 packer: 2017/01/05 17:06:42 ssh session open error: 'ssh: unexpected packet in response to channel open: <nil>', attempting reconnect
2017/01/05 17:06:42 packer: 2017/01/05 17:06:42 reconnecting to TCP connection for SSH
2017/01/05 17:06:42 packer: 2017/01/05 17:06:42 handshaking with SSH
2017/01/05 17:06:44 packer: 2017/01/05 17:06:44 handshake complete!
2017/01/05 17:06:44 packer: 2017/01/05 17:06:44 opening new ssh session
2017/01/05 17:07:30 packer: 2017/01/05 17:07:30 ssh session open error: 'ssh: unexpected packet in response to channel open: <nil>', attempting reconnect
2017/01/05 17:07:30 packer: 2017/01/05 17:07:30 reconnecting to TCP connection for SSH
2017/01/05 17:07:30 packer: 2017/01/05 17:07:30 handshaking with SSH
2017/01/05 17:07:32 packer: 2017/01/05 17:07:32 handshake complete!
2017/01/05 17:07:32 packer: 2017/01/05 17:07:32 opening new ssh session
2017/01/05 17:07:40 ui error: ==> amazon-ebs: Timeout waiting for SSH.
```

Builder configuration:

```
"builders": [
    {
      "type": "amazon-ebs",
      "region": "us-east-1",
      "source_ami": "ami-e13739f6",
      "instance_type": "t2.small",
      "ssh_username": "ubuntu",
      "ami_name": "Baker {{user `repo_name`}}-{{user `tag`}}-{{timestamp}}",
      "tags": {
        "OS_Version": "Ubuntu",
        "Release": "Latest"
      }
    }
  ]
```

**Comment by xrage** [comment] 2017-01-05 11:52
+1 same issue.

**Comment by mwhooker** [comment] 2017-01-05 21:41
hmm, I'm not able to reproduce this. 

We had some similar issues to this (#3318, #3699), which were resolved in #4008

I wonder if the fix in #4008 simply prevents the panic, but not the underlying issue. Do you have any provisioners? Do they restart the host?

**Comment by RajatGoyal** [comment] 2017-01-06 06:11
@mwhooker yes I have various shell provisioners and they don't restart the host.

**Comment by rickard-von-essen** [comment] 2017-01-07 11:38
@RajatGoyal do they restart ssh or network (`apt-get upgrade` etc)?

**Comment by RajatGoyal** [comment] 2017-01-08 05:55
yes they do, but this happens before running any provisioner, this happens when the instance is setup and it's trying to login for the first time

**Comment by yuvraj2987** [comment] 2017-01-09 22:02
I am experiencing this issue in google cloud as well.
No provisioner.
```
{
  "builders": [{
    "type": "googlecompute",
    "project_id": "googleproject",
    "source_image": "centos-6-v20161212",
    "zone": "us-central1-a",
    "network": "poc",
    "subnetwork": "internal-network",
    "tags": ["env-poc", "centos6"]
  }]
}
```
![image](https://cloud.githubusercontent.com/assets/4722567/21785318/e8958fd8-d673-11e6-86a2-e1aefe98868b.png)

![image](https://cloud.githubusercontent.com/assets/4722567/21785342/fd87811c-d673-11e6-80b3-118186298206.png)

I even tried to use debug functionality of packer. The intermediate instance is not able to accept my ssh connection.

**Comment by mwhooker** [comment] 2017-01-09 22:19
I'm sorry I can't really help with this issue unless I can get a json that reproduces the problem

**Comment by rickard-von-essen** [comment] 2017-01-10 07:47
@yuvraj2987 that is not the same issue. Please upgrade to the latest release, add `"ssh_username": "centos"`, retry and ask for further help on the [mailing list](https://www.packer.io/community/).

**Comment by rickard-von-essen** [comment] 2017-01-10 07:52
@RajatGoyal Debug this by creating a ssh keypair and configure packer to use it. Rerun with `--on-error=ask`. When the instance is up use the private key and ssh to the instance to verify if that works. If not do a standard network trouble shooting, check security groups, ACL's, iptable, instance console logs, network connectivity etc. When you have more info report back here and re-open.

**Closed by rickard-von-essen** 2017-01-10 07:52 UTC
Labels: communicator/ssh, need-more-info, need-repro
