### ISSUE TITLE
Docker build failing on Windows due to path syntax

### ISSUE THREAD

**Issue by shivjm** [mitchellh/packer#3471] opened 2016-04-25 17:13 UTC
Using Packer 0.10.0, [building a Docker image fails on Windows 7 x64](https://gist.github.com/shivjm/3d3c2b4b229069fa2fa84e7c1e08ce8d) because Docker expects volume paths in the form `/c/Foo/Bar/` rather than `C:\Foo\Bar`.

[Running Docker with the corrected path seems to work.](https://gist.github.com/shivjm/edae06c73736f6a92d261d884adcc189)

**Comment by cbednarski** [comment] 2016-04-25 17:17
Thanks for the report!

**Comment by arizvisa** [comment] 2016-04-29 22:19
Since these are msys-style paths... if packer for some reason is built using msys' golang, then you can call msys' `cygwin_conv_path` function using cgo's ffi to convert from a windows path to an msys path.
Otherwise, it'll probably need to be re-implemented in driver_docker.go.

There might be a few builders that don't properly normalize the path for whatever driver it's being passed into, as I just noticed in the virtualbox builder there's no reference to filepath.FromSlash to convert a path to the platform's representation and a similar issue in the VMware builder.

**Comment by mwhooker** [comment] 2017-01-30 23:11
I know this is the older ticket, but closing as a duplicate of #3734

**Closed by mwhooker** 2017-01-30 23:11 UTC
Labels: bug, builder/docker, windows-host
