### ISSUE TITLE
virtualbox-iso builder network adapter issues with virtualbox 5.1

### ISSUE THREAD

**Issue by jhkrischel** [mitchellh/packer#3757] opened 2016-07-28 04:34 UTC
With virtualbox 5.1, the OVF file created has a sparse Network section:

```
        <Network>
          <Adapter slot="0" enabled="true" MACAddress="0800276F4FE5" type="82540EM">
            <NAT/>
          </Adapter>
          <Adapter slot="1" type="82540EM"/>
          <Adapter slot="2" type="82540EM"/>
          <Adapter slot="3" type="82540EM"/>
          <Adapter slot="4" type="82540EM"/>
          <Adapter slot="5" type="82540EM"/>
          <Adapter slot="6" type="82540EM"/>
          <Adapter slot="7" type="82540EM"/>
        </Network>
```

In comparison, with virtualbox 5.0.26, the network settings are proper:

```
        <Network>
          <Adapter slot="0" enabled="true" MACAddress="080027967E30" cable="true" speed="0" type="82540EM">
            <DisabledModes/>
            <NAT>
              <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
              <Alias logging="false" proxy-only="false" use-same-ports="false"/>
            </NAT>
          </Adapter>
          <Adapter slot="1" enabled="false" MACAddress="080027FB4F38" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="2" enabled="false" MACAddress="0800279D475E" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="3" enabled="false" MACAddress="080027E05792" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="4" enabled="false" MACAddress="080027849293" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="5" enabled="false" MACAddress="0800275A2598" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="6" enabled="false" MACAddress="0800272AFF8A" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="7" enabled="false" MACAddress="080027E80098" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
        </Network>
```

There might be other virtualbox 5.1 issues beyond that, but I ran into that when my boxes were created with no cables connected.

**Comment by rickard-von-essen** [comment] 2016-07-28 05:54
This doesn't seem like a Packer bug. Please file a issue on VirtualBox, see https://www.virtualbox.org/wiki/Bugtracker. 

Reopen if the is special reason for Packer to handle this.

**Comment by jhkrischel** [comment] 2016-07-28 05:58
Created https://www.virtualbox.org/ticket/15705

**Comment by tknerr** [comment] 2016-07-29 12:34
@rickard-von-essen sure this is a virtualbox bug? Thought that Packer creates this file by means of the differnet `VBoxManage` commands.

I know that Vagrant had to be specifically updated for VirtualBox 5.1 (thus the early 1.8.5 release), so maybe Packer is affected from that too?

@sethvargo any input on this, e.g. specifically was it the networking stuff that had to be adapted for the 5.1 release?

**Comment by tknerr** [comment] 2016-07-29 12:37
P.S.: more specifically to the effect of this when using such a box with vagrant: 

 * `vagrant up` times out because it can't connect via SSH
 * looking at VirtualBox you can see that the default NAT adapter is not connected. Once you connect it, you can connect to it again via "ssh://localhost:2222" and so can vagrant

**Comment by rickard-von-essen** [comment] 2016-07-29 13:45
More information is needed to determine if this is an issue with Packer, Vagrant, VirtualBox or everything works as intended.

**Comment by rickard-von-essen** [comment] 2016-07-29 13:46
It would be great if someone could point out the commit in VirtualBox changing this behavior.

**Comment by MansM** [comment] 2016-07-29 22:06
Looking through the changelog of vb, i came acties this huge commit: https://www.virtualbox.org/changeset/61009/vbox

**Comment by ozeebee** [comment] 2016-08-01 14:40
This VirtualBox related issue is also reported in Vagrant project: https://github.com/mitchellh/vagrant/issues/7648 with a work-around for people using Vagrant.

**Comment by synthesizerpatel** [comment] 2016-08-21 07:52
I ran into a problem where I was trying to process a virtualbox-iso created image in a 'second-pass' by importing it via virtualbox-ovf, the system would hang when trying to SSH in.

After some debugging I realized I needed to install the VirtualBox-ext tools (so that I could VRDP in), it became clear that there was something wrong with the networking. The device wasn't getting a DHCP address.. I poked around a bit, tried a few things but the major element that clued me in was the OP's comment that the network 'cables' were unconnected on the box.

In my virtualbox-ovf template.json I added `[modifyvm,` {{.Name}}, --cableconnected1, on],` in my `vboxmanage` stanza for the builder. Box came up and was able to SSH no problem.

**Comment by ogarcia** [comment] 2016-08-21 11:22
@synthesizerpatel your workaround not work for me :cry:

**Comment by MiLk** [comment] 2016-09-06 09:08
I got the same issue while building an ubuntu image.

The cable is not connected when the vm boots.

With VBox 5.1, I get:
```xml
        <Network>
          <Adapter slot="0" enabled="true" MACAddress="080027C69206" type="virtio">
            <NAT>
              <DNS use-host-resolver="true"/>
            </NAT>
          </Adapter>
          <Adapter slot="1" type="82540EM"/>
          <Adapter slot="2" type="82540EM"/>
          <Adapter slot="3" type="82540EM"/>
          <Adapter slot="4" type="82540EM"/>
          <Adapter slot="5" type="82540EM"/>
          <Adapter slot="6" type="82540EM"/>
          <Adapter slot="7" type="82540EM"/>
        </Network>
```

With VBox 5.0, I get:
```xml
        <Network>
          <Adapter slot="0" enabled="true" MACAddress="08002794ECCF" cable="true" speed="0" type="virtio">
            <DisabledModes/>
            <NAT>
              <DNS pass-domain="true" use-proxy="false" use-host-resolver="true"/>
              <Alias logging="false" proxy-only="false" use-same-ports="false"/>
            </NAT>
          </Adapter>
          <Adapter slot="1" enabled="false" MACAddress="0800277112AD" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="2" enabled="false" MACAddress="0800277F1DC8" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="3" enabled="false" MACAddress="0800270C7327" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="4" enabled="false" MACAddress="080027E2A0A6" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="5" enabled="false" MACAddress="080027BBD19A" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="6" enabled="false" MACAddress="0800275CAEAB" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
          <Adapter slot="7" enabled="false" MACAddress="08002793A864" cable="true" speed="0" type="82540EM">
            <DisabledModes>
              <NAT>
                <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
                <Alias logging="false" proxy-only="false" use-same-ports="false"/>
              </NAT>
            </DisabledModes>
          </Adapter>
        </Network>
```

**Comment by kev009** [comment] 2016-09-15 20:59
FWIW you can work around in your Vagrantfile with (add one for each interface etc):
```
node.vm.provider 'virtualbox' do |vb|
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
end
```
but this does seem to be a VirtualBox 5.1 regression

**Comment by AmedeeBulle** [comment] 2016-10-03 14:38
Fyi, [this thread on the VirtualBox forum](https://forums.virtualbox.org/viewtopic.php?f=7&t=78840) is interesting...
To summarize, export is fine, the issue is in VirtualBox import and should be fixed in
- 5.1.6 for 5.1
- 5.0.28 for 5.0 (at this point in time not released yet, but fix is in [5.0.27 test build](https://www.virtualbox.org/wiki/Testbuilds))

**Comment by Techcadia** [comment] 2016-11-08 18:17
I upgraded to 5.1.8 of Virtualbox and this issue was resolved for me. The work around did work on my older version of Virtualbox but I would rather not have to hack all the files.

**Comment by rickard-von-essen** [comment] 2016-11-08 19:33
I'll close this since this is fixed in VirtualBox 5.1.6.

**Closed by rickard-von-essen** 2016-11-08 19:33 UTC
Labels: builder/virtualbox, invalid

**Comment by tknerr** [comment] 2016-11-11 22:38
Can also verify that it's fixed with VirtualBox 5.1.6

**Comment by scoter-oracle** [comment] 2017-01-13 15:32
We worked on this issue and fixed it into 5.1 release of VirtualBox.
At the same time the issue will be fixed of 5.0 into the future release 5.0.32.
VirtualBox-team - Oracle

**Comment by rickard-von-essen** [comment] 2017-01-13 15:50
@scoter-oracle Thanks for reporting back on this!

**Comment by esafzay** [comment] 2017-08-23 01:48
VirtualBox 5.1.26 r117224 (Qt5.6.2)
Ubuntu 17.04 as VM
When network type is 'Internal Network' I am getting this message in the boot:
A start job is running for Raise network interfaces

**Comment by samvv** [comment] 2019-10-26 13:56
I'm seeing this issue again in VirtualBox 6, unless I'm missing something very obvious. I'll file a new issue just to be sure.
