### ISSUE TITLE
Unable to delete floppy controller

### ISSUE THREAD

**Issue by rahamathid** [mitchellh/packer#2889] opened 2015-10-30 13:56 UTC
Hi, I am running latest packer on Windows server 2008 R2 with latest virtual box hypervisor. My build will completes many times, but fails in between due to unable to remove floppy dirve.I noted few blogs for it mentioning it to use latest packer. But this issue is not resolved even in the latest release. Plese confirm if there are any other alternative to resolve this issue.

**Comment by cbednarski** [comment] 2015-10-30 17:47
@rahamathid Thanks for the report! There's not much info to go on here -- can you share a minimal template that reproduces this so I can see what builders and provisioners you're using? Also as Windows 2008 is quite old, I don't know where I will find an ISO to test this but if it's a general floppy problem I might be able to repro on another OS.

**Comment by rahamathid** [comment] 2015-11-01 04:16
Hi, I have downloaded the default basic template for building OS, I will share it. Meanwhile, the issue is occuraing on both 2008 and 2012. This issue is happening intermittently. Below is the error message.

================
==> virtualbox-iso: Gracefully halting virtual machine...
    virtualbox-iso: Removing floppy drive...
==> virtualbox-iso: Error removing floppy controller: VBoxManage error: VBoxManage.exe: error: The machine '2008_r2-SQL'
 is already locked for a session (or being unlocked)
==> virtualbox-iso: VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap
, interface IMachine, callee IUnknown
==> virtualbox-iso: VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 1030 of file VBoxM
anageStorageController.cpp
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error removing floppy controller: VBoxManage error: VBoxManage.exe: error: The machine '
2008_r2-SQL' is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine
, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 1030 of file VBoxManageStorageControll
er.cpp

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error removing floppy controller: VBoxManage error: VBoxManage.exe: error: The machine '2008_r2-SQL'
 is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine
, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 1030 of file VBoxManageStorageControll
er.cpp

==> Builds finished but no artifacts were created.

D:\packer-windows-master>packer version
Packer v0.8.6

**Comment by rickard-von-essen** [comment] 2015-11-01 07:21
What is you VirtualBox version? This looks like it could be a bug in
VirtualBox.

**Comment by rahamathid** [comment] 2015-11-01 09:27
virtualbox 5.0.6,

**Comment by rahamathid** [comment] 2015-11-03 08:35
I have upgraded virtual box to 5.0.8, still have the same issue. any one ?

**Comment by markpeek** [comment] 2015-11-04 18:17
Thinking about this issue, it may be that the halt action isn't fully completing before the remove floppy step occurs. Might be good to run it with PACKER_LOG=1 and post the log entries between the "Gracefully halting..." message and the error. Do you have a ```shutdown_timeout`` set in your template? Have you tried manually doing the steps and timed how long the shutdown might take?

**Comment by Ian2020** [comment] 2016-07-28 13:13
Another instance of issue #2401?

**Comment by mwhooker** [comment] 2017-02-10 05:36
marking as dupe of #2401 #4432

**Closed by mwhooker** 2017-02-10 05:36 UTC
Labels: bug, windows-guest
