### ISSUE TITLE
Unmarshalling JSON Error With Azure

### ISSUE THREAD

**Issue by ritasker** [mitchellh/packer#3807] opened 2016-08-18 15:55 UTC
I am trying to provision a Windows VM image on Azure. But I am getting the following error when running my packer build.

```
==> azure-arm: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go value of type string' JSON = '{"value":"[ token - removed for readability]", "id":"https://pkrkv8rtf8zm99w.vault.azure.net/secrets/packerKeyVaultSecret/86b722b9502643c79e57304aa5b9ea7b","attributes":{"enabled":true,"created":1471517728,"updated":1471517728}}'
```

Following the setup [guide](https://www.packer.io/docs/builders/azure-setup.html). I ran [this](https://github.com/ritasker/packer/blob/azure-setup-script/contrib/azure-setup.sh) version of the `azure-setup.sh` script. The packer file I ran can be found [here](https://gist.github.com/ritasker/502dc2908623442d1495ff87c1ca8563) (I have taken the variables out). I get the following detailed [log](https://gist.github.com/ritasker/ad1d59f51ce0bbee84b711bd5f6fc8b7) when running with `PACKER_LOG=1` flag.

**Comment by boumenot** [comment] 2016-08-19 19:32
Sorry.  This appears to be a dupe of #3721.  The fix has been committed to master, but a release with the fix has not been made.  Are you able to build the tree?  Another user reported the issue, and I supplied a private build for Windows in #3766.  I do not know if this is an acceptable solution for you though.  Please let me know the best way to get you up and working.

**Comment by ritasker** [comment] 2016-08-22 16:08
I have been able to create an image using the latest code on master. 
![winning](https://cloud.githubusercontent.com/assets/344357/17861829/851f887a-688a-11e6-9946-31bb6ca1e2be.png).

Do you have a timeframe on the next release?

**Comment by boumenot** [comment] 2016-08-23 16:18
Sorry, I do not.

cc: @cbednarski

**Comment by cbednarski** [comment] 2016-08-24 16:25
Hey folks, I know there's a lot waiting to go out but unfortunately I don't have a release scheduled yet. It's in the pipe but I don't have a date to share right now.

**Comment by ritasker** [comment] 2016-08-24 16:26
Ok no problem. Shall we close this as it is a duplicate and it has already been fixed, even though it hasn't been released.

**Comment by boumenot** [comment] 2016-08-24 16:55
Once the code hits master it has been my stance to close an issue.

**Closed by boumenot** 2016-08-24 16:55 UTC
Labels: builder/azure, duplicate
