### ISSUE TITLE
Ansible-local: Unable to build image inside a virtualenv 

### ISSUE THREAD

**Issue by jpza** [mitchellh/packer#3726] opened 2016-07-17 23:16 UTC
```
-> % uname -a                                                                                                                (env: worktime)
Darwin omerta-9.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,2 Darwin

-> % packer version                                                                                                          (env: worktime)
Packer v0.10.1
```

The error all of my packer builds produce when building inside a virtualenv (created with mkvirtualenv) is: 

```
Build 'mesos-slave-ebs' errored: Error uploading playbook_dir directory: lstat /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7/../../../../Versions/2.7/Python/2.7.10_2: not a directory
```

The rest of the build logs for 'mesos-slave-ebs' are irrelevant and error free.

It's the following line which attempts to upload the playbook dir and causes the erroneous lookup: 

``` json
{
   "type": "ansible-local",
    "playbook_file": "mesos-slave.yml",
   "playbook_dir": ".."
},
```

Line 93 tells it to upload a directory which contains symlinks. In my case, python is necessarily mixed into the playbook directory and I use a virtualenv to manage the python dependencies my playbooks depend on. 

This seems to be due to packer being unable to follow symlinks created by the virtualenv. If I run the exact same build outside of the virtualenv packer builds flawlessly (as usual). 

Let me know if you need anything else. I am happy to provide.

**Comment by rickard-von-essen** [comment] 2016-07-18 05:50
Please provide a full minimal example to reproduce this, including template, playbook, and other files.

**Comment by mwhooker** [comment] 2017-01-28 01:53
Going to close this since we're still waiting for a response.

In the meantime, for anyone who comes upon this, I suggest creating a relocatable virtualenv https://virtualenv.pypa.io/en/stable/userguide/#making-environments-relocatable

**Closed by mwhooker** 2017-01-28 01:53 UTC
Labels: provisioner/ansible-local, waiting-reply
