### ISSUE TITLE
Googlecompute: Startup script incompatible with CoreOS

### ISSUE THREAD

**Issue by pschultz** [mitchellh/packer#4118] opened 2016-11-04 15:28 UTC
$ bin/packer version                                                  
    Packer v0.11.0

```json
{
  "builders": [
    {
      "type": "googlecompute",
      "account_file": "account.json",
      "project_id": "[...]",
      "source_image": "coreos-beta-1068-3-0-v20160627",
      "zone": "europe-west1-c",
      "ssh_username": "core",
      "image_name": "debug-{{ timestamp }}"
    }
  ]
}
```

* * *

[The startup script for GCE in v0.11.0](https://github.com/mitchellh/packer/blob/v0.11.0/builder/googlecompute/startup.go) doesn't seem to work on CoreOS machines. Running it manually certainly does not:

```
core@packer-581c9d7e-3dc7-efec-eedb-60de658803aa-1 ~ $ ./foo.sh 
Packer startup script starting.
Packer startup script done.
./foo.sh: line 10: gcloud: command not found
```

gcloud (and gsutil as well) are aliases, defined in /etc/profile.d -- so for login shells only:

```
core@packer-581c9d7e-3dc7-efec-eedb-60de658803aa-1 ~ $ type gcloud
gcloud is aliased to `(docker images google/cloud-sdk || docker pull google/cloud-sdk) > /dev/null;docker run -t -i --net=host -v /home/core/.config:/.config -v /var/run/docker.sock:/var/run/doker.sock google/cloud-sdk gcloud'
```

The script was changed in b54b82d3acd0f. Symptoms are the same as in #3829 and #4095: builds are hanging at "Startup script not finished yet. Waiting..."

Some random ideas that may or may not work:

* Run the script in a login shell.
* Source `/etc/profile.d/google-cloud-sdk.sh` if it exists
* Set the metadata with curl. [The API](https://cloud.google.com/compute/docs/storing-retrieving-metadata#updatinginstancemetadata) may be a bit too complicated to do that nicely and this isn't a solution for gsutil.

**Comment by pschultz** [comment] 2016-11-04 15:31
For completeness, google-cloud-sdk.sh contains the following:

```sh
#!/bin/sh
alias gcloud="(docker images google/cloud-sdk || docker pull google/cloud-sdk) > /dev/null;docker run -t -i --net="host" -v $HOME/.config:/.config -v /var/run/docker.sock:/var/run/doker.sock google/cloud-sdk gcloud"
alias gcutil="(docker images google/cloud-sdk || docker pull google/cloud-sdk) > /dev/null;docker run -t -i --net="host" -v $HOME/.config:/.config google/cloud-sdk gcutil"
alias gsutil="(docker images google/cloud-sdk || docker pull google/cloud-sdk) > /dev/null;docker run -t -i --net="host" -v $HOME/.config:/.config google/cloud-sdk gsutil"
```

I suppose one could also ask why the aliases are only defined for login shells. It stands to reason that many scripts would profit if they would be defined in all shells.

**Comment by rickard-von-essen** [comment] 2016-11-04 15:39
Slightly related to #4102

**Comment by luhkevin** [comment] 2016-12-09 08:43
Is there a fix or workaround for this? I'm also experiencing this issue on CoreOS

**Comment by rickard-von-essen** [comment] 2016-12-09 10:29
@pschultz You original example doesn't contain a `startup_script_file` is that correct?

@luhkevin Does it work if you instead insert the script in `metadata`?

**Comment by luhkevin** [comment] 2016-12-09 10:31
Have not tried that yet, I'll give it a shot soon. 
The script in question is just the contents of `StartupScriptLinux` in https://github.com/mitchellh/packer/blob/v0.11.0/builder/googlecompute/startup.go, correct?

**Comment by rickard-von-essen** [comment] 2016-12-09 11:02
Yes, and I think you can use it with adaptations and put it in metadata instead.

**Comment by pschultz** [comment] 2016-12-09 11:32
We don't use startup scripts. That's why #4102 fixed it for us.

**Comment by rickard-von-essen** [comment] 2016-12-09 11:49
Closing, see above.

**Comment by mwhooker** [comment] 2017-02-02 12:33
the problem is that the startup-script runs inside the `oem-gce` rocket container, which doesn't have access to docker, and so can't write metadata.

I'm thinking that probably the best way to get coreos working on GCE is to use the `user-data` field, instead of `startup-script`. See https://coreos.com/os/docs/latest/booting-on-google-compute-engine.html

Unfortunately I'm not sure we'll be able to get the start-up script to work without coreos involvement. 

There were 1 or 2 fixes I needed to make to the startup script to get it to work outside of the rkt container. here's the branch https://github.com/mitchellh/packer/compare/coreosgce


There's nothing we can do for now, so going to close this.

**Closed by mwhooker** 2017-02-02 12:33 UTC
Labels: bug, builder/google, waiting-reply
