### ISSUE TITLE
Packer can't parse private ssh key using OpenStack/Rackspace 

### ISSUE THREAD

**Issue by crimsongreen** [mitchellh/packer#2526] opened 2015-07-29 07:13 UTC
Hi,

I am experiencing an issue with Packer when attempting spin up a cloud server on Rackspace cloud. It appears to fail when parsing the private SSH key.

To reproduce please use the following template, add your username, password and image ID

```
{
 "builders": [{
   "type": "openstack",
   "identity_endpoint" : "https://identity.api.rackspacecloud.com/v2.0/",
   "username": "USERNAME",
   "password": "PASSWORD",
   "region": "LON",
   "ssh_username": "root",
   "source_image": "IMAGE_UUID",
   "flavor": "general1-2",
   "image_name": "packer_test"
 }]
}
```

This is the command I run: PACKER_LOG=1 packer build -debug template.json

Please see gist to see debug output of the step where Packer reads the private SSH key and fails to parse. Please note I am able to use the SSH key manually. I have tested this with Packer version v0.8.2

https://gist.github.com/crimsongreen/52f2e7d21f77471835eb

**Comment by jacderida** [comment] 2015-07-29 12:39
I am also experiencing this issue. Exact same error in the log. I think this is something to do with something Rackspace have changed, because I haven't updated my Packer to the latest version, and my error is when building an existing template that was working before.

**Comment by lauraionescu** [comment] 2015-08-03 14:05
Hi,

We are also experiencing this issue. We contacted Rackspace and they confirmed that they were making changes. As Packer is a third-party tool, they will not support or troubleshoot it. 
It seems others have this issue as well:
https://groups.google.com/forum/#!topic/packer-tool/Squ0nStU5_8

Is anyone working on this issue?

**Comment by jacderida** [comment] 2015-08-03 15:09
Hi Laura,

I also seen that thread. The pull requests that had been merged didn't resolve the issue for us. I suspect this wouldn't be difficult to fix, but unfortunately I've never coded in Go before, and simply don't have the time to learn at the moment.

Rackspace are disappointing when it comes to giving support on tooling. I had an issue before where the images saved by Packer sometimes get stuck when you want to spin one up later, and they basically just said tough, you need to do the images in their supported way.

Cheers,

Chris

**Comment by joemiller** [comment] 2015-08-05 22:35
+1, we are running into this as well. We will look at trying to submit a patch if we can. Not familiar with the packer codebase so if anyone has a pointer that'd be great. Also I hope the bug is not in the gophercloud lib, although if so that might mean rackspace would be on the hook for a fix.

**Comment by joemiller** [comment] 2015-08-06 00:08
We are digging into this a little bit more, and while I don't have a solution in mind yet, here are some notes:

Using this quick patch to print out the privatekey returned by rackspace:
```
diff --git a/builder/openstack/ssh.go b/builder/openstack/ssh.go
index 2ab1add..fb116b1 100644
--- a/builder/openstack/ssh.go
+++ b/builder/openstack/ssh.go
@@ -64,6 +64,7 @@ func CommHost(
 func SSHConfig(username string) func(multistep.StateBag) (*ssh.ClientConfig, error) {
        return func(state multistep.StateBag) (*ssh.ClientConfig, error) {
                privateKey := state.Get("privateKey").(string)
+               log.Printf("[DEBUG]: state/privateKey: '%s'", privateKey)

                signer, err := ssh.ParsePrivateKey([]byte(privateKey))
                if err != nil {
```

Now that we have the key, we can copy-paste it into a file and manipulate it. It looks like a normal 2048-bit PEM-encoded RSA key.

openssl is happy to parse the key:
```
$ openssl asn1parse -in rax.pem                                                                                                                                                                                                                                                                                1 ↵
    0:d=0  hl=4 l=1191 cons: SEQUENCE
    4:d=1  hl=2 l=   1 prim: INTEGER           :00
    7:d=1  hl=4 l= 257 prim: INTEGER           :C12C68B2E7A0BD431BA810702A739DD773BE91017B9755EE63888F937D81E22F900DF07F76D028C3B373B39D556F2D22383D4BBA9C109156C491F9E050E9D187EE747519E954F8219BBDE08567FCA547F43D8796492DCA9D551137AEA8A0A403D29DA5FBA9CEE63FE140B5253882A4E340E11FC0069A21D279BBB2F8FA1EF49378295DBC0FE0F2C252807234A88D150EE5AB3C9A40AA78C4E25C0CE85840839AE3FC850D7BCA6505F3D738F5B97D1C33D9D35054579C0C516EF97BAC4E5213ECD2DA508B2343126F54DEB3EEC1FECF9EC538CF6581012C79B6CF05CB2BA2E84BBDF4165CAF4A60D41A43278CCF3A509AFDAB331D01860C86633B1EDFFFEA00E5
  268:d=1  hl=2 l=   3 prim: INTEGER           :010001
  273:d=1  hl=4 l= 256 prim: INTEGER           :18F3747E8F3E8AD3AD31D315B9D5FF304209FE4ED3B8E3678C41AA51E1A73220F4996853FE73BAA03480A05595206C12FC72A6626F2010B5C564198368D01AB9550A83C99A02D89DF6B0DADC406738AE07951EFB416E81BA3AAFA3A292B3551C0D4B41923507BD63C8E383C24FFF47EEF6855D857F14CF839127B6614465552FB186A93C45D2518E7B179C79C91A9D31E5449F14FA0814F7A5E61FB4DDB813DADC03161680F28DA1C8307BAE93F5E9D0A1E50D8C25CEEC3811E85C375DDA1095D09F622D300074F83AC5A7EB8608412ED354394356F470E2BEE6AEC918BD5C8A968832A66BDAD8B2044DA12F86454ECC5E4394A7D021A406B1548E103A44076D
  533:d=1  hl=4 l= 129 prim: INTEGER           :D04FE33588748483DCCF8185056CC18157A4DB03D2B7E1538D1F5E3AF281716CB26C5652388C0F1CC7F919214AB410B65354C565E232D1044D86ED9941B258E7B5862293749BC1B0D297FB03CFB699767705A78BE4AEF8F11CA4032799AB6340AB69C2EF7D92BC71842C92C1957F1A1D0DC024887B04AC0A4ED74986EE395AA7
  666:d=1  hl=4 l= 129 prim: INTEGER           :ED65535D27EE5EACE270725A3EFB7B7CC95FEAEDF268151B6B429F29D4C460540016B25B9B08E90F2174D331BD9CA03C2E499345B251113C11FB107CA725FE19CB3EDD6A532E876E773609B82BD6F2B70875BB24838F345FEED548814A37F50FD17735132DA0664595863875B792F55C2F5E293DEB13BE871B758B1C26C2D593
  799:d=1  hl=4 l= 128 prim: INTEGER           :02F31EA4836A22F63B0A352B4D085D3517A89DF14FEA8AA644394D7C4832CD085CFE6BBA7E527D644AF09C0A7CA4501844D5CE75C2DE35577A418EDBBCB269CFDE22281B2E6B86329AC8CC2521ABD440792EFB505FCC9A79CF8E02FD6C8FA0B829B535AD6E79C571560DCB863237BA86EECAE9B985046BEB397292F7F62799C1
  931:d=1  hl=4 l= 128 prim: INTEGER           :76EBB14D1339C7D7973F7929582FA676A672143FCA94F52DDD176CA009E3ADD5A68DB81F4794B91B49493A9ACA3F71CD73EA8B89F87FBFC075C96D42E48095BFDA1ECDCFFB876D749AE7490B277AEFEF5C9F8D7607296FB536F144F6EF7504A03DF0177859FCE5FEA99EA91DDF2E111772EB1A81D806F604BC6EAF97149BB95D
 1063:d=1  hl=4 l= 128 prim: INTEGER           :59D36E94294C86FFE21799C7DF0F66C93F7D1F1C3B2659AAB0E5E881A2A2E30DED53ADF7AE3B46E9AC10DDA0414A3801B23A55340A2891BBFFD9FBE30A4CC20494BD497ED55334EDB583B25D652FAF12F2A2376054CDA8810C9727DFBFA24BDC9C8C89FEBC6086AB1254D16AF7FF5D18CB33705F0268946175C078BE19D19DAB
```

We also created a 2048-bit RSA key with ssh-keygen so that we have something to compare against:
```
$ ssh-keygen -f openssh-rsa.pem -b 2048 -t rsa 
```

openssl asn1parse of this key looks similar enough and parses fine:

```
$ openssl asn1parse -in openssh-rsa.pem
    0:d=0  hl=4 l=1189 cons: SEQUENCE
    4:d=1  hl=2 l=   1 prim: INTEGER           :00
    7:d=1  hl=4 l= 257 prim: INTEGER           :C60AF445E891AC6EBE86B252EC04080A80759FD7B8A762BE73F4E7CDE15DF21BC4A8D1E0FC9F43A81E3F5576AA52083590FD8115DDCBFAFCBC23D6A9A5D4794C43EE250863A4DC26DAD96B0BD5112ABAB4B3E8C990A9E1C35E6FE33E250513668662AC6459B69F953D37B33510F5CEEC1CE1C479DB097E6AE0BC4B38BE6FF5240E9321ECFB1B63607926E9A4322655D64300CDB940CF03C35497D0AED52763EFAA731E7DF5E4E0741B007F348C83441188FAF7457EDEF97AA54E205848E0037D9DEF5068F758E2810F89A5BE67876BA236F9DA482EA0042C9B807BF579D60171AB2D30003478481626B38E7511CC407B58511931C6A0284C84BABD383182F5E9
  268:d=1  hl=2 l=   3 prim: INTEGER           :010001
  273:d=1  hl=4 l= 257 prim: INTEGER           :A8F3936D48796E6793F7098EA076D7FD4D960B6557CCC4FAC1A5FF53AE9E1CFBFF8C1E7118532EBEEFFF0C040E4DA95F39706B7DA21870E8C800B3134BBBB63790044C6799CA7D5E507A074EB2D8D06133E400066579E87669CC7E4AF7FE1A8CEEBCA36180FFC1A8E9EEE8DDAEB8656D1D3EA605670DF4616D94757FD54762137D3595A4014A41635AD19198A2937638A19BB13E2FE16A7D31081559F16A8EF8523ADB1925B0C89E673765B9F852BA5F3D339CA9FA3E19B33B9BDCF2984A78FE84B47190889DD7B9CE9230C4EFBE7897B04760079A960C22058705DF81CA1D4DD83256A9D4E10C2B75464055C7C51BA25EF32FEF4BC522BD79BE26DE9BD18079
  534:d=1  hl=3 l= 129 prim: INTEGER           :F487D088F007B90C29DDE3D148F0A7173B0AA7DC4D2B9B9C5D74864C00AEB1B53E5A4D35555ECC9C120516CC10BE8E65C4B9828BB1BCE67C370B1F2E0C08361F3B7E9DF8D979FE23714483D5718BA0CBE7660AA89338632257EC1B339D6BFD7FCDADCB5CF365167B7EF701A363C737EC86C0F513AA2442CBE895AA2E82E9F05F
  666:d=1  hl=3 l= 129 prim: INTEGER           :CF54F0E188CF22D844F836E3A41D87CA1A77AD8AD249CA043496A7EBE0F3714C06DAC4D4527E0B7EF371C18AAD78F6D3C72C4D75C1A17E320BC45A4D7F70EDE6A8E74247D999671E80BCA44F0762BB289D79DB679FBCE907086D11364F6D039B2C397641903398FDA6B1A2D316ECBDB97D7FA03CB79C7EC06896E1C43F031EB7
  798:d=1  hl=3 l= 129 prim: INTEGER           :DC0EC54A16C8BC6D07D859C6E3DF3E5F979095539A571E28EFA9879A2A1B0C6DD0F92EF64A278FF6FBF87C7594B4082DE98610C76A6257017DFF9245BC2A3F9A87CE00980C0ECEF8525C984FA36946817972C930BF9C450A89193FB98977BFA01E16C326991B65CA298E5C790FB81EC9CAD3273A552960BB644A1BE6D38577FD
  930:d=1  hl=3 l= 128 prim: INTEGER           :6F9C7A4FEF2612CBF9D4E53786919F17DD47AFD49B7FBD90A5FEB446F6C216ABA6C4FE508E57EC385B3551CB25B788A859003072C3D9FBE555104ECC895E71B34A19B444998F4B43D069BCCA0E5FC8010545242794864DABCB8D6B46A15B3E25BA98F46037108FBB7C9103E63EE1130157DDEC94C3032BF8C854F114841759E1
 1061:d=1  hl=3 l= 129 prim: INTEGER           :BFD608F862E8665AADCD854E9B69B36DD4675D0037D80B8DC8ABB4F4A268BF2314F2DCFAB07134922B00D1C3C80DD2B7074503B942358A855E247124D208A5E67CC74E57D7B9291E8323E1A415914311FA11FEC3787F318152DE6B47883B6EA837CE1C3B52D09F6BF9CA2C02DE449EEF76C9229672AB2FC511D6597CA7C4B81C
```

The most interesting thing so far has been the results of converting the key from PEM -> DER -> PEM, using openssl. The resulting PEM generated by openssl is different for the rackspace-generated key, but is identical for the key generated by ssy-keygen:

```
$ openssl rsa -in rax.pem -inform pem -out rax.der -outform der
$ openssl rsa -in rax.der  -inform der   -out rax-new.pem -outform pem
$ md5sum rax.pem rax-new.pem
e8de49bb896a16bd00a2122974d37a6e  rax.pem
4478398190aa9455321e4cb3dc10fd8d  rax-new.pem

$ openssl rsa -in openssh-rsa.pem -inform pem -out openssh-rsa.der -outform der
$ openssl rsa -in openssh-rsa.der -inform der -out openssh-rsa-new.pem -outform pem
$ md5sum  openssh-rsa.pem openssh-rsa-new.pem
cc9ff4ec185aafd5671463b7048f6b37   openssh-rsa.pem
cc9ff4ec185aafd5671463b7048f6b37  openssh-rsa-new.pem
```

It looks like some folks working on gosnmp may have run into a similar issue too: http://comments.gmane.org/gmane.comp.lang.go.general/68138

At this point, I'm not sure what to do yet. I might consider converting from PEM->DER->PEM inside packer, although this would be hacky. It might be possible to patch the asn1 lib in golang core but if this is a disagreement between strict and loose DER compliance as the gosnmp thread has me believing, this could be a tough path.

It's also possible that RAX or Openstack could fix this on their end, but that also might be tough since this keys they generate appear to work with most other things besides golang's gossh and asn1 libs.

**Comment by lauraionescu** [comment] 2015-08-06 08:46
We had a look at the packer code, my team has no experience with golang however. 
You're right, the issue seems to be with the temporary keys generated by packer:

https://github.com/mitchellh/packer/blob/02273207dfd45985b80494fa662987423f943368/builder/openstack/step_key_pair.go#L52-L54

**Comment by joemiller** [comment] 2015-08-06 15:22
New info learned from our account folks @ rackspace:

- Here is the relevant change in openstack/nova : https://github.com/openstack/nova/commit/3f3f9bf22efd2fb209d2a2fe0246f4857cd2d21a  . The creation of ssh keys was switched from shelling out to ssh to using the paramiko python lib.
- paramiko returns keys in BER format instead of DER. DER being a stricter subset of BER. http://luca.ntop.org/Teaching/Appunti/asn1.html
- Ultimate solution might be a BER decoder in golang.
- Here is a BER lib that might prove useful: https://github.com/go-asn1-ber/asn1-ber

**Comment by coreywright** [comment] 2015-08-10 06:25
for the record (though @joemiller reported the gist of it), in case someone wants to work this from the packer/go consuming side (as compared to the nova/paramiko producing side), here's what i sent to our internal mailing list, specifically including links/references to code:

> I can now specifically say the problem is that Packer is limited to DER [1] while paramiko uses BER [2].
> 
> Distinguished Encoding Rules (DER) is a strict subset of Basic Encoding Rules (BER), with both being encoding rules for ASN.1. \[3\]  (I hope I got my terminology right there.)
> 
> The popular tools [4] consume BER and produce DER so there's no interoperability issue with the 800 lbs gorillas of the open source crypto and SSH worlds.
> 
> The solution is to integrate a BER decoder/unmarshaller [5] into the Go standard library (or at least for use by the/a pkcs1 package [6]).
> 
> [1] http://golang.org/src/encoding/asn1/asn1.go#L12
> [2] https://github.com/paramiko/paramiko/blob/master/paramiko/ber.py
> [3] http://luca.ntop.org/Teaching/Appunti/asn1.html
> [4] OpenSSL and OpenSSH, though the later uses the former
> [5] https://github.com/go-asn1-ber/asn1-ber
> [6] http://golang.org/src/crypto/x509/pkcs1.go#L39
> 
> Corey
> coreywright

**Comment by darrenhaken** [comment] 2015-08-17 16:49
Any idea on when this will be fixed & released?

At the moment we're running off a version of Packer built from source and we really want to get back onto the release cycle.

**Comment by jacderida** [comment] 2015-08-17 17:03
@darrenhaken What branch can you build from to get a fix? We tried building from source and the problem was still there.

**Comment by cbednarski** [comment] 2015-08-17 18:52
@darrenhaken @jacderida `0.8.5` includes a work-around that lets you specify an existing key instead of using a temporary key. I don't think I've seen a patch to re-implement the key generation, though.

**Comment by darrenhaken** [comment] 2015-08-17 19:13
So to confirm this has been released in 0.8.5? 

A member of my team said it hasn't been included in the release.

**Comment by coreywright** [comment] 2015-08-20 00:54
As an update from the OpenStack Nova perspective: assuming Paramiko releases a new version that includes https://github.com/paramiko/paramiko/pull/394 in September (as planned) and Nova doesn't revert or migrate away from Paramiko (before then), then Packer will be compatible with Nova again.

**Comment by conord33** [comment] 2015-09-02 16:45
@darrenhaken @cbednarski do you know how to use a custom key?  I have tried with `0.8.6` but with no success.  I have added the public key to rackspace and used the name on rackspace as the `ssh_keypair_name` value.  However, packer still creates a temporary key on rackspace, then times out.

Am I doing something wrong? Or is this feature not working?

**Comment by joemiller** [comment] 2015-09-02 17:28
This works, although we'd rather have the temporary key feature functioning
again. Here's a snippet of what we use. Perhaps you're missing the
`ssh_private_key_file` attr:

```
 {
      "type": "openstack",
      "ssh_private_key_file": "packer_build",
      "ssh_keypair_name": "packer_build",
      "ssh_username": "root",
...
```

and a file named packer_build exists with the private key contents.

**Comment by conord33** [comment] 2015-09-02 18:12
What version of packer are you using?

I am using `0.8.6` and when I use the `ssh_private_key_file` key I get the following error:
```
openstack output will be in this color.

==> openstack: Discovering enabled extensions...
==> openstack: Loading flavor: 2
    openstack: Verified flavor. ID: 2
==> openstack: Launching server...
==> openstack: Error launching source server: Expected HTTP response code [201 202] when accessing [POST https://iad.servers.api.rackspacecloud.com/v2/973472/servers], but got 400 instead
==> openstack: {"badRequest": {"message": "Invalid key_name provided.", "code": 400}}
Build 'openstack' errored: Error launching source server: Expected HTTP response code [201 202] when accessing [POST https://iad.servers.api.rackspacecloud.com/v2/973472/servers], but got 400 instead
{"badRequest": {"message": "Invalid key_name provided.", "code": 400}}

==> Some builds didn't complete successfully and had errors:
--> openstack: Error launching source server: Expected HTTP response code [201 202] when accessing [POST https://iad.servers.api.rackspacecloud.com/v2/973472/servers], but got 400 instead
{"badRequest": {"message": "Invalid key_name provided.", "code": 400}}

==> Builds finished but no artifacts were created.
```

I am also using these env vars `OS_AUTH_SYSTEM=rackspace` `OS_AUTH_URL=https://identity.api.rackspacecloud.com/v2.0/`

**Comment by joemiller** [comment] 2015-09-02 18:22
It sounds like rax's api doesn't know about the key_name. The ssh-key has
to be in the same RAX account _and_ same region. We often run into that
problem. Check that.

**Comment by conord33** [comment] 2015-09-02 18:31
That was it! Thanks a lot @joemiller !

I just needed to add the public key to rackspace with the same name.

**Comment by brandfocus** [comment] 2015-11-03 15:05
Incase anyone runs into the same issue when creating child RAX accounts with custom permission sets the key must be added to each account individually. Just adding the key to parent owner account is not sufficient.

**Comment by vallard** [comment] 2015-12-16 01:42
Not using Rackspace, but saw the same errors.  When I added the ```ssh_key_pair_name``` I got the error: 
```
 error(s) occurred:

* ssh_private_key_file is invalid: Error setting up SSH config: asn1: structure error: superfluous leading zeros in length
```

the log is: 
```
2015/12/15 17:39:17 Build debug mode: true
2015/12/15 17:39:17 Force build: false
2015/12/15 17:39:17 Preparing build: openstack
2015/12/15 17:39:17 Build 'openstack' prepare failure: 1 error(s) occurred:

* ssh_private_key_file is invalid: Error setting up SSH config: asn1: structure error: superfluous leading zeros in length2015/12/15 17:39:17 ui error: 1 error(s) occurred:

* ssh_private_key_file is invalid: Error setting up SSH config: asn1: structure error: superfluous leading zeros in length
2015/12/15 17:39:17 waiting for all plugin processes to complete... 2015/12/15 17:39:17 /usr/local/bin/packer-provisioner-shell: plugin process exited
2015/12/15 17:39:17 /usr/local/bin/packer-builder-openstack: plugin process exited
```

**Comment by vallard** [comment] 2015-12-16 05:50
Figured out my error was my key file was bad.  Typical.  As soon as I post something I find the answer.  In this case my private key was a *.pem file.  Regenerating a new one with ssh-keygen -t rsa worked by specifying the ```ssh_private_key_file``` name.  Leaving my blunder up to help posterity.  Don't judge me too harshly.  Thanks for all the hints!

**Comment by derks** [comment] 2015-12-16 07:10
I just ran into this issue as well on Rackspace Public Cloud.  The resolution for me (as mentioned previously in this thread) was:

 * All regions need the SSH public key file (with the same name as `ssh_keypair_name`)
 * The builder config needs both `ssh_private_key_file` **and** `ssh_keypair_name`


This biggest hangup was that I can't find any reference to using `ssh_keypair_name` and only tried it after finding this thread, and the error from Packer was a vague "SSH Authentication Failed".  Would benefit from adding notes on the `ssh_keypair_name` to the doc where applicable.

**Comment by rickard-von-essen** [comment] 2016-01-28 21:18
@cbednarski Maybe this is sever enough to add a note about it in the docs and it seams that it won't be resolved very soon? What do you think?

**Comment by cbednarski** [comment] 2016-01-28 23:07
@rickard-von-essen I need to read through the thread in more detail but it sounds like there is a gap in the docs on how to get this to work. Two issues I think:

1. The temporary key pair generation is broken because (IIRC) the key format changed.
2. The workaround is tricky because you need several things configured correctly for it to work. We can improve the docs for this certainly.

Regarding fixing #1, I have a few questions:

1. Does gophercloud have a fix and we just need to call it properly in packer?
2. Is this specific to rackspace or does it affect all openstack deployments?

I don't use openstack or rackspace so there's some setup complexity involved for me to look into this personally. Based on my scheduling I may be able to address this for 0.10 but I can incorporate a PR sooner if someone else has a fix.

**Comment by rickard-von-essen** [comment] 2016-01-29 11:17
Most of the details are in https://github.com/mitchellh/packer/issues/2526#issuecomment-128409275.

 1. No, gophercloud don't do anything with the keys. The problem starts from here:
https://github.com/mitchellh/packer/blob/024132a698092b0d950d0aaffdb8821616de6a72/builder/openstack/ssh.go#L68 and the error is probably in https://github.com/golang/crypto/blob/master/ssh/keys.go
 2. Yes this affects all OpenStack deployments using Liberty (Oct 2015) or later.

I opened an issue golang/go#14145 to get to the bottom with the parsing.

**Comment by rickard-von-essen** [comment] 2016-01-30 14:08
I'll create a workaround for this.

**Comment by rickard-von-essen** [comment] 2016-02-09 12:31
#3135 have a workaround for this where it uses OpenSSL to convert the key.

**Closed by rickard-von-essen** 2016-02-09 12:31 UTC
Labels: bug, builder/openstack

**Comment by smolinari** [comment] 2016-02-22 07:00
I am running into the same problem. Exactly as the OP describes it. 

Running 0.9.0. 

Also getting 

```
2016/02/22 07:58:49 packer-builder-openstack.exe: 2016/02/22 07:58:49 [DEBUG] Error getting SSH config: Error setting up SSH config: asn1: structure error: superfluous leading zeros in length
```

Scott

**Comment by rickard-von-essen** [comment] 2016-02-22 07:37
@smolinari Do you have ```openssl``` on the path?

**Comment by smolinari** [comment] 2016-02-22 07:47
Nope. Added and testing. 

Scott

**Comment by smolinari** [comment] 2016-02-22 08:23
@rickard-von-essen - I double checked the OpenSSL installation too, nothing helped. Still getting the same error. 

Scott

**Comment by rickard-von-essen** [comment] 2016-02-22 08:52
@smolinari Could you run with ```PACKER_LOG=1 packer build ...``` and gist the log.

**Comment by smolinari** [comment] 2016-02-22 19:21
@rickard-von-essen  

Here is the gist. 

https://gist.github.com/smolinari/481cbcf213edac13d7f1

Scott

**Comment by rickard-von-essen** [comment] 2016-02-22 20:08
@smolinari Could you remove everything in ```C:\packer``` and install v0.9.0, I think you are running the old plugins from v0.8.6. (see [CHANGELOG.md](https://github.com/mitchellh/packer/blob/master/CHANGELOG.md#090-february-19-2016))

**Comment by smolinari** [comment] 2016-02-22 20:13
Yeah, doing that now (because of the conversation in the other issue). 

Scott

**Comment by smolinari** [comment] 2016-02-22 20:20
Holy bean bags Batman! That was it. 

Thanks for the support Rickard! I appreciate it alot! 

Scott

**Comment by rickard-von-essen** [comment] 2016-02-22 20:22
@smolinari :+1: , I filed #3247 .
