### ISSUE TITLE
Packer hangs after script provisioner reboots vm (virtualbox-iso builder)

### ISSUE THREAD

**Issue by ktstevenson** [mitchellh/packer#4684] opened 2017-03-19 22:17 UTC
Packer reliably hangs during script provisioning if one of the scripts reboots the vm. The virtualbox vm reboots and responds correctly, but it looks like packer doesn't notice that the reboot occurs. I don't see any packer log messages between the time my script echos "rebooting" and when I hit ctrl-c to terminate the build.

The build runs to completion if I remove the script which reboots the vm.

Packer version: 0.12.3
Virtualbox version: 5.1.18r114002
MacOS Sierra 10.12.3

[Gist with related files](https://gist.github.com/ktstevenson/ba41b160da2426112c1e11ce1fcde1be)

**Comment by marema31** [comment] 2017-03-19 22:28
Reboot in shell provisionner tends to fail or hangs the build. Even the expect_disconnect seems to not always catch reboot.

I recommend you to use a script that stop the sshd daemon and reboot in nohup with a pause_before argument on the next provisionner has described in #4137.
We use it heavily at work and its working great.

I've proposed (#4555) a provisionner to solve that problem that currently waits for review.

**Comment by ktstevenson** [comment] 2017-03-19 23:08
I've tried changing my update.sh script to:
`yum -y update`
`systemctl stop sshd.service`
`nohup shutdown -r now < /dev/null > /dev/null 2>&1 &`
`sleep 300`


I'm still seeing a hang. (I waited 10 minutes this time.) I see no evidence that Packer ever attempts to start the next script in the list. I'd almost rather see a failure than this kind of hang. At least then I'd have more to debug 😄

**Comment by ktstevenson** [comment] 2017-03-20 00:14
I've worked around this by following the advice from @marema31 with a small twist.

Instead of the 'sleep 300', I'm doing an 'exit 0' after the nohup wrapped shutdown command. This seems to let Packer know that it can move on. A 'pause_before' directive is required before the next script.

So far, this is working.

**Comment by mwhooker** [comment] 2017-03-20 20:46
Thanks for the report. It looks like there are some good details here that should help us find a good solution. 

I think the reboot provisioner is probably the way to solve this, long term

**Comment by gaserre** [comment] 2017-03-24 16:53
I think there is a regression compared to packer 0.12.0. 
I am using the restart sshd method with a vmware-iso on VMWare Workstation Pro.  
In packer 0.12.0, it works reliably. 
In packer 1.1.0 built from master (last week or so) I see a hang after network interface is brought down and dhcp server is restarted.  Here's the script output:
```
    vmware-ova-1: DHCPOFFER of 192.168.254.128 from 192.168.254.254
    vmware-ova-1: DHCPACK of 192.168.254.128 from 192.168.254.254
    vmware-ova-1: bound to 192.168.254.128 -- renewal in 825 seconds.
    vmware-ova-1: + rm -fr /var/lib/dhcp/dhclient_dp0p160p1_lease /var/lib/dhcp/dhclient.leases /var/lib/dhcp/dhclient-v4-dp0p160p1-resolv.conf
==> vmware-ova-1: Stopping virtual machine...
==> vmware-ova-1: Deleting output directory...
Build 'vmware-ova-1' errored: Retryable error: Error removing temporary script at /tmp/script_975.sh: dial tcp 192.168.254.128:22: getsockopt: connection refused
```
And here's the shell provisioner:
```
{
        "type": "shell",
        "execute_command": "echo 'vyatta' | {{ .Vars }} sudo -E -S /bin/bash -e '{{ .Path }}'",
        "script": "provision-vmware.sh"
}
```
and the last bits of the shell script:
```
# interface went down earlier 
# temporarily restart IF and DHCP so packer can successfully shutdown
sleep 10
ip link set dev dp0p160p1 up
dhclient -v dp0p160p1

# clear our DHCP leases
rm -fr /var/lib/dhcp/*
```

**Comment by mwhooker** [comment] 2017-03-24 18:38
@gaserre There was a bug in the way the way the used to handle cleaning up provisioning scripts. It used to not clean up the script if there was a disconnect. It seems like maybe you were relying on that behavior, and now that it's fixed, your script doesn't work any more. I think the best option is to either configure the guest in such a way that you can reconnect to it after running your provisioning script, or set `skip_clean` to `true`: https://www.packer.io/docs/provisioners/shell.html#skip_clean

**Comment by mwhooker** [comment] 2017-03-24 19:10
I'm not able to reproduce the issue with vmware or virtualbox

```
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 starting remote command: echo 'vagrant' | PACKER_BUILDER_TYPE='virtualbox-iso' PACKER_BUILD_NAME='ubuntu-1604-vbox' PACKER_HTTP_ADDR='172.16.167.1:8756'  sudo -E -S bash '/tmp/script_3153.sh'
2017/03/24 12:08:28 ui:     ubuntu-1604-vbox: Rebooting the machine...
    ubuntu-1604-vbox: Rebooting the machine...
2017/03/24 12:08:28 ui:     ubuntu-1604-vbox: [sudo] password for vagrant: Failed to stop network.service: Unit network.service not loaded.
    ubuntu-1604-vbox: [sudo] password for vagrant: Failed to stop network.service: Unit network.service not loaded.
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 Remote command exited without exit status or exit signal.
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 [INFO] RPC endpoint: Communicator ended with: 2300218
2017/03/24 12:08:28 [INFO] 25 bytes written for 'stdout'
2017/03/24 12:08:28 [INFO] 94 bytes written for 'stderr'
2017/03/24 12:08:28 [INFO] RPC client: Communicator ended with: 2300218
2017/03/24 12:08:28 [INFO] RPC endpoint: Communicator ended with: 2300218
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 [INFO] 25 bytes written for 'stdout'
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 [INFO] RPC client: Communicator ended with: 2300218
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 [INFO] 94 bytes written for 'stderr'
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 opening new ssh session
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 ssh session open error: 'EOF', attempting reconnect
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 reconnecting to TCP connection for SSH
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 handshaking with SSH
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 handshake complete!
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 opening new ssh session
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 [INFO] agent forwarding enabled
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 starting remote command: rm -f /tmp/script_3153.sh
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 [INFO] RPC endpoint: Communicator ended with: 0
2017/03/24 12:08:28 [INFO] RPC client: Communicator ended with: 0
2017/03/24 12:08:28 [INFO] RPC endpoint: Communicator ended with: 0
2017/03/24 12:08:28 packer: 2017/03/24 12:08:28 [INFO] RPC client: Communicator ended with: 0
2017/03/24 12:08:28 ui: ==> ubuntu-1604-vbox: Gracefully halting virtual machine...
```

@ktstevenson  if you can post a complete json (need kickstarter) that reproduces the issue, I can investigate further

**Comment by ktstevenson** [comment] 2017-03-24 20:31
I've added the centos.ks kickstart file to the [gist](https://gist.github.com/ktstevenson/ba41b160da2426112c1e11ce1fcde1be). 

I've run two more builds and both hung. The guest is not changing IP addresses after the reboot.

It still looks to me like packer never sees the update.sh script complete.

**Comment by mwhooker** [comment] 2017-03-24 21:11
ok, thank you @ktstevenson. I can reproduce now. Solved by removing the lines `systemctl stop network` and `sleep 60`.

I'm not sure why we don't seem to realize we disconnected. Will investigate a bit more, but I'd like you to test with the above changes

**Comment by mwhooker** [comment] 2017-03-24 22:09
I was able to solve this by setting a deadline on the tcp connection

```
diff --git a/communicator/ssh/communicator.go b/communicator/ssh/communicator.go
index e3082ba..c4c59fb 100644
--- a/communicator/ssh/communicator.go
+++ b/communicator/ssh/communicator.go
@@ -80,6 +80,8 @@ func (c *comm) Start(cmd *packer.RemoteCmd) (err error) {
                return
        }

+       c.conn.SetDeadline(time.Now().Add(time.Minute))
+
        // Setup our session
        session.Stdin = cmd.Stdin
        session.Stdout = cmd.Stdout
@@ -272,6 +274,8 @@ func (c *comm) reconnect() (err error) {
                return
        }

+       c.conn.SetDeadline(time.Now().Add(1 * time.Minute))
+
        log.Printf("handshaking with SSH")

        // Default timeout to 1 minute if it wasn't specified (zero value). For
```

getting this merged is going to be a bigger project, though, because we'll need to make the timeout configurable, and evaluate where we set it. i.e., will need more testing.

Going to set this for after 1.0, but I believe a fair workaround is to not take down the network until then

**Comment by gaserre** [comment] 2017-03-24 22:12
@mwhooker Updating to the latest master and rebuilding fixed my problem (without using skip_clean).

**Comment by ktstevenson** [comment] 2017-03-25 02:22
@mwhooker I can confirm that removing `systemctl stop network` and `sleep 60` resolve the problem and my box builds as expected.

Thank you!

**Comment by mwhooker** [comment] 2017-03-25 02:31
Going to close and track the deadlining in #4709. Glad you got it working!

**Closed by mwhooker** 2017-03-25 02:31 UTC
Labels: builder/virtualbox, communicator/ssh

**Comment by secbitchris** [comment] 2017-09-21 14:56
FYI I experienced this with packer 1.1.0 just as described in this thread. Machine would fail to properly reboot, and script would disconnect.

Replacing "reboot" and "sleep 60" in my script with the following worked:

    echo "====> Shutting down the SSHD service and rebooting..."
    systemctl stop sshd.service
    nohup shutdown -r now < /dev/null > /dev/null 2>&1 &
    exit 0

**Comment by aksuna** [comment] 2017-09-27 19:38
Im experienced the same thing using packer 1.1.0 
`2017/09/27 13:54:27 packer: 2017/09/27 13:54:27 Remote command exited without exit status or exit signal.
2017/09/27 13:54:27 packer: 2017/09/27 13:54:27 [INFO] RPC endpoint: Communicator ended with: 2300218
2017/09/27 13:54:27 [INFO] 3058 bytes written for 'stdout'
2017/09/27 13:54:27 [INFO] 0 bytes written for 'stderr'
2017/09/27 13:54:27 [INFO] RPC client: Communicator ended with: 2300218
2017/09/27 13:54:27 [INFO] RPC endpoint: Communicator ended with: 2300218
2017/09/27 13:54:27 packer: 2017/09/27 13:54:27 [INFO] 3058 bytes written for 'stdout'
2017/09/27 13:54:27 packer: 2017/09/27 13:54:27 [INFO] 0 bytes written for 'stderr'
2017/09/27 13:54:27 packer: 2017/09/27 13:54:27 [INFO] RPC client: Communicator ended with: 2300218
2017/09/27 13:54:27 ui:     vmware-iso:   Installing : cpp-4.8.3-9.el7.x86_64                                       3/7
    vmware-iso:   Installing : cpp-4.8.3-9.el7.x86_64                                       3/7
2017/09/27 13:54:27 [INFO] (telemetry) ending shell
2017/09/27 13:54:27 [INFO] (telemetry) found error: Script disconnected unexpectedly.
2017/09/27 13:54:27 packer: 2017/09/27 13:54:27 Executing: /usr/bin/vmrun [-T ws list]
2017/09/27 13:54:28 packer: 2017/09/27 13:54:28 stdout: Total running VMs: 0
2017/09/27 13:54:28 packer: 2017/09/27 13:54:28 stderr:
2017/09/27 13:54:28 ui: ==> vmware-iso: Deleting output directory...
==> vmware-iso: Deleting output directory...
2017/09/27 13:54:31 [INFO] (telemetry) ending vmware-iso
2017/09/27 13:54:31 [INFO] (telemetry) found error: Script disconnected unexpectedly.
2017/09/27 13:54:31 ui error: Build 'vmware-iso' errored: Script disconnected unexpectedly.
2017/09/27 13:54:31 Builds completed. Waiting on interrupt barrier...
2017/09/27 13:54:31 machine readable: error-count []string{"1"}
2017/09/27 13:54:31 ui error: 
==> Some builds didn't complete successfully and had errors:
2017/09/27 13:54:31 machine readable: vmware-iso,error []string{"Script disconnected unexpectedly."}
2017/09/27 13:54:31 ui error: --> vmware-iso: Script disconnected unexpectedly.
2017/09/27 13:54:31 ui: 
==> Builds finished but no artifacts were created.
Build 'vmware-iso' errored: Script disconnected unexpectedly.
`

**Comment by rickard-von-essen** [comment] 2017-09-27 19:56
See the CHANGELOG.md there is a backwards incompatible change regarding scripts causing the ssh session to be disconnected.
