### ISSUE TITLE
Request for a git-head function

### ISSUE THREAD

**Issue by wilrnh** [mitchellh/packer#1832] opened 2015-01-11 06:52 UTC
Similar to the {{timestamp}} function, a git-head function simply returns the value of `git rev-parse --short HEAD`. A use-case for this is to name my AMIs/images in line with the version of the repo that was used to build them. I'm currently passing the commit hash as a user variable, but I think a built-in function would be practical here.

**Comment by ColinHebert** [comment] 2015-01-13 06:38
The problem is that's specific to git users, relies on git being installed and introduces complexity where it isn't needed.

I think that passing the commit hash as a user is the most sensible option. (plus some might say they want the current ref name or what not).

**Comment by sethvargo** [comment] 2015-02-25 00:10
Please see my reply here: https://github.com/mitchellh/packer/issues/1711#issuecomment-75871729. I'm going to close this issue (since the other one is older) and we can continue discussion on the other ticket :smile:

**Closed by sethvargo** 2015-02-25 00:10 UTC
