### ISSUE TITLE
Post-Processors for azure-arm builder?

### ISSUE THREAD

**Issue by hdatteln** [mitchellh/packer#4246] opened 2016-12-03 16:06 UTC
Hi, 
This is a question regarding the azure-arm builder and post-processors.

I was looking for a good way to spin up either a VM in Azure, or a vagrant box from a newly packer-created Azure .vhd image, for testing right after the image has been created.
So I thought I could use a post-processor for this, but I couldn't find anything that worked for me.

- the 'vagrant' post-processor currently doesn't support Azure, so that wasn't an option. I have seen that there is a request to support this (issue #[3607](https://github.com/mitchellh/packer/issues/3607)) , so maybe in future.
- the shell_local post-processor doesn't do anything, I assume because the azure-arm builder doesn't actually download any artifacts to the local machine. (maybe if it would be an idea to download the .json template?)

Do you have any further suggestions on how to go about this? I am wondering if i am overlooking anything.

Thank you, 
Heidi

**Comment by boumenot** [comment] 2016-12-04 00:49
These types of questions are better handled on the forums.  See _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) and https://www.packer.io/community/.

Having said that, there are many good examples on the [Azure/azure-quickstart-templates](https://github.com/Azure/azure-quickstart-templates) repo.  See [201-vm-specialized-vhd](https://github.com/Azure/azure-quickstart-templates/tree/master/201-vm-specialized-vhd) as a starting point.

**Comment by hdatteln** [comment] 2016-12-04 10:44
Cool, I'll move my question to the forums and rephrase it a little bit. I was wondering more about the post-processor bit, not so much about the Azure templates themselves.

**Comment by boumenot** [comment] 2016-12-04 14:35
Maybe I do not understand your question then.  Are you asking how to deploy the VHD created by Packer in Azure inside the VM that Packer spins up to create said VHD?

Or, are you asking how to deploy the VHD after the Packer build has finished by using a post-processor?  Basically, one configuration file to create the VHD, and then deploy it?  Packer for Azure emits a template that can be used to deploy the VHD that was just created.  Unfortunately, the template needs to be updated before it can be used.  We do not have a post-processor to do that, but we can change this issue to reflect that request.

**Comment by hdatteln** [comment] 2016-12-08 08:49
Hi, 
Right, I was wondering if there was a way to create the VHD and then deploy it, all from one configuration file, using a post-processor. 
Also, there might be other post-processing steps that I might want to take after a new image artifact has been built, e.g. grab the artifact URL and stick it into a catalog list somewhere or something like that (just an example).

**Comment by boumenot** [comment] 2016-12-08 19:37
Your request sounds reasonable to me.  There is a little bit work on the builder side that needs to be done - emit an  JSON artifact document that the local shell processor can use to deploy a VM to Azure.  A simple solution may involve the use for the XPlat CLI.  I do not know enough yet.

**Comment by hdatteln** [comment] 2016-12-09 19:11
Thank you for looking into this!

**Comment by mwhooker** [comment] 2017-01-30 21:57
I know this issue is older, but i'm going to mark this as a duplicate of #4350

**Closed by mwhooker** 2017-01-30 21:57 UTC
Labels: builder/azure, enhancement, help-wanted, post-processor/azure
