### ISSUE TITLE
Ansible Remote failed to handshake

### ISSUE THREAD

**Issue by emoshaya-cognito** [mitchellh/packer#3595] opened 2016-06-03 16:36 UTC
- Packer Version:0.10.1
- Host platform: CentOS

I am trying to use Packer's Ansible Remote Provisioner with both Docker and Amazon-EBS builders. However, I'm really struggling to connect to the builders.

I keep getting the following errors:

    Docker-Image: SSH proxy: accepted connection
==> Docker-Image: authentication attempt from 127.0.0.1:51886 to 127.0.0.1:42709 as centos using none
==> Docker-Image: centos is not a valid user
==> Docker-Image: authentication attempt from 127.0.0.1:51886 to 127.0.0.1:42709 as centos using publickey
==> Docker-Image: failed to handshake
    Docker-Image: fatal: [updatesvc]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
    Docker-Image:

[packer-template.txt](https://github.com/mitchellh/packer/files/298020/packer-template.txt)
[jenkins_ssh.txt](https://github.com/mitchellh/packer/files/298008/jenkins_ssh.txt)
[centos_ssh.txt](https://github.com/mitchellh/packer/files/298009/centos_ssh.txt)

**Comment by cbednarski** [comment] 2016-06-03 23:58
Thanks for the report. I think this is a duplicate of #3260. There is a [workaround documented](https://github.com/mitchellh/packer/issues/3260#issuecomment-199233230) in the thread. If this does not help, please add additional details to that thread. I'm going to close this one as a duplicate in order to keep the discussion in one place.

**Closed by cbednarski** 2016-06-03 23:58 UTC
Labels: duplicate, provisioner/ansible-remote
