### ISSUE TITLE
Auth error on amazon-ebs builder @ eu-central-1

### ISSUE THREAD

**Issue by ilk** [mitchellh/packer#1713] opened 2014-12-02 17:32 UTC
I got this error when I try to build a machine on eu-central-1. I used packer v 0.7.2 and the 8.0.0.dev version.

> ==> amazon-ebs: Error querying AMI: AWS was not able to validate the provided access credentials (AuthFailure)
> Build 'amazon-ebs' errored: Error querying AMI: AWS was not able to validate the provided access credentials (AuthFailure)

```
...
  "builders": [{
    "type": "amazon-ebs",
    "access_key": "xxxx",
    "secret_key": "xxxx",
    "region": "eu-central-1",
    "source_ami": "ami-90....",
    "instance_type": "t2.small",
    "ssh_username": "admin",
    "ami_name": "ilk-base-ami {{isotime| clean_ami_name}}",
    "ami_virtualization_type": "hvm",
    "security_group_id":"sg-8e7....",
    "vpc_id": "vpc-c4c....",
    "subnet_id" : "subnet-3b3...",
    "run_tags": {"Name":"packerami"}
  }],
...
```

With eu-west-1 it works fine.

**Comment by arosenhagen** [comment] 2015-01-02 10:58
related to V4 signing support for ec2 https://github.com/mitchellh/goamz/issues/120
you have to stick to eu-west-1 atm.

**Comment by nchammas** [comment] 2015-01-24 21:36
Is this issue the same as #1646?

**Comment by sethvargo** [comment] 2015-02-24 23:29
Closing as a duplicate of #1646

**Closed by sethvargo** 2015-02-24 23:29 UTC
