### ISSUE TITLE
Chef - Cleaning up chef node fails

### ISSUE THREAD

**Issue by a13x212** [mitchellh/packer#2342] opened 2015-06-29 02:44 UTC
Currently using a chef server 12 without a valid SSL certificate. Chef client and knife commands will warn you about this. 

I got around chef-client by using a config_template and adding option “trusted_certs_dir”. Adding an option to chef provisioner would be a nice to have. 

During “Cleaning up chef node”, it uses the knife command which fails.

==> docker: Cleaning up chef node...
    docker: WARNING: No knife configuration file found
    docker: ERROR: SSL Validation failure connecting to host: julia - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
    docker: ERROR: Could not establish a secure connection to the server.
    docker: Use `knife ssl check` to troubleshoot your SSL configuration.
    docker: If your Chef Server uses a self-signed certificate, you can use
    docker: `knife ssl fetch` to make knife trust the server's certificates.
    docker:
    docker: Original Exception: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

https://github.com/mitchellh/packer/blob/master/provisioner/chef-client/provisioner.go#L339

Possible solution?
knife node -c /tmp/packer-chef-client/client.rb delete node

#packer.json
```
{
    "builders": [
        {
            "type": "docker",
            "image": "ubuntu:14.04",
            "export_path": "wp.tar"
        }
    ],
    "provisioners": [
	{
	    "type": "file",
            "source": "/etc/chef/trusted_certs/julia.crt",
            "destination": "/tmp/julia.crt"
	},
	{
            "type": "shell",
            "inline": [
		"apt-get install -y curl",
		"mkdir -p /etc/chef/trusted_certs",
		"sudo mv /tmp/julia.crt /etc/chef/trusted_certs/julia.crt"
	    ]
        },
        {
            "type": "chef-client",
            "server_url": "https://julia/organizations/sunnet",
            "validation_key_path": "/etc/chef/validation.pem",
            "validation_client_name": "sunnet-validator",
            "config_template": "template",
            "install_command": "curl -L https://www.chef.io/chef/install.sh | sudo bash"
        }
    ]
}

## template file
log_level        :info
log_location     STDOUT
chef_server_url  "{{.ServerUrl}}"
client_key       "{{.ClientKey}}"
{{if ne .ValidationClientName ""}}
validation_client_name "{{.ValidationClientName}}"
{{else}}
validation_client_name "chef-validator"
{{end}}
{{if ne .ValidationKeyPath ""}}
validation_key "{{.ValidationKeyPath}}"
{{end}}
node_name "{{.NodeName}}"
{{if ne .ChefEnvironment ""}}
environment "{{.ChefEnvironment}}"
{{end}}
{{if ne .SslVerifyMode ""}}
ssl_verify_mode :{{.SslVerifyMode}}
{{end}}
trusted_certs_dir "/etc/chef/trusted_certs"

**Comment by cbednarski** [comment] 2015-06-29 06:22
@a13x212 If you're using a self-signed cert / CA does this work if you put your certs in `/etc/ssl/certs`? I think that's the correct way to make your system trust the cert -- those certs should apply to `curl`, `ruby`, `knife`, etc.

**Comment by cbednarski** [comment] 2015-06-29 06:26
Actually I think this is a dupe of #2306 @a13x212 I'm going to close this but please reopen if your issue is different.

**Closed by cbednarski** 2015-06-29 06:26 UTC
Labels: enhancement, provisioner/chef
