### ISSUE TITLE
File-provisioner fails to upload hidden files from source root

### ISSUE THREAD

**Issue by mak18ah** [mitchellh/packer#3309] opened 2016-03-04 20:01 UTC
For file-provisioner, when local source path to file contains a dotfile at root fails to upload into target machine.
sample packer template to illustrate the issue:
```
{
  "variables": {
    "app_slug": "test-app"
  },
  "builders": [
    {
      "type": "docker",
      "image": "ubuntu:14.04",
      "discard": true
    }
  ],
  "provisioners": [
    {
          "type": "file",
          "source": ".",
          "destination": "/tmp/app"
    },
    {
          "type": "file",
          "source": ".nvmrc",
          "destination": "/tmp/app"
    },
    {
       "type":"shell",
       "inline":[
         "echo `cat /tmp/app/test/.hello`",
         "echo `cat /tmp/app/.nvmrc`"
       ]
    }
  ]
}
```
 Example source dir:
```
├── build.log
├── compile.json
├── .nvmrc    # fails to copy this over to target, even when explicitly specified in packer template
└── test
    ├── .hello
    └──  project
        └── dir
            └── example.txt
```

Does not occur with dotfiles located in subdirectories.

Created project example here: https://github.com/mak18ah/packer-hidden-source-files-fail use `PACKER_LOG=1 packer build compile.json` to run
Here is the debug log: https://gist.github.com/mak18ah/465cd29945371ad09e62#file-file-provisioner-source-dotfile

Packer client version info:
```
$ PACKER_LOG=1 packer -version
2016/03/04 14:57:47 [INFO] Packer version: 0.8.6  f8f7b7a34c1be06058f5aca23a51247db12cdbc5+CHANGES
2016/03/04 14:57:47 Packer Target OS/Arch: darwin amd64
2016/03/04 14:57:47 Built with Go Version: go1.5
```

**Comment by cbednarski** [comment] 2016-03-04 20:36
Thanks for the report! I think this is a duplicate of #3142, even though the wording is slightly different. I'm going to close this issue and copy your report into #3142 so I can keep everything in one place. If you have any additional feedback please include it there! Thanks!

**Closed by cbednarski** 2016-03-04 20:36 UTC
Labels: bug, duplicate, provisioner/file
