### ISSUE TITLE
http2: invalid header field name when downloading virtualbox-iso iso from NGINX

### ISSUE THREAD

**Issue by hvindin** [mitchellh/packer#3844] opened 2016-08-31 14:08 UTC
When attempting to download a virtualbox iso file I get an error `http2: invalid header field name` as a response to the downloads to my server hosting with NGINX over https.

Details are fairly obvious from the logs.

**Packer Version**
Packer v0.10.1

**Host Platform**
Redhat Linux 7.1
3.10.0-327.28.3.el7.x86_64
GNU/Linux
x86_64

**Details**
https://gist.github.com/hvindin/21fa2c0e33a2cea7b957c57acba69a5f

Works fine if I download from another server without http2 enabled, so I suspect there's either an issue with nginx's implementation of http2 or with how packer is handling the headers.

**Comment by rickard-von-essen** [comment] 2016-08-31 19:26
Did you find out which header causes the error? Could you try to upgrade to the latest Nginx release? 1.11.3 to rule out that this is a non-issue.

**Comment by rickard-von-essen** [comment] 2016-08-31 20:44
Did you change anything? Suddenly it started to work fine.

**Comment by rickard-von-essen** [comment] 2016-08-31 21:08
Someone modified the Nginx config so now it "works" but it's misconfigured, headers come with mixed line feeds.

```
$ curl -sD http2_headers -o tmp.iso  https://vultr-jp01.home-v.ind.in/public/rhel-server-7.1-x86_64-boot.iso
$ file http2_headers                                                                                                                                        
http2_headers: ASCII text, with CRLF line terminators
```

I'm closing this since this seems to be a config error in Nginx. Reopen if you can reproduce the problem with a correctly configured Nginx server.

**Closed by rickard-von-essen** 2016-08-31 21:08 UTC
Labels: waiting-reply

**Comment by hvindin** [comment] 2016-08-31 22:58
Fair enough, I suspect that it's something that has been fixed in newer versions of nginx.

I upgraded nginx from ~10.0.0 to 11.3.0, interestingly, if I look at the access logs over the period where I upgraded I can see that at 7am, about two hours after I upgraded, the logs suddenly start looking like:

GET / HTTP/2.0" 403 389 - Go-http-client/2.0
GET / HTTP/2.0 403 389 - Go-http-client/2.0
GET / HTTP/1.1 - 301 185  - Go-http-client/1.1
GET / HTTP/1.1 - 301 185  - Go-http-client/1.1

after being pretty consistently:

GET / HTTP/2.0" 403 389 - Go-http-client/2.0
GET / HTTP/2.0 403 389 - Go-http-client/2.0
GET / HTTP/1.1 - 403 257  - Go-http-client/1.1
GET / HTTP/1.1 - 403 257  - Go-http-client/1.1

So I suspect that it's not that http/2.0 has started to work, its just now able to fall back to 1.1 without recieving a 403 response and instead being appropriately redirected.

Logs extract: https://gist.github.com/hvindin/03d4daf15575ead7d2d078eb876b174e

**Comment by hvindin** [comment] 2016-08-31 23:26
By the looks of it I'm not sure that your testing was entirely conclusive, on three seperate servers running three seperate configurations, two running nginx (11.3.0 and 10.0.0) and one running apache2 I get the foillowing:

http2_headers-httpd: ASCII text, with CRLF line terminators
http2_headers-nginx: ASCII text, with CRLF line terminators
http2_headers-old.nginx.config: ASCII text, with CRLF line terminators

And as far as I know CRLF line breaks are the correct behaviour for NGINX, most of the code writes out  like this:
```
ngx_http_v2_state_preface(ngx_http_v2_connection_t *h2c, u_char *pos,
    u_char *end)
{
    static const u_char preface[] = "PRI * HTTP/2.0\r\n";
```

I'll try and spin up a server with the old config on it (if I can remember what that was) and I'll reply back here if I can reproduce the issue.

**Comment by rickard-von-essen** [comment] 2016-09-01 04:40
I read the RFC and it clearly states that the communication must start with `HTTP/2.0\r\n`. As you say. Seems wired to mix line endings. 

I patched my `transport.go` to print out some debug information about which header that was faulty. But when I tried it the error was gone and the download was successful.
