### ISSUE TITLE
Why does `packer --version` exit with 1?

### ISSUE THREAD

**Issue by riggerthegeek** [mitchellh/packer#4717] opened 2017-03-27 20:53 UTC
I type in the command:

    packer --version

And I get out `0.12.3`. But it exits with 1

    echo $? // this is 1

Why is this?

The `packer version` command echos out `Packer v0.12.3` and exits with a 0, which feels like this should be the correct behaviour.

I'm running 0.12.3 Linux AMD64 version. I've run this on Fedora, Ubuntu and Alpine Linux and get the same on all systems

**Comment by mwhooker** [comment] 2017-03-27 21:22
it's because of a bug in the cli library we use. There's a patch out to solve it, but it's not merged yet. There's more details in #3370, which this is a dupe of

**Closed by mwhooker** 2017-03-27 21:22 UTC
