### ISSUE TITLE
local boxfile works with vagrant, after upload to atlas it wont 

### ISSUE THREAD

**Issue by MansM** [mitchellh/packer#3748] opened 2016-07-25 14:08 UTC
When I build a box with packer it works when I directly import it. When its uploaded (and I use vagrant box add ..) the vm get made but it launches with the network cable disconnected so vagrant cant connect. 

I have seen this behaviour on my Centos and Debian build:

```
"post-processors": [
      [{
        "type": "vagrant",
        "compression_level": "9",
        "output": "/Users/Mans/Dropbox/boxfiles/{{ user `PACKER_BOX_NAME` }}_{{.Provider}}.box",
        "keep_input_artifact": false
      },
      {
        "type": "atlas",
        "token": "{{user `ATLAS_TOKEN`}}",
        "artifact": "mansm/CentOS-7",
        "artifact_type": "vagrant.box",
        "metadata": {
          "created_at": "{{timestamp}}",
          "provider": "virtualbox",
          "version": ""
        }
      }]
    ]
```
---

OSX 10.11.6

$ packer --version
0.10.1

$ vagrant --version
Vagrant 1.8.5

tried with virtualbox 5.1.0 and 5.1.2

**Comment by rickard-von-essen** [comment] 2016-07-25 17:13
Could you run `md5` on the local box file and on the downloaded box from atlas.

**Comment by MansM** [comment] 2016-07-26 12:17
For some reason I cant download the box file? did the url bit change (got this url from vagrant)
https://atlas.hashicorp.com/mansm/boxes/Debian-Wheezy/versions/0.3/providers/virtualbox.box

MD5 (debian-7.8.0-amd64_virtualbox.box) = 1b800582f8f357cc39de3236923c4144
(local file)

**Comment by rickard-von-essen** [comment] 2016-07-26 12:47
If the md5 sums of the boxes are the same this is definitely not a Packer issue.

**Comment by rickard-von-essen** [comment] 2016-07-26 12:48
What do you mean with directly import it? Import the OVA into VirtualBox or add the local `.box` file to Vagrant?

**Comment by MansM** [comment] 2016-07-26 12:58
using config.vm.box = "/Users/Mans/Dropbox/boxfiles/CentOS-7-x86_64_virtualbox.box"

but, when I use the ovf file as input for as an virtualbox-ovf build, I have the same issue
I have to put:
        [ "modifyvm", "{{.Name}}", "--cableconnected1", "on"]

inside the json file to get it working

this is actually the reason to think its resulting from packer for some reason. But that ovf is coming from the unpacked vagrant download....

**Comment by rickard-von-essen** [comment] 2016-07-26 13:04
Please provide a full template, scripts and vagrantfiles to reproduce this and include you workflow to reproduce.

**Comment by MansM** [comment] 2016-07-26 13:23
git clone https://bitbucket.org/cybermans/packer.git

you probably need to update the output of the postprocessor

**Comment by MansM** [comment] 2016-07-27 10:28
@rickard-von-essen can you confirm my issue with the git repo supplied?

**Comment by rickard-von-essen** [comment] 2016-07-27 20:41
I can't reproduce this. Are you sure you are note running a old build of you box or something.

I would like to close this unless you provide some more details showing what's different in the two cases, it seems like very unlikely that Vagrant behave differently with the exact same box from two different sources (atlas vs local).

**Comment by ogarcia** [comment] 2016-08-01 18:27
I have same issue and I think that is related with #3757.

I build https://atlas.hashicorp.com/ogarcia/boxes/archlinux-x64 with packer and have the network cable disconnected.

**Comment by rickard-von-essen** [comment] 2016-11-08 19:35
This seems to be a duplicate of #3757. Please upgrade to VirtualBox 5.1.6 and reopen if that doesn't help.

**Closed by rickard-von-essen** 2016-11-08 19:35 UTC
Labels: builder/virtualbox, duplicate, post-processor/atlas, post-processor/vagrant
