### ISSUE TITLE
Packer builds multiple AWS instance-store images with the same name

### ISSUE THREAD

**Issue by jarro2783** [mitchellh/packer#3958] opened 2016-10-04 01:02 UTC
packer version: 0.10.1
host: linux amd64

When building multiple AWS instance-store AMIs in the same job, the default packer build command produces AMIs that have the same file names for the image manifest and the image parts for each of the AMIs. This is because the default `bundle_prefix` is `"image-{{timestamp}}"`, where timestamp appears to be the time that packer started.

The result of this is unbootable AMIs if they are uploaded to the same S3 bucket path.

**Comment by mwhooker** [comment] 2016-10-04 01:05
thanks for the report @jarro2783.

By any chance do you have a minimal packer.json file that reproduces this? Would help debugging a bit.

**Comment by jarro2783** [comment] 2016-10-04 01:08
I'll put one together for you.

**Comment by jarro2783** [comment] 2016-10-04 01:46
Creating a minimal working build might be a bit difficult due to the way we have our infrastructure set up. Here is a part of the build log showing two different images being built with the same timestamp. I'll try to get a minimal working build together but I might have to come back to it if it takes too long since I have other things to do.

    08:10:02     14.04 pv.instance-store: Splitting /tmp/image-1475496002.tar.gz.enc...
    08:10:02     14.04 pv.instance-store: Created image-1475496002.part.00
    08:10:02     14.04 pv.instance-store: Created image-1475496002.part.01
    08:10:02     14.04 pv.instance-store: Created image-1475496002.part.02
    08:10:02     14.04 pv.instance-store: Created image-1475496002.part.03

    08:09:07     12.04 pv.instance-store: Splitting /tmp/image-1475496002.tar.gz.enc...
    08:09:07     12.04 pv.instance-store: Created image-1475496002.part.00
    08:09:07     12.04 pv.instance-store: Created image-1475496002.part.01
    08:09:07     12.04 pv.instance-store: Created image-1475496002.part.02
    08:09:07     12.04 pv.instance-store: Created image-1475496002.part.03

**Comment by jarro2783** [comment] 2016-10-04 02:06
Yes we already came up with that fix. It seemed like a bug though that the default configuration doesn't work.

**Comment by mwhooker** [comment] 2017-01-22 06:46
I think this is working as intended. thanks!

**Comment by mwhooker** [comment] 2017-02-04 02:56
I think this is a documentation problem. Going to close this and track in #4446

**Closed by mwhooker** 2017-02-04 02:56 UTC
Labels: bug, builder/amazon
