### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jonathansd1** [mitchellh/packer#4390] opened 2017-01-13 00:29 UTC
Packer: v0.12.1
Host: Windows_Server-2012-R2_RTM-English-64Bit-Base-2016.12.14 (ami-21414f36)

This build is being performed by Jenkins. The AMI to be burned is also based on the same AMI as above. This error appears transitory as I have since completed the build without modifying any of the configuration.

See job output [here](https://gist.githubusercontent.com/jonathansd1/8f6bef6963a2da9f81f5324aed8eee77/raw/652797a90cf54d07d64ee6b574f2bef83f687bb0/Burn-Base-AMI-%25234.log).
See crash.log [here](https://gist.githubusercontent.com/jonathansd1/e3e40102cf267245f742d9467b914c58/raw/7e6e418399a240465912830f016094f128413c60/crash.log).

For my packer build, I'm using the following files:
[base.json](https://gist.githubusercontent.com/jonathansd1/29125cfcba548074436c367cd1b901b3/raw/b718abd7dcf4f369f83849c3ea78bf539b1afb6a/base.json)
[windows.ps1](https://gist.githubusercontent.com/jonathansd1/95c2a36f6d5ce9a0c349640a80688398/raw/908648b7bb76c97200fecb5caaf7e440c29a71ee/windows.ps1)
[roles.ps1](https://gist.githubusercontent.com/jonathansd1/2d866b65b140d41d99b2706899fcb8ac/raw/c035ae28c389099e749f7abecf64f3f7c70630dc/roles.ps1)
[assets.ps1](https://gist.githubusercontent.com/jonathansd1/baf9b3e381cdc2338dc993f37cc5b3e2/raw/df58283121d79d58e49d92fd857d2e8ad24a4c7c/assets.ps1)

**Comment by mwhooker** [comment] 2017-01-17 07:23
here's the relevant bit

```
2017/01/12 20:47:14 packer.exe: panic: runtime error: invalid memory address or nil pointer dereference
2017/01/12 20:47:14 packer.exe: [signal 0xc0000005 code=0x0 addr=0x58 pc=0x1201690]
2017/01/12 20:47:14 packer.exe: 
2017/01/12 20:47:14 packer.exe: goroutine 160 [running]:
2017/01/12 20:47:14 packer.exe: panic(0x13e5f00, 0xc04200a080)
2017/01/12 20:47:14 packer.exe: 	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1af
2017/01/12 20:47:14 packer.exe: github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp.cleanupContent(0xc04213fb80, 0xc04232e400, 0x3a, 0x0, 0x0)
2017/01/12 20:47:14 packer.exe: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp/cp.go:172 +0x150
2017/01/12 20:47:14 packer.exe: github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp.doCopy(0xc04213fb80, 0xc0423b2d20, 0x1e2e0e0, 0xc0420e64e0, 0xc042409e80, 0x1a, 0x0, 0x2e)
2017/01/12 20:47:14 packer.exe: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp/cp.go:45 +0x6f8
2017/01/12 20:47:14 packer.exe: github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp.(*Winrmcp).Write(0xc042367fe0, 0xc0422486c0, 0x1a, 0x1e2e0e0, 0xc0420e64e0, 0xc04202d9f8, 0xc04202d9d8)
2017/01/12 20:47:14 packer.exe: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp/winrmcp.go:90 +0x82
2017/01/12 20:47:14 packer.exe: github.com/mitchellh/packer/communicator/winrm.(*Communicator).Upload(0xc0422484e0, 0xc0422486c0, 0x1a, 0x1e2e0e0, 0xc0420e64e0, 0x0, 0x1, 0x170490)
2017/01/12 20:47:14 packer.exe: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/communicator/winrm/communicator.go:127 +0x127
2017/01/12 20:47:14 packer.exe: github.com/mitchellh/packer/packer/rpc.(*CommunicatorServer).Upload(0xc042409b00, 0xc042248640, 0xc04225a200, 0x0, 0x0)
2017/01/12 20:47:14 packer.exe: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/packer/rpc/communicator.go:280 +0x169
2017/01/12 20:47:14 packer.exe: reflect.Value.call(0xc0423b2660, 0xc0422d8148, 0x13, 0x162570c, 0x4, 0xc04202ded0, 0x3, 0x3, 0xc04238d800, 0x68a, ...)
2017/01/12 20:47:14 packer.exe: 	/usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:434 +0x5cf
2017/01/12 20:47:14 packer.exe: reflect.Value.Call(0xc0423b2660, 0xc0422d8148, 0x13, 0xc04202ded0, 0x3, 0x3, 0x0, 0xc042285440, 0x8f78ff)
2017/01/12 20:47:14 packer.exe: 	/usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:302 +0xab
2017/01/12 20:47:14 packer.exe: net/rpc.(*service).call(0xc04232e000, 0xc0424cbfc0, 0xc042367c28, 0xc04213f680, 0xc042409ce0, 0x12db680, 0xc042248640, 0x16, 0x12f4480, 0xc04225a200, ...)
2017/01/12 20:47:14 packer.exe: 	/usr/local/Cellar/go/1.7.3/libexec/src/net/rpc/server.go:383 +0x14f
2017/01/12 20:47:14 packer.exe: created by net/rpc.(*Server).ServeCodec
2017/01/12 20:47:14 packer.exe: 	/usr/local/Cellar/go/1.7.3/libexec/src/net/rpc/server.go:477 +0x428
```

haven't looked too closely at this yet, but this crash seems to be triggered by ` github.com/mitchellh/packer/vendor/github.com/packer-community/winrmcp/winrmcp.cleanupContent`, which is a 3rd party tool

**Comment by mwhooker** [comment] 2017-01-17 07:38
here's the line it's crashing on https://github.com/mitchellh/packer/blob/master/vendor/github.com/packer-community/winrmcp/winrmcp/cp.go#L172

I suspect that the line `cmd, _ := shell.Execute("powershell", "Remove-Item", filePath, "-ErrorAction SilentlyContinue")` is failing, returning a nil value for `cmd`. I will open an issue on winrmcp and see if we can get more info.

**Comment by mwhooker** [comment] 2017-01-17 09:47
this is a duplicate of #3286

**Closed by mwhooker** 2017-01-17 09:47 UTC
Labels: crash, upstream-bug, windows-guest
