### ISSUE TITLE
Packer crash with vagrant post-processor

### ISSUE THREAD

**Issue by leelynne** [mitchellh/packer#3097] opened 2016-01-22 01:06 UTC
https://gist.github.com/cbednarski/26e40b91a1dba233cc78

No crash when I remove the use of the vagrant post processor.

**Comment by cbednarski** [comment] 2016-01-22 01:18
Thanks for the report. Strange that the post-processor crashes so early in the build.

Can you share your build template? Also, which version of VirtualBox are you using?

**Comment by leelynne** [comment] 2016-01-22 01:50
VirtualBox - Version 5.0.10 r104061

I was doing an virtualbox-ovf build only in this case:

{
    "variables": {
        "image_version": "",
        "source_ami_ebs_id": "",
        "source_vbox_name": "",
        "source_vbox_version": "",
        "user_home": "{{env `HOME`}}",
        "fbot_version": "1.0.2",
        "os_version": "14.04",
        "release_name": "trusty",
        "puppet_version": "3.7.4",
        "iam_profile": "image_builder",
        "default_vbox_arn": ""
    },
    "provisioners": [
        {
            "type": "shell",
            "script": "provisioners/bootstrap.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}} {{user `puppet_version`}} {{user `release_name`}}"
        },
        {
            "type": "file",
            "source": "layout/",
            "destination": "/var/deploy"
        },
        {
            "type": "puppet-masterless",
            "module_paths": [
                "../../shared/puppet/modules",
                "vendor"
            ],
            "manifest_file": "provisioners/config.pp"
        },
        {
            "type": "puppet-masterless",
            "only": ["amazon-ebs"],
            "module_paths": [
                "../../shared/puppet/modules",
                "vendor"
            ],
            "manifest_file": "provisioners/aws.pp"
        },
        {
            "type": "shell",
            "only": ["docker"],
            "script": "provisioners/docker.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}}"
        },
        {
            "type": "shell",
            "script": "provisioners/fixer.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}}"
        },
        {
            "type": "shell",
            "script": "../../shared/provisioners/tokenstore.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}}"
        },
        {
            "type": "shell",
            "only": ["amazon-ebs"],
            "script": "provisioners/newrelic.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}}"
        },
        {
            "type": "file",
            "only": ["virtualbox-ovf"],
            "source": "tools/vboxmeta/bin",
            "destination": "/var/deploy/bin"
        },
        {
            "type": "shell",
            "only": ["virtualbox-ovf"],
            "script": "provisioners/vboxmeta.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}} {{user `default_vbox_arn`}}"
        },
        {
            "type": "shell",
            "only": ["amazon-ebs"],
            "script": "provisioners/services.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}} fbot {{user `fbot_version`}}"
        }
    ],
    "builders": [
        {
            "type": "amazon-ebs",
            "ami_description": "{{user `description`}}",
            "region": "us-west-2",
            "source_ami": "{{user `source_ami_ebs_id`}}",
            "instance_type": "t2.medium",
            "iam_instance_profile":"{{user `iam_profile`}}",
            "ssh_username": "ubuntu",
            "ami_name": "mybox-{{user `type`}}-{{user `version`}}",
            "ssh_timeout": "6m",
            "vpc_id": "vpc-abc",
            "security_group_id": "sg-abc",
            "subnet_id": "subnet-abc",
            "associate_public_ip_address": true,
            "tags": {
                "Name": "{{user `description`}}",
                "type": "{{user `type`}}",
                "source":"{{user `source_ami_ebs_id`}}",
                "image_version": "{{user `version`}}",
                "boot_type":"ebs",
                "ssh_user":"ubuntu",
                "approved": "no"
            }
        },
        {
            "type": "virtualbox-ovf",
            "source_path": "{{user `user_home`}}/.vagrant.d/boxes/{{user `source_vbox_name`}}/{{user `source_vbox_version`}}/virtualbox/box.ovf",
            "ssh_username": "vagrant",
            "ssh_password": "vagrant",
            "headless": true,
            "shutdown_command": "echo 'vagrant' | sudo -S shutdown -P now"
        },
        {
            "type": "docker",
            "image": "mybox/ubuntu",
            "run_command": [
                "--privileged",
                "-d",
                "-i",
                "-t",
                "{{.Image}}",
                "/sbin/my_init"
            ],
            "commit": true
        }
    ],
    "post-processors": [
        [
            {
                "type": "vagrant",
                "only": ["virtualbox-ovf"],
                "output": "mybox-{{user `type`}}-{{user `version`}}.box"
            },
            {
                "type": "vagrant-s3",
                "only": ["virtualbox-ovf"],
                "region": "us-west-2",
                "bucket": "fdep",
                "manifest": "vagrant/mybox-{{user `type`}}.json",
                "box_name": "mybox-{{user `type`}}",
                "box_dir": "vagrant/boxes",
                "version": "{{ user `version` }}"
            }
        ],
        [
            {
                "type": "docker-tag",
                "repository": "mybox/ubuntu",
                "tag": "{{user `image_version`}}",
                "force": true,
                "only": [
                    "docker"
                ]
            }
        ]
    ]
}

**Comment by leelynne** [comment] 2016-01-22 01:52
With better formatting:
```json
{
    "variables": {
        "image_version": "",
        "source_ami_ebs_id": "",
        "source_vbox_name": "",
        "source_vbox_version": "",
        "user_home": "{{env `HOME`}}",
        "fbot_version": "1.0.2",
        "os_version": "14.04",
        "release_name": "trusty",
        "puppet_version": "3.7.4",
        "iam_profile": "image_builder",
        "default_vbox_arn": ""
    },
    "provisioners": [
        {
            "type": "shell",
            "script": "provisioners/bootstrap.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}} {{user `puppet_version`}} {{user `release_name`}}"
        },
        {
            "type": "file",
            "source": "layout/",
            "destination": "/var/deploy"
        },
        {
            "type": "puppet-masterless",
            "module_paths": [
                "../../shared/puppet/modules",
                "vendor"
            ],
            "manifest_file": "provisioners/config.pp"
        },
        {
            "type": "puppet-masterless",
            "only": ["amazon-ebs"],
            "module_paths": [
                "../../shared/puppet/modules",
                "vendor"
            ],
            "manifest_file": "provisioners/aws.pp"
        },
        {
            "type": "shell",
            "only": ["docker"],
            "script": "provisioners/docker.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}}"
        },
        {
            "type": "shell",
            "script": "provisioners/fixer.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}}"
        },
        {
            "type": "shell",
            "script": "../../shared/provisioners/tokenstore.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}}"
        },
        {
            "type": "shell",
            "only": ["amazon-ebs"],
            "script": "provisioners/newrelic.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}}"
        },
        {
            "type": "file",
            "only": ["virtualbox-ovf"],
            "source": "tools/vboxmeta/bin",
            "destination": "/var/deploy/bin"
        },
        {
            "type": "shell",
            "only": ["virtualbox-ovf"],
            "script": "provisioners/vboxmeta.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}} {{user `default_vbox_arn`}}"
        },
        {
            "type": "shell",
            "only": ["amazon-ebs"],
            "script": "provisioners/services.sh",
            "execute_command": "chmod +x {{ .Path }};sudo -n {{ .Vars }} {{ .Path}} fbot {{user `fbot_version`}}"
        }
    ],
    "builders": [
        {
            "type": "amazon-ebs",
            "ami_description": "{{user `description`}}",
            "region": "us-west-2",
            "source_ami": "{{user `source_ami_ebs_id`}}",
            "instance_type": "t2.medium",
            "iam_instance_profile":"{{user `iam_profile`}}",
            "ssh_username": "ubuntu",
            "ami_name": "mybox-{{user `type`}}-{{user `version`}}",
            "ssh_timeout": "6m",
            "vpc_id": "vpc-abc",
            "security_group_id": "sg-abc",
            "subnet_id": "subnet-abc",
            "associate_public_ip_address": true,
            "tags": {
                "Name": "{{user `description`}}",
                "type": "{{user `type`}}",
                "source":"{{user `source_ami_ebs_id`}}",
                "image_version": "{{user `version`}}",
                "boot_type":"ebs",
                "ssh_user":"ubuntu",
                "approved": "no"
            }
        },
        {
            "type": "virtualbox-ovf",
            "source_path": "{{user `user_home`}}/.vagrant.d/boxes/{{user `source_vbox_name`}}/{{user `source_vbox_version`}}/virtualbox/box.ovf",
            "ssh_username": "vagrant",
            "ssh_password": "vagrant",
            "headless": true,
            "shutdown_command": "echo 'vagrant' | sudo -S shutdown -P now"
        },
        {
            "type": "docker",
            "image": "mybox/ubuntu",
            "run_command": [
                "--privileged",
                "-d",
                "-i",
                "-t",
                "{{.Image}}",
                "/sbin/my_init"
            ],
            "commit": true
        }
    ],
    "post-processors": [
        [
            {
                "type": "vagrant",
                "only": ["virtualbox-ovf"],
                "output": "mybox-{{user `type`}}-{{user `version`}}.box"
            },
            {
                "type": "vagrant-s3",
                "only": ["virtualbox-ovf"],
                "region": "us-west-2",
                "bucket": "forgedeploy",
                "manifest": "vagrant/mybox-{{user `type`}}.json",
                "box_name": "mybox-{{user `type`}}",
                "box_dir": "vagrant/boxes",
                "version": "{{ user `version` }}"
            }
        ],
        [
            {
                "type": "docker-tag",
                "repository": "myox/ubuntu",
                "tag": "{{user `image_version`}}",
                "force": true,
                "only": [
                    "docker"
                ]
            }
        ]
    ]
}
```

**Comment by leelynne** [comment] 2016-01-22 04:57
Downgrading to packer 0.8.5 fixed the issue.

**Comment by mwhooker** [comment] 2017-01-22 01:37
Gonna close this since it seems like there's a workable solution. If you test in the latest build of packer and it's still crashing, please open another ticket.

**Closed by mwhooker** 2017-01-22 01:37 UTC
Labels: crash, post-processor/vagrant

**Comment by mchagan** [comment] 2017-03-06 22:23
I tried to reproduce this with 0.12.3 and couldn't.  Is this still an issue?
