### ISSUE TITLE
ansible provisioner doesn't pickup vars from group_vars/

### ISSUE THREAD

**Issue by yosefy** [mitchellh/packer#3576] opened 2016-05-25 22:09 UTC
hi , having problem with group_vars here with ansible remote
- Packer: Version 0.10.1
- Host: platform ubuntu 14.04
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/yosefy/941ea504fa13641edf34973c51b501d3
- The _simplest example template and scripts_ needed to reproduce the bug.
  {
  "builders": [{
    "ssh_private_ip": "true",
    "ssh_timeout": "10m",
    "ami_virtualization_type":"hvm",
    "type": "amazon-ebs",
    "region": "us-west-2",
    "source_ami": "ami-xxx",
    "instance_type": "t2.micro",
    "subnet_id": "subnet-xxx",
    "vpc_id": "vpc-xxx",
    "security_group_id": "xxx",
    "ssh_keypair_name": "kanalony",
    "ssh_private_key_file": "/root/.ssh/xxx.pem",
    "ssh_username": "ubuntu",
    "ami_name": "xxx {{timestamp}}"
  }],
  
  "provisioners": [{
      "type": "ansible",
      "user": "ubuntu",
      "playbook_file": "/etc/ansible/playbook/xxx.yml",
      "groups": ["tag_Name_prod_group","tag_Env_prod"],
      "user": "ubuntu",
      "ssh_host_key_file": "/root/.ssh/kanalony.pem"
    }]
  }

in /etc/ansible/group_vars , i have file tag_Env_prod with the variable that is not picked up

thanks

**Comment by ricardclau** [comment] 2016-07-07 06:44
You need to specify an inventory (in this case possibly ec2.py), otherwise the inventory packer uses is just localhost

Another option we use is to create a different playbook exclusive for packer targeting hosts: all

**Comment by mwhooker** [comment] 2017-01-29 02:57
seems to be dupe of #3863

**Closed** 2017-01-29 02:57 UTC
Labels: provisioner/ansible-remote, question
