### ISSUE TITLE
Packer crashed

### ISSUE THREAD

**Issue by JonCubed** [mitchellh/packer#3006] opened 2015-12-18 11:46 UTC
packer crashed while building a windows ami, here is the log it told me to upload
~~[crash.zip](https://github.com/mitchellh/packer/files/66522/crash.zip)~~ [crash.log](https://gist.github.com/rickard-von-essen/bf424d07b0c125b0cc2c)

Let me know if you need any other details

**Comment by rickard-von-essen** [comment] 2015-12-18 13:24
Gisted log: https://gist.github.com/rickard-von-essen/bf424d07b0c125b0cc2c

**Comment by rickard-von-essen** [comment] 2016-10-15 11:49
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

I'm closing this since it's old, most likely fixed and doesn't contain enough info to reproduce. If you still have this problem with the latest release please reopen and provide the info listed above.

**Closed by rickard-von-essen** 2016-10-15 11:49 UTC
Labels: builder/amazon, communicator/winrm, crash
