### ISSUE TITLE
OpenStack builder reports "Connection reset by peer" when querying Nova extensions

### ISSUE THREAD

**Issue by erhudy** [mitchellh/packer#4450] opened 2017-01-24 17:40 UTC
Summary: the following failure reliably occurs when attempting to build an image using Packer 0.12.2, communicating with Nova API v2.1 (hostnames and IPs have been sanitized):
```
==> openstack: Discovering enabled extensions...
Build 'openstack' errored: Error loading extensions: Get https://openstack:8774/v2.1/5ddddf0023b148aab46c12b260410e71/extensions: read tcp 192.168.1.101:33470->172.16.100.5:8774: read: connection reset by peer
```

`curl`ing this URL with a valid Keystone token from the same place that the Packer build is being executed from reliably returns the expected JSON result from the Nova API.

Build platform is Linux (Ubuntu 16.04.1 AMD64). Problem occurs when using any OpenStack builder template, failure occurs immediately.

Problem does not occur on various older Packer versions (did not bisect all Packer versions, but Packer in our environment is known to not have this issue as of 0.9.0).

**Comment by erhudy** [comment] 2017-01-24 17:46
Log file with IPs sanitized is at https://gist.github.com/erhudy/5a70ec34785949134b3c05bbb685d7f5.

**Comment by rickard-von-essen** [comment] 2017-01-24 18:01
Could you share the output of `openstack extension list`?

**Comment by erhudy** [comment] 2017-01-24 18:06
```
$ openstack extension list
Extensions list not supported by Identity API
Could not find requested endpoint in Service Catalog.
```

Service catalog on this OpenStack cluster is configured thusly:
```
+-----------------+----------+--------------------------------------------------------------------------------------------------+
| Name            | Type     | Endpoints                                                                                        |
+-----------------+----------+--------------------------------------------------------------------------------------------------+
| Volume Service  | volume   | DRR1                                                                                             |
|                 |          |   public: https://openstack.example.com:8776/v2/5ddddf0023b148aab46c12b260410e71     |
|                 |          | DRR1                                                                                             |
|                 |          |   admin: https://openstack.example.com:8776/v2/5ddddf0023b148aab46c12b260410e71      |
|                 |          | DRR1                                                                                             |
|                 |          |   internal: https://openstack.example.com:8776/v2/5ddddf0023b148aab46c12b260410e71   |
|                 |          |                                                                                                  |
| keystone        | identity | DRR1                                                                                             |
|                 |          |   admin: https://openstack.example.com:35357/v3                                      |
|                 |          | DRR1                                                                                             |
|                 |          |   internal: https://openstack.example.com:5000/v3                                    |
|                 |          | DRR1                                                                                             |
|                 |          |   public: https://openstack.example.com:5000/v3                                      |
|                 |          |                                                                                                  |
| cinderv2        | volumev2 | DRR1                                                                                             |
|                 |          |   admin: https://openstack.example.com:8776/v2/5ddddf0023b148aab46c12b260410e71      |
|                 |          | DRR1                                                                                             |
|                 |          |   internal: https://openstack.example.com:8776/v2/5ddddf0023b148aab46c12b260410e71   |
|                 |          | DRR1                                                                                             |
|                 |          |   public: https://openstack.example.com:8776/v2/5ddddf0023b148aab46c12b260410e71     |
|                 |          |                                                                                                  |
| Image Service   | image    | DRR1                                                                                             |
|                 |          |   admin: https://openstack.example.com:9292/                                         |
|                 |          | DRR1                                                                                             |
|                 |          |   public: https://openstack.example.com:9292/                                        |
|                 |          | DRR1                                                                                             |
|                 |          |   internal: https://openstack.example.com:9292/                                      |
|                 |          |                                                                                                  |
| Compute Service | compute  | DRR1                                                                                             |
|                 |          |   admin: https://openstack.example.com:8774/v2.1/5ddddf0023b148aab46c12b260410e71    |
|                 |          | DRR1                                                                                             |
|                 |          |   internal: https://openstack.example.com:8774/v2.1/5ddddf0023b148aab46c12b260410e71 |
|                 |          | DRR1                                                                                             |
|                 |          |   public: https://openstack.example.com:8774/v2.1/5ddddf0023b148aab46c12b260410e71   |
|                 |          |                                                                                                  |
| EC2 Service     | ec2      | DRR1                                                                                             |
|                 |          |   public: https://openstack.example.com:8773/services/Cloud                          |
|                 |          | DRR1                                                                                             |
|                 |          |   internal: https://openstack.example.com:8773/services/Cloud                        |
|                 |          | DRR1                                                                                             |
|                 |          |   admin: https://openstack.example.com:8773/services/Admin                           |
|                 |          |                                                                                                  |
+-----------------+----------+--------------------------------------------------------------------------------------------------+
```

**Comment by erhudy** [comment] 2017-01-24 18:09
From the OpenStack side, it sees the request come through to the Nova API and indicates that it replied successfully:
```
2017-01-24 12:26:27.327 311175 INFO nova.osapi_compute.wsgi.server [req-71e1dcb0-c229-44dc-9e52-ffbc08e4a86e erhudy 5ddddf0023b148aab46c12b260410e71 - - -] 100.71.64.5 "GET /v2.1/5ddddf0023b148aab46c12b260410e71/extensions HTTP/1.1" status: 200 len: 21761 time: 0.1086738
```

**Comment by erhudy** [comment] 2017-01-24 18:11
Problem begins to occur in Packer 0.10.0 (AMD64 binary downloaded from the Hashicorp release service).

**Comment by rickard-von-essen** [comment] 2017-01-24 19:09
Can you confirm that you get the error with 0.10.0 but not with 0.9.0? The only change in the openstack builder introduced in 0.10.0 is #3209.

**Comment by erhudy** [comment] 2017-01-24 19:17
Verified that the exact same template fails when run with Packer 0.10.0 but builds correctly with Packer 0.9.0, under the same shell session (see below).
```
erhudy@erhudy-inst:/mnt/extra/erhudy/bcpc-packer-images$ ../packer-0.10.0 version
Packer v0.10.0

Your version of Packer is out of date! The latest version
is 0.12.2. You can update by downloading from www.packer.io
erhudy@erhudy-inst:/mnt/extra/erhudy/bcpc-packer-images$ ../packer-0.9.0 version
Packer v0.9.0

Your version of Packer is out of date! The latest version
is 0.12.2. You can update by downloading from www.packer.io
erhudy@erhudy-inst:/mnt/extra/erhudy/bcpc-packer-images$ ../packer-0.10.0 build packer-cloud-compute-drr1-xenial.json
openstack output will be in this color.

==> openstack: Discovering enabled extensions...
Build 'openstack' errored: Error loading extensions: Get https://openstack.example.com:8774/v2.1/5ddddf0023b148aab46c12b260410e71/extensions: read tcp 192.168.1.101:35878->172.16.100.5:8774: read: connection reset by peer

==> Some builds didn't complete successfully and had errors:
--> openstack: Error loading extensions: Get https://openstack.example.com:8774/v2.1/5ddddf0023b148aab46c12b260410e71/extensions: read tcp 192.168.1.101:35878->172.16.100.5:8774: read: connection reset by peer

==> Builds finished but no artifacts were created.
erhudy@erhudy-inst:/mnt/extra/erhudy/bcpc-packer-images$ ../packer-0.9.0 build packer-cloud-compute-drr1-xenial.json
openstack output will be in this color.

==> openstack: Discovering enabled extensions...
==> openstack: Loading flavor: generic1.small
    openstack: Verified flavor. ID: eb053b0f-4873-4474-a542-f3b23f690e25
==> openstack: Creating temporary keypair: packer 5887a7a1-83f7-be4d-1128-fcf7bd5dbca3 ...
==> openstack: Created temporary keypair: packer 5887a7a1-83f7-be4d-1128-fcf7bd5dbca3
==> openstack: Successfully converted BER encoded SSH key to DER encoding.
==> openstack: Launching server...
    openstack: Server ID: 57731d3a-cfd6-4c83-ab66-30f44a157c7c
==> openstack: Waiting for server to become ready...
^C^C^C^C^C^C==> openstack: Error waiting for server (57731d3a-cfd6-4c83-ab66-30f44a157c7c) to become ready: interrupted
==> openstack: Terminating the source server: 57731d3a-cfd6-4c83-ab66-30f44a157c7c ...
^C==> openstack: Deleting temporary keypair: packer 5887a7a1-83f7-be4d-1128-fcf7bd5dbca3 ...
Build 'openstack' errored: Error waiting for server (57731d3a-cfd6-4c83-ab66-30f44a157c7c) to become ready: interrupted
Cleanly cancelled builds after being interrupted.
```

**Comment by erhudy** [comment] 2017-01-26 14:10
What we're seeing from intercepting the HTTP requests Packer is sending is that for <= 0.9.0, it does not set the `Connection: close` header. Packer 0.10.0 does, though. They both appear to have been built with Go 1.6 (so presumably the stdlib was the same in both cases). Perusing through Gophercloud source, https://github.com/rackspace/gophercloud/blame/c90cb954266e1bdd6d1914678fd6909fc5fabbfa/provider_client.go#L189 looks like it has something to do with it, but the blame timestamp indicates that's been there for a long while before the bug started appearing for us.

**Comment by rickard-von-essen** [comment] 2017-01-26 16:51
I can confirm that v0.9.0 used a gophercloud version without that change. Let me build v0.12.0 without that line.

**Comment by rickard-von-essen** [comment] 2017-01-26 17:04
[packer_linux_amd64-issue-4450 v0.12.2](https://www.dropbox.com/s/wqkt1jc3scj6d8z/packer_linux_amd64-issue-4450?dl=0] please try this build.

**Comment by erhudy** [comment] 2017-01-26 17:22
Problem still occurs. I see now that gophercloud was vendored in 0.9.0 but was largely removed in 0.10.0. Can we know which commit the vendored gophercloud in 0.9.0 was based on so that we can continue bisecting gophercloud commits and comparing to master at the time 0.10.0 was built?

**Comment by rickard-von-essen** [comment] 2017-01-26 17:41
Ohh damn! That build _didn't_ contain the "fix", I have updated the file, can you redownload it and try again. Sorry!

**Comment by erhudy** [comment] 2017-01-26 18:08
Looks like that build does indeed fix it. There's another failure further down after it launches the instnace (reports failure searching for floating IP from the pool and terminates the build), but I'll investigate that separately from this issue.

**Comment by rickard-von-essen** [comment] 2017-01-26 19:20
Could you open an issue at https://github.com/gophercloud/gophercloud reference this and ping the author of the probematic commit (since he did it for Terraform which is another HashiCorp tool).

**Comment by rickard-von-essen** [comment] 2017-03-10 14:03
Closing this since this was a configuration problem in HAProxy. The culprit was `option nolinger` in the HAProxy configuration.

**Closed by rickard-von-essen** 2017-03-10 14:03 UTC
Labels: bug, builder/openstack, upstream-bug
