### ISSUE TITLE
VirtualBox: VMs not cleaned up in some scenarios

### ISSUE THREAD

**Issue by mayani** [mitchellh/packer#3700] opened 2016-07-08 22:25 UTC
**Description**

VMs created by packer are not cleaned up in certain scenarios.
1. If process is sent a kill (Ctrl +C) during the export step, the VM created by Packer is not cleaned up.
2. If process is sent a kill during wait for `pause_before`, the VM is neither powered off, nor cleaned up.
3. Noticed, that when process is killed for parallel builds, some VMs were not cleaned up. Could be because of 1, and 2.
4. Not verified if issue manifests itself when, process is killed during other waits.

**Packer Version** 0.10.1
**Host Platform** MacOSX
**GuestVM** CentOS 7

Template, Packer Log, Script files attached. 

[template.json.txt](https://github.com/mitchellh/packer/files/355201/template.json.txt)
[packer_log.txt](https://github.com/mitchellh/packer/files/355200/packer_log.txt)
[update.sh.txt](https://github.com/mitchellh/packer/files/355206/update.sh.txt)

**Comment by kwilczynski** [comment] 2016-07-17 10:12
@mayani I am not entirely sure if this would help you, but perhaps you could adopt something that I have had to put in place too to perform clean-up on failure.

I run this script when Packer build fails: [virtualbox.sh](https://gist.github.com/kwilczynski/81aee1790709a31382cc#file-virtualbox-sh).

Maybe you could use something like this too.

**Comment by mayani** [comment] 2016-07-18 17:54
@kwilczynski Thanks. At some point, I had added something similar to this, except I did not have the VBoxManage discardstate step in it.

**Comment by kwilczynski** [comment] 2016-07-21 17:08
@mayani does it work for you?

From my personal experience I can tell, that VirtualBox can be very stubborn when it goes to trying to remove a virtual machine in somewhat broken state.

**Comment by mayani** [comment] 2016-07-21 17:36
@kwilczynski My Packer build runs about once a day. I have seen some instability, but sometimes it has been because of Packer timeouts. I am not sure if any of the cases were because of VirtualBox.

**Comment by kwilczynski** [comment] 2016-07-21 17:41
@mayani what time outs are you seeing? Perhaps there is a different issue luring somewhere. Do you have an example output?

**Comment by mayani** [comment] 2016-07-21 18:50
@kwilczynski

Unfortunately, I don't have the logs.

Sometimes on reboots the last thing on console is "Rebooting" from an echo. Nothing is rendered to the console after that.

I have multiple remote-shell provisioners. The last script in first provisioner has the reboot ; sleep 60. I also have a pause_before: 1m on the next remote-shell provisioner. Though unlikely, but timeout may be because 1m is not enough for VM to reboot completely, this should still not cause the VM to be stuck indefinitely.

**Comment by kwilczynski** [comment] 2016-07-21 18:53
@mayani I see. On the note of reboots, look at this issue #3487, maybe it would help.

**Comment by mwhooker** [comment] 2017-02-11 04:57
Are you still hitting this issue? There have been a number of fixes to packer around this type of thing.

I'm going to close this because I wasn't able to reproduce the problem. If you're still getting this, please make sure you try with the latest versions of packer and virtualbox, and comment here and I'll reopen the issue.

### cancelling during pause_before
```
==> vbox: Pausing 10m0s before the next provisioner...
^C2017/02/10 20:45:11 Closing stdin because interrupt received.
2017/02/10 20:45:11 Stopping build: vbox
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Received interrupt signal (count: 1). Ignoring.
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Received interrupt signal (count: 1). Ignoring.
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Received interrupt signal (count: 1). Ignoring.
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Received interrupt signal (count: 1). Ignoring.
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Received interrupt signal (count: 1). Ignoring.
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Cancelling the step runner...
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Received interrupt signal (count: 1). Ignoring.
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Cancelling provisioning due to interrupt...
2017/02/10 20:45:11 ui: ==> vbox: Provisioning with shell script: scripts-1604/vagrant.sh
==> vbox: Provisioning with shell script: scripts-1604/vagrant.sh
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Opening scripts-1604/vagrant.sh for reading
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 opening new ssh session
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 [INFO] 563 bytes written for 'uploadData'
2017/02/10 20:45:11 [INFO] 563 bytes written for 'uploadData'
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Starting remote scp process:  scp -vt /tmp
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Started SCP session, beginning transfers...
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Copying input data into temporary file so we can read the length
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 [DEBUG] scp: Uploading script_9907.sh: perms=C0644 size=563
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 SCP session complete, closing stdin pipe.
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Waiting for SSH session to complete.
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 scp stderr (length 31): Sink: C0644 563 script_9907.sh
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 opening new ssh session
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 starting remote command: chmod 0755 /tmp/script_9907.sh
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 [INFO] RPC endpoint: Communicator ended with: 0
2017/02/10 20:45:11 [INFO] RPC client: Communicator ended with: 0
2017/02/10 20:45:11 [INFO] RPC endpoint: Communicator ended with: 0
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 [INFO] RPC client: Communicator ended with: 0
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 opening new ssh session
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 starting remote command: echo 'vagrant' | PACKER_BUILDER_TYPE='virtualbox-iso' PACKER_BUILD_NAME='vbox' PACKER_HTTP_ADDR='10.0.2.2:8174'  sudo -E -S bash '/tmp/script_9907.sh'
2017/02/10 20:45:11 ui:     vbox: [sudo] password for vagrant: --2017-02-11 04:45:11--  https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub
    vbox: [sudo] password for vagrant: --2017-02-11 04:45:11--  https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub
2017/02/10 20:45:11 packer: 2017/02/10 20:45:11 Executing VBoxManage: []string{"controlvm", "ubuntu-1604-vbox", "poweroff"}
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 Remote command exited without exit status or exit signal.
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 [INFO] RPC endpoint: Communicator ended with: 2300218
2017/02/10 20:45:12 [INFO] 0 bytes written for 'stdout'
2017/02/10 20:45:12 [INFO] 197 bytes written for 'stderr'
2017/02/10 20:45:12 [INFO] RPC client: Communicator ended with: 2300218
2017/02/10 20:45:12 [INFO] RPC endpoint: Communicator ended with: 2300218
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 [INFO] 0 bytes written for 'stdout'
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 [INFO] 197 bytes written for 'stderr'
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 [INFO] RPC client: Communicator ended with: 2300218
2017/02/10 20:45:12 ui:     vbox: Resolving raw.githubusercontent.com (raw.githubusercontent.com)...
    vbox: Resolving raw.githubusercontent.com (raw.githubusercontent.com)...
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 opening new ssh session
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 ssh session open error: 'EOF', attempting reconnect
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 reconnecting to TCP connection for SSH
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 reconnection error: dial tcp 127.0.0.1:4067: getsockopt: connection refused
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 Retryable error: Error removing temporary script at /tmp/script_9907.sh: dial tcp 127.0.0.1:4067: getsockopt: connection refused
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 stdout:
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 Executing VBoxManage: []string{"storageattach", "ubuntu-1604-vbox", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "none"}
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 stdout:
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 stderr:
2017/02/10 20:45:12 ui: ==> vbox: Unregistering and deleting virtual machine...
==> vbox: Unregistering and deleting virtual machine...
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 Executing VBoxManage: []string{"unregistervm", "ubuntu-1604-vbox", "--delete"}
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 stdout:
2017/02/10 20:45:12 packer: 2017/02/10 20:45:12 stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2017/02/10 20:45:12 ui: ==> vbox: Deleting output directory...
==> vbox: Deleting output directory...
2017/02/10 20:45:12 Build cancelled: vbox
2017/02/10 20:45:12 ui error: Build 'vbox' errored: Build was cancelled.
2017/02/10 20:45:12 Builds completed. Waiting on interrupt barrier...
2017/02/10 20:45:12 ui: Cleanly cancelled builds after being interrupted.
2017/02/10 20:45:12 waiting for all plugin processes to complete...
Build 'vbox' errored: Build was cancelled.
Cleanly cancelled builds after being interrupted.
2017/02/10 20:45:12 /Users/mwhooker/go/bin/packer: plugin process exited
2017/02/10 20:45:12 /Users/mwhooker/go/bin/packer: plugin process exited
2017/02/10 20:45:12 /Users/mwhooker/go/bin/packer: plugin process exited
2017/02/10 20:45:12 /Users/mwhooker/go/bin/packer: plugin process exited
2017/02/10 20:45:12 /Users/mwhooker/go/bin/packer: plugin process exited
2017/02/10 20:45:12 [ERR] Error decoding response stream 7: EOF
2017/02/10 20:45:12 /Users/mwhooker/go/bin/packer: plugin process exited
```

### cancelling during export

```
2017/02/10 20:54:24 ui: ==> vbox: Exporting virtual machine...
==> vbox: Exporting virtual machine...
2017/02/10 20:54:24 ui:     vbox: Executing: export ubuntu-1604-vbox --output output-vbox/ubuntu-1604-vbox.ovf
2017/02/10 20:54:24 packer: 2017/02/10 20:54:24 Executing VBoxManage: []string{"export", "ubuntu-1604-vbox", "--output", "output-vbox/ubuntu-1604-vbox.ovf"}
    vbox: Executing: export ubuntu-1604-vbox --output output-vbox/ubuntu-1604-vbox.ovf
^C2017/02/10 20:54:40 Closing stdin because interrupt received.
2017/02/10 20:54:40 Stopping build: vbox
2017/02/10 20:54:40 packer: 2017/02/10 20:54:40 Received interrupt signal (count: 1). Ignoring.
2017/02/10 20:54:40 packer: 2017/02/10 20:54:40 Cancelling the step runner...
2017/02/10 20:54:56 packer: 2017/02/10 20:54:56 stdout:
2017/02/10 20:54:56 packer: 2017/02/10 20:54:56 stderr: 0%...CANCELED
2017/02/10 20:54:56 packer: VBoxManage: error: Appliance write failed
2017/02/10 20:54:56 packer: VBoxManage: error: File not accessible or erroneous file contents
2017/02/10 20:54:56 packer: VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
2017/02/10 20:54:56 packer: VBoxManage: error: Context: "RTEXITCODE handleExportAppliance(HandlerArg *)" at line 1258 of file VBoxManageAppliance.cpp
2017/02/10 20:54:56 ui error: ==> vbox: Error exporting virtual machine: VBoxManage error: 0%...CANCELED
==> vbox: VBoxManage: error: Appliance write failed
==> vbox: VBoxManage: error: File not accessible or erroneous file contents
==> vbox: VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
==> vbox: VBoxManage: error: Context: "RTEXITCODE handleExportAppliance(HandlerArg *)" at line 1258 of file VBoxManageAppliance.cpp
==> vbox: Error exporting virtual machine: VBoxManage error: 0%...CANCELED
==> vbox: VBoxManage: error: Appliance write failed
==> vbox: VBoxManage: error: File not accessible or erroneous file contents
==> vbox: VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
==> vbox: VBoxManage: error: Context: "RTEXITCODE handleExportAppliance(HandlerArg *)" at line 1258 of file VBoxManageAppliance.cpp
2017/02/10 20:54:56 packer: 2017/02/10 20:54:56 Executing VBoxManage: []string{"storageattach", "ubuntu-1604-vbox", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "none"}
2017/02/10 20:54:56 packer: 2017/02/10 20:54:56 stdout:
2017/02/10 20:54:56 packer: 2017/02/10 20:54:56 stderr: VBoxManage: error: No storage device attached to device slot 1 on port 0 of controller 'IDE Controller'
2017/02/10 20:54:56 packer: VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component SessionMachine, interface IMachine, callee nsISupports
2017/02/10 20:54:56 packer: VBoxManage: error: Context: "DetachDevice(Bstr(pszCtl).raw(), port, device)" at line 393 of file VBoxManageStorageController.cpp
2017/02/10 20:54:56 ui: ==> vbox: Unregistering and deleting virtual machine...
2017/02/10 20:54:56 packer: 2017/02/10 20:54:56 Executing VBoxManage: []string{"unregistervm", "ubuntu-1604-vbox", "--delete"}
==> vbox: Unregistering and deleting virtual machine...
2017/02/10 20:54:56 packer: 2017/02/10 20:54:56 stdout:
2017/02/10 20:54:56 packer: 2017/02/10 20:54:56 stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2017/02/10 20:54:56 ui: ==> vbox: Deleting output directory...
==> vbox: Deleting output directory...
2017/02/10 20:54:56 Build cancelled: vbox
2017/02/10 20:54:56 ui error: Build 'vbox' errored: Error exporting virtual machine: VBoxManage error: 0%...CANCELED
VBoxManage: error: Appliance write failed
VBoxManage: error: File not accessible or erroneous file contents
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleExportAppliance(HandlerArg *)" at line 1258 of file VBoxManageAppliance.cpp
2017/02/10 20:54:56 Builds completed. Waiting on interrupt barrier...
2017/02/10 20:54:56 ui: Cleanly cancelled builds after being interrupted.
2017/02/10 20:54:56 waiting for all plugin processes to complete...
Build 'vbox' errored: Error exporting virtual machine: VBoxManage error: 0%...CANCELED
VBoxManage: error: Appliance write failed
VBoxManage: error: File not accessible or erroneous file contents
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleExportAppliance(HandlerArg *)" at line 1258 of file VBoxManageAppliance.cpp
Cleanly cancelled builds after being interrupted.
2017/02/10 20:54:56 /Users/mwhooker/go/bin/packer: plugin process exited
```

In both cases, the box wasn't in virtualbox any more.

**Closed by mwhooker** 2017-02-11 04:57 UTC
Labels: bug, builder/virtualbox
