### ISSUE TITLE
"checksums didn't match expected:" when they do match. (md5 only)

### ISSUE THREAD

**Issue by DarwinJS** [mitchellh/packer#3825] opened 2016-08-23 19:53 UTC
Packer 0.10.0
PowerShell 5
Checksum: md5
ISO Location: local hard drive
Builder: virtualbox-iso

The below error messages were experienced despite calculating the hash with Get-FileHash and 3rd party utilities.

Change to SHA1 and it all works fine.

Sorry if this is a dupe - I searched first.

**virtualbox-iso: Error downloading: checksums didn't match expected: 0e7c09aab20dec3cd7eab236dab90e78
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.**

**Comment by rickard-von-essen** [comment] 2016-08-23 19:59
Can you calculate the SHA1 sum with GNU or BSD `shasum` and verify?

**Comment by DarwinJS** [comment] 2016-08-23 20:17
I used get-filehash to calculate the SHA1 that works and that SHA1 matches the website the ISO came from.  So SHA1 is working.

I am windows - so I used get-filehash and winmd5 for the md5 hash - they both agreed.
Just also checked in Microsoft tool: https://www.microsoft.com/en-us/download/details.aspx?id=11533 and Nirsoft: http://www.nirsoft.net/utils/hash_my_files.html

And they all give the same md5 hash that packer does not seem to like.

**Comment by rickard-von-essen** [comment] 2016-08-23 20:21
Could you provide an example? It's hard to find a broken SHA1 calculation by guessing.

**Comment by DarwinJS** [comment] 2016-08-23 20:27
This happened on both the Server 2012 R2 Enterprise Eval (Downloadable for free at Microsoft's site: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2012-r2) and their ISO for licensed ISO media for Server 2012 R2 (not the one "with update").

Also it is the **MD5 hash that is broken** - not SHA1.

Since these are very large files (4.1 GB and 4.4 GB) it may have to do with the file size along WITH md5.

**Comment by rickard-von-essen** [comment] 2016-08-23 21:38
Is there a official list on Microsofts pages with the checksums? And what's the SHA1 (or 256, 512) for the ISO. I need to verify that I have the same iso and see if I can reproduce this.
 
```
md5 /Volumes/LaCie/isos/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-
US-IR3_SSS_X64FREE_EN-US_DV9.ISO
MD5 (/Volumes/LaCie/isos/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO) = 5b5e08c490ad16b59b1d9fab0def883a
```

**Comment by DarwinJS** [comment] 2016-08-23 21:57
I just logged into the trial site and was surprised to see they do not give any hashes.

On the MSDN downloads site they only give SHA1 hashes.

Maybe I'm not understanding, but If you generate your own hash with multiple utilities and they all match and then that same hash fails under packer - won't you have sufficient proof?

**Comment by DarwinJS** [comment] 2016-08-23 22:05
Sorry, didn't answer your other question - yes the second file in your post is the one and has the exact same hash I was trying to use under packer.

Thanks!

**Comment by rickard-von-essen** [comment] 2016-08-23 22:13
It's not about prof. I need a way to reproduce this.

Can you confirm that you get this problem with `9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO` which has the SHA1 sum `849734f37346385dac2c101e4aacba4626bb141c`?

```
shasum /Volumes/LaCie/isos/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO
849734f37346385dac2c101e4aacba4626bb141c  /Volumes/LaCie/isos/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO
```

**Comment by DarwinJS** [comment] 2016-08-23 22:16
I don't have that ISO, but I do get it with the one in your previous post:

```
md5 /Volumes/LaCie/isos/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-
US-IR3_SSS_X64FREE_EN-US_DV9.ISO
MD5 (/Volumes/LaCie/isos/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO) = 5b5e08c490ad16b59b1d9fab0def883a
```

**Comment by rickard-von-essen** [comment] 2016-08-24 07:06
Closing this sine your MD5 sum is wrong according to the info you have given. If you disagree reopen and provide exactly `iso file name`, `md5`, `sha1`.

- iso: 9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO
- md5: 5b5e08c490ad16b59b1d9fab0def883a
- sha1: 849734f37346385dac2c101e4aacba4626bb141c

**Comment by DarwinJS** [comment] 2016-08-24 11:03
We have the same hashes for that same file (see screenshot belos).

However, on my system packer complains that the md5 hash does not match when I use this exact md5 hash on this ISO in my packer template JSON.

![image](https://cloud.githubusercontent.com/assets/11597190/17928441/ac38c2c0-69c8-11e6-9eb1-168fead50545.png)

**Comment by vtolstov** [comment] 2016-08-24 11:05
Provide full json file template, may be something windows related...

**Comment by rickard-von-essen** [comment] 2016-08-24 11:47
Your original report have:
```
virtualbox-iso: Error downloading: checksums didn't match expected: 0e7c09aab20dec3cd7eab236dab90e78
```
Which is incorrect.

Yes a full json template will decrease the confusion.

**Comment by DarwinJS** [comment] 2016-08-24 12:00
The original error is from the licensed media.  I reported the error after I received it a second time from a completely different ISO from my first one.  I had found someone else having an error with the trial media. Since not everyone has access to the licensed media, we have since been discussing the trial media as it is easy to obtain.

Below is the template. It is a modified version of this one: https://github.com/mwrock/packer-templates/blob/master/vbox-2012r2.json
Just yesterday I successfully built from it when using the SHA1 checksum.  Right now before posting it I simply changed back to MD5 (same checksum we are both getting from external utilities) and received this exact error.

So to be clear the below template produced the below error.  If I simply change to the SHA1 (same one as we are both getting discussed in this thread) it runs without a problem.

```
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: file:///C:/SW/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.iso
    virtualbox-iso: Error downloading: checksums didn't match expected: 5b5e08c490ad16b59b1d9fab0def883a
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.
```

Packer template (modified version of: https://github.com/mwrock/packer-templates/blob/master/vbox-2012r2.json)

```
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--natpf1", "guest_winrm,tcp,,55985,,5985" ],
        [ "modifyvm", "{{.Name}}", "--memory", "2048" ],
        [ "modifyvm", "{{.Name}}", "--vram", "48" ],
        [ "modifyvm", "{{.Name}}", "--cpus", "2" ]
      ],
      "guest_additions_mode": "{{ user `guest_additions_mode` }}",
      "guest_additions_path": "C:/users/vagrant/VBoxGuestAdditions.iso",
      "guest_os_type": "Windows2012_64",
      "headless": "{{ user `headless` }}",
      "iso_url": "{{ user `iso_url` }}",
      "iso_checksum": "{{ user `iso_checksum` }}",
      "iso_checksum_type": "sha1",
      "communicator": "winrm",
      "winrm_username": "vagrant",
      "winrm_password": "vagrant",
      "winrm_timeout": "12h",
      "shutdown_command": "a:/PackerShutdown.bat",
      "shutdown_timeout": "15m",
      "floppy_files": [
        "answer_files/2012_r2{{user `core`}}/Autounattend.xml",
        "scripts/oracle.cer",
        "scripts/postunattend.xml",
        "scripts/boxstarter.ps1",
        "scripts/PackerShutdown.bat",
        "scripts/package.ps1",
        "scripts/SetupComplete-2012.cmd",
        "scripts/Test-Command.ps1"
      ]
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "script": "scripts/provision.ps1"
    }
  ],
  "variables": {
    "core": "",
    "guest_additions_mode": "upload",
    "headless": "true",
    "iso_url": "C:\\SW\\9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.iso",
    "iso_checksum_type": "MD5",
    "iso_checksum": "5b5e08c490ad16b59b1d9fab0def883a"
  }
}
```

**Comment by vtolstov** [comment] 2016-08-24 12:25
Nice! Next - run build with PACKER_LOG=1 and attach you packer debug log 
https://www.packer.io/docs/other/debugging.html

**Comment by DarwinJS** [comment] 2016-08-24 12:33
Here you go:

[packerfailsmd5.zip](https://github.com/mitchellh/packer/files/434660/packerfailsmd5.zip)

**Comment by vtolstov** [comment] 2016-08-24 12:58
I have no idea, may be create example go binary that tries to calculate md5 sum of this file and check it output?

**Comment by DarwinJS** [comment] 2016-08-24 13:20
I think we've established that the checksum is solid.  Also the system I am using to generate the checksum (which matches the checksums generated on this thread) is the same system packer is running on.

Has anyone attempt to repo the problem with the said file and md5 checksum?

**Comment by dragon788** [comment] 2016-09-22 20:48
I'm having the same issue, using MD5 seems to be the culprit. I have the same checksum for the 2012r2 standard evaluation file,  5b5e08c490ad16b59b1d9fab0def883a. I think there is a bug in the logic for the checksums where it is comparing with something NOT MD5 and claiming it failed.

**Comment by mwhooker** [comment] 2017-02-11 06:20
@DarwinJS Is this indeed the template you're modifying to see these errors?

```
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--natpf1", "guest_winrm,tcp,,55985,,5985" ],
        [ "modifyvm", "{{.Name}}", "--memory", "2048" ],
        [ "modifyvm", "{{.Name}}", "--vram", "48" ],
        [ "modifyvm", "{{.Name}}", "--cpus", "2" ]
      ],
      "guest_additions_mode": "{{ user `guest_additions_mode` }}",
      "guest_additions_path": "C:/users/vagrant/VBoxGuestAdditions.iso",
      "guest_os_type": "Windows2012_64",
      "headless": "{{ user `headless` }}",
      "iso_url": "{{ user `iso_url` }}",
      "iso_checksum": "{{ user `iso_checksum` }}",
      "iso_checksum_type": "sha1",
      "communicator": "winrm",
      "winrm_username": "vagrant",
      "winrm_password": "vagrant",
      "winrm_timeout": "12h",
      "shutdown_command": "a:/PackerShutdown.bat",
      "shutdown_timeout": "15m",
      "floppy_files": [
        "answer_files/2012_r2{{user `core`}}/Autounattend.xml",
        "scripts/oracle.cer",
        "scripts/postunattend.xml",
        "scripts/boxstarter.ps1",
        "scripts/PackerShutdown.bat",
        "scripts/package.ps1",
        "scripts/SetupComplete-2012.cmd",
        "scripts/Test-Command.ps1"
      ]
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "script": "scripts/provision.ps1"
    }
  ],
  "variables": {
    "core": "",
    "guest_additions_mode": "upload",
    "headless": "true",
    "iso_url": "C:\\SW\\9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.iso",
    "iso_checksum_type": "MD5",
    "iso_checksum": "5b5e08c490ad16b59b1d9fab0def883a"
  }
}
```

I think the problem is that you're changing the `iso_checksum_type` in the `variables` section, which isn't actually being referenced by the builder section. it's still hard coded as `"iso_checksum_type": "sha1",`.

Please try this template instead:


```
{
  "builders": [
    {
      "type": "virtualbox-iso",
      "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--natpf1", "guest_winrm,tcp,,55985,,5985" ],
        [ "modifyvm", "{{.Name}}", "--memory", "2048" ],
        [ "modifyvm", "{{.Name}}", "--vram", "48" ],
        [ "modifyvm", "{{.Name}}", "--cpus", "2" ]
      ],
      "guest_additions_mode": "{{ user `guest_additions_mode` }}",
      "guest_additions_path": "C:/users/vagrant/VBoxGuestAdditions.iso",
      "guest_os_type": "Windows2012_64",
      "headless": "{{ user `headless` }}",
      "iso_url": "{{ user `iso_url` }}",
      "iso_checksum": "{{ user `iso_checksum` }}",
      "iso_checksum_type": "{{ user `iso_checksum_type` }}",
      "communicator": "winrm",
      "winrm_username": "vagrant",
      "winrm_password": "vagrant",
      "winrm_timeout": "12h",
      "shutdown_command": "a:/PackerShutdown.bat",
      "shutdown_timeout": "15m",
      "floppy_files": [
        "answer_files/2012_r2{{user `core`}}/Autounattend.xml",
        "scripts/oracle.cer",
        "scripts/postunattend.xml",
        "scripts/boxstarter.ps1",
        "scripts/PackerShutdown.bat",
        "scripts/package.ps1",
        "scripts/SetupComplete-2012.cmd",
        "scripts/Test-Command.ps1"
      ]
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "script": "scripts/provision.ps1"
    }
  ],
  "variables": {
    "core": "",
    "guest_additions_mode": "upload",
    "headless": "true",
    "iso_url": "C:\\SW\\9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.iso",
    "iso_checksum_type": "md5",
    "iso_checksum": "5b5e08c490ad16b59b1d9fab0def883a"
  }
}
```

If you try that one and still get a checksum error, please post here and I'll re-open the issue.

**Closed by mwhooker** 2017-02-11 06:20 UTC
Labels: bug

**Comment by jbittner79** [comment] 2018-04-11 02:08
I figured out the issue here.... 16th line down...

{
  "builders": [
    {
      "type": "virtualbox-iso",
      "vboxmanage": [
        [ "modifyvm", "{{.Name}}", "--natpf1", "guest_winrm,tcp,,55985,,5985" ],
        [ "modifyvm", "{{.Name}}", "--memory", "2048" ],
        [ "modifyvm", "{{.Name}}", "--vram", "48" ],
        [ "modifyvm", "{{.Name}}", "--cpus", "2" ]
      ],
      "guest_additions_mode": "{{ user `guest_additions_mode` }}",
      "guest_additions_path": "C:/users/vagrant/VBoxGuestAdditions.iso",
      "guest_os_type": "Windows2012_64",
      "headless": "{{ user `headless` }}",
      "iso_url": "{{ user `iso_url` }}",
      "iso_checksum": "{{ user `iso_checksum` }}",       <<< this needs the sha1 hash,  **849734f37346385dac2c101e4aacba4626bb141c**
      "iso_checksum_type": "sha1",
      "communicator": "winrm",
      "winrm_username": "vagrant",
      "winrm_password": "vagrant",
      "winrm_timeout": "12h",
      "shutdown_command": "a:/PackerShutdown.bat",
      "shutdown_timeout": "15m",
      "floppy_files": [
        "answer_files/2012_r2{{user `core`}}/Autounattend.xml",
        "scripts/oracle.cer",
        "scripts/postunattend.xml",
        "scripts/boxstarter.ps1",
        "scripts/PackerShutdown.bat",
        "scripts/package.ps1",
        "scripts/SetupComplete-2012.cmd",
        "scripts/Test-Command.ps1"
      ]
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "script": "scripts/provision.ps1"
    }
  ],
  "variables": {
    "core": "",
    "guest_additions_mode": "upload",
    "headless": "true",
    "iso_url": "C:\\SW\\9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.iso",
    "iso_checksum_type": "MD5",
    "iso_checksum": "5b5e08c490ad16b59b1d9fab0def883a"
  }
}
