### ISSUE TITLE
Digitalocean creating droplet from custom image, error

### ISSUE THREAD

**Issue by gabriel403** [mitchellh/packer#1792] opened 2014-12-24 20:26 UTC
Using this json

```
{
  "builders": [
  {
    "type"         : "digitalocean",
    "api_token"    : "myapitoken",
    "image"        : "myprivateimageid",
    "region"       : "nyc3",
    "size"         : "512mb",
    "snapshot_name": "prowl-v2",
    "droplet_name" : "prowl.io"
  }],
  "provisioners": [{
    "type"          : "puppet-masterless",
    "manifest_file" : "manifests/prowl.pp",
    "module_paths"  : ["../../puppet/modules"]
  }]
}
```

and running `PACKER_LOG=true packer build prowl-do.json`

I get 

```
2014/12/24 20:19:26 packer-builder-digitalocean: 2014/12/24 20:19:26 sending new request to digitalocean: https://api.digitalocean.com/v2/droplets buffer: {"name":"prowl.io","region":"nyc3","size":"512mb","image":"","ssh_keys":["605362"]}
2014/12/24 20:19:27 packer-builder-digitalocean: 2014/12/24 20:19:27 response from digitalocean: {"id":"unprocessable_entity","message":"You specified an invalid image for Droplet creation."}
```

seems as if packer is dropping the image name before sending the request.

```
$ packer version
Packer v0.7.5
```

**Comment by sethvargo** [comment] 2015-02-24 23:51
This might have been fixed by https://github.com/mitchellh/packer/pull/1875. If not, the error is indicating that your image_id is not correct. Please double check your image id.

**Closed by sethvargo** 2015-02-24 23:51 UTC

**Comment by mojotalantikite** [comment] 2015-03-12 22:58
I ran into this earlier today, it doesn't look like #1875 fixes it. 

Looks like the problem is that private images return null for a slug:
```
{"id":10985731,"name":"base-2015-03-12","distribution":"Ubuntu","slug":null,"public":false,"regions":["nyc3"],"created_at":"2015-03-12T18:02:31Z","min_disk_size":20,"type":"snapshot"}
```
Packer uses the slug for setting the image name on the request, so private images end up requesting "image":"", which obviously throws an error.

I fixed this in a fork, I'll push it up in a few.

**Comment by gabriel403** [comment] 2015-03-13 11:07
@mojotalantikite awesome! I gave up and was building them by hand for custom images :smiley:

**Comment by dietervds** [comment] 2015-04-14 07:58
Thanks for the fix @mojotalantikite, ran into this as well.
Has there been a PR for the fix yet?

If not, is there a workaround to get it to run anyway for now?

**Comment by dietervds** [comment] 2015-04-14 14:13
Thanks @mojotalantikite :-)

**Comment by kaelumania** [comment] 2016-02-16 16:40
i am still experiencing this issue

**Comment by kaelumania** [comment] 2016-02-16 17:26
It seems that the logic in order to read images by name (fetching private images and comparing slug, name or id) has been removed since this issue was closed. Currently the DigitalOcean API is used directly and it does not support finding images by name.

**Comment by TamerElfeky** [comment] 2020-01-03 13:00
Is this issue resolved  yet ? i am still facing the same error

```==> digitalocean: Creating droplet...
==> digitalocean: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.
==> digitalocean: Deleting temporary ssh key...
Build 'digitalocean' errored: Error creating droplet: POST https://api.digitalocean.com/v2/droplets: 422 You specified an invalid image for Droplet creation.
```
