### ISSUE TITLE
File Provisioner - File not uploaded if destination path contains spaces

### ISSUE THREAD

**Issue by Raznic** [mitchellh/packer#2714] opened 2015-09-06 15:46 UTC
There appears to be a problem with the file provisioner when the destination path contains spaces. For example the following file provisioner doesn't give me any problems:

``` json
{
    "type": "file",
    "source": "startup.bat",
    "destination": "C:\\startup.bat"
}
```

But the following example does:

``` json
{
    "type": "file",
    "source": "startup.bat",
    "destination": "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\startup.bat"
}
```

Packer won't throw any errors when running the file provisioner, but when I check the destination folder the uploaded file isn't there. I've only tested this behavior for Windows builds, haven't really tried it on Linux.

**Comment by pecigonzalo** [comment] 2015-09-06 21:19
Try doing 
```
{
    "type": "file",
    "source": "startup.bat",
    "destination": "'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\startup.bat'"
}
```

Adding the ```'``` might be a workaround

**Comment by Raznic** [comment] 2015-09-07 15:22
Just tried @pecigonzalo's suggestion, but unfortunately the file still isn't being uploaded.

**Comment by pecigonzalo** [comment] 2015-09-07 21:24
The error seems to be on https://github.com/packer-community/winrmcp project.
```
null output will be in this color.

==> null: Waiting for WinRM to become available...
==> null: Connected to WinRM!
==> null: Uploading ../scripts/Write-ZeroesToFreeSpace.ps1 => "C:/tmp dir/Write-ZeroesToFreeSpace.ps1"
==> null: Upload failed: Error restoring file from $env:TEMP\winrmcp-55ee0043-8f52-d008-3693-3d2c56c3747f.tmp to 'C:\tmp dir\Write-ZeroesToFreeSpace.ps1': restore operation returned code=1
Build 'null' errored: Error restoring file from $env:TEMP\winrmcp-55ee0043-8f52-d008-3693-3d2c56c3747f.tmp to 'C:\tmp dir\Write-ZeroesToFreeSpace.ps1': restore operation returned code=1

==> Some builds didn't complete successfully and had errors:
--> null: Error restoring file from $env:TEMP\winrmcp-55ee0043-8f52-d008-3693-3d2c56c3747f.tmp to 'C:\tmp dir\Write-ZeroesToFreeSpace.ps1': restore operation returned code=1

==> Builds finished but no artifacts were created.
```

**Comment by swade1987** [comment] 2016-03-08 21:13
was this ever resolved?

**Comment by Raznic** [comment] 2016-03-08 21:55
Just tried testing in 0.9.0, but I'm still running into the same error.

**Comment by swade1987** [comment] 2016-03-08 22:01
I am running 0.9.0 as well.

Regards

Steve
------------------------------------
Steven Wade
Principal Consultant
Steven Wade Consulting Ltd
steven@stevenwade.co.uk<mailto:steven@stevenwade.co.uk>
www.stevenwade.co.uk<http://www.stevenwade.co.uk>
uk.linkedin.com/in/stevendavidwade/<http://uk.linkedin.com/in/stevendavidwade/>

On 8 Mar 2016, at 21:56, Raznic <notifications@github.com<mailto:notifications@github.com>> wrote:


Just tried testing in 0.9.0, but I'm still running into the same error.

**Comment by yyolk** [comment] 2016-03-21 16:54
I'm seeing this error when uploading a `chef/` directory to an AMI that was previously built from packer (tiering AMIs) but not when I create an AMI all in one go.

**Comment by yyolk** [comment] 2016-03-23 18:37
Through a bunch of research it seems that I was having a race condition.

I was able to resolve my issue by adding a `"pause_before": "30s"` to the `file` and `powershell` provisioner steps that were causing me issues.

Refs: https://github.com/packer-community/packer-windows-plugins/issues/25

**Comment by kopaka** [comment] 2016-05-01 03:54
FYI, I am having a [discussion](https://github.com/packer-community/winrmcp/pull/14) with the owner of the [winrmcp](https://github.com/packer-community/winrmcp) project about a simple fix to resolve this very issue.

**Comment by kopaka** [comment] 2016-05-02 05:34
Pull Request https://github.com/mitchellh/packer/pull/3488 submitted to fix this issue.

**Comment by mixmatch** [comment] 2016-05-20 22:02
still seeing this in 0.10.1

**Comment by gwiddel** [comment] 2016-06-03 06:18
Confirmed still happening in 0.10.1

**Comment by davidobrien1985** [comment] 2016-06-22 01:38
So, has anybody found a solution to this?

```
packer --version
0.10.1
```

Trying to copy files from my laptop to an Azure VM and it errors out with

```
==> azure-arm: Waiting for WinRM to become available...
==> azure-arm: Connected to WinRM!
==> azure-arm: Uploading c:\dev\packer\vagrant\packer-azure/PSWindowsUpdate => C:\Program Files\WindowsPowerShell\Module
s\PSWindowsUpdate
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: Error restoring file from $env:TEMP\winrmcp-5769e8e8-b22f-db59-9024-a3e23279449e.tmp to 'C:\P
rogram Files\WindowsPowerShell\Modules\PSWindowsUpdate\Add-WUOfflineSync.ps1': restore operation returned code=1

==> Some builds didn't complete successfully and had errors:
--> azure-arm: Error restoring file from $env:TEMP\winrmcp-5769e8e8-b22f-db59-9024-a3e23279449e.tmp to 'C:\Program Files
\WindowsPowerShell\Modules\PSWindowsUpdate\Add-WUOfflineSync.ps1': restore operation returned code=1

==> Builds finished but no artifacts were created.
```

Kind of don't want to go via Storage Accounts on Azure, I'm already doing this on AWS with S3 and it's sort of painful.

**Comment by yyolk** [comment] 2016-06-22 01:49
What happens when you add `pause_before` on the first command after WinRM is available?

**Comment by davidobrien1985** [comment] 2016-06-22 03:52
@yyolk no change:

```
==> azure-arm: Waiting for WinRM to become available...
==> azure-arm: Connected to WinRM!
==> azure-arm: Pausing 30s before the next provisioner...
==> azure-arm: Uploading c:\dev\packer\vagrant\packer-azure/PSWindowsUpdate => C:\Program Files\WindowsPowerShell\Module
s\PSWindowsUpdate
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: Error restoring file from $env:TEMP\winrmcp-576a0922-8456-b2c6-db77-c07880045104.tmp to 'C:\P
rogram Files\WindowsPowerShell\Modules\PSWindowsUpdate\Add-WUOfflineSync.ps1': restore operation returned code=1

==> Some builds didn't complete successfully and had errors:
--> azure-arm: Error restoring file from $env:TEMP\winrmcp-576a0922-8456-b2c6-db77-c07880045104.tmp to 'C:\Program Files
\WindowsPowerShell\Modules\PSWindowsUpdate\Add-WUOfflineSync.ps1': restore operation returned code=1

==> Builds finished but no artifacts were created.
```

It connects to WinRM, but then fails.

**Comment by yyolk** [comment] 2016-06-22 04:16
Thanks @davidobrien1995 for checking my issue is still mysterious but WinRM is unstable in general from my experience building over 250 production APIs in the last month with 0.10.1

**Comment by jamiemjennings** [comment] 2016-07-25 19:27
Fyi @davidobrien1985 I have a packer fork at https://github.com/jamiemjennings/packer which resolves this issue using the patch implemented by @kopaka mentioned above. Unfortunately the official packer project hasn't been able to include the patched version of `winrmcp` due to [unrelated issues](https://github.com/mitchellh/packer/pull/3488#issuecomment-217610265).

**Comment by obilodeau** [comment] 2016-07-26 14:19
Even if the destination path doesn't contain spaces this issue still happens as long as at least one copied file contains a space. For example with this config (which doesn't have spaces):

```json
        {
                "type": "file",
                "source": "{{user `tools_path`}}/",
                "destination": "C:\\Tools"
        }
```

Build fails on file with a space:
```
==> virtualbox-iso: Uploading /home/olivier/opt/malboxes-tools/ => C:\Tools
[...]
Build 'virtualbox-iso' errored: Error restoring file from $env:TEMP\winrmcp-57976d77-c664-49bd-14ed-dd28996a28c2.tmp to 'C:\Tools\ExeinfoPe\skins\Skin - blue deep water.jpg': restore operation returned code=1
```

**Comment by Linuturk** [comment] 2016-07-28 16:13
Can confirm I'm still seeing this as well.
Packer v0.10.1

```
[18:20:38] 1469668838,,ui,error,==> amazon-ebs: Upload failed: Error restoring file from $env:TEMP\winrmcp-57995de3-66db-74b2-d3c2-3cfc8a14b498.tmp to 'C:\Program Files\Mozilla Firefox\defaults\pref\local-settings.js': restore operation returned code=1
```

**Comment by netflash** [comment] 2016-08-10 21:04
Same story here :-(
```
==> amazon-ebs: Uploading grid.cmd => C:\ProgramData\grid.cmd
==> amazon-ebs: Uploading grid.cmd => C:\ProgramData\Microsoft\grid.cmd
==> amazon-ebs: Uploading grid.cmd => C:\ProgramData\Microsoft\Windows\grid.cmd
==> amazon-ebs: Uploading grid.cmd => C:\ProgramData\Microsoft\Windows\Start Menu\grid.cmd
==> amazon-ebs: Upload failed: Error restoring file from $env:TEMP\winrmcp-57ab961f-c1c9-2bc2-3bc0-93ad1204133d.tmp to 'C:\ProgramData\Microsoft\Windows\Start Menu\grid.cmd': restore operation returned code=1
```

**Comment by ssccio** [comment] 2016-08-22 12:47
Per https://www.packer.io/docs/provisioners/file.html:

"The recommended usage of the file provisioner is to use it to upload files, and then use shell provisioner to move them to the proper place, set permissions, etc."

ie 
{
  "type": "file",
  "source": "files/config.xml",
  "destination": "C:\\temp\\config.xml"
},
{
  "type": "powershell",
  "inline": [ "move c:\\temp\\config.xml 'C:\\Program Files\\Amazon\\Ec2ConfigService\\settings\\config.xml'" ]
}

**Comment by ramubachala** [comment] 2016-09-23 18:35
Any update on this defect? or have you guys figure out any workaround?

**Comment by ssccio** [comment] 2016-09-26 14:25
Upload to a directory without a space then move it from there.

**Comment by mwhooker** [comment] 2017-01-22 02:26
We updated winrmcp in https://github.com/mitchellh/packer/pull/4424

Verified that this is fixed with

```
  "provisioners": [
      {
          "type": "file",
          "source": "files/myfile",
          "destination": "C:\\my file upload"
      },
      {
            "type": "powershell",
              "inline": ["dir c:\\"]
      }

  ],
```

**Closed by mwhooker** 2017-01-22 02:26 UTC
Labels: bug, communicator/winrm, provisioner/file, windows-host

**Comment by LymanZerga** [comment] 2019-05-13 19:11
Spaces in paths can be fixed by surrounding the path with double quotes.
`
"provisioners": [
      {
          "type": "file",
          "source": "files/myfile",
          "destination": "\"C:\\my file upload\""
      }
],
`
