### ISSUE TITLE
Azure: Cryptic Error Message when Marketplace is Missing Image

### ISSUE THREAD

**Issue by boumenot** [mitchellh/packer#3731] opened 2016-07-18 22:15 UTC
packer: v0.10.2+CHANGES

I deployed the following Debian template, and the deployment failed.

``` json
{
  "variables": {
      "client_id": "{{env `ARM_CLIENT_ID`}}",
      "tenant_id": "{{env `ARM_TENANT_ID`}}",
    "client_secret": "{{env `ARM_CLIENT_SECRET`}}",
    "resource_group": "{{env `ARM_RESOURCE_GROUP`}}",
    "storage_account": "{{env `ARM_STORAGE_ACCOUNT`}}",
    "subscription_id": "{{env `ARM_SUBSCRIPTION_ID`}}",
    "ssh_user": "packer",
    "ssh_pass": "Super820121SecretLong##$#Trails"
  },
  "builders": [{
    "type": "azure-arm",

    "client_id": "{{user `client_id`}}",
    "tenant_id": "{{user `tenant_id`}}",
    "client_secret": "{{user `client_secret`}}",
    "resource_group_name": "{{user `resource_group`}}",
    "storage_account": "{{user `storage_account`}}",
    "subscription_id": "{{user `subscription_id`}}",

    "capture_container_name": "images",
    "capture_name_prefix": "packer",

    "ssh_username": "{{user `ssh_user`}}",
    "ssh_password": "{{user `ssh_pass`}}",

    "image_publisher": "credativ",
    "image_offer": "Debian",
    "image_sku": "8",
      "ssh_pty": "true",
      "os_type": "linux",

    "location": "South Central US",
    "vm_size": "Standard_A2"
  }],
  "provisioners": [{
    "execute_command": "echo '{{user `ssh_pass`}}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'",
    "inline": [
      "apt-get update",
      "apt-get upgrade -y",

      "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
    ],
    "inline_shebang": "/bin/sh -x",
    "type": "shell"
  }]
}
```

Packer responded with the following error message.

``` text
==> azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
```

The network trace contained better information that should have been shown to the user.  It contained this error message.

``` json
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https:\/\/aka.ms\/arm-debug for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{  \"status\": \"Failed\",  \"error\": {    \"code\": \"ResourceDeploymentFailure\",    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",    \"details\": [      {        \"code\": \"ImageNotFound\",        \"message\": \"The platform image 'credativ:Debian:8:latest' is not available. Verify that all fields in the storage profile are correct.\"      }    ]  }}"
            }
        ]
    }
}
```

There's JSON embedded in JSON, so if you extract the contents of message.

``` json
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'.",
        "details": [
            {
                "code": "ImageNotFound",
                "message": "The platform image 'credativ:Debian:8:latest' is not available. Verify that all fields in the storage profile are correct."
            }
        ]
    }
}
```

:100: Finally!  A helpful error message.

**Comment by mwhooker** [comment] 2017-01-30 21:48
It looks like this is a dupe of #3536, which I believe has been fixed. Please reopen if I'm wrong

**Closed by mwhooker** 2017-01-30 21:48 UTC
Labels: builder/azure
