### ISSUE TITLE
Failures due to recoverable AWS errors have returned

### ISSUE THREAD

**Issue by patricklucas** [mitchellh/packer#1539] opened 2014-09-27 19:09 UTC
Most of these were fixed up last fall after I opened #574 and #668, but a number of these transient AWS errors have returned, causing a steady stream of builds to fail.

For example, we are again seeing Packer fail after it can't find the instance immediately after launch:

```
11:59:39 ==> amazon-ebs: Inspecting the source AMI...
11:59:39 ==> amazon-ebs: Creating temporary keypair: packer 5427091b-3a8e-abeb-57d8-2c6d0793a9b6
11:59:40 ==> amazon-ebs: Launching a source AWS instance...
11:59:41 ==> amazon-ebs: Error finding source instance (i-d2dd6518): The instance ID 'i-d2dd6518' does not exist (InvalidInstanceID.NotFound)
11:59:41 ==> amazon-ebs: Deleting temporary keypair...
11:59:41 Build 'amazon-ebs' errored: Error finding source instance (i-d2dd6518): The instance ID 'i-d2dd6518' does not exist (InvalidInstanceID.NotFound)
```

That one is the most frequent, but we also occasionally see IO timeouts as well:

```
10:46:57 ==> amazon-ebs: Stopping the source instance...
10:46:59 ==> amazon-ebs: Waiting for the instance to stop...
10:47:30 ==> amazon-ebs: Creating the AMI: generictrusty-ami_1219
10:47:30     amazon-ebs: AMI: ami-c38f8786
10:47:30 ==> amazon-ebs: Waiting for AMI to become ready...
10:49:13 ==> amazon-ebs: Error waiting for AMI: read tcp 204.246.163.231:443: i/o timeout
10:49:13 ==> amazon-ebs: Terminating the source AWS instance...
10:49:14 ==> amazon-ebs: Deleting temporary keypair...
10:49:14 Build 'amazon-ebs' errored: Error waiting for AMI: read tcp 204.246.163.231:443: i/o timeout
```

IIRC, these all _used_ to be covered by retries, so perhaps it is a regression.

**Comment by ckelner** [comment] 2015-01-08 19:12
:+1:

**Comment by allenluce** [comment] 2015-01-08 22:54
Seeing this several times this week (using v0.7.5).

**Comment by grayaii** [comment] 2015-01-09 19:03
We see several times a week too (using v0.7.2).  Is there anything that we can do to help fix or identify the problem better?

**Comment by elasticdog** [comment] 2015-01-30 15:51
Just wanted to add another comment saying that we're seeing this on a very regular basis as well. Let us know if there is any additional information that would make tracking this down any easier.

**Comment by timurb** [comment] 2015-01-30 18:50
By chance have you tried running packer in a different AWS Region?
I think we've experienced some AWS-related issues (probably somewhat different ones though) with vagrant-aws and packer in US-West (Oregon) region but they've immediately almost disappeared when we've moved to EU region.

**Comment by elasticdog** [comment] 2015-01-30 19:27
> By chance have you tried running packer in a different AWS Region?

@timurb we've seen this in both us-west-1 and us-west-2

**Comment by cosmopetrich** [comment] 2015-01-31 01:41
I've encountered it regularly on ap-southeast-2 as well.

**Comment by ckelner** [comment] 2015-01-31 01:43
Ours have been across us-east-1 and us-west-2, haven't executed in other regions.

**Comment by ava-miket** [comment] 2015-02-02 18:34
We are experiencing this in us-west-1 inside a VPC with v0.7.5.  This was also referenced in 
mitchellh/packer#878 which was closed in Feb 2014, but users continue to report problems with.

**Comment by rhysyngsun** [comment] 2015-02-09 20:42
Assuming this is the same issue, we've been seeing this frequently with v0.7.5 in us-west-1:

     amazon-ebs: Waiting for AMI to become ready... 
     amazon-ebs: Error waiting for AMI: Get <REDACTED DescribeImages API>: dial tcp: i/o timeout

**Comment by elasticdog** [comment] 2015-02-11 21:22
To add some specific frequency data...over the past 5 days, we've triggered jobs in our deployment pipeline 44 times, 11 of which have failed due to this "Error finding source instance" error. I'm hoping someone has a decent workaround soon.

**Comment by jacob-webber** [comment] 2015-02-13 07:20
Getting this error ap-southeast-2 - annoying as its sporadic.

**Comment by mgcleveland** [comment] 2015-02-19 18:07
+1 also seeing this error.  We are running a custom build of packer with this branch merged in: https://github.com/mitchellh/packer/pull/1764.  1764 resolves the errors it addresses, but we have now moved on to the (occasional) error tracked by this issue.

**Comment by renat-sabitov-sirca** [comment] 2015-02-19 22:17
@mgcleveland Try also this patch: https://github.com/mitchellh/goamz/pull/180

It fixes retry bugs and increases retry counts in goamz, which is the root cause for transient AWS errors

**Comment by blalor** [comment] 2015-02-25 11:34
Yep, getting these, too.  It's not just a packer problem, as Amazon spews these pretty frequently in other contexts, but this class of error really should trigger a backoff and retry.  Yeah, I know that's easier said than done, since I need to build it into my own tooling… :-P

```
==> ami-cheffed-role-qa-testrunner: Error finding source instance (i-9a325560): The instance ID 'i-9a325560' does not exist (InvalidInstanceID.NotFound)
```

**Comment by iskar909** [comment] 2015-03-04 16:36
Confirming I'm having this issue as well.  Packer frequently leaves an instance alive post failure. us-east-1

**Comment by jantman** [comment] 2015-03-06 19:19
I just got bitten by this too. I'm not sure I'd say this "isn't a packer problem" - it's certainly an issue with either Packer or the underlying library it uses. For better or worse, yeah, 503s aren't uncommon from AWS. It's up to the tool to perform a retry (ideally with exponential backoff) before throwing an error.

**Comment by TronPaul** [comment] 2015-03-09 03:56
I was hitting timeouts on every run of amazon-ebs even after premaking a security group. Patching goamz with [mitchellh/goamz#180](https://github.com/mitchellh/goamz/pull/180) made it work first try. Thanks for the fix, @renat-sabitov-sirca.

**Comment by niknaknet** [comment] 2015-03-14 23:23
To add some observations to this, working with the really basic 'example.json' from the starter guide:
using an m3.medium in us-east-1, with no VPC, I get success.
however working in eu-west-1, in a vpc, I consistently get a failure on the security group, which 'does not exist'.

.... emitting .... 
amazon-ebs output will be in this color.

==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Creating temporary keypair: packer 5504b87e-cf88-d720-31d6-743468549e4b
==> amazon-ebs: Creating temporary security group for this instance...
==> amazon-ebs: Authorizing SSH access on the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Error launching source instance: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (VPCResourceNotSpecified)
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (VPCResourceNotSpecified)

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (VPCResourceNotSpecified)

==> Builds finished but no artifacts were created.

... hopefully that adds something useful

... I am using Packer v0.7.5 from homebrew on OSX

**Comment by ehershey** [comment] 2015-03-27 23:54
+1. I'd love to see this merged and in a new release.

**Comment by healsjnr** [comment] 2015-06-02 01:12
+1 Any word on when / if the pull req above is going to get merged in?

**Comment by geekpete** [comment] 2015-06-05 06:47
And failing is fine, but the script needs to clean up after itself.
Any created resources need to be deleted if the process has failed part way through.

**Comment by renewooller** [comment] 2015-06-09 05:29
+1 also very keen to hear if there is a plan to fix this

**Comment by mitchellh** [comment] 2015-06-10 17:34
This should be fixed with our switch to the official AWS library that does this automatically.

**Closed by mitchellh** 2015-06-10 17:34 UTC
Labels: bug, builder/amazon

**Comment by allenluce** [comment] 2015-06-10 17:39
@mitchellh can you add a link to the relevant issue or PR or commit?

**Comment by mitchellh** [comment] 2015-06-10 17:41
#2034

**Comment by richard-hulm** [comment] 2015-07-08 13:48
Updated to 0.8.1 and getting an intermittent failure on some of our AMI builds that seem related to this?

Fails to create a security group occasionally

See logs below
```
1436361832,,ui,say,amazon-ebs output will be in this color.
1436361832,,ui,say,
1436361832,,ui,say,==> amazon-ebs: Prevalidating AMI Name...
1436361832,,ui,say,==> amazon-ebs: Inspecting the source AMI...
1436361833,,ui,say,==> amazon-ebs: Creating temporary keypair: packer 559d2468-a0ce-6ef8-ddbb-f67f14cf31d9
1436361833,,ui,say,==> amazon-ebs: Creating temporary security group for this instance...
1436361833,,ui,say,==> amazon-ebs: Authorizing access to port 22 the temporary security group...
1436361833,,ui,say,==> amazon-ebs: Launching a source AWS instance...
1436361833,,ui,error,==> amazon-ebs: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-78d8d51d' does not exist in VPC 'vpc-XXXXXXX'\n==> amazon-ebs: 	status code: 400%!(PACKER_COMMA) request id: []
1436361833,,ui,say,==> amazon-ebs: No AMIs to cleanup
1436361833,,ui,say,==> amazon-ebs: Deleting temporary security group...
1436361833,,ui,say,==> amazon-ebs: Deleting temporary keypair...
1436361833,,ui,error,Build 'amazon-ebs' errored: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-78d8d51d' does not exist in VPC 'vpc-XXXXXXX'\n	status code: 400%!(PACKER_COMMA) request id: []
1436361833,,error-count,1
1436361833,,ui,error,\n==> Some builds didn't complete successfully and had errors:
1436361833,amazon-ebs,error,Error launching source instance: InvalidGroup.NotFound: The security group 'sg-78d8d51d' does not exist in VPC 'vpc-XXXXXXXX'\n	status code: 400%!(PACKER_COMMA) request id: []
1436361833,,ui,error,--> amazon-ebs: Error launching source instance: InvalidGroup.NotFound: The security group 'sg-78d8d51d' does not exist in VPC 'vpc-XXXXXXXX'\n	status code: 400%!(PACKER_COMMA) request id: []
```

**Comment by elasticdog** [comment] 2015-07-08 14:50
@richard-hulm sounds like an exponential back-off should be used for that query in a similar fashion to this original issue with the instance IDs, due to EC2's back-end being [eventually consistent](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency). The switch to goamz may not have helped in that regard, but I don't know enough about that code to confirm.

**Comment by renewooller** [comment] 2015-07-12 23:03
A work around could be to specify your own security group.
