### ISSUE TITLE
After exporting virtual machine: Error unregistering guest additions

### ISSUE THREAD

**Issue by virgo47** [mitchellh/packer#3121] opened 2016-01-28 13:56 UTC
Because I had random problems with `guest_additions_mode` "upload" (found known issues around WinRM upload of big files), I tried "attach" which worked very well for me. The difference, though, was that after my VM was ready, it still had D: optical drive with additions in it. I decided to remove it with:

```
"vboxmanage_post": [
                [
                    "storageattach",
                    "{{.Name}}",
                    "--storagectl",
                    "IDE Controller",
                    "--port",
                    "1",
                    "--device",
                    "0",
                    "--medium",
                    "none"
                ]
            ]
```

This worked, except for the error during final steps of VM export -- these are not fatal, just very red ;-) (lines from Error... to the one finishing with cpp, first/last two are added for context).

```
==> virtualbox-iso: Exporting virtual machine...
    virtualbox-iso: Executing: export packer-virtualbox-iso-1453981832 --output output-virtualbox-iso\packer-virtualbox-iso-1453981832.ovf
==> virtualbox-iso: Error unregistering guest additions: VBoxManage error: VBoxManage.exe: error: No storage device attached to device slot 0 on port 1 of controller 'IDE Controller'
==> virtualbox-iso: VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component SessionMachine, interface IMachine, callee IUnknown
==> virtualbox-iso: VBoxManage.exe: error: Context: "DetachDevice(Bstr(pszCtl).raw(), port, device)" at line 393 of file VBoxManageStorageController.cpp
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Running post-processor: vagrant
```

Is my case invalid? Should I do it differently? Now my crated VM does not have optical disk, so my goal is achieved. If this is the right way, can the message be less alarming and probably not "Error"?

**Comment by dragon788** [comment] 2016-06-24 21:29
@virgo47 I like your workaround, I just ran into and reported the root bug which is Packer not removing the additional optical drive automatically, but I believe there was an issue with this related to VMware where it wasn't removing the ISO, and your solution is very similar to one suggested in that case as well.

**Comment by gsingh93** [comment] 2016-12-24 07:23
I'm seeing those error messages as well with the same `vboxmanage_post` settings. Any idea why it happens?

**Comment by rickard-von-essen** [comment] 2016-12-24 08:48
Please try using [`post_shutdown_delay`](https://www.packer.io/docs/builders/virtualbox-iso.html#post_shutdown_delay)

**Comment by mwhooker** [comment] 2017-01-30 21:43
I know this is older, but marking as dupe of #3652

**Closed by mwhooker** 2017-01-30 21:43 UTC
Labels: builder/virtualbox, question
