### ISSUE TITLE
PUPPET (MASTERLESS) PROVISIONER - manifest_file can be directory

### ISSUE THREAD

**Issue by neekipatel** [mitchellh/packer#1761] opened 2014-12-15 21:43 UTC
Hi,

The new puppet version doesn't allow import statements in manifest files. They recommend running puppet apply on a directory with a bunch of smaller manifest broken down. However packer requires the manifest_file key to be a file not a directory. Can you consider this key to be a directory.

Example

"provisioners": [
    {
      "type": "puppet-masterless",
      "manifest_file": "/etc/puppet/manifest/my_website",
      "module_paths" : [ "/etc/puppet/modules" ]
    }
]

Puppet Structure:

/etc/puppet/manifest/my_website/
 - 01.crons.pp
 - 02.vhosts.pp
 - 03.rewrites.pp
 - 04.node.pp
 
In older version of puppet I would have my_website.pp with but off imports to crons.pp, vhosts.pp ....

Since puppet got rid of inheritances and imports can you consider the manfiest_file to be a directory instead, Here is the puppet doc that explains this approch: https://docs.puppetlabs.com/puppet/latest/reference/dirs_manifest.html

Thanks,
Neeki Patel

**Comment by sethvargo** [comment] 2015-02-24 23:42
Duplicate of #1446

**Closed by sethvargo** 2015-02-24 23:42 UTC
Labels: provisioner/puppet

**Comment by Munna1234** [comment] 2017-06-08 21:24
This code is utilized nevertheless would certainly be a wonderful enthusiasts item as they do not provide the codes such as this anymore. <a href="http://gratuitxblcodes.com/">abonnement xbox live gratuit</a> Duplicate the alphanumeric code produced on the message area, from the Xbox Live Gold Generator program.
