### ISSUE TITLE
VMware builder lstat 'no such file or directory'

### ISSUE THREAD

**Issue by Lee303** [mitchellh/packer#3087] opened 2016-01-19 11:38 UTC
During step 'StepPrepareTools' following the shutting down of the provisioned VM, the following error halts the provisioning:

2016/01/19 12:37:22 ui: ask: ==> vmware-iso: Pausing before cleanup of step 'StepPrepareTools'. Press enter to continue.
==> vmware-iso: Pausing before cleanup of step 'StepPrepareTools'. Press enter to continue. 
2016/01/19 12:37:23 ui: scan err: unexpected newline
Build 'vmware-iso' errored: lstat output_windows2008r2: no such file or directory

2016/01/19 12:37:23 ui error: Build 'vmware-iso' errored: lstat output_windows2008r2: no such file or directory
2016/01/19 12:37:23 Waiting on builds to complete...
2016/01/19 12:37:23 Builds completed. Waiting on interrupt barrier...
2016/01/19 12:37:23 machine readable: error-count []string{"1"}
2016/01/19 12:37:23 ui error: 
==> Some builds didn't complete successfully and had errors:
2016/01/19 12:37:23 machine readable: vmware-iso,error []string{"lstat output_windows2008r2: no such file or directory"}
2016/01/19 12:37:23 ui error: --> vmware-iso: lstat output_windows2008r2: no such file or directory

I'm unsure how to trace this further, any help would be appreciated!

Lee

**Comment by dave2** [comment] 2016-01-21 01:02
Can you post your packer template, and what version of packer is this against?

**Comment by Lee303** [comment] 2016-01-29 10:40
Hi,

This is against the latest version of packer (manually built). Template is below for the builder:

{

    "variables": {
        "username": "Administrator",
        "password": "password",
        "disk_size": "30720",

        "temp_path":"C:\\Windows\\Temp"
    },
    "builders": [
        {
            "type": "vmware-iso",
            "communicator": "winrm",
            "iso_url": "file:///root/win2008r2.iso",
            "iso_checksum": "9b0cd5b11cc2e92badb74450f0cac03006d3c63a2ada36cb1eb95c1bf4b2608f",
            "iso_checksum_type": "sha256",
            "output_directory": "output_windows2008r2",
            "shutdown_command": "cmd.exe /c shutdown -s -f",
            "disk_size": "{{ user `disk_size`}}",

            "headless": true,
            "guest_os_type": "windows7srv-64",
            "remote_type": "esx5",
            "remote_username": "root",
            "remote_password": "password",
            "remote_host": "172.25.103.156",
            "remote_port": 2020,
            "vnc_port_min": 8443,
            "vnc_port_max": 8444,
            "tools_upload_flavor": "windows",
            "vmx_data": {
                "memsize": "4096",
                "numvcpus": "8",
                "cpuid.coresPerSocket": "4",
                "scsi0.virtualdev": "pvscsi",
                "sched.scsi0:0.shared": "normal",
                "sched.scsi0:0.throughputCap": "off",
                "ethernet0.networkName": "Packer"
            },


            "winrm_username": "{{ user `username`}}",
            "winrm_password": "{{ user `password`}}",
            "winrm_timeout": "10h",
            "winrm_insecure": true,
            "winrm_use_ssl": true,
            "winrm_port": 5986,

            "vm_name": "windows2008r2-{{isotime \"2006-01-02\"}}",
            "boot_wait": "5s",
            "floppy_files": [
                "unattend/ecloud/esx_51/2008r2/Autounattend.xml",
                "drivers/ecloud/esx_51/2008/*"
            ]
        }
    ]
........................


Cheers,
Lee

**Comment by majinjing3** [comment] 2016-03-07 11:04
try to create a dir named "output_windows2008r2" in you working dir, or add format parameter into builder. #3050

**Comment by matt-deboer** [comment] 2016-07-14 16:20
Adding `"format": "ovf"` into the template got me past this problem on packer 0.10.1.
This was based on the code changes in PR #3050, as mentioned by @jim3mar.

**Comment by nickcharlton** [comment] 2016-09-24 17:59
I've been seeing this error myself and I can confirm that I'm not seeing it on `master` where #3050 has been merged in. I'd recommend compiling yourself against `master` whilst we wait for a release.

**Comment by Lee303** [comment] 2016-09-24 18:07
Cheers guys, will give it another go and let you know!

**Comment by mwhooker** [comment] 2016-10-14 05:52
looks like this was fixed in #3050

**Closed by mwhooker** 2016-10-14 05:52 UTC
Labels: builder/vmware, question, waiting-reply, windows-guest
