### ISSUE TITLE
Atlas Packer Crash: amazon-ebs unexpected EOF

### ISSUE THREAD

**Issue by lochlainn** [mitchellh/packer#3079] opened 2016-01-15 21:27 UTC
http://pastebin.ca/3334053 is the full crash log.

Packer v0.9.0.rc1 (25108c8d13912434d0f32faaf1ea13cdc537b21e+CHANGES)
amazon-ebs output will be in this color.
==> amazon-ebs: Prevalidating AMI Name...
Build 'amazon-ebs' errored: unexpected EOF
==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: unexpected EOF
==> Builds finished but no artifacts were created.
!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Any time I try to build via packer push, I get this error.  I'm able to build locally, but running the build on Atlas fails consistently.

**Comment by cbednarski** [comment] 2016-01-15 21:39
Thanks for the report. This is not a release build so I'm not sure what the issue is, but my guess is that there is something weird in the version of the AWS SDK that this version was compiled with. We will pin this dependency when we release 0.9.

/cc @pearkes

**Comment by cbednarski** [comment] 2016-01-15 23:17
@lochlainn Can you share more of your log? Some of my colleagues working on Atlas suspect that this might be related to a disk full issue in Atlas. If you prefer you can reach out to [atlas support](support@hashicorp.com) and they can reference your build history.

**Comment by rickard-von-essen** [comment] 2016-10-15 11:36
I'll close this since there is to little information to work with. Please reopen if you still see this problem and can share more info or reach out to the Atlas support.

**Closed by rickard-von-essen** 2016-10-15 11:36 UTC
Labels: bug, builder/amazon, waiting-reply
