### ISSUE TITLE
Packer crash

### ISSUE THREAD

**Issue by ljankowski** [mitchellh/packer#3318] opened 2016-03-07 16:40 UTC
Hi,

We use packer on daily basis and this was the first packer crash we encountered.
It's a CentOS7 build, virtualbox-iso builder in a headless mode. 

Build usually finishes within 10-15mins, this one was frozen after half an hour.
Before actually trying to log in via ssh I stupidly pressed ctrl+c, which surprisingly generated the crash.log. If I knew, I'd try to debug it first. Artefact in form of a VirtualBox image hadn't been removed.

[crash.log.txt](https://github.com/mitchellh/packer/files/161642/crash.log.txt)

It looks like build died on 'yum upgrade' or 'reboot'. it never got to the next provisioner.

Snip from the template:
```json
  "provisioners": [
    {
      "type": "shell",
      "environment_vars": [
        "http_proxy={{user `proxy`}}",
        "https_proxy={{user `proxy`}}",
        "ftp_proxy={{user `proxy`}}"
      ],
      "inline": [ "yum -y upgrade" ]
    },{
      "type"  : "shell",
      "except": [ "docker" ],
      "inline": [ "reboot" ]
    },{
      "type": "shell",
      "pause_before": "20s",
      "environment_vars": [
        "http_proxy={{user `proxy`}}",
        "https_proxy={{user `proxy`}}",
        "ftp_proxy={{user `proxy`}}"
      ],
      "scripts": [
        "{{user `work_dir`}}/scripts/{{user `template_name`}}/add_repos.sh",
```

I'm not too bothered by this, as I said it was one-off problem.
However crash message says, you keen to see it, so here it is.
Restarted rebuild, without any alterations, finished successfully.

Let me know if I can help any further.

Thanks,
Lukasz

**Comment by cbednarski** [comment] 2016-03-07 17:45
Thanks for the report. This is an [odd crash](https://gist.github.com/cbednarski/8db69b96b905ad8dc6bf#file-packer-crash-log-L2204-L2228) I do not think I have seen before.

Also, I noticed you are using packer 0.8.6; this _may_ already be fixed in the latest release.

**Comment by ljankowski** [comment] 2016-03-08 10:58
It is an odd crash. Like I said, it was just one-off, so not too bothered.
For the time-being upgraded packer to 0.9.0 and will monitor.

I'll let you know if crashes again.

Thanks

**Comment by mwhooker** [comment] 2016-10-14 08:16
I think this is a dupe of #3699

**Closed by mwhooker** 2016-10-14 08:16 UTC
Labels: crash, need-repro
