### ISSUE TITLE
enhancement request for setting the image destination container (Azure builder)

### ISSUE THREAD

**Issue by hdatteln** [mitchellh/packer#4673] opened 2017-03-16 15:11 UTC
This is an **enhancement request** for setting the 'capture_container_name' in the Azure builder.

## How it works currently
Currently, I can only define the last subdirectory name of the target storage container of an Azure image.
From the documentation:
> capture_container_name (string) Destination container name. Essentially the "directory" where your VHD will be organized in Azure. The captured VHD's URL will be https://.blob.core.windows.net/system/Microsoft.Compute/Images//.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.vhd.

## Suggested Enhancement
It would be great if I could control the full container path/name;
For example, I would like to have the new image saved as  https://****.blob.core.windows.net/my_images/.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.vhd. .

## Reason for this request:
In Azure, I was trying to create a Managed Image from one of my packer-created VHD images under /system/Microsoft.Compute/Images/myfolder/myimage.vhd

This resulted in the following error:
`The blob name in URL https://*****.blob.core.windows.net/system/Microsoft.Compute/Images/customimage/azcustomimage-osDisk.****.vhd contains a slash. This is presently not supported for disks.`

As a work-around, i can copy the vhd into another location with no subdirectories (e.g. https://****.blob.core.windows.net/my_images/), and use that for creating the managed image.
However, it would be great if it was possible to set this location from the azure builder.

**Comment by boumenot** [comment] 2017-03-16 19:04
Thank you for open an issuing, and for providing such a well thought out post.

This is a dupe of #3626 and to an extent #4565.  My current thinking it to make this a post-processor that automatically moves the image to where you want.  The Azure APIs insist on putting the blob under this hierarchy, and make it impossible to pick an alternate location.

I don't know if Managed Disks provide a better solution for this scenario (I suspect not), but if they do that may be a better alternative.

**Closed by boumenot** 2017-03-16 19:04 UTC
Labels: builder/azure, duplicate, post-processor/azure
