### ISSUE TITLE
0.7.2 File Uploader Bug

### ISSUE THREAD

**Issue by steve-dave** [mitchellh/packer#1717] opened 2014-12-03 07:32 UTC
I am not sure when this bug was introduced, but I discovered it when I recently upgraded to 0.7.2.

When uploading a directory that contains symliniks, previously they were properly dereferenced and the files they pointed at were successfully uploaded.  Now, although packer reports the directory is successfully uploaded, only a few bytes of each of the files are actually uploaded.  My theory is that although the content is read from the correct file, the size used is the size of the symlink file.

In the example below, only 25 bytes of ../../backend/files/hosts are uploaded, even though the actual file contains 240 bytes:
```
$ ls -al hosts
lrwxr-xr-x  1 x  y  25  3 Dec 17:28 hosts -> ../../backend/files/hosts
$ ls -al ../../backend/files/hosts
-rw-r--r--  1 x  y  240 30 Jul 14:38 ../../backend/files/hosts
```

Perhaps Go libraries that packer is built against have changed their behaviour or the change is somehow related to using temp files instead of memory for getting file sizes before uploading?

**Comment by sethvargo** [comment] 2015-02-24 23:30
Duplicate of https://github.com/mitchellh/packer/issues/1627

**Closed by sethvargo** 2015-02-24 23:30 UTC
