### ISSUE TITLE
qemu: Error processing QemuArggs: No version found

### ISSUE THREAD

**Issue by lucassrg** [mitchellh/packer#3586] opened 2016-05-31 20:30 UTC
Failed to build qemu template on Windows 7 machine: Packer could not read qemu version.

qemu stores all CLI commands outputs into a log file: stdout.txt and it seems packer is trying to read that from a console/variable. 

- Packer Version: 0.10.1
- Host platform: Windows 7 64 bits
- Debug log file: [log](https://gist.github.com/lucassrg/7f05629aab9acd721460d5e5e2021040) 

- Qemu emulator: 2.6.50

**Comment by cbednarski** [comment] 2016-05-31 22:11
Are the QEMU commands in your path? I think the one packer calls by default is `qemu-system-x86_64`.

**Comment by lucassrg** [comment] 2016-05-31 22:26
Yes, I added qemu installed folder into Windows PATH, and I'm able to call them from any location using PowerShell.
The point is, when I call qemu --version (or any other command) the output is stored in a stdio.txt file instead of print out in the console.

**Comment by lucassrg** [comment] 2016-06-01 18:03
After reviewing the source code I can say this is definitely a bug. The way qemu outputs its version on Windows hosts seems to be different than other OS. I was taking a look on the function [Driver.Version()](https://github.com/mitchellh/packer/blob/master/builder/qemu/driver.go#L181) which is used to return qemu's version and it's running a command (qemu -version) and retrieving its "stdout" as a way to retrieve qemu version. Unfortunately it fails on windows hosts because it returns a null/empty string, since the output value is stored in stdio.txt file at qemu's root folder.

**Comment by lucassrg** [comment] 2016-06-02 14:11
Is there any work around available? (i.e. bypass version verification setting up some property/variable)

**Comment by vtolstov** [comment] 2016-06-02 14:15
2016-06-02 17:11 GMT+03:00 Lucas Gomes <notifications@github.com>:

> Is there any work around available? (i.e. bypass version verification
> setting up some property/variable)


I think we can switch by GOOS and in case of windows check stdout.txt, but
does it possible to run qemu under windows and get stdout not in file? Can
you check this (i don't have windows system)


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@yoctocloud.net

**Comment by lucassrg** [comment] 2016-06-02 14:38
I have checked this out and unfortunately it seems not to be possible. This is what the [documentation](http://wiki.qemu.org/Hosts/W32#Special_W32_devices) says: 

> 
Text which is normally printed by QEMU to the console output channels (normally known as standard output = stdout and standard error output = stderr) might be written to files called stdout.txt and stderr.txt. If you want to see QEMU's help messages or if it does not work as expected, you should look for these files in the directory where your exe file is installed.

**Comment by vtolstov** [comment] 2016-06-02 16:23
2016-06-02 17:39 GMT+03:00 Lucas Gomes <notifications@github.com>:

> I have checked this out and unfortunately it seems not to be possible.
> This is what the documentation
> <http://wiki.qemu.org/Hosts/W32#Special_W32_devices> says:
>
> Text which is normally printed by QEMU to the console output channels
> (normally known as standard output = stdout and standard error output =
> stderr) might be written to files called stdout.txt and stderr.txt. If you
> want to see QEMU's help messages or if it does not work as expected, you
> should look for these files in the directory where your exe file is
> installed.
>
>
ok, so we need to switch on GOOS while detect version and in case of
windows try to read this fiile. This is not too complex, so may be in near
feature i have enought time to fix this, or pr welcome =)


-- 
Vasiliy Tolstov,
e-mail: v.tolstov@yoctocloud.net

**Comment by lfarnell** [comment] 2016-07-08 23:54
I think i may have solved this issue. I think what the problem is that the tools provide by https://qemu.weilnetz.de seem to be broken since 2013. I downloaded the package http://lassauge.free.fr/qemu/release/Qemu-2.5.0-windows.7z and used this and it seems to work. I of course put the folder location in my path and pointed the qemuargs to the location of the bios folder for the roms. I get the version output fine using this package. i did have to put this into the qemu builder for it too work without errors:
``` json
"qemu_binary": "qemu-system-x86_64",
      "qemuargs": [
        [
          "-L",
          "C:\\Program Files\\qemu\\Bios"
        ]
```

This is an older build of qemu for windows, but it seems to be the only reliable build.

**Comment by vtolstov** [comment] 2016-07-09 13:28
@cbednarski may be add to docs this info?

**Comment by lfarnell** [comment] 2016-07-09 14:28
I can added it to the docs and send a pull request

**Comment by vtolstov** [comment] 2016-07-09 14:57
Thanks!
9 Июл 2016 г. 17:29 пользователь "Luke Farnell" <notifications@github.com>
написал:

**Comment by ryanmaclean** [comment] 2016-07-09 22:04
@stweil, is the version output something you're aware of? I've also come across the bug with https://qemu.weilnetz.de builds today (and unfortunately the work-around is a no-go at the moment).

**Comment by ryanmaclean** [comment] 2016-07-09 23:08
I've provided feedback on #3702 as I think it might require some further work before adding to the official docs. Is anyone able to test on non-Fast Ring Windows 10?

**Comment by lfarnell** [comment] 2016-07-10 03:21
I tested on Windows 7 enterprise. My laptop is Windows 10 slow ring. I can test on that and see what happens

**Comment by stweil** [comment] 2016-07-10 07:39
@ryanmaclean, I am not sure whether I have understood the problem  discussed here correctly, but maybe the first chapter of my [FAQ](https://qemu.weilnetz.de/FAQ) answers your question.

**Comment by ryanmaclean** [comment] 2016-07-10 16:18
Thanks for the quick reply, @stweil. The problem seems to stem from Packer requiring the Qemu version to be output to stdout, whereas in newer Wemu build for Windows this is sent to stdout.txt. I tried a few workarounds to no avail.

**Comment by lfarnell** [comment] 2016-07-10 18:19
I just tried to install [QEMU for Windows](https://qemu.weilnetz.de/w64/) and [QEMU on Windows](http://lassauge.free.fr/qemu/) on Windows 10 slow-ring and i wasnt able to view anything in the console for QEMU for Windows but i was able to for QEMU on Windows. I would assume a code change would have to be made if enough people want QEMU to be an option on Windows systems.

**Comment by stweil** [comment] 2016-07-10 18:39
@lfarnell, did you read https://qemu.weilnetz.de/FAQ? Just set the correct environment variable, then you'll get console output.

**Comment by lfarnell** [comment] 2016-07-10 18:56
OK so setting the ENV works! it resolves all the problems. I can update my PR to include this and it should alleviate most of the issue.

**Comment by ryanmaclean** [comment] 2016-07-10 22:45
This is fantastic news - thanks @stweil, and sorry I missed that on my first read through!

**Comment by ryanmaclean** [comment] 2016-07-10 22:56
I've confirmed that `export SDL_STDIO_REDIRECT=1` in the shell (cygwin for me)  prior to running the build will work, along with `"headless": true,` in the JSON file.

**Comment by lfarnell** [comment] 2016-07-10 23:38
i've updated the PR with the latest solution. If the PR is merged i think that this issue can be closed.

**Closed** 2016-08-23 21:53 UTC
Labels: builder/qemu, question, windows-host
