### ISSUE TITLE
Duplicate AMI

### ISSUE THREAD

**Issue by waiteb3** [mitchellh/packer#2123] opened 2015-05-19 23:49 UTC
When coping AMIs, it duplicates the AMI even if it was built in the same region

```json
{
  "region": "us-west-2",
  "ami_regions": [
    "us-east-1",
    "us-west-2"
  ]
}
```

It's only mildly annoying, but it'd be nice if it was either documented or dealt with in the logic.

**Comment by henrysher** [comment] 2015-06-04 15:44
@mitchellh my PR failed in the ci test, however, it seems the failure was not caused by my code.

**Comment by mitchellh** [comment] 2015-06-08 16:26
Fixed by #2175

**Closed by mitchellh** 2015-06-08 16:26 UTC
Labels: bug, builder/amazon
