### ISSUE TITLE
File provisioner strange behavior if parent directory missing

### ISSUE THREAD

**Issue by jantman** [mitchellh/packer#1477] opened 2014-09-09 18:07 UTC
If I specify a file provisioner to upload a single file to a given path, i.e. ``/root/.ssh/known_hosts`` and the parent directory (``/root/.ssh``) does not exist, it places the file *at that path* - i.e. ``/root/.ssh`` becomes a file with the content that was specified.

This is highly illogical, and was very confusing to me...

**Comment by catsby** [comment] 2015-06-15 21:27
Hey all – I'm closing this now, I can't reproduce it on `master`:

```
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Uploading quickstart.json => /tmp/some/dirs/dont/exist/quickstart.json
==> amazon-ebs: Upload failed: scp: /tmp/some/dirs/dont/exist: No such file or directory
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: scp: /tmp/some/dirs/dont/exist: No such file or directory

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: scp: /tmp/some/dirs/dont/exist: No such file or directory

==> Builds finished but no artifacts were created.
```

Let me know if you run into this again

**Closed by catsby** 2015-06-15 21:27 UTC
Labels: bug, provisioner/file

**Comment by neechbear** [comment] 2017-11-22 13:46
I see this behaviour on version 1.1.2 for x86_64 Linux. It too me time time to work out what was going on.

My provisioner configuration is:

```
    {
      "type": "file",
      "source": "http-proxy.conf",
      "destination": "/etc/systemd/system/docker.service.d/http-proxy.conf"
    },
```

This previously worked when I was using an older version of the Docker package which DID create the `/etc/systemd/system/docker.service.d` parent directory for me.

I then rebuild the image with Packer with a newer version Docker which does NOT create the `/etc/systemd/system/docker.service.d` parent directory for me. This time, Packer completed without any warnings or errors, and places the contents of my source `http-proxy.conf` file into a filename called `/etc/systemd/system/docker.service.d`.

In my opinion this behaviour is strange and unexpected. I think it should result in a fatal error of some kind.

I do not see the kind of error that the previous post by @catsby indicates.

**Comment by SwampDragons** [comment] 2017-11-28 01:00
@neechbear sorry you're experiencing an issue, but this is a really old ticket.  Can you open a new one with all the steps to reproduce we request in our issue template?

**Comment by mwhooker** [comment] 2017-12-01 00:20
@neechbear that behavior _is_ probably unexpected and errors should be made clearer. The problem is that there was a bug in how the docker communicator worked before. What the docs say (which isn't a _great_ excuse), is that the parent directory needs to exist before writing a file to it. We fixed a bug, which is why this behavior changed in a patch number fix.
