### ISSUE TITLE
Make the --debug pausing after each step optional

### ISSUE THREAD

**Issue by bobziuchkovski** [mitchellh/packer#1687] opened 2014-11-21 21:29 UTC
It would be wonderful if, by default, --debug only paused after an error is encountered.  I can see where there are times it would be useful to pause after every step, but more often than not I'm only interested in pausing at the point packer fails.

Proposed:

--debug behaves exactly as it does now, except it only pauses when an error is encountered
--stepwise switch added to pause after every step, switch valid only if --debug is enabled

**Comment by Mil0dV** [comment] 2015-01-05 09:18
+1 for @ziuchkovski suggestion. Our packer builds often take 5-10mins, and launching an ec2 instance with the resulting AMI isn't that fast either. To improve our debug-workflow I would really like a 'fire and forget' debug mode which allows me to switch to something else and when I come back I can see the output and log in to the instance to determine the steps needed to get the desired result. 

(Ideally I would have our rake task that fires packer log in to the instance for me, but that's also somewhat off topic. It also seems near-impossible to use the 'hang' @joshuacox suggested in this use-case)

**Comment by zettabyte** [comment] 2015-07-31 02:01
I've been watching feature request #409 for close to two years now (not long after it was created). As many people have commented on that issue and as @Mil0dV and @ziuchkovski have requested here, we really do need a way to fire a build, come back later and if there's an error, have the opportunity to inspect the instance. So, here's another +1 for this (or #409).

**Comment by joshuacox** [comment] 2015-07-31 02:38
Not to detract from your +1, but don't forget about setting 
`PACKER_LOG=1`
I believe this gives all the detailed output you are going to see in debug mode without the steps, you just have to set an env var rather than supply a option.   What would that option be named out of curiosity? -debug-nowait perhaps?  I kind of prefer the method of just appending an enormous amount v's in a flag (i.e. `-vvvvvvvvvvvvvvvvvvvvvvvv`)

**Comment by joshuacox** [comment] 2015-07-31 02:48
just a suggestion on perhaps a name and implied functionality:

`--rm=false  `   <--- perhaps would be useful, like in docker, and might take care @zettabyte and @ziuchkovski 's needs to inspect them

**Comment by zettabyte** [comment] 2015-07-31 14:50
Yeah, bringing up `PACKER_LOG` is a red herring as far as I'm concerned. I specifically mentioned, "have the opportunity to inspect the instance" for a reason. The second comment on this issue is a suggestion to set `PACKER_LOG` followed up by a response explaining why that's insufficient.

**Comment by mattolenik** [comment] 2015-08-13 21:19
I'm also having difficulty debugging Packer provisioning failures. The debug logs do not provide enough useful information...I really need a way to have the VM left intact to inspect.

**Comment by ebelew** [comment] 2015-08-23 18:41
Situation where I can't think of an alternative to a way to pause in the middle: Using packer:vmware-iso builder, I had added the tools_upload options on a windows guest. The upload appeared to be working, but 7zip failed to extract the archive. 

I had to enable the head, log in on the head and open explorer while other provisioning was being done. Then opened explorer to watch the folder, and see that the file was 0bytes. However, this wasted a lot of time because I had to baby-sit the VM creation from start to finish. 

The first suggestion is definitely what I was looking for when I found this problem. The log gave no real info except that 7zip failed due to a bad archive file.

**Comment by orivej** [comment] 2015-10-04 16:40
https://github.com/orivej/multistep/commit/e02bce9811c65138ea2e84c7162cd8769f35858f implements @ziuchkovski's suggestion, but it requires https://github.com/mitchellh/multistep/pull/5 to be useful.

**Comment by orivej** [comment] 2015-11-12 00:46
Oops, wrong link, the patch for packer is at https://github.com/orivej/packer/tree/debug-on-error

**Comment by absolutejam** [comment] 2015-11-17 21:17
And the ability to re-run a step if it errors!

It pains me to start a build, wait 20 minutes to see if the error that happened last time is still present (Which it usually is) and re-start the process 5 times (I'm in the midst of doing that now!).

**Comment by orivej** [comment] 2015-12-03 06:36
https://github.com/orivej/packer/tree/debug-on-error-2 allows you to retry the failed step, although without further modifications the overall build is likely to fail even if retry succeeds.

This branch is recent enough to incorporate #2608 (packer with built-in plugins), and to use it you have to delete previously installed plugin binaries (with names starting with `packer-`).

**Comment by mjperrone** [comment] 2016-02-20 23:58
dropping into an ssh session on error would be super helpful to make my debug loop shorter.

**Comment by amosshapira** [comment] 2016-03-22 00:04
+1 for any way to make it possible to ssh into an instance after a failed build. "--debug" is annoying not only because it requires pressing "Enter" every time but mainly because it sometimes silently requires more than one "Enter", leaving to almost randomly pressing extra "Enter"'s until I see a response.

**Comment by orivej** [comment] 2016-03-22 07:00
@amosshapira, reliable input handling can be restored by removing the call to `setupStdin()` from `main.go`. (https://github.com/mitchellh/packer/issues/409#issuecomment-161530252)

**Comment by jmound** [comment] 2016-05-05 21:41
An option that would help would be `continue-through-step $stepname` such that `packer build -debug` would not pause until it reached that particular step. eg. `packer build -debug --continue-through-step StepConnect` would run packer in debug mode but not pause until hitting the `StepConnect` step. 

I believe I saw this idea mentioned elsewhere, but can't find it at the moment.

**Comment by munjeli** [comment] 2016-05-11 00:56
Well, I'd be a fan of don't destroy, like vagrant. I set the log var and the detailed output does help a lot, but for now my workaround is simply to put a long sleep in a shell provisioner before the failure and ssh into the box to run the failure by hand, which makes me feel silly, but works. I name the ssh key for the amazon-ebs builder so packer doesn't make it's own.

**Comment by PeterMika** [comment] 2016-05-19 20:49
For those who share my goal of compiling that latest dev release of packer while integrating orivej earlier fix that pauses on first fail of packer build here are the steps I took achieve to that.

1. Complete "Setting up Go to work on Parker" steps 1-4 . ( see https://github.com/mitchellh/packer/blob/master/CONTRIBUTING.md )
2. 'git checkout master`
3. `git remote add fork https://github.com/orivej/packer`
4. `git fetch fork`
5. `git checkout -b debug-on-error fork/debug-on-error`
6. `git merge debug-on-error`
7.  `make`
8.  run  `./bin/packer build -debug template.json`

I can confirm that this worked for me and provisioning only paused when there was an error.

I was not able to successfully merge https://github.com/orivej/packer/tree/debug-on-error-2. 

I'm curious, I'm fairly new to packer and git and this issue; is there some other way people have been implementing orivej's fixes then how I have described?

**Comment by worstadmin** [comment] 2016-07-13 22:04
It can't merge because it's so far behind origin/master. Also this fix needs to become a PR on a current dev branch of packer. I'm taking a look now and will try to submit something useful.

**Comment by rickard-von-essen** [comment] 2016-11-11 22:56
Closing this since the `--on-error` flag added in 0.11.0 (#3885) should cover this use case.

**Closed by rickard-von-essen** 2016-11-11 22:56 UTC
Labels: core, debug-mode, enhancement

**Comment by lklepner** [comment] 2017-05-01 19:59
HI @rickard-von-essen 

I don't think the --on-error flag addresses the issue the OP raised, which is to enter debug mode with a keyfile and IP address when an error is encountered. 

As things are currently stand omitting the -debug flag skips the output of the IP address and download of the key file early on.. so even though the partial build is saved, accessing it is difficult if not impossible.

**Comment by rickard-von-essen** [comment] 2017-05-02 19:06
Finding the IP is simple and for getting access I recommend to using a non temporary ssh key pair.

**Comment by erichs** [comment] 2017-05-26 15:11
Hi, @rickard-von-essen!

With respect, using a non-temporary ssh key is a workaround. If setting the key to a known, probably shared key is a requirement to get tighter feedback loops during development, developers will do so, and are incentivized to check this key into the repo. 

At this point, one must ask: what is the purpose of supporting temporary ssh keys if we can't use them effectively?

**Comment by rickard-von-essen** [comment] 2017-05-27 10:48
The point of ephemeral temporary keys is that the are secure, they only exist in memory for the duration of the build. 

In small organizations it's easy to have personal keypairs in AWS that you can reference in a user variable. In larger organizations centralized auth is inevitable. So getting access is not handled by Packer/AWS at all.

**Comment by erichs** [comment] 2017-05-27 15:21
@rickard-von-essen, thanks for the response!

Granted: it's on me and my organization to provision SSH keys or other means of access. Possibly this provisioning happens at Packer build time, possibly it happens via some other bootstrapping with Chef or Ansible post-launch. 

As I understand the OP, the request here is for behavior that, on error during Packer provisioning, uses the in-memory, ephemeral credentials to drop me in an SSH session automatically. As I understand it, the new `--on-error` flag does not support this. Please correct me if I'm wrong here, I'd love it if that were the case!

If that can't be arranged, the secondary ask is that the ephemeral credentials can be written out to disk, without having to manually step through all steps, as the `-debug` flag does currently. Basically, there's a common workflow that would really benefit from `--on-error=ssh` (preferred) or `--on-error=write-pemfile` (workable). As I see it, this common workflow isn't being supported, and this is contrary to the Tao of Hashicorp.

**Comment by rickard-von-essen** [comment] 2017-05-28 12:39
> As I understand the OP, the request here is for behavior that, on error during Packer provisioning, uses the in-memory, ephemeral credentials to drop me in an SSH session automatically. As I understand it, the new --on-error flag does not support this.

That is correct. That exact solution requires allot of work. I don't say we object it but it's not a priority for us currently.

> Basically, there's a common workflow that would really benefit from --on-error=ssh (preferred) or --on-error=write-pemfile (workable).

Feel free to open a PR.

> As I see it, this common workflow isn't being supported, and this is contrary to the Tao of Hashicorp.

I don't see how the current solution contradict Tao. There is basically three types of debugging/developing of a Packer template. 1) Builder part where dropping to SSH doesn't help since the problem is not in that area. 2) Connectivity issues, requires some sort of out of band trouble shooting since SSH is (obviously) not working. 3) Provisioner problem/issue, these are best to troubleshoot with a `null` builder.

**Comment by mooperd** [comment] 2017-07-11 14:13
+1 In order to speed up debugging I would also like to be able to log in to a virtual machine without having to press enter throughout the build process.

**Comment by rickard-von-essen** [comment] 2017-07-11 15:23
See #5107
