### ISSUE TITLE
/mnt is mounted with ephemeral storage automatically

### ISSUE THREAD

**Issue by SydOps** [mitchellh/packer#3160] opened 2016-02-08 01:12 UTC
We use packer to build AMI image, but recently I found a strange problem.

When start a instance type (such as c3.large, which has two ephemeral storages) with previous images (built at 2014), the ephemeral disk devices are attached as blank disks.

But recently we re-built the images with packer (I download latest packer version), after start a new instance with same instance type, one of ephemeral storage is mounted automatically at `/mnt`, which is not in our expect. 

```
$ lsblk
NAME                   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda                   202:0    0   15G  0 disk
└─xvda1                202:1    0   15G  0 part /
xvdb                   202:16   0 15.3G  0 disk /mnt

$ grep mnt /etc/fstab
/dev/xvdb	/mnt	auto	defaults,nofail,comment=cloudconfig	0	2
```
So what I can do to get blank ephemeral storages device with packer images?

Here is the packer version I am using.
```
$ packer --version
0.8.6
``

**Comment by SydOps** [comment] 2016-02-08 22:24
If the source image is PV image `RHEL-6.5_GA-x86_64-9-Hourly2 (ami-45ea8f7f)`, I didn't have this /mnt issue.

But if I build with HVM image `RHEL-6.5_HVM_GA-x86_64-7-HVM-Hourly2 (ami-452eb67f)`, the rest settings are same in `template.json` file, I see `/mnt` on new instance.

**Comment by kwilczynski** [comment] 2016-07-07 08:00
@SydOps this is cloud-init doing, nothing to do with Packer. See this: http://cloudinit.readthedocs.io/en/latest/topics/examples.html (search for "mounts"). You can switch off this behaviour by passing empty array/list as part of your user data cloud-config section.

**Comment by rickard-von-essen** [comment] 2016-07-07 09:02
Closing since this is not an Packer issue. Hope the above link helps otherwise try posting on the mailing list

**Closed by rickard-von-essen** 2016-07-07 09:02 UTC
Labels: builder/amazon, question

**Comment by JarenGlover** [comment] 2017-12-04 20:01
@kwilczynski how would someone solve this problem if they were using bash shell script in their user_data instead of cloud-init.

**Comment by kwilczynski** [comment] 2017-12-04 20:46
Hi @JarenGlover, a good question.

How are you executing content of the user-data? Are you manually pull the content from the metadata service (see: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-user-data-retrieval), or are you running systemd unit on Container Linux?

Since I miss some details, I am going to try to generalise...

Whichever it would be, the idea is to execute unmount of `/mnt` sufficiently early (when using `cloud-init`, it starts quite early, often before things like e.g. `/etc/rc.local`), or if you cannot guarantee when it would run, then in your bootstrap script just make sure that the mount point is unmounted before dong anything with it - in other words, add `umount -l -f /mnt` just before doing other things with the ephemeral volume.

**Comment by JarenGlover** [comment] 2017-12-05 07:26
@kwilczynski we are pulling via metadata server. 

however, the situation I find myself in is the cloud-init appears to auto define `xvdb` at `/mnt` even if the device doesn't exist. I am not sure how to set default via shell as noted in your hyperlink. 

It appears one can't use shell + cloud-init yaml (?) in an ec2 instance user-data.

So at the end of my `user_data` shell script I did a `sed` command to remove the entire entry from `/etc/fstab` ... interesting enough an ec2 instance doesn't recover smoothly from a reboot with the below entry in the `/etc/fstab` and the device doesn't exist.  i3.large HVM. 

```
$ grep mnt /etc/fstab
/dev/xvdb       /mnt    auto    defaults,nobootwait,comment=cloudconfig 0       2
```

**Comment by kwilczynski** [comment] 2017-12-05 12:26
@JarenGlover you could maybe use multipart user-data, but I am not sure from the top of my head, whether it would work.

A question from me - why not use cloud-init? Is it not working for you? It also does other things like e.g. deploy SSH keys for your user, etc. Unless you handle this automatically yourself.

By the content of `/etc/fstab` I can see you are using Ubuntu (which is why I am surprised your don't want to use cloud-init to take care about your user data fro you, especially since it is installed by default in Canonical's cloud images; unless you are backing your own AMI, etc.), thus there is another mount option you can use - `nofail`.

The `nobootwait` is just a hint not to wait for the volume/mount point to become ready (e.g. using NBD or NFS, etc.), but `nofail` is the one which is going to ignore the failure caused by the device not being there.

You can bake your own AMI with updated content of the `/etc/fstab` to remove anything being there by default, and also remove cloud-init, if you really not want to use it. So this might be an option.

I am not sure what is your use case, though. :)

**Comment by JarenGlover** [comment] 2017-12-07 02:48
>A question from me - why not use cloud-init? Is it not working for you? It also does other things like e.g. deploy SSH keys for your user, etc. Unless you handle this automatically yourself.

fair question. I inherited it (not great answer i know). 

> You can bake your own AMI with updated content of the /etc/fstab to remove anything being there by default, and also remove cloud-init, if you really not want to use it. So this might be an option.

yep this would work too. 

I ended up with a nice sed command before my config management installed. It seems to work. If it fails at scale. I'll report back. Thanks this was very helpful cc @kwilczynski 

for those who make it this far and want to know the sed command.

`sed -i "/\/dev\/xvdb.*\/mnt.*defaults,nobootwait,comment=cloudconfig/d" /etc/fstab`

**Comment by CliveJL** [comment] 2018-01-16 12:56
I appreciate that this issue is Closed, but I've just stumbled across this problem and the root cause in my case was using a Packer file that we haven't updated for a long, long time that was using an "m3.medium" EC2 instance as its "instance_type". This is one of the few EC2 instance types that still have SSD storage (the old /dev/xvdb device) provisioned as standard. So even though we're primarily launching t2s from the Packer-built AMI, they ended up having the additional line in fstab due to "cloud-init" during the AMI build. I've switched the Packer "instance_type" to a t2 for the build and all is well with the resultant AMIs now... I hope this might help someone else who comes across this issue from a Google search as I did :)
