### ISSUE TITLE
Packer crashes with communicator=none

### ISSUE THREAD

**Issue by epowell** [mitchellh/packer#2736] opened 2015-09-11 19:57 UTC
Packer v0.8.6 on Centos 7.1, running vmware-iso builder remotely against ESXi 6.0.0.

I am provisioning a custom CentOS 7 machine that installs with no networking available. The resulting VM is to be packaged and distributed for deployment on customer networks, and this VM itself provides DHCP services so it cannot consume DHCP. 

Clearly, SSH provisioning won't work here, which is fine - the install is automated with just a few boot commands. However, Packer doesn't seem to like this configuration. The error seems directly related to using 'none' as the communicator:

`packer-builder-vmware-iso: panic: interface conversion: interface is nil, not packer.Communicator`

Full crash.log: https://gist.github.com/epowell/c5a3bc2751fd71bd3e68

**Comment by dbarrosop** [comment] 2015-09-14 07:17
I got exactly the same issue. In my case, I am also trying to build a box without any communicator.

**Comment by rickard-von-essen** [comment] 2015-09-14 08:29
It fails on this code https://github.com/mitchellh/packer/blob/master/builder/vmware/common/step_shutdown.go#L37
 the none communicator sets communicator in the statebag to nil.

We need to find all places where we get the communicator and only need it OR better introduce a _null object_ for the non communicator. @cbednarski what do you think?

**Comment by epowell** [comment] 2015-09-17 15:17
I agree with the null-object approach in principle, but it looks like there may be some reliance on side-effects from what I see happening in the VMware builder. There may be more side-effects that need to be simulated elsewhere in the code, so it may be more complicated than checking for nil everywhere.

I've got a (poor) first attempt at this here: https://gist.github.com/epowell/413620190028180588c2
I don't have a working Go dev environment, and am pretty new to it so I don't expect that to work at all. I expect there are much better patterns to do this, but I figured I'd take a swing at it.

**Comment by epowell** [comment] 2015-09-17 18:27
An alternate point fix for this: https://gist.github.com/epowell/b02c52aaeebaa624681c

This would not handle any other occurrences later in the vmware-iso builder.

**Comment by aneeshusa** [comment] 2016-01-10 18:10
#2772 was closed as a dupe of this issue, but it's for VirtualBox while this is for the VMWare provider. Can the title be changed to not be VMWare specific (i.e., "Packer crashes with communicator=none") to represent the expanded scope?

**Comment by cbednarski** [comment] 2016-01-15 01:42
@rickard-von-essen Thanks for linking the related issues. The change proposed in https://github.com/mitchellh/packer/pull/2848 LGTM. I will test and review tomorrow.

**Closed** 2016-01-21 20:44 UTC
Labels: bug, core, crash
