### ISSUE TITLE
Packer crashes with communicator set to "none"

### ISSUE THREAD

**Issue by borzwazie** [mitchellh/packer#3333] opened 2016-03-10 16:42 UTC
Describe the problem and include the following information:
- Packer Version: 0.9.1 dev
- Host platform : Ubuntu 15.04
- Crash Log: https://gist.github.com/borzwazie/153af05801d97b7b6b39

I am getting a crash when I have `"communicator": "none"`, although I am not trying to use a provisioner. I have a pre-existing ISO that I want to turn into an image, and which already contains all the artifacts I need. 

The key part of the crash seems to be here:

2016/03/09 16:47:12 ui: ^[[1;32m==> virtualbox-iso: Unregistering and deleting virtual machine...^[[0m
2016/03/09 16:47:12 packer: 2016/03/09 16:47:12 Executing VBoxManage: []string{"unregistervm", "box1", "--delete"}
2016/03/09 16:47:12 packer: 2016/03/09 16:47:12 stdout: 
2016/03/09 16:47:12 packer: 2016/03/09 16:47:12 stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2016/03/09 16:47:12 packer: panic: interface conversion: *none.comm is not packer.Communicator: missing method DownloadDir
2016/03/09 16:47:12 packer: 

Here's my json:

{
  "builders": [
    {
      "vm_name": "box1",
      "type": "virtualbox-iso",
      "http_directory": ".",
      "disk_size": 2000,
      "iso_url": "box_i686_4.0.iso",
      "iso_checksum": "4f1872fb8f1d0f095210d5269923e2b0",
      "iso_checksum_type": "md5",
      "headless": "false",
      "shutdown_command": "",
      "communicator": "none",
      "vboxmanage": [
          ["modifyvm", "{{.Name}}", "--memory", "1024"],
          ["modifyvm", "{{.Name}}", "--cpus", "2"],
          ["modifyvm", "{{.Name}}", "--nic2", "intnet"]
      ],
      "boot_command": [
`"<wait10>1<enter>y<enter><wait10><wait10><wait10><wait10>y<enter><wait10><enter>"`
      ]
    }
  ]
}

I also crash with 0.9.0. I built 0.9.1 dev in an attempt to work around the issue, since I see there have been some submissions to work around similar issues, but no joy.

**Comment by borzwazie** [comment] 2016-03-10 16:51
In #3304, it was suggested to me to work around this issue by setting:

`"virtualbox_version_file": "none"`

However, this was not successful, and the crash still occurs.

**Comment by cbednarski** [comment] 2016-03-10 22:34
Thanks for opening an issue. `none` is a special case and I think most of the builders don't handle it yet.

**Comment by mwhooker** [comment] 2017-02-02 09:06
I know this was earlier, but it's a dupe of #3618. Tracking fix in #3619

**Closed by mwhooker** 2017-02-02 09:06 UTC
Labels: builder/virtualbox, communicator/null, crash
