### ISSUE TITLE
ESXi Remote command exited with '1': vim-cmd vmsvc/power.off 954 with latest source of Packer

### ISSUE THREAD

**Issue by sllanglois** [mitchellh/packer#3980] opened 2016-10-10 19:51 UTC
[zr60-remote.json.txt](https://github.com/mitchellh/packer/files/520287/zr60-remote.json.txt)
[zr6.0.cfg.txt](https://github.com/mitchellh/packer/files/522083/zr6.0.cfg.txt)
[packer.log.txt](https://github.com/mitchellh/packer/files/520288/packer.log.txt)

I downloaded and compiled the latest master to pick up the fix for 

* https://github.com/mitchellh/packer/issues/3087
* https://github.com/mitchellh/packer/pull/3050

However, in so doing, I am getting an error when the VMware VM is being shut down

==> vmware-iso: Gracefully halting virtual machine...
2016/10/10 12:09:56 packer: 2016/10/10 12:09:56 starting remote command: /sbin/halt -h -p
2016/10/10 12:09:56 packer: 2016/10/10 12:09:56 Remote command exited without exit status or exit signal.
2016/10/10 12:09:56 packer: 2016/10/10 12:09:56 opening new ssh session
2016/10/10 12:09:56 packer: 2016/10/10 12:09:56 starting remote command: vim-cmd vmsvc/power.getstate 954
2016/10/10 12:09:57 ui: ==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Stopping virtual machine...
2016/10/10 12:09:57 packer: 2016/10/10 12:09:57 opening new ssh session
2016/10/10 12:09:57 packer: 2016/10/10 12:09:57 starting remote command: vim-cmd vmsvc/power.off 954
2016/10/10 12:09:58 packer: 2016/10/10 12:09:58 Remote command exited with '1': vim-cmd vmsvc/power.off 954
2016/10/10 12:09:58 ui error: ==> vmware-iso: Error stopping VM: 'vim-cmd vmsvc/power.off 954'
==> vmware-iso:
==> vmware-iso: Stdout: Powering off VM:
==> vmware-iso:
==> vmware-iso:
==> vmware-iso: Stderr: Power off failed
==> vmware-iso:
==> vmware-iso: Error stopping VM: 'vim-cmd vmsvc/power.off 954'
==> vmware-iso:
2016/10/10 12:09:58 ui: ==> vmware-iso: Unregistering virtual machine...

If I go back to 0.10.2 I do not get this error but of course I still have the issue where the output directory need to exist on the local machine.

Attached json, kickstartfile, and full DEBUG_LOG=1 output. Please let me know if you need anything else.

**Comment by rickard-von-essen** [comment] 2016-10-11 14:22
You probably want to rotate that root password in the kickstart file.

**Comment by rickard-von-essen** [comment] 2016-10-16 06:52
I didn't get your example to run. The kickstart is broken. But I tested with `centos-7.2` from [chef/bento](https://github.com/chef/bento) which I modified to use ESXi. And I could reproduce this and this is actually a duplicate of #4006. 

Thank you for reporting this.

**Closed by rickard-von-essen** 2016-10-16 06:52 UTC
Labels: bug, builder/vmware, duplicate, regression
