### ISSUE TITLE
Existence of definitions in "variables" section not checked

### ISSUE THREAD

**Issue by candlerb** [mitchellh/packer#4003] opened 2016-10-14 07:53 UTC
- Packer v0.10.2
- OSX 10.11.6

The [documentation for user variables](https://www.packer.io/docs/templates/user-variables.html) says:

> User variables must first be defined in a variables section within your template.

However this is not enforced: I accidentally missed a variable out of the "variables" section and there was no complaint.

Simple reproducing case:

```
{
  "variables": {
  },

  "builders": [
    {
      "type":         "null",
      "ssh_host":     "127.0.0.1",
      "ssh_username": "xxx{{ user `foo` }}",
      "ssh_password": "xxx{{ user `bar` }}"
    }
  ]
}
```

This is happily accepted by `packer build` and `packer validate`, even if you don't specify any `-var foo=...` or `-var bar=...` flags on the command line.

The flip side of this gives a second, related issue: you are allowed to define variables on the command line which are _not_ listed in the variables section. For example:

```
packer build -var xyzzy=12345 foo.json
```

is happily accepted, even if there is no "xyzzy" defined in "variables"

I believe the intention was that both the above cases should raise errors; but if not, the documentation needs clarifying.

**Comment by mwhooker** [comment] 2017-02-04 07:05
dupe of #3439

**Closed by mwhooker** 2017-02-04 07:05 UTC
Labels: bug, core
