### ISSUE TITLE
Building in parallel from same ISO fails

### ISSUE THREAD

**Issue by bassamtabbara** [mitchellh/packer#1665] opened 2014-11-09 00:42 UTC
Using the packer definition here:

https://github.com/bassamtabbara/coreos-packer

I run the following and get the error below:
```
> packer build coreos.json 
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://alpha.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso
==> parallels-iso: Downloading or copying ISO
    parallels-iso: Downloading or copying: http://alpha.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso
    virtualbox-iso: Download progress: 21%
    virtualbox-iso: Download progress: 45%
    virtualbox-iso: Download progress: 69%
    virtualbox-iso: Download progress: 93%
==> virtualbox-iso: Starting HTTP server on port 8720
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Error attaching ISO: VBoxManage error: VBoxManage: error: Could not get the storage format of the medium '/Users/bassam/ceph/coreos-packer/packer_cache/6891e018db9edc34d9ea92a8b4d710c16af6e8ab25f75e0ff4c54c60c828ae70.iso' (VERR_NOT_SUPPORTED)
==> virtualbox-iso: VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component Medium, interface IMedium, callee nsISupports
==> virtualbox-iso: VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
==> virtualbox-iso: VBoxManage: error: Invalid UUID or filename "/Users/bassam/ceph/coreos-packer/packer_cache/6891e018db9edc34d9ea92a8b4d710c16af6e8ab25f75e0ff4c54c60c828ae70.iso"
```
When I build using the -parallel=false flag the issue does not reproduce.

**Comment by mitchellh** [comment] 2015-06-09 03:53
This looks like a transient VirtualBox issue. Can anyone reproduce this anymore? I haven't been able to. I'm wondering if adding a checksum will fix this: perhaps the downloaded files are corrupt? 

Closing without a new repro. Sorry!

**Closed by mitchellh** 2015-06-09 03:53 UTC
Labels: bug, builder/virtualbox, core
