### ISSUE TITLE
Packer failing to SCP linux.iso

### ISSUE THREAD

**Issue by timc3** [mitchellh/packer#2950] opened 2015-11-18 12:14 UTC
Using Packer 0.8.6 on CentOS 7.1 and VMWare Workstation 12, itself a VM running in VMWare ESXi5.5. The guest I am creating is CentOS6.x so I am using the linux tools and in my logs I get

```
2015/11/18 12:30:36 packer-builder-vmware-iso: 2015/11/18 12:30:36 Detected IP: 192.168.152.128
2015/11/18 12:30:37 packer-builder-vmware-iso: 2015/11/18 12:30:37 [INFO] Attempting SSH connection...
2015/11/18 12:30:37 packer-builder-vmware-iso: 2015/11/18 12:30:37 reconnecting to TCP connection for SSH
2015/11/18 12:30:37 packer-builder-vmware-iso: 2015/11/18 12:30:37 handshaking with SSH
[1;32m==> vmware-image: Connected to SSH![0m
[1;32m==> vmware-image: Uploading the 'linux' VMware Tools[0m
2015/11/18 12:30:37 ui: [1;32m==> vmware-image: Connected to SSH![0m
2015/11/18 12:30:37 packer-builder-vmware-iso: 2015/11/18 12:30:37 handshake complete!
2015/11/18 12:30:37 packer-builder-vmware-iso: 2015/11/18 12:30:37 [INFO] no local agent socket, will not connect agent
2015/11/18 12:30:37 ui: [1;32m==> vmware-image: Uploading the 'linux' VMware Tools[0m
2015/11/18 12:30:37 packer-builder-vmware-iso: 2015/11/18 12:30:37 opening new ssh session
2015/11/18 12:30:37 packer-builder-vmware-iso: 2015/11/18 12:30:37 Starting remote scp process:  scp -vt .
2015/11/18 12:30:37 packer-builder-vmware-iso: 2015/11/18 12:30:37 Started SCP session, beginning transfers...
2015/11/18 12:30:37 packer-builder-vmware-iso: 2015/11/18 12:30:37 Copying input data into temporary file so we can read the length
2015/11/18 12:30:37 packer-builder-vmware-iso: 2015/11/18 12:30:37 [DEBUG] Uploading linux.iso: perms=C0644 size=73424896

```

Then it will sit there for 2 hours or so.  I can SSH in to 192.168.152.128 manually. 

The relevant part of the configuration file: 

```
  "builders": [
    {
      "type": "vmware-iso",
      "name": "vmware-image",
      "boot_command": [
        "<tab><wait> vmlinux text initrd=initrd.img intremap=no_x2apic_optout network --bootproto=dhcp ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos-6.7/ks.cfg<enter><wait>"
       ],
      "boot_wait": "45s",
      "iso_url": "http://ftp.funet.fi/pub/mirrors/centos.org/6.7/isos/x86_64/CentOS-6.7-x86_64-minimal.iso",
      "iso_checksum": "9381a24b8bee2fed0c26896141a64b69",
      "iso_checksum_type": "md5",
      "ssh_username": "root",
      "ssh_password": "cantemo",
      "ssh_wait_timeout": "45m",
      "ssh_skip_request_pty": true,
      "ssh_port": 22,
      "shutdown_command": "shutdown -P now",
      "guest_os_type": "linux",
      "http_directory": "http/",
      "http_port_min": 9800,
      "http_port_max": 9899,
      "vm_name": "centos-portal",
      "vmdk_name": "centos-portal",
      "vmx_data": {
        "memsize": "5096",
        "numvcpus": "2",
        "cpuid.coresPerSocket": "1",
        "scsi0.virtualDev": "lsisas1068",
        "log.filename": "/tmp/portalcentos.log"
      },
      "tools_upload_flavor": "linux",
      "headless": true
    }
  ],
```

**Comment by icnocop** [comment] 2015-11-21 08:29
Have you tried explicitly setting `"tools_upload_path": ""/tmp/{{.Flavor}}.iso""` for example?

**Comment by timc3** [comment] 2015-11-21 15:04
I will try that. I am also manually able to ssh in to the guest, but it’s running extremely slow, and SCP might just be timing out or having extreme packet loss. I wonder if there is another problem with VMWare Workstation 12 on CentOS 7.1 or similar.

**Comment by imduffy15** [comment] 2015-11-23 22:49
Any update on this? Seeing the same issue with RHEL 7.2 and VMWare 11.

**Comment by imduffy15** [comment] 2015-12-18 00:27
@timc3 did you find any resolution for this?

**Comment by timc3** [comment] 2016-01-07 09:49
No, so far I haven’t found any. I think I am going to try and reinstall.

**Comment by timc3** [comment] 2016-01-14 07:31
I managed to recreate the problem on my OSX with packer, and in my configuration I then tried to remove setting the tools iso - and that actually worked. Going to try again on Linux to see what happens.

**Comment by palmertime** [comment] 2016-05-09 15:49
I'm still experiencing the same issue as above.  However, it is not taking hours but it is taking 15-20 minutes just to upload the linux.iso.

[DEBUG] Uploading linux.iso

Has anyone found a fix for this?

**Comment by imduffy15** [comment] 2016-05-25 23:20
Hi @palmertime 

Found a fix today.... The issue is related to TCP checksum offloading on the virtual network interface in vmware see https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2052904 for more information. 

The ideal fix is in the interface driver.... the quick and easy fix (what I plan to do) just requires loading a kernel module on your vmware host.

```
modprobe nf_conntrack_ipv4
```

**Comment by mwhooker** [comment] 2017-02-03 07:36
Doesn't look like there's much we can do about this one. If anyone can confirm that adding the kernel module solves this for them, I'll add it to the docs

**Closed by mwhooker** 2017-02-03 07:36 UTC
Labels: bug, builder/vmware
