### ISSUE TITLE
Feature request: clean up VMImport snapshot after packer amazon-import post-processor renames and deregisters original VMImport AMI

### ISSUE THREAD

**Issue by layer3switch** [mitchellh/packer#4183] opened 2016-11-18 17:23 UTC
amazon-import post-processor doesn't delete snapshot created during VMImport. Once renaming AMI is completed and deregistered original AMI, the original snapshot should be safe to delete.

```
$ packer version
Packer v0.12.0

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F2009
```

**Comment by mwhooker** [comment] 2016-11-18 18:40
duplicate of #3320

**Closed by mwhooker** 2016-11-18 18:40 UTC
