### ISSUE TITLE
Image creation in gcp project through packerV0.12.3 throws an access issue as mentioned below

### ISSUE THREAD

**Issue by pjayaraj** [mitchellh/packer#4747] opened 2017-03-31 09:33 UTC
BUG: Image creation in gcp project through packer throws access issue as mentioned below but it works fine with Packer version 0.10.2.

==> googlecompute: * The user does not have access to service account 'xxx@yyy.iam.gserviceaccount.com'.  User: 'xxx@yyy.iam.gserviceaccount.com'.  Ask a project owner to grant you the iam.serviceAccountActor role on the service account
2017/03/30 00:08:29 ui error: Build 'googlecompute' errored: Error creating instance: 1 error(s) occurred:

We checked in gcp that the above  serviceaccount role mapping exists.

Packer version from `0.12.3`
Host platform Ubuntu 14.04
Debug log output from `PACKER_LOG=1 packer build template.json`.
Debug Log https://gist.github.com/pjayaraj/395c56a086b5972f63e5446d6a20c6a7
Sample template https://gist.github.com/pjayaraj/2c5818ce31c3decf9bcddb41752dac49

**Comment by Mortanon** [comment] 2017-03-31 09:55
Look here for the cause -> https://github.com/mitchellh/packer/issues/4608

**Comment by rickard-von-essen** [comment] 2017-03-31 10:06
I'll close this as a dupe of #4608

**Closed by rickard-von-essen** 2017-03-31 10:06 UTC
Labels: builder/google, duplicate
