### ISSUE TITLE
packer -v returns nonzero status code

### ISSUE THREAD

**Issue by captaincapsaicin** [mitchellh/packer#3605] opened 2016-06-08 22:37 UTC
- Packer Version 10.1
- Host platform Mac OS X El Capitan 10.11.5
https://gist.github.com/captaincapsaicin/506ce156201937292b7093d46f30d3fa

```
$ packer -v
0.10.1
$ echo $?
1
```

**Comment by cbednarski** [comment] 2016-06-08 22:42
Thanks for the report. This is a duplicate of https://github.com/mitchellh/packer/issues/3370.

**Closed by cbednarski** 2016-06-08 22:42 UTC
Labels: bug, duplicate

**Comment by captaincapsaicin** [comment] 2016-06-08 23:34
Ah thanks! That one eluded my brief search.

**Comment by cbednarski** [comment] 2016-06-08 23:34
Yeah not easy to search for; I knew it was there already. :)
