### ISSUE TITLE
add expect_disconnect in Windows shell provisioners

### ISSUE THREAD

**Issue by Wenzel** [mitchellh/packer#4198] opened 2016-11-23 10:03 UTC
I would like to use the `Powershell` provisioner to execute the command `Enable-PSRemoting -Force -SkipNetworkProfileCheck`.

As it stops and starts the `WinRM` service, packer is disconnected and the build fails.
Could you implement `expect_disconnect` in `Windows Shell` and `Powershell` provisioners ?

Thanks !

**Comment by mwhooker** [comment] 2017-01-30 19:59
Unfortunately that's not information we get from our winrm client. I could definitely see this being useful, but it's not something we're targeting for 1.0, so I'm going to close this. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

**Closed by mwhooker** 2017-01-30 19:59 UTC
Labels: enhancement, provisioner/windows-shell

**Comment by mwhooker** [comment] 2017-01-30 20:01
dupe of #4433
