### ISSUE TITLE
Add ability to build from vagrant box

### ISSUE THREAD

**Issue by feniix** [mitchellh/packer#1681] opened 2014-11-19 21:19 UTC
Hi, 

It'd be nice to be able to build virtualbox and vmware from a vagrant image.

Like adding an option for each builder virtualbox-vagrant vmware-vagrant, it should not be too different from ovf but it would save the time of downloading a vagrant box and unpacking it.

we could have an option for the box name in the vagrant cloud format for example 'ubuntu/trusty64' 

Or can that be done already with some config tricks?

it'd be something like

```
{
  "builders":[{
    "type": "virtualbox-vagrant",
    "box_url": "http://link.to.the.box/box",
    "box_name": "ubuntu/trusty64"
  }]
}
```

That'd go and download the box file, unpack the file, put it in a temporary/cache directory and then do similar to what the virtualbox-ovf builder does.

**Comment by sethvargo** [comment] 2015-02-24 23:12
This is a duplicate of #869

**Closed by sethvargo** 2015-02-24 23:12 UTC
