### ISSUE TITLE
packer returns 1 when executed as 'packer --version'

### ISSUE THREAD

**Issue by shantanugadgil** [mitchellh/packer#4676] opened 2017-03-16 21:20 UTC
- Packer version from `packer version`
Packer v0.12.3

- Host platform
Linux x86_64 (CentOS, Debian)

When Packer is executed as "packer --version" it returns "1" rather than "0" 😢 
When executed as "packer version", it returns "0" correctly! 😮 

- Also tested with rc1
Packer v1.0.0-rc1 (99aec637af87c36f41163fd3d0e0c98ea38779d4+CHANGES)

This is not the same as Terraform, Consul, etc.

Regards,
Shantanu

**Comment by mwhooker** [comment] 2017-03-16 21:23
duplicate of #3370

**Comment by mwhooker** [comment] 2017-03-16 21:23
thanks for the report. There's a fix out for this but it's an upstream bug

**Closed by mwhooker** 2017-03-16 21:23 UTC
