### ISSUE TITLE
Qemu builder fails when used with the `scsi` interface

### ISSUE THREAD

**Issue by MohdAhmad** [mitchellh/packer#4278] opened 2016-12-13 01:55 UTC
The qemu builder in conjunction with the `scsi` interface fails. Is this a known issue? Any idea what could be going wrong?

I am running packer inside a centos VM on vmware fusion with 

*Packer v0.12.0*

*Qemu KVM*
~~~
[root@localhost libexec]# rpm --query qemu-kvm
qemu-kvm-1.5.3-105.el7_2.7.x86_64
~~~

*Centos version*
~~~
[root@localhost templates-packer]# rpm --query centos-release
centos-release-7-2.1511.el7.centos.2.10.x86_64
~~~

*Template*
~~~
[root@localhost templates-packer]# cat centos-7.json
{
       	"builders":
       	[
       		{
       			"type": "qemu",
       			"iso_url": "http://centos.firehosted.com/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso",
       			"iso_checksum": "88c0437f0a14c6e2c94426df9d43cd67",
       			"iso_checksum_type": "md5",
       			"output_directory": "output_centos_test",
       			"shutdown_command": "shutdown -P now",
       			"disk_size": 500000,
       			"format": "qcow2",
       			"headless": true,
       			"accelerator": "kvm",
       			"http_directory": "httpdir",
       			"http_port_min": 10082,
       			"http_port_max": 10089,
       			"ssh_host_port_min": 2222,
       			"ssh_host_port_max": 2229,
       			"ssh_username": "root",
       			"ssh_password": "somepassword",
       			"ssh_port": 22,
       			"ssh_wait_timeout": "30m",
       			"vm_name": "tdhtest",
       			"net_device": "virtio-net",
       			"disk_interface": "scsi",
       			"boot_wait": "15s",
       			"qemu_binary": "/usr/libexec/qemu-kvm",
       			"boot_command":
       			[
       				"<tab> cmdline ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos7-ks.cfg<enter>"
       			]
       		}
       	]
}
~~~

*Packer logs*
~~~
[root@localhost templates-packer]# export PACKER_LOG=1 && packer build centos-7.json
2016/12/12 17:06:45 [INFO] Packer version: 0.12.0
2016/12/12 17:06:45 Packer Target OS/Arch: linux amd64
2016/12/12 17:06:45 Built with Go Version: go1.7.3
2016/12/12 17:06:45 Detected home directory from env var: /root
2016/12/12 17:06:45 Using internal plugin for amazon-chroot
2016/12/12 17:06:45 Using internal plugin for amazon-ebsvolume
2016/12/12 17:06:45 Using internal plugin for digitalocean
2016/12/12 17:06:45 Using internal plugin for parallels-iso
2016/12/12 17:06:45 Using internal plugin for profitbricks
2016/12/12 17:06:45 Using internal plugin for file
2016/12/12 17:06:45 Using internal plugin for parallels-pvm
2016/12/12 17:06:45 Using internal plugin for openstack
2016/12/12 17:06:45 Using internal plugin for amazon-ebs
2016/12/12 17:06:45 Using internal plugin for amazon-instance
2016/12/12 17:06:45 Using internal plugin for azure-arm
2016/12/12 17:06:45 Using internal plugin for cloudstack
2016/12/12 17:06:45 Using internal plugin for docker
2016/12/12 17:06:45 Using internal plugin for googlecompute
2016/12/12 17:06:45 Using internal plugin for null
2016/12/12 17:06:45 Using internal plugin for virtualbox-ovf
2016/12/12 17:06:45 Using internal plugin for qemu
2016/12/12 17:06:45 Using internal plugin for virtualbox-iso
2016/12/12 17:06:45 Using internal plugin for vmware-iso
2016/12/12 17:06:45 Using internal plugin for vmware-vmx
2016/12/12 17:06:45 Using internal plugin for ansible
2016/12/12 17:06:45 Using internal plugin for chef-client
2016/12/12 17:06:45 Using internal plugin for file
2016/12/12 17:06:45 Using internal plugin for puppet-masterless
2016/12/12 17:06:45 Using internal plugin for puppet-server
2016/12/12 17:06:45 Using internal plugin for salt-masterless
2016/12/12 17:06:45 Using internal plugin for shell-local
2016/12/12 17:06:45 Using internal plugin for windows-shell
2016/12/12 17:06:45 Using internal plugin for ansible-local
2016/12/12 17:06:45 Using internal plugin for chef-solo
2016/12/12 17:06:45 Using internal plugin for powershell
2016/12/12 17:06:45 Using internal plugin for shell
2016/12/12 17:06:45 Using internal plugin for windows-restart
2016/12/12 17:06:45 Using internal plugin for docker-import
2016/12/12 17:06:45 Using internal plugin for manifest
2016/12/12 17:06:45 Using internal plugin for artifice
2016/12/12 17:06:45 Using internal plugin for checksum
2016/12/12 17:06:45 Using internal plugin for compress
2016/12/12 17:06:45 Using internal plugin for docker-push
2016/12/12 17:06:45 Using internal plugin for googlecompute-export
2016/12/12 17:06:45 Using internal plugin for vagrant-cloud
2016/12/12 17:06:45 Using internal plugin for atlas
2016/12/12 17:06:45 Using internal plugin for shell-local
2016/12/12 17:06:45 Using internal plugin for vagrant
2016/12/12 17:06:45 Using internal plugin for vsphere
2016/12/12 17:06:45 Using internal plugin for amazon-import
2016/12/12 17:06:45 Using internal plugin for docker-save
2016/12/12 17:06:45 Using internal plugin for docker-tag
2016/12/12 17:06:45 Detected home directory from env var: /root
2016/12/12 17:06:45 Attempting to open config file: /root/.packerconfig
2016/12/12 17:06:45 [WARN] Config file doesn't exist: /root/.packerconfig
2016/12/12 17:06:45 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[googlecompute:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-googlecompute digitalocean:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-digitalocean amazon-instance:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-instance azure-arm:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-azure-arm cloudstack:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-cloudstack docker:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-docker amazon-chroot:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-chroot parallels-iso:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-iso file:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-file openstack:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-openstack virtualbox-iso:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-iso profitbricks:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-profitbricks parallels-pvm:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-pvm vmware-iso:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-iso vmware-vmx:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-vmx amazon-ebsvolume:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebsvolume amazon-ebs:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebs null:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-null virtualbox-ovf:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-ovf qemu:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-qemu] PostProcessors:map[googlecompute-export:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-googlecompute-export atlas:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-atlas vagrant:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant docker-save:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-save manifest:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-manifest vagrant-cloud:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant-cloud compress:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-compress docker-push:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-push shell-local:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-shell-local docker-import:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-import checksum:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-checksum vsphere:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere amazon-import:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-amazon-import docker-tag:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-tag artifice:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-artifice] Provisioners:map[windows-restart:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-restart chef-client:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-client puppet-masterless:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-masterless shell-local:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell-local ansible-local:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible-local shell:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell chef-solo:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-solo powershell:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-powershell ansible:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible file:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-file puppet-server:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-server salt-masterless:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-salt-masterless windows-shell:/usr/local/sbin/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-shell]}
2016/12/12 17:06:45 Setting cache directory: /root/templates-packer/packer_cache
2016/12/12 17:06:45 Loading builder: qemu
2016/12/12 17:06:45 Plugin could not be found. Checking same directory as executable.
2016/12/12 17:06:45 Current exe path: /usr/local/sbin/packer
2016/12/12 17:06:45 Creating plugin client for path: /usr/local/sbin/packer
2016/12/12 17:06:45 Starting plugin: /usr/local/sbin/packer []string{"/usr/local/sbin/packer", "plugin", "packer-builder-qemu"}
2016/12/12 17:06:45 Waiting for RPC address for: /usr/local/sbin/packer
2016/12/12 17:06:45 Detected home directory from env var: /root
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 [INFO] Packer version: 0.12.0
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Packer Target OS/Arch: linux amd64
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Built with Go Version: go1.7.3
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Detected home directory from env var: /root
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Attempting to open config file: /root/.packerconfig
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 [WARN] Config file doesn't exist: /root/.packerconfig
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[] PostProcessors:map[] Provisioners:map[]}
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Setting cache directory: /root/templates-packer/packer_cache
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 args: []string{"packer-builder-qemu"}
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Plugin minimum port: 10000
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Plugin maximum port: 25000
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Detected home directory from env var: /root
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Plugin address: unix /tmp/packer-plugin825926824
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Waiting for connection...
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Serving a plugin connection...
qemu output will be in this color.

2016/12/12 17:06:45 ui: qemu output will be in this color.
2016/12/12 17:06:45 ui:
2016/12/12 17:06:45 Build debug mode: false
2016/12/12 17:06:45 Force build: false
2016/12/12 17:06:45 On error:
2016/12/12 17:06:45 Preparing build: qemu
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 use specified accelerator: kvm
2016/12/12 17:06:45 Waiting on builds to complete...
2016/12/12 17:06:45 Starting build run: qemu
2016/12/12 17:06:45 Running builder: qemu
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Qemu path: /usr/libexec/qemu-kvm, Qemu Image page: /usr/bin/qemu-img
2016/12/12 17:06:45 ui: ==> qemu: Downloading or copying ISO
==> qemu: Downloading or copying ISO
2016/12/12 17:06:45 ui:     qemu: Downloading or copying: http://centos.firehosted.com/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso
    qemu: Downloading or copying: http://centos.firehosted.com/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Acquiring lock to download: http://centos.firehosted.com/7/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso
2016/12/12 17:06:45 packer: 2016/12/12 17:06:45 Verifying checksum of /root/templates-packer/packer_cache/8ab19c1aa34566cdbe6ac249f8d5492732f11f712e44adaf6ac594b3f1502442.iso
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 [DEBUG] Initial checksum matched, no download needed.
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 No floppy files specified. Floppy disk will not be made.
==> qemu: Creating hard drive...
2016/12/12 17:06:46 ui: ==> qemu: Creating hard drive...
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Executing qemu-img: []string{"create", "-f", "qcow2", "output_centos_test/tdhtest", "500000M"}
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 stdout: Formatting 'output_centos_test/tdhtest', fmt=qcow2 size=524288000000 encryption=off cluster_size=65536 lazy_refcounts=off
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 stderr:
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Trying port: 10083
==> qemu: Starting HTTP server on port 10083
2016/12/12 17:06:46 ui: ==> qemu: Starting HTTP server on port 10083
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Looking for available communicator (SSH, WinRM, etc) port between 2222 and 2229
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Trying port: 2224
==> qemu: Found port for communicator (SSH, WinRM, etc): 2224.
==> qemu: Looking for available port between 5900 and 6000 on 127.0.0.1
2016/12/12 17:06:46 ui: ==> qemu: Found port for communicator (SSH, WinRM, etc): 2224.
2016/12/12 17:06:46 ui: ==> qemu: Looking for available port between 5900 and 6000 on 127.0.0.1
2016/12/12 17:06:46 ui: ==> qemu: Starting VM, booting from CD-ROM
==> qemu: Starting VM, booting from CD-ROM
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Looking for available port between 5900 and 6000 on 127.0.0.1
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Trying port: 5996
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Found available VNC port: 5996 on IP: 127.0.0.1
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Qemu --version output: QEMU emulator version 1.5.3 (qemu-kvm-1.5.3-105.el7_2.7), Copyright (c) 2003-2008 Fabrice Bellard
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Qemu version: 1.5.3
    qemu: The VM will be run headless, without a GUI. If you want to
    qemu: view the screen of the VM, connect via VNC without a password to
    qemu: 127.0.0.1:5996
2016/12/12 17:06:46 ui:     qemu: The VM will be run headless, without a GUI. If you want to
    qemu: view the screen of the VM, connect via VNC without a password to
    qemu: 127.0.0.1:5996
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Qemu Builder has no floppy files, not attaching a floppy.
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Executing /usr/libexec/qemu-kvm: []string{"-drive", "file=output_centos_test/tdhtest,if=scsi,cache=writeback,format=qcow2", "-vnc", "127.0.0.1:96", "-machine", "type=pc,accel=kvm", "-cdrom", "/root/templates-packer/packer_cache/8ab19c1aa34566cdbe6ac249f8d5492732f11f712e44adaf6ac594b3f1502442.iso", "-boot", "once=d", "-name", "tdhtest", "-device", "virtio-net,netdev=user.0", "-m", "512M", "-netdev", "user,id=user.0,hostfwd=tcp::2224-:22"}
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Started Qemu. Pid: 5928
2016/12/12 17:06:46 packer: 2016/12/12 17:06:46 Qemu stderr: qemu-kvm: Unknown device 'lsi53c895a' for bus 'PCI'
==> qemu: Error launching VM: Qemu failed to start. Please run with PACKER_LOG=1 to get more info.
2016/12/12 17:06:46 ui error: ==> qemu: Error launching VM: Qemu failed to start. Please run with PACKER_LOG=1 to get more info.
2016/12/12 17:06:46 ui: ==> qemu: Deleting output directory...
2016/12/12 17:06:46 ui error: Build 'qemu' errored: Build was halted.
2016/12/12 17:06:46 Builds completed. Waiting on interrupt barrier...
2016/12/12 17:06:46 machine readable: error-count []string{"1"}
2016/12/12 17:06:46 ui error:
==> Some builds didn't complete successfully and had errors:
2016/12/12 17:06:46 machine readable: qemu,error []string{"Build was halted."}
2016/12/12 17:06:46 ui error: --> qemu: Build was halted.
2016/12/12 17:06:46 ui:
==> Builds finished but no artifacts were created.
2016/12/12 17:06:46 waiting for all plugin processes to complete...
==> qemu: Deleting output directory...
Build 'qemu' errored: Build was halted.

==> Some builds didn't complete successfully and had errors:
--> qemu: Build was halted.

==> Builds finished but no artifacts were created.
2016/12/12 17:06:46 /usr/local/sbin/packer: plugin process exited
~~~

**Comment by DanHam** [comment] 2017-01-13 12:07
@MohdAhmad If you have a Red Hat subscription you can read about this issue in full [here](https://access.redhat.com/solutions/1156423). The 'Root Cause' given in the doc is:

> QEMU is trying to initialize a default scsi bus type, lsi53c895a, **which is disabled in RHEL**.

RHEL chose to disable use of plain 'scsi' as the disk interface because of the bug described [here](https://bugzilla.redhat.com/show_bug.cgi?id=1019220).

Long and short, you cannot use `"disk_interface": "scsi"` when building with Qemu on RHEL or RHEL variants such as CentOS. You will need to switch to one of the other available options given in the [docs](https://www.packer.io/docs/builders/qemu.html#disk_interface)

@rickard-von-essen Updating the docs with the relevant info seems like the simplest solution here. I've issued a PR that can be merged if you are in agreement.

**Closed** 2017-01-13 19:22 UTC
Labels: bug, builder/qemu

**Comment by MohdAhmad** [comment] 2017-03-18 01:14
@DanHam thanks for clarifying.
