### ISSUE TITLE
Changes to flopy_files is a breaking change

### ISSUE THREAD

**Issue by trodemaster** [mitchellh/packer#3977] opened 2016-10-09 18:12 UTC
Looking at https://github.com/mitchellh/packer/pull/2919 that changes how the floppy files handles directories and this is a breaking change. See the attached gist for the results. 

I think we need to verify that this change is working as expected. If it is we need some clear explanation on how it's supposed to work. In our case we want all the files specified to be copied to the root of the floppy image. Ideally this code change would not be a breaking change and allow you to specify folders that can be copied to the image with the path intact optionally. 

Packer Version Packer v0.11.0.dev (ae256b98d9f69ab6ef4be622f08ac8fe10064fa1)
Ubuntu 16.04
VMware Workstation 12.5
vmware-iso builder
https://github.com/mitchellh/packer/pull/2919

Gist with log and resulting file layout changes.
https://gist.github.com/trodemaster/dae712006288451d10563ee15e1e922f

**Comment by rickard-von-essen** [comment] 2016-10-09 19:14
Thank you for reporting this. To my understanding this was not supposed to be a braking change. I'll look into it.

**Comment by rickard-von-essen** [comment] 2016-10-09 19:50
@mwhooker if you are doing a release I suggest reverting #2919.

**Comment by rickard-von-essen** [comment] 2016-10-09 20:01
Ping @arizvisa will you have a look?

**Comment by trodemaster** [comment] 2016-10-10 23:09
Had a fresh look at this issue today. After reviewing the docs that go with this release it's clear that this is not intentionally breaking. Looks like when you pass a directory with floppy_files it shows that the files are being copied in the cli but they just don't end up on the floppy image. Also confirmed on macOS 10.12/go 1.7.1/VMware Fusion.

**Comment by rickard-von-essen** [comment] 2016-10-11 14:19
I have also reproduced this and created a unit test that shows that the error is not in [Run](https://github.com/mitchellh/packer/blob/master/common/step_create_floppy.go#L28) so I assume the issue is in [Add](https://github.com/mitchellh/packer/blob/master/common/step_create_floppy.go#L202). I'll investigate further today and provide my unit tests.

**Comment by rickard-von-essen** [comment] 2016-10-11 20:02
I'm adding test here [rickard-von-essen - issue-3977](https://github.com/rickard-von-essen/packer/tree/issue-3977)

**Comment by arizvisa** [comment] 2016-10-11 21:06
looking into it right now too.

**Comment by arizvisa** [comment] 2016-10-11 22:32
Well, one issue on Windows: From looking at a hexdump of the floppy disk that was generated, it looks like some backslashes made it into the floppy disk paths which is busted and means that I missed a filepath.ToSlash somewhere.

Specifically in common/step_create_floppy.go:217
```
		entry,err := d.AddFile(path.Base(src))
```
Should be changed to:
```
		entry,err := d.AddFile(path.Base(filepath.ToSlash(src)))
```
And then at common/step_create_floppy.go:238
```
		directory,filename := filepath.Split(pathname)

		base,err := removeBase(basedirectory, directory)
		if err != nil { return err }
```
Should be changed to:
```
		directory,filename := filepath.Split(filepath.ToSlash(pathname))

		base,err := removeBase(basedirectory, filepath.FromSlash(directory))
		if err != nil { return err }
```

I'm still working on why the other files in the root directory aren't being listed on the floppy. Will update this issue with more info as I figure it out.

**Comment by arizvisa** [comment] 2016-10-12 00:03
Ok, so what's going on is that files were being put under the "." subdirectory instead of the root directory. This is due to a misuse of filepath.Clean() as I must have mis-assumed that if it was given an empty string it would return an empty string since there's nothing to clean. Instead, filepath.Clean() replaces an empty string with ".". `dircache` is a function that caches the directory so that the right filesystem node is returned for a directory. When an empty string is passed to it, it's supposed to return the root directory.

In common/step_create_floppy.go:340, you can change the following.
```
			input := path.Clean(<-Input)
```
to this code, which will cause an empty string (the root directory) to be passed through so that the correct fs node will be returned.
```
			input := <-Input
			if len(input) > 0 { input = path.Clean(input) }
```
Sorry about that.

**Comment by rickard-von-essen** [comment] 2016-10-12 06:20
@arizvisa will you PR a fix when you are ready. 
I think it would be good if there was a test that runs this step with a non-trivial content and then uses `go-fs` to read the `floppy_file` and verify the content. The logic in `add()` is currently untested and terrible complex.

**Comment by arizvisa** [comment] 2016-10-13 03:04
Yeah, I agree. The way the original author faked the test-case by adding names to a map that's queried was pretty hacky. This PR actually existed due to an issue I was having with "\"s working it's way into the filenames. Last year when I was trying to get the PR merged, I was asked specifically to restore the bogus testcase despite it not guaranteeing that a floppy disk wasn't corrupt due to it's use of the FilesAdded backdoor.

But, if you guys do end up writing a testcase to validate a corrupt root directory, keep in mind that go-fs totally allows "\" and "." in filenames and so it's idea of a corrupt fatfs is totally different from windows' idea of a corrupt fatfs.

Anyways, I submitted at PR at #3998.

**Comment by mwhooker** [comment] 2016-10-14 01:11
@trodemaster would be curious to hear if the patch at #3998 fixes this for you. I'll try to test myself if I can

**Comment by trodemaster** [comment] 2016-10-14 18:54
Happy to do that. Hints on how I can check out the arizvisa:floppy-recurse branch?

**Comment by mwhooker** [comment] 2016-10-14 19:21
something like this should work

`git fetch -fu origin refs/pull/3998/head:pr/3998 && git checkout pr/3998;`

**Comment by trodemaster** [comment] 2016-10-14 21:11
OK that worked for pulling down the updated code. The fix has also worked and the floppy is populated with the correct files now!

**Comment by mwhooker** [comment] 2016-10-14 21:14
awesome, thanks so much for testing @trodemaster

**Closed** 2016-10-14 21:19 UTC
Labels: bug, builder/parallels, builder/qemu, builder/virtualbox, builder/vmware, regression
