### ISSUE TITLE
Feature request: Expose created instance's private and public ips.

### ISSUE THREAD

**Issue by kronos** [mitchellh/packer#4173] opened 2016-11-16 00:47 UTC
It would be extremely convenient to have it as variable on provision steps.

**Comment by mwhooker** [comment] 2016-11-16 19:06
I believe this is a duplicate of #3889

**Closed by mwhooker** 2016-11-16 19:06 UTC
Labels: enhancement

**Comment by rickard-von-essen** [comment] 2016-11-16 19:46
Just for reference for all provisioners that run on the host this is trivial. For `ansible` this is trivial. 

The only one left is `shell-local` for that something simple like this solves it:
```json
{
  "type": "shell",
  "inline": [ "ifconfig eth0 | sed -ne 's/.*inet \(.*\) netmask.*/\1/gp' > /tmp/ip" ]
},
{
  "type": "file",
  "direction": "download",
  "source": "/tmp/ip",
  "destination": "ip"
},
{
  "type": "shell-local",
  "inline": [ "IP=$(cat ip) echo \"Host ip is: $IP\"" ]
}
```

**Comment by RajatGoyal** [comment] 2016-11-17 12:19
@rickard-von-essen Thanks for the workaround!

**Comment by hhassoun** [comment] 2017-03-10 20:29
@RajatGoyal Not sure how the ifconfig can help, it would return the internal IP address instead of the required public interface. 
Had to use something like this to pick the public IP from the build instance:
"inline": [ "curl http://checkip.amazonaws.com -o /tmp/ip" ]

**Comment by dayglojesus** [comment] 2017-03-21 23:05
Machine metadata really should be exposed and available for provisioning and post-processing. It will make Packer workflows much more flexible.
