### ISSUE TITLE
enhancement: Array of tags for `docker-tag` post processor.

### ISSUE THREAD

**Issue by dpetzel** [mitchellh/packer#2097] opened 2015-05-05 20:47 UTC
Sorry if this is covered elsewhere, but I wasn't able to find it. The way we are building images we would like to apply more than one tag. It seems applying the `docker-tag` tag twice yields this error:

```
build 'docker' errored: 1 error(s) occurred:

* Post-processor failed: Unknown artifact type: packer.post-processor.docker-tag
Can only tag from Docker builder artifacts.
```

We have the following two use cases:
1) Being able to apply a version number as well as `latest`
2) When pushing to multiple registries (internal in different locations), it requires that the image be tagged with the internal registry name. In this case we need to change the hostname portion of the tag. 

The end result for two registries is 4 distinct tags. It would be awesome if we could do this natively with the post-processor.

**Comment by higebu** [comment] 2015-05-06 01:39
Hi @dpetzel ,

I had same problem, and found a workaround.
Example template.json is following:

```json
{
  "builders":[{
    "type": "docker",
    "image": "fedora",
    "commit": "true"
  }],
  "provisioners":[
    {
      "type": "shell",
      "inline": [
        "yum update -y",
        "yum clean all"
      ]
    }
  ],
  "post-processors": [
    [
      {
        "type": "docker-tag",
        "repository": "higebu/fedora1",
        "tag": "0.1"
      },
      "docker-push"
    ],
    [
      {
        "type": "docker-tag",
        "repository": "higebu/fedora1",
        "tag": "latest"
      },
      "docker-push"
    ],
    [
      {
        "type": "docker-tag",
        "repository": "higebu/fedora2",
        "tag": "0.1"
      },
      "docker-push"
    ],
    [
      {
        "type": "docker-tag",
        "repository": "higebu/fedora2",
        "tag": "latest"
      },
      "docker-push"
    ]
  ]
}
```

**Comment by dpetzel** [comment] 2015-05-06 19:06
@higebu thanks, that worked perfectly!

**Comment by iroller** [comment] 2016-07-07 08:26
Can't reproduce but it seems like the following works in some templates and doesn't in other ones:
```
"post-processors": [
    [
      {
        "type": "docker-tag",
        "repository": "higebu/fedora1",
        "tag": "0.1"
      },
      {
        "type": "docker-tag",
        "repository": "higebu/fedora1",
        "tag": "latest"
      },
      {
        "type": "docker-tag",
        "repository": "higebu/fedora2",
        "tag": "0.1"
      },
      {
        "type": "docker-tag",
        "repository": "higebu/fedora2",
        "tag": "latest"
      },
      "docker-push"
    ]
```

Could someone from developers confirm or deny that such a config is supposed to work?


Big 👍 on supporting an array for tags.

**Comment by rickard-von-essen** [comment] 2016-07-07 09:22
You seem to have a stray `docker-push`.

**Comment by mwhooker** [comment] 2017-02-04 07:32
Sounds like we have a viable workaround. If someone would like to implement this, it should be quite straight-forward. I would add another config field called `tags`, which is an array of strings. See how we deal with a similar situation here https://github.com/mitchellh/packer/blob/master/provisioner/shell/provisioner.go#L151-L161

However, right now we're focused on 1.0. This has very low chance of ever being a priority for us, so we'd rather close this issue than have it stagnate for years to come. The best way to get this implemented would be to submit a PR. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk)
 for more details on 1.0.

**Closed by mwhooker** 2017-02-04 07:32 UTC
Labels: easy, enhancement, post-processor/docker

**Comment by yellowmegaman** [comment] 2018-01-15 13:31
For everyone stuck with this one, example with private repos:

```
  "post-processors": [
    [
      {
        "type": "docker-tag",
        "repository": "{{user `docker_registry`}}/{{user `app`}}",
        "tag": "{{user `tag`}}"
      },
      {
        "type": "docker-push",
        "login": true,
        "login_server": "{{user `docker_registry`}}",
        "login_username": "{{user `docker_username`}}",
        "login_password": "{{user `docker_password`}}"
      }
    ],
    [
      {
        "type": "docker-tag",
        "repository": "{{user `docker_registry`}}/{{user `app`}}",
        "tag": "latest"
      },
      {
        "type": "docker-push",
        "login": true,
        "login_server": "{{user `docker_registry`}}",
        "login_username": "{{user `docker_username`}}",
        "login_password": "{{user `docker_password`}}"
      }
    ]
  ]
```

Just note `],` and `[` in the middle. Didn't find `type: docker-push` in docs right away

**Comment by nqb** [comment] 2019-11-08 12:14
I open a new issue to request this feature, see #8351
