### ISSUE TITLE
Custom packer.d directory location.

### ISSUE THREAD

**Issue by es1o** [mitchellh/packer#3443] opened 2016-04-15 08:54 UTC
Hello.

I would like feature to customize location of packer.d directory. Now default is ~/packer.d.

It is important for me because I use remote home directory with restricted access, only I can read and write from my home directory. I can't change that permissions.

As result packer docker builder fails because docker image try reads file from this directory.
I run packer from my user. 

I created a local user to run packer but with this WA I can't store packer code in my home directory because this local user doesn't have access. Additionally I lose access to ~/.ssh dir and I can't commit my code to repository. My WA works but it is uncomfortable.

**Comment by cbednarski** [comment] 2016-04-20 00:36
Sorry for the late reply. Afaik it is not possible to change the configuration directory but I think you should be able to use `PACKER_TMP_DIR` to change the location Docker will use.

**Comment by wyroot** [comment] 2016-10-22 06:35
Hello, I have the same problem, ``PACKER_TMP_DIR`` is not a solution because packer uses packer.d always from ``$HOME``. I've submitted fix for this, I hope it is a good quality and will be able to merge, because it is my first go code ever. :)

**Comment by tylert** [comment] 2016-10-26 13:49
PACKER_TMP_DIR isn't currently in the list at https://www.packer.io/docs/other/environmental-variables.html either.

**Comment by es1o** [comment] 2016-10-26 16:20
Hi @cbednarski , `PACKER_TMP_DIR` doesn't work.

**Comment by jrm16020** [comment] 2016-11-11 21:32
+1 for the feature.

I've encountered this but with a different scenario.  I'm using the Packer container based on Alpine and updated it to use the `nobody` user.  `nobody` can't write to `.packer.d` and produces this error as well.  I can work around this at the moment by overriding HOME in my container.

**Comment by mwhooker** [comment] 2017-02-27 03:21
This is working for me now

```
~/dev/packertest [venv] ᐅ packer build dockercp.json
docker output will be in this color.

==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: ubuntu:xenial
    docker: xenial: Pulling from library/ubuntu
    docker: Digest: sha256:71cd81252a3563a03ad8daee81047b62ab5d892ebbfbf71cf53415f29c130950
    docker: Status: Image is up to date for ubuntu:xenial
==> docker: Starting docker container...
    docker: Run command: docker run -v /Users/mwhooker/dev/packertest/packer.d/packer-docker611145912:/packer-files -d -i -t ubuntu:xenial /bin/bash
    docker: Container ID: 41d165086bca1e6aeb86634bd2c20054d5e6bd01319e215737cf036113fd413d
==> docker: Uploading ./FILES/0604.txt => /tmp/
==> docker: Provisioning with shell script: /var/folders/yy/ff0tkhr141xdxvxf5fz43kmw0000gn/T/packer-shell809000618
    docker: total 4
    docker: -rw----r-- 1 root root  0 Feb 27 03:18 0604.txt
    docker: -rwxr-xr-x 1 root root 24 Feb 27 03:18 script_6779.sh
==> docker: Committing the container
    docker: Image ID: sha256:fc64903f11895bf2b6752a0304456216e2677da767ee633a3cfe4b4ac5233f30
==> docker: Killing the container: 41d165086bca1e6aeb86634bd2c20054d5e6bd01319e215737cf036113fd413d
Build 'docker' finished.

==> Builds finished. The artifacts of successful builds are:
--> docker: Imported Docker image: sha256:fc64903f11895bf2b6752a0304456216e2677da767ee633a3cfe4b4ac5233f30
~/dev/packertest [venv] ᐅ echo $PACKER_TMP_DIR
/Users/mwhooker/dev/packertest/packer.d
```

it's also now been documented here https://github.com/mitchellh/packer/blob/master/website/source/docs/builders/docker.html.md#overriding-the-host-directory

If you're not able to get `PACKER_TMP_DIR` to work, please open a new issue and be sure to include 

1. json file to reproduce issue
2. packer version
3. logs from `PACKER_LOG=1 packer build ...`
4. host operating system

**Closed by mwhooker** 2017-02-27 03:21 UTC
Labels: question, waiting-reply
