### ISSUE TITLE
Shutdown command failing

### ISSUE THREAD

**Issue by chrisbalmer** [mitchellh/packer#4103] opened 2016-11-03 02:03 UTC
- Packer Version: `v0.11.0`
- Host: `macOS Sierra 10.12.1`
- Debug: https://gist.github.com/chrisbalmer/7b0129a83922ce7c59d93c7690941d39
- Example template.json: https://gist.github.com/chrisbalmer/5e08f89566a6553cb6bbb9ca0e85aab6
- Example ks_el.cfg to boot installer: https://gist.github.com/chrisbalmer/a5e7338675db0457f3342e8b015e51a7
- Builder: `vmware-iso`
- Virtualization platform: `VMware Fusion 8.5 Pro`

When finishing the build and powering off the VM, packer reports a failure of the shutdown command.

```
Build 'centos72hw9v3' errored: Shutdown command has non-zero exit status.

Stdout: 

Stderr: 

==> Some builds didn't complete successfully and had errors:
--> centos72hw9v3: Shutdown command has non-zero exit status.

Stdout:

Stderr:

==> Builds finished but no artifacts were created.
```

- If I use other EL ISOs like RHEL 7.2, same issue occurs.
- Using `poweroff` for the shutdown command results in the same error.
- If I compile packer `v0.10.2` and run the same build with the older packer version, it works.
- I was using a version from around `v0.8.2` before and upgraded to v0.11.0 this week. The builds worked with the `v0.8.X` version I had used as well.

**Comment by chrisbalmer** [comment] 2016-11-03 04:01
It appears this is the last commit that it worked on:

2ba266cde164ae86e080b04a41d504c560034036

**Comment by rickard-von-essen** [comment] 2016-11-03 07:49
Thanks for reporting this. This is a duplicate of #4054, and is already fixed in master.

**Closed by rickard-von-essen** 2016-11-03 07:49 UTC
