### ISSUE TITLE
File provisioner over WinRM does not create directory

### ISSUE THREAD

**Issue by skrysmanski** [mitchellh/packer#4753] opened 2017-04-04 07:54 UTC
On packer 0.12.3, the `file` provisioner doesn't work correctly when used with the `WinRM` communicator when provisioning a directory.

According to the [docs ](https://www.packer.io/docs/provisioners/file.html):

>If the source is /foo (no trailing slash), and the destination is /tmp, then the contents of /foo on the local machine will be uploaded to /tmp/foo on the remote machine. The foo directory on the remote machine will be created by Packer.

So I have this provisioner:

``` json
{
	"type": "file",
	"source": "myprovdir",
	"destination": "c:\\"
}
```

When I use `ssh` as communicator, the files in the directory `myprovdir` will be copied to `c:\myprovdir`.

However, when I use `winrm` as communicator, the files will all end up directly on `c:\` (and no directory `myprovdir` will be created).

Note: It doesn't matter whether I specified the destination as `c:\` or `c:/`.

I'm using Windows Server 2012 R2 as guest os and Windows 8.1 as host os.

**Comment by mwhooker** [comment] 2017-04-04 17:27
I believe this is a duplicate of #3562 which is fixed on master.

If you'd like to test that this works on the master branch, that'd be very helpful: https://releases.hashicorp.com/packer/1.0.0-rc3/

**Closed by mwhooker** 2017-04-04 17:27 UTC
