### ISSUE TITLE
packer timestamp interpolation out-of-sync

### ISSUE THREAD

**Issue by leroux** [mitchellh/packer#4136] opened 2016-11-08 23:47 UTC
Packer version: 0.11.0

Problem
--------
The variable used to interpolate `{{ timestamp }}` is initialized once per process.
Depending on system load, the initialized values can vary by milliseconds to entire seconds.
This means that the `{{ timestamp }}` value for a post-processor could be a whole second greater than the value in a `builder`.

I think `InitTime` is initialized for each spawned process that imports `interpolate`.
https://github.com/mitchellh/packer/blob/5ef142c8bd32404f328ad428e46c4c8c3512918e/template/interpolate/funcs.go#L22

Proof
-----
Patch interpolate so that it writes out the `cmdline` and `InitTime` to a log:
```
diff --git a/template/interpolate/funcs.go b/template/interpolate/funcs.go
index 92c3ce5..25ada8f 100644
--- a/template/interpolate/funcs.go
+++ b/template/interpolate/funcs.go
@@ -20,6 +20,18 @@ var InitTime time.Time

 func init() {
        InitTime = time.Now().UTC()
+
+       f, err := os.OpenFile("/tmp/packer-inittimes.txt", os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0600)
+       if err != nil {
+               panic(err)
+       }
+       defer f.Close()
+
+       cmdline := strings.Join(os.Args[:], ",")
+       _, err = f.WriteString(cmdline + ": " + InitTime.String() + "\n")
+       if err != nil {
+               panic(err)
+       }
 }

 // Funcs are the interpolation funcs that are available within interpolations.
```

Run packer build...

InitTime log:
```
$ tail -F /tmp/packer-inittimes.txt
tail: cannot open '/tmp/packer-inittimes.txt' for reading: No such file or directory
tail: '/tmp/packer-inittimes.txt' has appeared;  following new file
packer,validate,build/ubuntu1404-unprovisioned.json: 2016-11-08 23:34:46.357799384 +0000 UTC
/home/moosh/build/packer,validate,build/ubuntu1404-unprovisioned.json: 2016-11-08 23:34:46.364081843 +0000 UTC
/home/moosh/build/packer,plugin,packer-builder-virtualbox-iso: 2016-11-08 23:34:46.371295021 +0000 UTC
/home/moosh/build/packer,plugin,packer-post-processor-shell-local: 2016-11-08 23:34:46.378918535 +0000 UTC
/home/moosh/build/packer,plugin,packer-post-processor-shell-local: 2016-11-08 23:34:46.387543364 +0000 UTC
packer,inspect,build/ubuntu1404-unprovisioned.json: 2016-11-08 23:34:46.406656989 +0000 UTC
/home/moosh/build/packer,inspect,build/ubuntu1404-unprovisioned.json: 2016-11-08 23:34:46.412059962 +0000 UTC
packer,build,--,build/ubuntu1404-unprovisioned.json: 2016-11-08 23:34:46.424485157 +0000 UTC
/home/moosh/build/packer,build,--,build/ubuntu1404-unprovisioned.json: 2016-11-08 23:34:46.430641658 +0000 UTC
/home/moosh/build/packer,plugin,packer-builder-virtualbox-iso: 2016-11-08 23:34:46.438389731 +0000 UTC
/home/moosh/build/packer,plugin,packer-post-processor-shell-local: 2016-11-08 23:34:46.445320815 +0000 UTC
/home/moosh/build/packer,plugin,packer-post-processor-shell-local: 2016-11-08 23:34:46.453208381 +0000 UTC
```

**Comment by leroux** [comment] 2016-11-10 00:27
@rickard-von-essen, I don't have a reliable repro since it's a timing issue. I could try to simulate a heavily loaded system and get close to hitting it more often. I'll get back with my findings when I get some time.

**Comment by mwhooker** [comment] 2017-01-23 21:09
this is a duplicate of #3958

**Comment by mwhooker** [comment] 2017-01-24 00:25
@leroux ok I see what you mean. Could you weigh in over at https://github.com/mitchellh/packer/issues/4446 ?

I'm trying to get some use-cases for this

**Comment by mwhooker** [comment] 2017-02-04 02:55
@leroux Here's a workaround for now

```json
{
    "variables": {
        "runid": "{{env `PACKER_RUN_UUID`}}"
    },
    "builders": [
        {
            "commit": true,
            "image": "fedora:25",
            "type": "docker"
        }
    ],
    "provisioners": [
        {
            "destination": "/tmp/test2-{{user `runid`}}.txt",
            "source": "files/foo.txt",
            "type": "file"
        },
        {
            "destination": "/tmp/test-{{user `runid`}}.txt",
            "source": "files/foo.txt",
            "type": "file"
        }
}
```

That will be the same ID for every file in the provisioner. This can be solved through documentation, so I'm going to track in #4446 and close this for now

**Closed by mwhooker** 2017-02-04 02:55 UTC
Labels: bug, core, need-repro

**Comment by leroux** [comment] 2017-02-04 03:11
Thanks, Matthew. I'm satisfied with this workaround.



On Fri, Feb 3, 2017, at 20:56, Matthew Hooker wrote:

> @leroux[1] Here's a workaround for now



> {  "variables": {  "runid": "{{env `PACKER_RUN_UUID`}}" },
> "builders": [ {  "commit": true,  "image": "fedora:25",  "type":
> "docker" } ],  "provisioners": [ {  "destination": "/tmp/test2-{{user
> `runid`}}.txt",  "source": "files/foo.txt",  "type": "file" }, {
> "destination": "/tmp/test-{{user `runid`}}.txt",  "source":
> "files/foo.txt",  "type": "file" } }
> That will be the same ID for every file in the provisioner. This can
> be solved through documentation, so I'm going to track in #4446[2] and
> close this for now
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].
> 


Links:

  1. https://github.com/leroux
  2. https://github.com/mitchellh/packer/issues/4446
  3. https://github.com/mitchellh/packer/issues/4136#issuecomment-277413522
