### ISSUE TITLE
Consider supporting HJSON.

### ISSUE THREAD

**Issue by howardroark** [mitchellh/packer#1819] opened 2015-01-07 13:57 UTC
http://laktak.github.io/hjson/

HJSON is a superset of JSON which makes things a lot more human friendly when it comes to editing.  I love packer but sometimes editing JSON can be very tedious (even with vim :P ).  The format is really nice because the mental leap between the two is basically non-existent. It is sort of the gateway between the human and the machine format.

There is no go implementation just yet, but there could be!

**Comment by sethvargo** [comment] 2015-01-07 15:28
Hi there,

I am going to close this as a duplicate of https://github.com/mitchellh/packer/issues/1768. While HCL != HJSON, this is something we have already discussed and will be doing shortly.

**Closed by sethvargo** 2015-01-07 15:28 UTC

**Comment by howardroark** [comment] 2015-01-07 15:42
Fair enough!  I think I'll fork this and try adding HJSON either way though.  It's nice because I don't have to reference anything.  Just write JSON in a naturally lazy way :)

Thanks!

**Comment by sethvargo** [comment] 2015-01-07 15:46
@howardroark you can do that with HCL too. And the HCL json parser has support for comments too.

**Comment by howardroark** [comment] 2015-01-07 16:19
That's great! I just didn't see any examples of that nature on the README file for HCL.

Thanks for clarifying.
