### ISSUE TITLE
remove the guest additions dvd drive

### ISSUE THREAD

**Issue by rgl** [mitchellh/packer#4349] opened 2017-01-02 19:01 UTC
when running the `virtualbox-iso` builder and `"guest_additions_mode": "attach",` packer should also remove the cd/dvd drive as it already does with the floppy drive.

I'm running packer 0.12.1.

**Comment by rickard-von-essen** [comment] 2017-01-02 21:41
Please add some info why this is a improvement.

**Comment by rgl** [comment] 2017-01-02 22:39
this is needed for the same reason as packer removes the floppy drive. that is, when you export the VM to a vagrant box, the resulting VM will have an extra dvd drive, and also with a possible wrong iso file inserted (e.g. the machine that will use the box might not event have the same .iso file).

**Comment by rickard-von-essen** [comment] 2017-01-03 19:54
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

---

> when you export the VM to a vagrant box, the resulting VM will have an extra dvd drive

I couldn't repro that, please provide the information required in the template.

**Comment by rgl** [comment] 2017-01-06 19:00
* Packer is 0.12.1
* Host is Windows 10
* Template is at [rgl/ubuntu-vagrant](https://github.com/rgl/ubuntu-vagrant), before running please comment the line `eject /dev/sr1` to really see that the guest additions iso is still on the drive (the entire drive should also be removed, well, maybe the IDE controller too; packer only removes the drive where it inserted the main iso file).
* The packer.log is at https://gist.github.com/rgl/3032984c5d551e25a1593d91623d46e3

**Comment by mwhooker** [comment] 2017-01-30 21:17
I think we need to remove this in `builder/virtualbox/common/step_remove_devices.go`. Should be straight forward, just needs to be tested

**Comment by mwhooker** [comment] 2017-01-30 21:42
This is a duplicate of #3652

**Closed by mwhooker** 2017-01-30 21:42 UTC
Labels: builder/virtualbox, easy, post-1.0
