### ISSUE TITLE
Shell provisioner doesn't properly wait for all stdout.

### ISSUE THREAD

**Issue by themalkolm** [mitchellh/packer#2527] opened 2015-07-29 10:54 UTC
We invoke shell provisioner and packer tends to trim the last one. The way to workaround is to drop 'sleep 5' as the *last* command in the inline script. This way it is somehow doesn't trim output anymore.

**Comment by cbednarski** [comment] 2015-07-29 17:08
Thanks for the report! I'm closing this at it sounds like a duplicate of #2527

**Closed by cbednarski** 2015-07-29 17:08 UTC
Labels: bug, core, duplicate
