### ISSUE TITLE
Packer crash on amazon ebs build

### ISSUE THREAD

**Issue by byrnedo** [mitchellh/packer#3069] opened 2016-01-14 13:05 UTC
Pushing a pretty simple build up to atlas I get the following.

Any ideas what's going wrong or how I should debug further?

_Template_:

```
{
    "variables": {
        "aws_access_key": "",
        "aws_secret_key": ""
    },
    "builders": [{
        "type": "amazon-ebs",
        "access_key": "{{user `aws_access_key`}}",
        "secret_key": "{{user `aws_secret_key`}}",
        "region": "eu-central-1",
        "source_ami": "ami-accff2b1",
        "instance_type": "t2.micro",
        "ssh_username": "ubuntu",
        "ami_name": "packer-example {{timestamp}}"
    }],
    "provisioners": [{
        "type": "shell",
        "inline": [
            "sleep 30",
            "sudo apt-get update",
            "sudo apt-get install -y redis-server"
        ]
    }],
    "post-processors": ["vagrant",
        {
            "type": "atlas",
            "token": "{{user `atlas_token`}}",
            "artifact": "byrnedo/packer-tutorial",
            "artifact_type": "amazon.ami",
            "metadata": {
                "created_at": "{{timestamp}}"
            }
        }
    ],
    "push": {
        "name": "byrnedo/packer-tutorial"
    }
}
```

_Log_ (There's more but first stack):

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
panic: runtime error: invalid memory address or nil pointer dereference
2016/01/14 12:59:22 packer: [signal 0xb code=0x1 addr=0x0 pc=0xcf1110]
2016/01/14 12:59:22 packer: 
2016/01/14 12:59:22 packer: goroutine 48 [running]:
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/aws/ec2metadata.(_EC2Metadata).GetMetadata(0x0, 0x13133e0, 0x19, 0x0, 0x0, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:18 +0x1b0
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:128 +0x74
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(_EC2RoleProvider).Retrieve(0xc8201f4cc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:85 +0x7b
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/aws/credentials.(_ChainProvider).Retrieve(0xc8201f4cf0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go:65 +0xf2
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/aws/credentials.(_Credentials).Get(0xc82018c640, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:182 +0x111
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/private/signer/v4.(_signer).sign(0xc82008b130, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go:123 +0x3bf
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/private/signer/v4.Sign(0xc82021a000)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/private/signer/v4/v4.go:97 +0x1e7
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/aws/request.(_HandlerList).Run(0xc82021a118, 0xc82021a000)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:115 +0x9f
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/aws/request.(_Request).Sign(0xc82021a000, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/request/request.go:197 +0xce
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/aws/request.(_Request).Send(0xc82021a000, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/aws/request/request.go:207 +0x54
2016/01/14 12:59:22 packer: github.com/aws/aws-sdk-go/service/ec2.(_EC2).DescribeImages(0xc820026298, 0xc8202037a0, 0xc8201ff000, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/aws/aws-sdk-go/service/ec2/api.go:2962 +0x4f
2016/01/14 12:59:22 packer: github.com/mitchellh/packer/builder/amazon/common.(_StepPreValidate).Run(0xc8201ff000, 0x7febd7b032a8, 0xc8201f5020, 0x7febd7b032a8)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/mitchellh/packer/builder/amazon/common/step_pre_validate.go:34 +0x3a4
2016/01/14 12:59:22 packer: github.com/mitchellh/multistep.(_BasicRunner).Run(0xc8201cd900, 0x7febd7b032a8, 0xc8201f5020)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/mitchellh/multistep/basic_runner.go:70 +0x330
2016/01/14 12:59:22 packer: github.com/mitchellh/packer/builder/amazon/ebs.(_Builder).Run(0xc82017e000, 0x7febd7b02d78, 0xc8201fed20, 0x7febd7b02dc0, 0xc8201fdfa0, 0x7febd7b02df0, 0xc820026278, 0x0, 0x0, 0x0, ...)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/mitchellh/packer/builder/amazon/ebs/builder.go:171 +0x16be
2016/01/14 12:59:22 packer: github.com/mitchellh/packer/packer/rpc.(_BuilderServer).Run(0xc820184640, 0x1, 0xc8201fdec0, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /Users/pearkes/code/golang/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x3b9
2016/01/14 12:59:22 packer: reflect.Value.call(0xf661a0, 0x108e640, 0x13, 0x1214660, 0x4, 0xc82008bed8, 0x3, 0x3, 0x0, 0x0, ...)
2016/01/14 12:59:22 packer:     /usr/local/go/src/reflect/value.go:432 +0x120a
2016/01/14 12:59:22 packer: reflect.Value.Call(0xf661a0, 0x108e640, 0x13, 0xc82008bed8, 0x3, 0x3, 0x0, 0x0, 0x0)
2016/01/14 12:59:22 packer:     /usr/local/go/src/reflect/value.go:300 +0xb1
2016/01/14 12:59:22 packer: net/rpc.(_service).call(0xc8200f5980, 0xc8200f5940, 0xc82017d9e0, 0xc820079580, 0xc820184940, 0xdf77a0, 0xc8201fdeb0, 0xca, 0xdc7600, 0xc8201fdec0, ...)
2016/01/14 12:59:22 packer:     /usr/local/go/src/net/rpc/server.go:383 +0x1c1
2016/01/14 12:59:22 packer: created by net/rpc.(*Server).ServeCodec
2016/01/14 12:59:22 packer:     /usr/local/go/src/net/rpc/server.go:477 +0x4ac
2016/01/14 12:59:22 packer: 
```

**Comment by rickard-von-essen** [comment] 2016-10-15 11:39
Please supply the information requested in the issue template:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).

**Comment by eric-aldinger** [comment] 2017-01-19 22:28
Same publishing an AWS AMI 

Packer Host: Ubuntu 14 
AMI Target: Ubuntu 16
packer -version 0.12.1
[log](https://gist.github.com/eric-aldinger/5971027d90f1340772e9a285d3413840)

Does not happen consistently.

RELEVANT ERROR LOG

2017/01/19 14:05:25 packer: panic: runtime error: invalid memory address or nil pointer dereference
2017/01/19 14:05:25 packer: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5ecc57]
2017/01/19 14:05:25 packer: 
2017/01/19 14:05:25 packer: goroutine 16 [running]:
2017/01/19 14:05:25 packer: panic(0x13beea0, 0xc42000e140)
2017/01/19 14:05:25 packer:     /usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
2017/01/19 14:05:25 packer: github.com/mitchellh/packer/builder/amazon/ebs.(*stepCreateAMI).Run(0xc4202461f0, 0x1e117a0, 0xc4203ea810, 0x0)
2017/01/19 14:05:25 packer:     /Users/mwhooker/go/src/github.com/mitchellh/packer/builder/amazon/ebs/step_create_ami.go:72 +0x917
2017/01/19 14:05:25 packer: github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep.(*BasicRunner).Run(0xc4204062c0, 0x1e117a0, 0xc4203ea810)
2017/01/19 14:05:25 packer:     /Users/mwhooker/go/src/github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep/basic_runner.go:70 +0x207
2017/01/19 14:05:25 packer: github.com/mitchellh/packer/builder/amazon/ebs.(*Builder).Run(0xc420222000, 0x1e140e0, 0xc4203e58a0, 0x1e0d0a0, 0xc4203ee8f0, 0x1e12e60, 0xc4202461a8, 0xc4201c1b30, 0x0, 0x0, ...)
2017/01/19 14:05:25 packer:     /Users/mwhooker/go/src/github.com/mitchellh/packer/builder/amazon/ebs/builder.go:196 +0x11cb
2017/01/19 14:05:25 packer: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc42022c320, 0x1, 0xc4201bfdb0, 0x0, 0x0)
2017/01/19 14:05:25 packer:     /Users/mwhooker/go/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x218
2017/01/19 14:05:25 packer: reflect.Value.call(0xc42001f980, 0xc4200303f8, 0x13, 0x15ffd31, 0x4, 0xc420389ed0, 0x3, 0x3, 0x0, 0x0, ...)
2017/01/19 14:05:25 packer:     /usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:434 +0x5c8
2017/01/19 14:05:25 packer: reflect.Value.Call(0xc42001f980, 0xc4200303f8, 0x13, 0xc420389ed0, 0x3, 0x3, 0xc4203b80b8, 0x1, 0x0)
2017/01/19 14:05:25 packer:     /usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:302 +0xa4
2017/01/19 14:05:25 packer: net/rpc.(*service).call(0xc42022a140, 0xc42022a100, 0xc420294030, 0xc42001bf00, 0xc420242740, 0x13117c0, 0xc4201bfdac, 0x18a, 0x12e6d00, 0xc4201bfdb0, ...)
2017/01/19 14:05:25 packer:     /usr/local/Cellar/go/1.7.3/libexec/src/net/rpc/server.go:383 +0x148
2017/01/19 14:05:25 packer: created by net/rpc.(*Server).ServeCodec
2017/01/19 14:05:25 packer:     /usr/local/Cellar/go/1.7.3/libexec/src/net/rpc/server.go:477 +0x421
2017/01/19 14:05:25 ui error: Build 'sw-pentaho-7-analytics-ami' errored: unexpected EOF

**Comment by mwhooker** [comment] 2017-01-22 06:39
This is a duplicate of #4303

Please try again with latest packer.

**Closed by mwhooker** 2017-01-22 06:39 UTC
Labels: bug, builder/amazon, crash
