### ISSUE TITLE
Packer usage message incorrect, no --version

### ISSUE THREAD

**Issue by lutnos** [mitchellh/packer#1949] opened 2015-02-25 13:09 UTC
Trivial, I know!

`DavesiMac:pack-it dave$ packer --help`
`usage: packer [--version] [--help] <command> [<args>]`

`Available commands are:`
`    build       build image(s) from template`
`    fix         fixes templates from old versions of packer`
`    inspect     see components of a template`
`    push        push template files to a Packer build service`
`    validate    check that a template is valid`
`    version     Prints the Packer version`

Bad:

`DavesiMac:pack-it dave$ packer --version`
`usage: packer [--version] [--help] <command> [<args>]`

`Available commands are:`
`    build       build image(s) from template`
`    fix         fixes templates from old versions of packer`
`    inspect     see components of a template`
`    push        push template files to a Packer build service`
`    validate    check that a template is valid`
`    version     Prints the Packer version`

Good:

`DavesiMac:pack-it dave$ packer version`
`Packer v0.7.5`

`DavesiMac:pack-it dave$ `

Thanks

**Comment by sethvargo** [comment] 2015-02-25 15:24
This is a duplicate of https://github.com/mitchellh/packer/pull/1756

**Closed by sethvargo** 2015-02-25 15:24 UTC
