### ISSUE TITLE
Failing to build on Ubuntu with Packer and VMware Workstation 

### ISSUE THREAD

**Issue by catesandrew** [mitchellh/packer#2192] opened 2015-06-09 13:11 UTC
VMware v11.1.0 build-2496824
Packer v0.7.5
Host OS: Ubuntu 14.04 on bare metal

Packer hangs when trying to build an image with VMware. Take for instance, [this ubuntu image from bento](https://github.com/chef/bento/blob/master/ubuntu-14.04-amd64.json), it works with packer on mac and vmware fusion, but times out on ubuntu. 

Pretty sure this has a lot to do with a newer version of workstation than packer. Am hoping that the new 0.8 release will take care of it but I didn't see anything in the upcoming release notes mentioning it. So not sure how many people are using packer to build images on Linux boxes and wanted to report it to throw it on the radar. thanks

```
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting HTTP server on port 8454
==> vmware-iso: Starting virtual machine...
==> vmware-iso: Waiting 10s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for SSH to become available...
==> vmware-iso: Timeout waiting for SSH.
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Timeout waiting for SSH.
```

**Comment by epkdavj** [comment] 2015-06-10 13:37
Hi, i have same issue trying to create an image from a rhel based vmx.

vxsdp01 output will be in this color.

==> vxsdp01: Cloning source VM...
==> vxsdp01: Starting virtual machine...
==> vxsdp01: Waiting 10s for boot...
==> vxsdp01: Connecting to VM via VNC
==> vxsdp01: Typing the boot command over VNC...
==> vxsdp01: Waiting for SSH to become available...
==> vxsdp01: Timeout waiting for SSH.
==> vxsdp01: Stopping virtual machine...
==> vxsdp01: Deleting output directory...
Build 'vxsdp01' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> vxsdp01: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.

**Comment by mitchellh** [comment] 2015-06-10 18:04
What is VMware doing while waiting for SSH? Can you start with a GUI and see what is happening?

**Comment by catesandrew** [comment] 2015-06-10 18:52
@mitchellh, gui just sits there with the flashing shell underbar prompt. the setup proceeds as expected, at end its a blank red screen with extra line on bottom and the flashing prompt.

**Comment by epkdavj** [comment] 2015-06-11 05:36
For me, it reaches the login prompt and i can login via the console or ssh via the configured eth ports. Then the timeout hits and the virtual machine gets deleted.

**Comment by mitchellh** [comment] 2015-06-13 21:08
@catesandrew Does the OS install succeed? Is it even starting? This is still looking like a virtualization or configuration problem, and not yet a Packer problem.

**Comment by catesandrew** [comment] 2015-06-14 06:12
@mitchellh it starts but doesn't succeed. again, works for vmware fusion and virtualbox on mac/ubuntu. Here's a [screenshot video](http://youtu.be/AKoS8Nxc4JE).

**Comment by mitchellh** [comment] 2015-06-23 01:01
@catesandrew Thanks for the video. After watching the video, I'm 100% certain this is something to do with your machine setup that is running Linux. It likely isn't a bug in VMware or anything, it is probably just a networking issue. The problem is that at that point in the install, the installer tries to talk to the internet, and its failing. Packer is still just waiting for the install to succeed (but it never does, it will time out after some time). 

Please take a look at your network settings for VMware, the solution lies there somewhere.

**Closed by mitchellh** 2015-06-23 01:01 UTC
Labels: bug, builder/vmware, waiting-reply

**Comment by catesandrew** [comment] 2015-06-23 03:52
@mitchellh, thanks! I had the following `.curlrc`, something it didn't like. I would of never figured it out till I just saw your comment!!

```
# cURL default configuration file
# http://curl.haxx.se/docs/manpage.html

# Limit the time (in seconds) the connection to the server is allowed to take
connect-timeout = 30

# Follow HTTP redirects
location

# Limit the time (in seconds) the whole operation is allowed to take
# (prevents cURL from hanging due to slow networks or links going down)
max-time = 300

# When following a redirect, automatically set the previous URL as referer
referer = ";auto"

# Show error messages
show-error

# Do not show the progress meter
silent

# Send a fake UA string for the HTTP servers that sniff it
user-agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9) AppleWebKit/537.13+ (KHTML, like Gecko) Version/5.1.7 Safari/534.57.2"
```
