### ISSUE TITLE
AMI created with aws-chroot has /etc/resolv.conf missing

### ISSUE THREAD

**Issue by rag1998** [mitchellh/packer#4698] opened 2017-03-22 22:13 UTC
We have Packer running as part of Spinnaker and in an effort to speed up bake times we tried using chroot and noticed that /etc/resolv.conf missing when an instance is launched using chroot baked AMI.

We even tried creating this file as part of the shell script that gets run during bake, but looks like its being deleted as part of a cleanup step maybe? 

This problem doesn't exist with aws-ebs template, seems to happen only with aws-chroot.

- 0.12.3
- Ubuntu
- log: https://gist.github.com/rag1998/6bc546b4609c38d9b7020e327c226077
- template: https://gist.github.com/rag1998/9fb34d33592ae729b32e7d9360096d42
- shell script run by template(can see where I deliberately added a symlink for the resolv.conf file : https://gist.github.com/rag1998/2847acca3f1066d31a689f28ff88750d

**Comment by mwhooker** [comment] 2017-03-22 22:47
hmm, not sure exactly what's going on without digging in further.

What happens if you remove your provisioning step altogether? The logs show the resolv.conf getting copied, and not being removed, so I suspect it's getting removed somehow in the provisioner.

**Comment by rickard-von-essen** [comment] 2017-03-23 02:35
_copy_files_ are clean up in https://github.com/mitchellh/packer/blob/master/builder/amazon/chroot/step_copy_files.go#L63

Can't really see why that is done and never the less it should happen after the snapshot for the AMI have been created. 

Seems like a bug to me...

**Comment by rag1998** [comment] 2017-03-23 13:54
Thanks for looking into this..

@mwhooker, still need an answer to that? If so I can give it a try and get back to you..

**Comment by Ssrinivasan1** [comment] 2017-03-23 15:04
when i tried to copy the file as part of script 
sfunction provision_deb() {
  # https://www.packer.io/docs/builders/amazon-chroot.html look at gotchas at the end.
  if [[ "$disable_services" == "true" ]]; then
    echo "creating /usr/sbin/policy-rc.d to prevent services from being started"
    echo '#!/bin/sh' | sudo tee /usr/sbin/policy-rc.d > /dev/null
    echo 'exit 101' | sudo tee -a /usr/sbin/policy-rc.d > /dev/null
    sudo chmod a+x /usr/sbin/policy-rc.d
  fi

  if [[ "$repository" != "" ]]; then
    IFS=';' read -ra repo <<< "$repository"
    for i in "${repo[@]}"; do
      echo "deb $i" | sudo tee -a /etc/apt/sources.list.d/spinnaker.list > /dev/null
    done
  fi

  sudo apt-get update
  if [[ "$upgrade" == "true" ]]; then
    sudo unattended-upgrade -v
  fi

  # Enforce the package installation order.
  for package in $packages; do sudo DEBIAN_FRONTEND=noninteractive apt-get install --force-yes -y $package; done

  # https://www.packer.io/docs/builders/amazon-chroot.html look at gotchas at the end.
  if [[ "$disable_services" == "true" ]]; then
    echo "removing /usr/sbin/policy-rc.d"
    sudo rm -f /usr/sbin/policy-rc.d
    #sudo ln -s /run/resolvconf/resolv.conf
    sudo cp /run/resolvconf/resolv.conf /etc/resolv.conf
  fi

I got the below error that the
        amazon-chroot: cp: cannot stat '/run/resolvconf/resolv.conf': No such file or directory
==> amazon-chroot: Unmounting the root device...
==> amazon-chroot: Detaching EBS volume...
==> amazon-chroot: Deleting the created EBS volume...

also i saw there was an issue opened in regards to the same and closed it, https://github.com/mitchellh/packer/issues/500

so is the issue brought back in the newer version?

**Comment by mwhooker** [comment] 2017-03-23 21:16
unfortunately I'm unable to reproduce.

```
ubuntu@ip-172-31-49-42:~$ cat packer.json
{
    "builders": [
        {
            "access_key": "xxx",
            "ami_name": "packer-example {{timestamp}}",
            "ami_virtualization_type": "hvm",
            "command_wrapper": "sudo {{.Command}}",
            "name": "chroot_builder",
            "region": "us-east-1",
            "root_volume_size": 8,
            "secret_key": "xxx",
            "source_ami": "ami-fce3c696",
            "type": "amazon-chroot"
        }
    ]
}

ubuntu@ip-172-31-49-42:~$ sudo ./packer build packer.json
chroot_builder output will be in this color.

==> chroot_builder: Prevalidating AMI Name...
==> chroot_builder: Gathering information about this EC2 instance...
    chroot_builder: Found Image ID: ami-fce3c696
==> chroot_builder: Checking the root device on source AMI...
==> chroot_builder: Creating the root volume...
==> chroot_builder: Attaching the root volume to /dev/sdf
==> chroot_builder: Mounting the root device...
==> chroot_builder: Mounting additional paths within the chroot...
    chroot_builder: Mounting: /proc
    chroot_builder: Mounting: /sys
    chroot_builder: Mounting: /dev
    chroot_builder: Mounting: /dev/pts
    chroot_builder: Mounting: /proc/sys/fs/binfmt_misc
==> chroot_builder: Copying files from host to chroot...
    chroot_builder: /etc/resolv.conf
==> chroot_builder: Unmounting the root device...
==> chroot_builder: Detaching EBS volume...
==> chroot_builder: Creating snapshot...
    chroot_builder: Snapshot ID: snap-0b0399f61e98b8d03
==> chroot_builder: Registering the AMI...
==> chroot_builder: AMI: ami-6b43f07d
==> chroot_builder: Waiting for AMI to become ready...
==> chroot_builder: Deleting the created EBS volume...
Build 'chroot_builder' finished.

$ ssh ubuntu@54.82.229.142

ubuntu@ip-172-31-25-114:~$ cat /etc/resolv.conf
domain ec2.internal
search ec2.internal
nameserver 172.31.0.2

ubuntu@ip-172-31-25-114:~$ curl http://169.254.169.254/latest/meta-data/ami-id
ami-6b43f07d
```

If you can post a runnable json that reproduces the issue, I can investigate

**Comment by rag1998** [comment] 2017-03-24 00:05
Thanks for doing that, that led me to use the same AMI you used as our base AMI and helped in finding some more info on this issue.

So the problem seems to be that our base AMI is Ubuntu 16.04, so I created a new base AMI using the 14.04 AMI and fed that to packer, this didn't have a missing resolv.conf file while the 16.04 AMI did!

Our packer box(AMI Builder) is 14.04, but since the base AMI is 16.04 we are wondering if thats causing an issue, so next step is to try and upgrade the packer box to 16.04 and build with a 16.04 base AMI to see if that resolves it!

**Comment by mwhooker** [comment] 2017-03-24 01:10
yeah, let me know. I thought about testing 16.04, which I still think is a good idea. I can try doing that next week if you don't get to it first

**Comment by rickard-von-essen** [comment] 2017-03-24 06:10
I think that it's because 16.04 uses systemd which handles [resolve.conf](https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html).

By default it's probably a symlink to /var/run...

**Comment by rag1998** [comment] 2017-03-24 13:59
@rickard-von-essen, sure is a symlink: resolv.conf -> ../run/resolvconf/resolv.conf

**Comment by rickard-von-essen** [comment] 2017-03-24 18:37
So I reproduced this, and these are my conclusions:

1) This is because `/etc/resolv.conf` from 14.04 is a file and when copied overwrites the link that in 16.04 pointing to `../run/resolvconf/resolv.conf`.

2) Be careful to build on the same distribution as your target when using `amazon-chroot` sometimes even version matters.

3) _The real bug_ is that it is not possible to _not_ any `copy_files` since setting it to `[]` will result in the default `[ "/etc/resolv.conf" ]`. @mwhooker  I'm not sure how to fix this without braking BC. Maybe we should just make a not in the docs about the work around (4))?

4) The workaround is just to create a dummy file say `touch /tmp/.ignore` and then add `"copy_files": [ "/tmp/.ignore" ]` to your config.

**Comment by mwhooker** [comment] 2017-03-24 18:41
@rickard-von-essen ahh, good catch. Will think about this. At minimum we should make a note in the docs. Maybe there is a way around this, though (like using a pointer hack in the config)

**Comment by rickard-von-essen** [comment] 2017-03-24 18:44
Yes I guess the pointer hack would work but would also change existing behaviour.

**Comment by mwhooker** [comment] 2017-03-24 19:42
@rickard-von-essen I think I found a nice solution if you want to review #4708

**Comment by rag1998** [comment] 2017-03-24 20:04
Both the builder(packer) and base AMI to be created being on 16.04 doesn't resolve it..

**Comment by mwhooker** [comment] 2017-03-24 20:08
You might have to set `"copy_files": ["/run/resolvconf/resolv.conf"]` or something.

**Comment by mwhooker** [comment] 2017-03-24 22:39
I built ubuntu 16.04 with the head of packer. Here's my template:

```
{
    "builders": [
        {
            "access_key": "xxx",
            "ami_name": "packer-example {{timestamp}}",
            "ami_virtualization_type": "hvm",
            "command_wrapper": "sudo {{.Command}}",
            "name": "chroot_builder",
            "region": "us-east-1",
            "root_volume_size": 8,
            "secret_key": "xxx",
            "source_ami": "ami-2757f631",
            "type": "amazon-chroot",
            "copy_files": []
        }
    ],
    "provisioners": [],
    "variables": {}
}
```

I launched the AMI built with the above and connected to it and the resolv.conf file was where it was supposed to be:

```
ubuntu@ip-172-31-30-92:~$ cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.31.0.2
search ec2.internal
```

I'll update the docs a bit to say that you might need to do this for systemd, but I think this is resolved.

@rag1998 If you're trying to mutate the resolv.conf file then I think you need to find out how to do that using systemd (see https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html)

the [mailing list](https://groups.google.com/forum/#!forum/packer-tool) might be the best place to get help for that.

Feel free to comment here if you think there's still a bug in packer and I'll try to help out, but closing this for now

**Closed by mwhooker** 2017-03-24 22:39 UTC
Labels: bug, builder/amazon

**Comment by asgoel** [comment] 2019-05-03 03:04
@mwhooker  I am having trouble resolving DNS after creating a `chroot` volume (and am unable to find `/etc/resolv.conf`. Here is a short config describing the issue:

```
{
    "variables": {
        "region": null,
        "source_ami_environment_tag": "production"
    },

    "builders": [{
        "type": "amazon-chroot",
        "region": "{{user `region`}}",
        "command_wrapper": "sudo {{.Command}}",
        "source_ami": "ami-09b42c38b449cfa59",
        "ami_name": "chroot_test__{{isotime \"2006_01_02_150405.000\"}}",
        "ami_virtualization_type": "hvm",
        "ena_support": true,
        "nvme_device_path": "/dev/nvme0n1p",
        "device_path": "/dev/sdf",
        "copy_files": []
    }],

    "provisioners": [
        {
            "type": "shell",
            "inline": [
                "cat /etc/resolv.conf"
            ]
        }
    ]
}
```

This is the error output:
```
amazon-chroot output will be in this color.

2019-05-03T03:03:09Z: ==> amazon-chroot: Prevalidating AMI Name: chroot_test__2019_05_03_030309.329
2019-05-03T03:03:10Z: ==> amazon-chroot: Gathering information about this EC2 instance...
2019-05-03T03:03:10Z:     amazon-chroot: Found Image ID: ami-09b42c38b449cfa59
2019-05-03T03:03:10Z: ==> amazon-chroot: Checking the root device on source AMI...
2019-05-03T03:03:10Z: ==> amazon-chroot: Creating the root volume...
2019-05-03T03:03:25Z: ==> amazon-chroot: Attaching the root volume to /dev/sdf
2019-05-03T03:03:31Z: ==> amazon-chroot: Mounting the root device...
2019-05-03T03:03:31Z: ==> amazon-chroot: Mounting additional paths within the chroot...
2019-05-03T03:03:31Z:     amazon-chroot: Mounting: /proc
2019-05-03T03:03:31Z:     amazon-chroot: Mounting: /sys
2019-05-03T03:03:31Z:     amazon-chroot: Mounting: /dev
2019-05-03T03:03:31Z:     amazon-chroot: Mounting: /dev/pts
2019-05-03T03:03:31Z:     amazon-chroot: Mounting: /proc/sys/fs/binfmt_misc
2019-05-03T03:03:31Z: ==> amazon-chroot: Provisioning with shell script: /tmp/packer-shell655574812
2019-05-03T03:03:31Z:     amazon-chroot: cat: /etc/resolv.conf: No such file or directory
2019-05-03T03:03:31Z: ==> amazon-chroot: Unmounting the root device...
2019-05-03T03:03:31Z: ==> amazon-chroot: Detaching EBS volume...
2019-05-03T03:03:36Z: ==> amazon-chroot: Deleting the created EBS volume...
2019-05-03T03:03:37Z: Build 'amazon-chroot' errored: Script exited with non-zero exit status: 1

==> Some builds didn't complete successfully and had errors:
--> amazon-chroot: Script exited with non-zero exit status: 1

==> Builds finished but no artifacts were created.
```

Thoughts

**Comment by rickard-von-essen** [comment] 2019-05-03 07:02
@asgoel please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/

(and see this [section of the docs](https://packer.io/docs/builders/amazon-chroot.html#copy_files))
