### ISSUE TITLE
"Unsupported protocol scheme" / openstack

### ISSUE THREAD

**Issue by onaclov2000** [mitchellh/packer#2597] opened 2015-08-13 18:02 UTC
https://github.com/mitchellh/packer/issues/2341

* Get /: unsupported protocol scheme ""

I am seeing a similar error, but have no variables, not sure how to work around it.
```json
{
"builders": [{
"type": "openstack",
"flavor": "3",
"ssh_username": "ubuntu",
"image_name": "gitlab",
"source_image": "X", // not relevant
"floating_ip_pool": "IP", // not relevant
"use_floating_ip": true
}]
}
```

**Comment by onaclov2000** [comment] 2015-08-13 18:16
I'm attempting to build this FROM a VM on the same openstack infrastructure if that helps.

**Comment by onaclov2000** [comment] 2015-08-13 19:44
Appears that if you don't do the proper "openstack" login credentials stuff BEFORE packer validate it still dies. I'm not sure if this is a "feature" or not, but I'll leave that to you. I thought validate was just checking that the .json was right, and met the tools expectations for contents. I didn't realize it actually attempted to reach out to openstack.

**Comment by cbednarski** [comment] 2015-08-14 21:56
@onaclov2000 Yes, we also check credentials for e.g. Atlas and AWS so I think this is fairly consistent between providers. We'd like to do more at validation time, too, like test whether we can download ISOs and such. We can make this more clear in the documentation.

Does this information resolve the issue for you? Your initial report does not indicate what you were invoking (build vs validate) or what logs were associated with the failure so I'm not sure exactly how the failure manifested in your case.

**Comment by xpicio** [comment] 2015-08-26 08:37
@onaclov2000 I had the same issue with packer 0.8.5 on OS X 10.10.5 with a private OpenStack setup. I fixed the problem setting up the env variable 
```
OS_AUTH_URL=http://my-hostname:5000/v2.0/
```

**Comment by RyanGWU82** [comment] 2015-09-09 14:50
I'm having the same problem with building Rackspace (OpenStack) servers. I'm using Packer 0.8.1 and 0.8.6 on OS X 10.10.5. Everything works fine for building Amazon EC2 instances, but I get an error when building OpenStack servers. I'm also using environment variables for authentication, and I've confirmed they're set correctly. This was working a few weeks ago (possibly with an older version of Packer) so I'm a little confused why it suddenly stopped working.

This is the output of `packer build`:

```
$ packer build -only=rackspace-ord centos7.json 
rackspace-ord output will be in this color.

1 error(s) occurred:

* Get /: unsupported protocol scheme ""
```

Here's are my `variables` and `builder` configs:

```json
{
  "variables": {
    "aws_access_key": "{{env `AWS_ACCESS_KEY_ID`}}",
    "aws_secret_key": "{{env `AWS_SECRET_ACCESS_KEY`}}",
    "rackspace_username": "{{env `RACKSPACE_USERNAME`}}",
    "rackspace_api_key": "{{env `RACKSPACE_API_KEY`}}"
  },
  "builders": [
    {
      "name": "rackspace-ord",
      "type": "openstack",
      "communicator": "ssh",
      "ssh_pty": true,
      "username": "{{user `rackspace_username`}}",
      "api_key": "{{user `rackspace_api_key`}}",
      "region": "ORD",
      "ssh_username": "root",
      "image_name": "runscope-centos7-{{timestamp}}",
      "source_image": "bfa5783c-e40e-4668-adc1-feb0ae3d7a46",
      "flavor": "performance1-2"
    },
    ...
  ]
}
```

**Comment by nohtyp** [comment] 2015-09-15 12:16
I am having the same issue with CentOS 7 OpenStack (Juno):

```
packer build firstbuild.json
openstack output will be in this color.

1 error(s) occurred:

* Get /: unsupported protocol scheme ""
```

My code:
```
{
"variables": {
	"myusername": "{{env `OS_USERNAME`}}",
	"mypassword": "{{env `OS_PASSWORD`}}"
  },
	
"builders": [
    {
	"type": "openstack",
	"ssh_username": "root",
	"image_name": "foster_test_centos7.1",
	"source_image": "9582b3f5-6e2a-4ce5-8e41-777cadba499f",
	"flavor": "m1.small",
	"username": "{{user `myusername`}}",
	"password": "{{user `mypassword`}}",
	"insecure": "true"
    }
 ],
"provisioners": [
    {
	"type": "shell",
	"inline": ["systemctl disable firewalld"]
    }
  ]
}
```

**Comment by rickard-von-essen** [comment] 2016-02-09 12:29
The docs have been updated, see [Docs OpenStack](https://github.com/mitchellh/packer/blob/master/website/source/docs/builders/openstack.html.markdown) until next release when the site will be updated.

**Comment by rickard-von-essen** [comment] 2016-02-12 19:13
If someone knows what they did wrong, could you add some details here so I can reproduce it and see if we can catch the error and provide a better error message. (The current error message comes from a combination of gophercloud, the OpenStack Go lib, and the Go std URL lib.)

**Comment by smolinari** [comment] 2016-02-21 19:10
Hi,

It seems, if I add the  "identity_endpoint" key and value the 

`Get /: unsupported protocol scheme ""`

error goes away. However, other problems come up. I am not sure if it is because of the URL I am using or what, but I can't seem to get the Rackspace builder to connect. 

Depending on what URL I use, I get either a 401 or this. 
Scott

**Comment by rickard-von-essen** [comment] 2016-02-21 19:19
@smolinari You need to include the version, try ```OS_AUTH_URL=https://identity.api.rackspacecloud.com/v2.0```

**Comment by smolinari** [comment] 2016-02-22 04:50
Ahh, I had `/token` at the end of my URL. That URL works.

Can you change the docs and add that URL in the example instead of this.

`"identity_endpoint": "http://<destack-ip>:5000/v3"` 

It is misleading.

And add the key and value to the RS Public Cloud example too, as the Public Cloud access needs it too it seems.

Scott

**Comment by rickard-von-essen** [comment] 2016-02-22 07:33
@smolinari The ```identity_endpoint``` example you are referring to is for DevStack, and it is correct. The _Rackspace_ example should probably be extended with ```OS_*``` environment variables. I suggest that you read under **Notes On OpenStack Authorization** and try to use a _OpenStack RC file_. (This can probably be clarified a bit about v2 identity API)

**Comment by zhaomizhi** [comment] 2016-09-28 00:03
I had this issue too and it turned out that i did not export my OpenStack credentials to the environment. After `source`, i don't have the problem any more. This problem seems like related to credentials.

**Comment by rickard-von-essen** [comment] 2016-09-28 04:56
Closing this since this seems like a usage error.

**Closed by rickard-von-essen** 2016-09-28 04:56 UTC
Labels: bug, builder/openstack, docs, waiting-reply
