### ISSUE TITLE
Shell provisioner exits on excessive output

### ISSUE THREAD

**Issue by kashyapparikh-ck** [mitchellh/packer#2083] opened 2015-04-30 18:46 UTC
May be related to #1184 which was marked closed but I am still seeing this issue in latest version 0.7.5.

Fairly easy to reproduce.

In my case I am running a script that runs a long list of salt states and the script is exiting before its complete. Redirecting output is not a very good options since  I want a CI job to monitor it:

```
2015/04/30 11:31:10 packer-provisioner-shell: 2015/04/30 11:31:10 [INFO] 402333 bytes written for 'stdout'
2015/04/30 11:31:10 packer-provisioner-shell: 2015/04/30 11:31:10 [ERR] 'stdout' copy error: io: read/write on closed pipe
2015/04/30 11:31:10 ui: ==> amazon-ebs: Stopping the source instance...
==> amazon-ebs: Stopping the source instance...
```

**Comment by thanosd** [comment] 2015-06-03 20:23
Yup - seeing this on 0.7.5 as well. Very consistent.

**Comment by mlococo** [comment] 2015-06-15 16:22
I'm also reproducing this on 0.7.5, same error output in the log.

**Comment by mitchellh** [comment] 2015-06-15 21:51
This was an upstream issue which will be fixed for 0.8.0

**Comment by kashyap-parikh** [comment] 2015-12-04 23:37
Still reproducible in 0.8.6

**Comment by cmeisinger** [comment] 2016-03-09 17:40
Still present in 0.9.0.

**Comment by bewatts** [comment] 2016-07-26 16:23
Still present in Packer v0.10.1

**Comment by mwhooker** [comment] 2016-09-23 17:29
reopening. Can anyone who's still seeing this reproduce this reliably? An example json file would be really helpful.

**Comment by cmeisinger** [comment] 2016-09-27 21:05
Please disregard my prior post.   The output is truncated, but the operation doesn't hang now.  

Sorry!

**Comment by mwhooker** [comment] 2017-01-22 07:00
unable to reproduce with

```
  "provisioners": [{
      "type": "shell",
      "inline": [
          "dd if=/dev/urandom of=output.file bs=1024 count=1024",
          "hexdump output.file"
      ]
  }]
```


which is excessive output afaict. Going to close. If you're still seeing this, please open a new issue with a minimal json file which will reproduce the issue

**Closed by mwhooker** 2017-01-22 07:00 UTC
Labels: bug, need-repro, provisioner/shell

**Comment by Anish123bosco** [comment] 2017-06-03 07:18
Still present in 1.0.0

2017/05/25 17:19:31 [INFO] 1445270 bytes written for 'stdout'
2017/05/25 17:19:31 [ERR] 'stdout' copy error: stream closed
2017/05/25 17:19:31 packer: 2017/05/25 17:19:31 [INFO] 0 bytes written for 'stderr'
2017/05/25 17:19:31 packer: 2017/05/25 17:19:31 [INFO] RPC client: Communicator ended with: 2
2017/05/25 17:19:31 packer: 2017/05/25 17:19:31 [INFO] 777814 bytes written for 'stdout'
2017/05/25 17:19: vmware-iso: + multi_accept on;
31 packer: 2017/05/25 17:19:31 [ERR] 'stdout' copy error: io: read/write on closed pipe

**Comment by JoshuaEdwards1991** [comment] 2019-12-05 14:57
1.4.5

Still getting this error from a massive output

**Comment by SwampDragons** [comment] 2019-12-05 17:52
Hi, @JoshuaEdwards1991 -- this issue was closed two years ago; it's likely that you're seeing something new. Will you please open a new issue with the steps to reproduce requested in the bug issue template?  

Thanks!
