### ISSUE TITLE
no_device not working for instance backed AMIs

### ISSUE THREAD

**Issue by jlintz** [mitchellh/packer#3001] opened 2015-12-15 19:13 UTC
```
{
  "variables": {
    "aws_access_key": "",
    "aws_secret_key": "",
    "provision_script": ""
  },
  "builders": [{
     "ami_block_device_mappings": [
            {
              "device_name": "/dev/sdb",
              "no_device": true
            },
            {
              "device_name": "/dev/sdc",
              "no_device": true
            },
            {
              "device_name": "sdb",
              "no_device": true
            },
            {
              "device_name": "sdc",
              "no_device": true
            }
          ],
    "type": "amazon-instance",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "us-east-1",
    "source_ami": "ami-ed135687",
    "instance_type": "c3.large",
    "ssh_username": "ubuntu",
    "security_group_id": "packer",
    "account_id": "273001990628",
    "s3_bucket": "chartbeat-amis",
    "ami_virtualization_type": "hvm",
    "x509_cert_path": "{{user `x509_cert_path`}}",
    "x509_key_path": "{{user `x509_key_path`}}",
    "bundle_vol_command": "sudo -n bash -c 'ec2-bundle-vol -k {{.KeyPath}} -u {{.AccountId}} -c {{.CertPath}} -r x86_64 -p {{.Prefix}} --no-filter --batch'",
    "bundle_upload_command": "sudo -n bash -c 'ec2-upload-bundle -b {{.BucketName}} -m {{.ManifestPath}} -a {{user `aws_access_key`}} -s {{user `aws_secret_key`}} -d {{.BundleDirectory}} --batch --retry'",
    "ami_name": "chartbeat-base {{timestamp}}",
    "tags": {
        "OS_Version": "Ubuntu",
        "Release": "12.04",
        "Name": "base"
    }
  }],
  "provisioners": [{
    "type": "shell",
    "script": "{{user `provision_script`}}"
  }]
}
```

According to CloudTrail the call to RegisterImage looks like 

```
{
    "eventVersion": "1.03",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "",
        "arn": "",
        "accountId": "",
        "accessKeyId": "",
        "userName": "justin"
    },
    "eventTime": "2015-12-15T19:01:11Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "RegisterImage",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "",
    "userAgent": "aws-sdk-go/1.0.0 (go1.5.1; darwin; amd64)",
    "requestParameters": {
        "imageLocation": "chartbeat-amis/image-1450205038.manifest.xml",
        "name": "chartbeat-base 1450205038",
        "blockDeviceMapping": {
            "items": [
                {
                    "deviceName": "/dev/sdb",
                    "noDevice": {}
                },
                {
                    "deviceName": "/dev/sdc",
                    "noDevice": {}
                },
                {
                    "deviceName": "sdb",
                    "noDevice": {}
                },
                {
                    "deviceName": "sdc",
                    "noDevice": {}
                }
            ]
        }
    },
    "responseElements": {
        "imageId": "ami-64c3890e"
    },
    "requestID": "09c525d0-e6be-447f-8b30-48c8c41d4c64",
    "eventID": "cbb7f78d-a379-42cb-af40-93e77a82247a",
    "eventType": "AwsApiCall",
    "recipientAccountId": ""
}
```

(removed some identifying info)

Which ends up with an AMI where sdb and sdc are still block devices.  According to the docs, it looks like `NoDevice` should be a string but it seems like it's ending up as an empty hash?

**Comment by jlintz** [comment] 2015-12-15 20:47
Also if you set `no_device` to just "" , it generates the wrong block device mapping
```
blockDeviceMapping": {
            "items": [
                {
                    "deviceName": "/dev/sdb",
                    "ebs": {
                        "deleteOnTermination": false
                    }
                },
                {
                    "deviceName": "/dev/sdc",
                    "ebs": {
                        "deleteOnTermination": false
                    }
                },
                {
                    "deviceName": "sdb",
                    "ebs": {
                        "deleteOnTermination": false
                    }
                },
                {
                    "deviceName": "sdc",
                    "ebs": {
                        "deleteOnTermination": false
                    }
                }
            ]
```

**Comment by cbednarski** [comment] 2015-12-16 22:48
@catsby I think you have looked into this issue in the past and I _vaguely_ recall that there was an upstream issue related to this. Can you confirm? This issue maybe a dupe, too, but it's still not resolved.

**Comment by catsby** [comment] 2015-12-17 15:46
I have a GitHub issue open on the SDK:

- https://github.com/aws/aws-sdk-go/issues/307

Doesn't appear to have much traction/priority though. 
The original Packer was closed after a workaround was shared:

- https://github.com/mitchellh/packer/issues/2398

**Comment by jlintz** [comment] 2015-12-17 16:50
@catsby unfortunately the workaround doesn't appear to be working, it says just specify `device_name` and `no_device` which I'm already doing.  If it's an upstream issue i'll see if I can poke around there and see what's going on

**Comment by runningman84** [comment] 2016-12-14 11:08
any news here? I have the same problem.

All of these combinations do not work:
```
      {
        "device_name" : "/dev/sdc",
        "virtual_name" : "ephemeral1",
        "no_device" : true
      },
      {
        "device_name" : "/dev/sdd",
        "no_device" : true
      },
      {
        "device_name" : "/dev/sde",
        "virtual_name" : "ephemeral3",
        "no_device" : "true"
      }
```

**Comment by runningman84** [comment] 2016-12-14 12:28
@catsby do you have any working workarround?

**Comment by rickard-von-essen** [comment] 2016-12-14 12:44
@runningman84 Can you gist a debug log and your template?

**Comment by runningman84** [comment] 2016-12-14 16:52
hmm it looks like the new version of packer does not have this problem anymore. I was running 0.8.x before...

**Comment by rickard-von-essen** [comment] 2016-12-14 17:11
Closing this. Open a new issue you can reproduce this on 0.12.0.

**Closed** 2016-12-14 17:11 UTC
Labels: bug, builder/amazon
