### ISSUE TITLE
Error waiting for SSH with PK authentication

### ISSUE THREAD

**Issue by rmbrad** [mitchellh/packer#3027] opened 2015-12-31 17:46 UTC
I'm attempting to create a CentOS 7 image using the VirtualBox ISO builder, where the public key is injected during the kickstart install, but once the install completes Packer is unable to use the private key to authenticate. My current setup consists of OS X 10.11.2, VirtualBox 5.0.10 and Packer 0.8.6; but I've also encountered the same issue on OS X 10.10.5 and Windows 7. Here's the Packer logs from the failure:
```
2015/12/24 14:04:59 packer-builder-virtualbox-ovf: 2015/12/24 14:04:59 [INFO] Attempting SSH connection...
2015/12/24 14:04:59 packer-builder-virtualbox-ovf: 2015/12/24 14:04:59 reconnecting to TCP connection for SSH
2015/12/24 14:04:59 packer-builder-virtualbox-ovf: 2015/12/24 14:04:59 handshaking with SSH
2015/12/24 14:04:59 packer-builder-virtualbox-ovf: 2015/12/24 14:04:59 handshake error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2015/12/24 14:04:59 packer-builder-virtualbox-ovf: 2015/12/24 14:04:59 [DEBUG] SSH handshake err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2015/12/24 14:04:59 packer-builder-virtualbox-ovf: 2015/12/24 14:04:59 [DEBUG] Detected authentication error. Increasing handshake attempts.
2015/12/24 14:04:59 ui error: ==> virtualbox-ovf: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
==> virtualbox-ovf: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
2015/12/24 14:05:00 packer-builder-virtualbox-ovf: 2015/12/24 14:05:00 Executing VBoxManage: []string{"controlvm", "packer-virtualbox-ovf-1450983755", "power off"}
```
I've attached a zip containing the CentOS KS, Packer templates and a throwaway key for reproducing the issue. The base.json template will create a CentOS 7 image and configure it for PK authentication. Once the base VM is built if you attempt to run ovf.json it will fail with the above error.

I've tried various SSHD configuration settings, but can not get publickey to show up in the list of authentication methods. Yet, if I manually import the base VM and map it's port on the host I can manually authenticate using the private key and OpenSSH, as well as run the null.json packer template without issue.

[packer-issue.zip](https://github.com/mitchellh/packer/files/75658/packer-issue.zip)

Also, here's a link to the original [thread](https://groups.google.com/forum/#!topic/packer-tool/cnb9EGh4hg8) about the issue in the Packer google group.

**Comment by rickard-von-essen** [comment] 2016-01-01 21:07
This is most likely a duplicate of #2428

**Comment by rmbrad** [comment] 2016-01-03 20:32
@rickard-von-essen Yeah it is, everything works using `ssh_key_path` in the template. Thanks.

**Comment by rickard-von-essen** [comment] 2016-01-04 12:19
Closing as duplicate of #2428

**Closed by rickard-von-essen** 2016-01-04 12:19 UTC
Labels: duplicate, waiting-reply
