### ISSUE TITLE
Packer crashed while creating vagrant box

### ISSUE THREAD

**Issue by andrewtarry** [mitchellh/packer#3014] opened 2015-12-21 08:48 UTC
The crash occurred when creating the a new vagrant box with `packer build`

[crash.log.txt](https://github.com/mitchellh/packer/files/68241/crash.log.txt)

**Comment by cbednarski** [comment] 2015-12-22 23:52
Thanks for the report. `malloc deadlock` is a weird error. This may be related to a bug fixed in go 1.5.2 so I'm assuming this will be resolved when we build the next release.

Can you reproduce this consistently? If so can you share some additional information, such as what template is used to repro?

**Comment by mwhooker** [comment] 2017-02-03 08:23
A lot has changed since this issue was reported, so going to close for now. If you continue to run into this, please make sure you try with the latest version of packer, and, if possible, a json file which reproduces this issue.

**Closed by mwhooker** 2017-02-03 08:23 UTC
Labels: core, crash
