### ISSUE TITLE
Failed to get certificate URL

### ISSUE THREAD

**Issue by nikhilmutkekar** [mitchellh/packer#3866] opened 2016-09-07 15:42 UTC
Getting the certificate's URL ...
  -> Key Vault Name        : 'pkrkv****l8x9'
  -> Key Vault Secret Name : 'packerKeyVaultSecret'
  ...failed to get certificate URL, retry(0)
  ...failed to get certificate URL, retry(1)
  ...failed to get certificate URL, retry(2)
  ...failed to get certificate URL, retry(3)
  ...failed to get certificate URL, retry(4)

 Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal number into Go value of type string'.

Receiving this error for Azure ARM based packer build for Windows-2012-R2 SKU. Help !

**Comment by boumenot** [comment] 2016-09-07 17:47
Sorry about this.  This issue is fixed in master, but a release with the fix has not been made.  You have three solutions to the problem.

1. You can rebuild master, and pick up the fix.
1. I made a private build available for another user, see #3766 for details. 
1. Wait for next official Packer release.  I do not have an ETA on when that will be.

Dupe of #3721

**Closed by boumenot** 2016-09-07 17:47 UTC
Labels: builder/azure, duplicate

**Comment by avishnyakov** [comment] 2016-11-24 05:22
Having the same issue, testing the private build available in #3766

**Comment by boumenot** [comment] 2016-11-24 05:29
The latest release of Packer, 0.12, has all of the Azure fixes and features (including this one).  Please retry with this build.  If you still have issues open a new issue with the [debug log](https://www.packer.io/docs/other/debugging.html) and I'll investigate.

**Comment by avishnyakov** [comment] 2016-11-24 05:37
Right, thanks for getting back.

Tested on 0.11/0.12, same outcome. Opening up a new issue.

**Comment by avishnyakov** [comment] 2016-11-24 05:49
Done, here we go:
failed to get certificate URL, retry(0) issue with winrm #4201
