### ISSUE TITLE
Azure-arm builder : runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mani0070** [mitchellh/packer#3766] opened 2016-07-30 09:37 UTC
runtime error: invalid memory address or nil pointer dereference

Packer v0.10.1
Windows 10
Debug log - https://gist.github.com/mani0070/fbffa4ba7e77aa5c81a65667bb5c278a

my template : https://gist.github.com/mani0070/41e8c3b83b2d2a5af02cdeb5097ed9dd

**Comment by rickard-von-essen** [comment] 2016-07-30 09:50
Crashes on:
```
2016/07/30 10:27:02 packer.exe: panic: runtime error: invalid memory address or nil pointer dereference
2016/07/30 10:27:02 packer.exe: [signal 0xc0000005 code=0x1 addr=0x0 pc=0x64397e]
2016/07/30 10:27:02 packer.exe: 
2016/07/30 10:27:02 packer.exe: goroutine 15 [running]:
2016/07/30 10:27:02 packer.exe: panic(0x12b6e20, 0xc082002080)
2016/07/30 10:27:02 packer.exe: 	/usr/local/go/src/runtime/panic.go:481 +0x3f4
2016/07/30 10:27:02 packer.exe: github.com/mitchellh/packer/builder/azure/arm.(*StepGetCertificate).getCertificateUrl(0xc082505b00, 0xc0822f2860, 0xf, 0x1646f20, 0x14, 0x0, 0x0, 0x0, 0x0)
2016/07/30 10:27:02 packer.exe: 	/Users/cbednarski/go/src/github.com/mitchellh/packer/builder/azure/arm/step_get_certificate.go:42 +0xee
```

**Comment by mani0070** [comment] 2016-07-30 09:53
I have tried running them few times and it crashes with same error.

**Comment by rickard-von-essen** [comment] 2016-07-30 10:34
Please provide the full debug log.

**Comment by mani0070** [comment] 2016-07-30 11:52
updated the full log now

**Comment by boumenot** [comment] 2016-07-30 17:32
Thanks for reporting the issue.  This appears to be a dupe of #3581.  Azure is responding with 403 when it tries to access KeyVault.  This generally indicates that the wrong ObjectID was set in the template.  Please review the value.

```batch
azure ad sp show --spn <client_id>
```

There may be another issue once you address this one with 0.10.1 concerning KeyVault and certificate.  The tip of master has the fix, but it has not yet been released.

Let me know if this corrects the crash, and if so, we can strategize about another fix.

**Comment by mani0070** [comment] 2016-07-30 18:39
updated the object id using Get-AzureRmADApplication -ApplicationId ******************
new logs are here : https://gist.github.com/mani0070/fbffa4ba7e77aa5c81a65667bb5c278a

**Comment by boumenot** [comment] 2016-07-31 05:13
The error is exactly the same, so I still think you are not providing the correct ObjectID.

**Comment by mani0070** [comment] 2016-07-31 06:19
I have updated the objectID and now the error is different

[error01.txt](https://github.com/mitchellh/packer/files/392285/error01.txt)

**Comment by boumenot** [comment] 2016-07-31 16:34
This is progress, however unfortunate it is.  This is the second issue that I spoke of previously.  This was address in PR #3721, but that code has not been released.  If you're able you can build the code yourself, or I can send you a build of tip.

**Comment by boumenot** [comment] 2016-08-01 04:15
Here you [go][1].

[1]: https://1drv.ms/f/s!AmGtc0f52KBYgcpny1TFN9Pf-UzW9A

**Comment by mani0070** [comment] 2016-08-01 12:49
it worked this time . Excited :-)

**Comment by boumenot** [comment] 2016-08-02 01:04
w00t!

**Closed by boumenot** 2016-08-02 01:04 UTC
Labels: builder/azure, crash
