### ISSUE TITLE
possible bug in qemu builder with qemu < 2.0 and default -drive args

### ISSUE THREAD

**Issue by hiciu** [mitchellh/packer#3192] opened 2016-02-13 00:26 UTC
Hello,

While trying to understand #2445 I've found this:

https://github.com/mitchellh/packer/blob/e920ad25bf35a8e769038cb219e4883a26001e13/builder/qemu/step_run.go#L98-L116

```go

	defaultArgs := make(map[string]interface{})
	var driveArgs []string

	if qemuMajor >= 2 {
		driveArgs = append(driveArgs, ...)
	} else {
		defaultArgs["-drive"] = fmt.Sprintf("file=%s,if=%s,cache=%s", imgPath, config.DiskInterface, config.DiskCache)
	}

	defaultArgs["-device"] = deviceArgs
	defaultArgs["-drive"] = driveArgs
```

If I understand correctly if `qemuMajor < 2` then `defaultArgs["-drive"]` will be empty. Possible fix could involve changing this:

```
		defaultArgs["-drive"] = fmt.Sprintf("file=%s,if=%s,cache=%s", imgPath, config.DiskInterface, config.DiskCache)
```

to something like:

```
		driveArgs = append(driveArgs, fmt.Sprintf("file=%s,if=%s,cache=%s", imgPath, config.DiskInterface, config.DiskCache))
```

I'm willing to prepare PR with bugfix if this is indeed a bug :).

**Comment by dkruger** [comment] 2016-02-25 19:20
I can confirm running packer v0.9.0 and QEMU version 1.0.1 on Fedora Core 17, that qemu-system-x86_64 will indeed have an empty "-drive" parameter.

Using template from the documentation:
```JSON
{
  "builders":
  [
    {
      "type": "qemu",
      "iso_url": "http://mirror.symnds.com/distributions/CentOS-vault/6.5/isos/x86_64/CentOS-6.5-x86_64-minimal.iso",
      "iso_checksum": "0d9dc37b5dd4befa1c440d2174e88a87",
      "iso_checksum_type": "md5",
      "output_directory": "output_centos_tdhtest",
      "shutdown_command": "shutdown -P now",
      "disk_size": 5000,
      "format": "qcow2",
      "headless": false,
      "accelerator": "kvm",
      "http_directory": "httpdir",
      "http_port_min": 10082,
      "http_port_max": 10089,
      "ssh_host_port_min": 2222,
      "ssh_host_port_max": 2229,
      "ssh_username": "root",
      "ssh_password": "s0m3password",
      "ssh_port": 22,
      "ssh_wait_timeout": "30s",
      "vm_name": "tdhtest",
      "net_device": "virtio-net",
      "disk_interface": "virtio",
      "boot_wait": "5s",
      "boot_command":
      [
        "<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/centos6-ks.cfg<enter><wait>"
      ]
    }
  ]
}
```
Running `PACKER_LOG=yes packer build centos6_example.json`

Results in the attached output: [centos6_example_log.txt](https://github.com/mitchellh/packer/files/147147/centos6_example_log.txt)

With the lines of note being:

> 2016/02/25 14:14:05 packer.io: 2016/02/25 14:14:05 Executing /usr/bin/qemu-system-x86_64: []string{"-vnc", "0.0.0.0:31", "-cdrom", "/home/kru52025/devops-packer-templates/packer_cache/ad281eafcdbc45c8b26f10bcbed5474d6bd035e847a6a6d6cd08e1b920b6ba4e.iso", "-machine", "type=pc,accel=kvm", "-device", "virtio-net,netdev=user.0", "-m", "512M", "-boot", "once=d", "-name", "tdhtest", "-netdev", "user,id=user.0,hostfwd=tcp::2226-:22", "-drive"}
> 2016/02/25 14:14:05 packer.io: 2016/02/25 14:14:05 Started Qemu. Pid: 27544
> 2016/02/25 14:14:05 packer.io: 2016/02/25 14:14:05 Qemu stderr: qemu-system-x86_64: -drive: requires an argument

**Comment by rickard-von-essen** [comment] 2016-02-26 10:04
@vtolstov Can you have a look at this? What do you think?

**Comment by vtolstov** [comment] 2016-02-26 14:06
please check my pr

**Comment by vtolstov** [comment] 2016-02-26 14:08
@hiciu yes, this is a bug. thanks!

**Comment by rickard-von-essen** [comment] 2016-02-26 19:24
@hiciu and/or @dkruger It would be great if anyone could verify that PR #3272 fixes your problems.

@vtolstov Thanks for your quick response!

**Comment by cbednarski** [comment] 2016-02-29 21:53
Hey folks, sorry about the mixup here. I noticed after merging that the fix is invalid since the `driveArgs` type is a list rather than a map and can't be accessed by key the same way `defaultArgs` is, so we'll need to do something slightly different here.

**Comment by vtolstov** [comment] 2016-03-01 21:17
sorry for misteke, i'm create new pr. please check it.

**Closed** 2016-03-01 21:22 UTC
Labels: bug, builder/qemu
