### ISSUE TITLE
Crash when adding atlas upload

### ISSUE THREAD

**Issue by gamename** [mitchellh/packer#1937] opened 2015-02-20 19:01 UTC
```
1424457934,,ui,say,==> virtualbox-ovf: Running post-processor: atlas
1424457935,,ui,message,    virtualbox-ovf (atlas): Creating artifact: nextgxdx/tns-centos-70
1424457936,,ui,error,Build 'virtualbox-ovf' errored: 1 error(s) occurred:\n\n* Post-processor failed: unexpected EOF
1424457936,,error-count,1
1424457936,,ui,error,\n==> Some builds didn't complete successfully and had errors:
1424457936,virtualbox-ovf,error,1 error(s) occurred:\n\n* Post-processor failed: unexpected EOF
1424457936,,ui,error,--> virtualbox-ovf: 1 error(s) occurred:\n\n* Post-processor failed: unexpected EOF
1424457936,,ui,say,\n==> Builds finished but no artifacts were created.

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Packer crashed! This is always indicative of a bug within Packer.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Packer[1] so that we can fix this.

[1]: https://github.com/mitchellh/packer/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by gamename** [comment] 2015-02-20 19:04
json file: https://gist.github.com/gamename/8698b9834f7cfb3be749

crash log: https://gist.github.com/gamename/83564722cca40c4a0536

**Comment by sethvargo** [comment] 2015-02-25 00:47
Duplicate of https://github.com/mitchellh/packer/issues/1815. Thank you for reporting though!

**Closed by sethvargo** 2015-02-25 00:47 UTC
