### ISSUE TITLE
amazon-ebs fails with unclear error message if workstation time is out of sync

### ISSUE THREAD

**Issue by charlieda** [mitchellh/packer#3140] opened 2016-02-01 15:03 UTC
If the localtime of the machine running packer is more than 5 minutes different from the time according to AWS, packer fails with the following error, even in debug mode:

```
==> amazon-ebs: Error querying AMI: AuthFailure: AWS was not able to validate the provided access credentials
==> amazon-ebs:     status code: 401, request id: []
```

It would be nice to have a more user friendly error message, as AWS does return a `InvalidSecurity.RequestHasExpired` error.

**Comment by mwhooker** [comment] 2017-02-06 21:59
hmm, was only able to get a `AuthFailure` code, not requesthasexpired.

Marking as a dupe of #2611

The solution for now is a documentation update. Possibly in the future we could point to the docs if we hit an error like that, but it's not something we're targeting for 1.0, so going to close this

**Closed by mwhooker** 2017-02-06 21:59 UTC
Labels: builder/amazon, enhancement
