### ISSUE TITLE
Connection to script provisioner seems to close early

### ISSUE THREAD

**Issue by psander-scalearc** [mitchellh/packer#2551] opened 2015-08-03 23:49 UTC
When running a lengthy script provisioner, the ssh connection from Packer seems to close early.  After the command is sent through the pipe, some of the output from the provisioner do not appear in the output of Packer.  This seems to happen only for the last script provisioner if there are more than one.  I've seen this in combination with both AWS and VirtualBox builders.

The symptom is similar to a client library using a close(2) system call after its last write, rather than using shutdown(2) and then reading until an EOF appears on the return stream and then closing the socket.

**Comment by cbednarski** [comment] 2015-08-03 23:53
Thanks for the report. I think this is a duplicate of https://github.com/mitchellh/packer/issues/2391, and I think the reasons this happens are similar to what you described, but using go channels internal to packer rather than unix pipes.

I am going to close this as a dupe but please re-open if your issue is different.

**Closed by cbednarski** 2015-08-03 23:53 UTC
Labels: bug, core, duplicate

**Comment by psander-scalearc** [comment] 2015-08-03 23:57
Sounds like an escalation to the keepers of the Go runtime environment is in order.
