### ISSUE TITLE
Packer jumps to next provisioner during SSH failiure

### ISSUE THREAD

**Issue by m1keil** [mitchellh/packer#2216] opened 2015-06-11 21:11 UTC
I'm re-posting this issue since #2004 seems to bit a bit different case from mine.

We stumbled across this issue during our nightly image build. It looks like Packer is skipping to next provision step during short phases of SSH timeout / disconnections.
I was able to reproduce this issue locally with Virtualbox. To simulate SSH disconnection it's possible to just disconnect the Wifi or pull the ethernet plug (works on OS X 10.10).

Below is a config for reproducing this:

```
{
  "builders": [
    {
      "name": "virtualbox",
      "type": "virtualbox-ovf",
      "source_path": "</path/to/ovf>",
      "vm_name": "packer_demo",
      "ssh_username": "vagrant",
      "ssh_key_path": "<path/to/pk>",
      "ssh_wait_timeout": "2m",
      "shutdown_command": "sudo -S shutdown -P now",
      "headless": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": "sleep 3600"
    },
    {
      "type": "shell",
      "inline": "echo hello world!"
    }
 ]
}
```

And here's the output:

```
packer > bin/packer build /tmp/packerfile.json -machine-readable
1434055239,,ui,say,virtualbox output will be in this color.
1434055239,,ui,say,


1434055239,,ui,say,==> virtualbox: Downloading or copying Guest additions
1434055239,,ui,message,    virtualbox: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
1434055239,,ui,say,==> virtualbox: Importing VM: /Users/michael/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-trusty64/20150427.0.0/virtualbox/box.ovf
1434055245,,ui,say,==> virtualbox: Creating forwarded port mapping for SSH (host port 3026)
1434055245,,ui,say,==> virtualbox: Starting the virtual machine...
1434055245,,ui,message,    virtualbox: WARNING: The VM will be started in headless mode%!(PACKER_COMMA) as configured.\n    virtualbox: In headless mode%!(PACKER_COMMA) errors during the boot sequence or OS setup\n    virtualbox: won't be easily visible. Use at your own discretion.
1434055245,,ui,say,==> virtualbox: Waiting 10s for boot...
1434055255,,ui,say,==> virtualbox: Typing the boot command...
1434055255,,ui,say,==> virtualbox: Waiting for SSH to become available...
1434055261,,ui,say,==> virtualbox: Connected to SSH!
1434055261,,ui,say,==> virtualbox: Uploading VirtualBox version info (4.3.28)
1434055263,,ui,say,==> virtualbox: Uploading VirtualBox guest additions ISO...
1434055264,,ui,say,==> virtualbox: Provisioning with shell script: /var/folders/w6/l2lpj_k97yg_g887bpyyyqkc0000gn/T/packer-shell730614948
<<<------------------------SSH disconnection here----------------------------------->>>
1434055274,,ui,say,==> virtualbox: Provisioning with shell script: /var/folders/w6/l2lpj_k97yg_g887bpyyyqkc0000gn/T/packer-shell497869510
1434055281,,ui,message,    virtualbox: hello world!
1434055281,,ui,say,==> virtualbox: Gracefully halting virtual machine...
1434055284,,ui,say,==> virtualbox: Preparing to export machine...
1434055284,,ui,message,    virtualbox: Deleting forwarded port mapping for SSH (host port 3026)
1434055284,,ui,say,==> virtualbox: Exporting virtual machine...
1434055284,,ui,message,    virtualbox: Executing: export packer_demo --output output-virtualbox/packer_demo.ovf
1434055328,,ui,say,==> virtualbox: Unregistering and deleting imported VM...
1434055328,,ui,say,Build 'virtualbox' finished.
1434055328,,ui,say,\n==> Builds finished. The artifacts of successful builds are:
1434055328,virtualbox,artifact-count,1
1434055328,virtualbox,artifact,0,builder-id,mitchellh.virtualbox
1434055328,virtualbox,artifact,0,id,VM
1434055328,virtualbox,artifact,0,string,VM files in directory: output-virtualbox
1434055328,virtualbox,artifact,0,files-count,2
1434055328,virtualbox,artifact,0,file,0,output-virtualbox/packer_demo-disk1.vmdk
1434055328,virtualbox,artifact,0,file,1,output-virtualbox/packer_demo.ovf
1434055328,virtualbox,artifact,0,end
1434055328,,ui,say,--> virtualbox: VM files in directory: output-virtualbox
```

Here is a `lsof` output I ran in parallel during the process, which shows that actual socket disconnection happened and new connection established instead:

```
(1) > lsof -i -nP | grep packer
packer-bu 74985 michael    3u  IPv4 0x9caca6b354ef56d7      0t0  TCP 127.0.0.1:61401->127.0.0.1:3026 (ESTABLISHED)
(2) > lsof -i -nP | grep packer
(3) > lsof -i -nP | grep packer
packer-bu 74985 michael    3u  IPv4 0x9caca6b34ad5e537      0t0  TCP 127.0.0.1:61411->127.0.0.1:3026 (ESTABLISHED)
```

(1) First provision script running over SSH
(2) Offline phase until reconnection
(3) Second provision script running over new SSH connection

This was tested with 0.7.5 and latest from version from master branch.

**Comment by mitchellh** [comment] 2015-06-11 21:18
This will be fixed with #2210! Please check that out.

**Comment by m1keil** [comment] 2015-06-11 21:30
did:
1. git pull 
2. make updatedeps
3. make (test fail?)
4. make dev
5. ran the whole process

getting same result.

**Comment by mitchellh** [comment] 2015-06-11 21:32
I ran your same config locally to verify the fix so I'm going to have to say its probably a build environment issue... :-\ Make sure the `packer version` has the right SHA in it?

**Comment by m1keil** [comment] 2015-06-11 21:36
```
/Users/michael/go/src/github.com/mitchellh/packer
 (master) packer > git branch
* master
 (master) packer > bin/packer version
Packer v0.7.5
```

Am I doing something wrong? I'm not yet familiar with Go build tools and I just followed the steps in the readme.

**Comment by mitchellh** [comment] 2015-06-11 21:39
Ah darn, I forgot to update the version. It doesn't affect anything but it results in you not being able to see the Git SHA in that command. I just pushed that up.

**Comment by mitchellh** [comment] 2015-06-11 21:40
OH! I just realized this issue is completely different from the PR. Sorry.

This is unfortunately "working as intended." On the remote side we actually can't distinguish between an "SSH failure" and a "server is rebooting." And we prefer the latter to allow for shell scripts to perform reboots. Perhaps one option is to have an option that says: "don't allow SSH errors" or the inverse of "expect SSH errors" ?

**Comment by m1keil** [comment] 2015-06-11 21:44
But wouldn't a reboot timeout and the whole process will fail anyway?

**Comment by mitchellh** [comment] 2015-06-11 21:46
Right, so we treat that as a non-failure scenario, but to the client it just always looks like an abrupt connection close. I think we should just add a setting to make this easier.

**Comment by m1keil** [comment] 2015-06-11 21:56
I guess such setting would be better then nothing :-)
Can this setting be on the provision config level and not global one?
So I could do something like:
```
  "provisioners": [
    {
      "type": "shell",
      "file": "do_work.sh"
    },
    {
      "type": "shell",
      "allow_ssh_disconnection": true,
      "inline": "reboot"
    },
    "type": "shell",
      "file": "do_some_more_work.sh"
    }
```

**Comment by mitchellh** [comment] 2015-06-11 21:57
Yep!

**Comment by m1keil** [comment] 2015-06-11 21:57
sweet! thanks :+1:

**Comment by m1keil** [comment] 2015-06-11 22:07
Oh, so something still bugged me about your comment ("working as intended.").
Here's a a race case for this:

```
{
  "builders": [
    {
      "name": "virtualbox",
      "type": "virtualbox-ovf",
      "source_path": "/Users/michael/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-trusty64/20150427.0.0/virtualbox/box.ovf",
      "vm_name": "packer_demo",
      "ssh_username": "vagrant",
      "ssh_key_path": "/Users/michael/.vagrant.d/insecure_private_key",
      "ssh_wait_timeout": "2m",
      "shutdown_command": "sudo -S shutdown -P now",
      "headless": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": "sleep 3600"
    }
 ]
}
```

If I repeat the process, now I hit different issue:
```
packer > bin/packer build /tmp/packerfile.json -machine-readable
1434060218,,ui,say,virtualbox output will be in this color.
1434060218,,ui,say,
1434060219,,ui,say,==> virtualbox: Downloading or copying Guest additions
1434060219,,ui,message,    virtualbox: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
1434060219,,ui,say,==> virtualbox: Importing VM: /Users/michael/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-trusty64/20150427.0.0/virtualbox/box.ovf
1434060225,,ui,say,==> virtualbox: Creating forwarded port mapping for SSH (host port 3178)
1434060225,,ui,say,==> virtualbox: Starting the virtual machine...
1434060225,,ui,message,    virtualbox: WARNING: The VM will be started in headless mode%!(PACKER_COMMA) as configured.\n    virtualbox: In headless mode%!(PACKER_COMMA) errors during the boot sequence or OS setup\n    virtualbox: won't be easily visible. Use at your own discretion.
1434060225,,ui,say,==> virtualbox: Waiting 10s for boot...
1434060235,,ui,say,==> virtualbox: Typing the boot command...
1434060235,,ui,say,==> virtualbox: Waiting for SSH to become available...
1434060240,,ui,say,==> virtualbox: Connected to SSH!
1434060240,,ui,say,==> virtualbox: Uploading VirtualBox version info (4.3.28)
1434060243,,ui,say,==> virtualbox: Uploading VirtualBox guest additions ISO...
1434060244,,ui,say,==> virtualbox: Provisioning with shell script: /var/folders/w6/l2lpj_k97yg_g887bpyyyqkc0000gn/T/packer-shell726259216
1434060247,,ui,say,==> virtualbox: Gracefully halting virtual machine...
1434060247,,ui,error,==> virtualbox: Failed to send shutdown command: dial tcp 127.0.0.1:3178: connection refused
1434060248,,ui,say,==> virtualbox: Unregistering and deleting imported VM...
1434060248,,ui,say,==> virtualbox: Deleting output directory...
1434060248,,ui,error,Build 'virtualbox' errored: Failed to send shutdown command: dial tcp 127.0.0.1:3178: connection refused
1434060248,,error-count,1
1434060248,,ui,error,\n==> Some builds didn't complete successfully and had errors:
1434060248,virtualbox,error,Failed to send shutdown command: dial tcp 127.0.0.1:3178: connection refused
1434060248,,ui,error,--> virtualbox: Failed to send shutdown command: dial tcp 127.0.0.1:3178: connection refused
1434060248,,ui,say,\n==> Builds finished but no artifacts were created.
```

It looks like the shutdown got no ssh retry?

**Comment by mitchellh** [comment] 2015-06-11 22:10
It doesn't, no. If you shut down SSH, you have to add another SSH script that waits for it to come back.

**Comment by m1keil** [comment] 2015-06-11 22:24
So there's some kind of difference in behavior here that user might feel confused about:
1. If there's only a single provision script, connection drops will always fail the build (I assume that's what most people are familiar with)
2. If there's multiple provision scripts, connection drops will possibly be a successful build

Isn't it better to just make shutdown_command as a special kind of shell provisioner that has the same SSH retry mechanism to bypass the requirement for dummy script in case reboot + shutdown is needed? 

Obviously a bit of off-topic here.

**Comment by pecigonzalo** [comment] 2015-06-24 04:30
This will also be useful for the winrm communicator and provisioners...

**Comment by mstrache** [comment] 2015-07-29 00:04
I'm not sure but think I have the same issue. I have a jenkins building multiple VirtualBox machines at the same time. From time to time VirtualBox seems to crash during export
```
01:31:20 ==> default: Error exporting virtual machine: VBoxManage error: 0%...10%...20%...
01:31:20 ==> default: Progress object failure: NS_ERROR_ABORT
01:31:21 ==> default: Unregistering and deleting virtual machine...
01:31:21 ==> default: Deleting output directory...
```
triggering some chain reaction that causes all parallel build boxes to fail too
```
01:31:20 ==> default: Gracefully halting virtual machine...
01:31:20 ==> default: Failed to send shutdown command: dial tcp 127.0.0.1:2952: connection refused
01:31:21 ==> default: Unregistering and deleting virtual machine...
01:31:21 ==> default: Deleting output directory...
```
```
01:31:21 ==> default: Gracefully halting virtual machine...
01:31:21 ==> default: Failed to send shutdown command: dial tcp 127.0.0.1:3625: connection refused
01:31:21 ==> default: Unregistering and deleting virtual machine...
01:31:21 ==> default: Deleting output directory...
```
```
01:31:20 ==> default: Gracefully halting virtual machine...
01:31:20 ==> default: Failed to send shutdown command: dial tcp 127.0.0.1:4274: connection refused
01:31:21 ==> default: Unregistering and deleting virtual machine...
01:31:21 ==> default: Deleting output directory...
```
Only one box survived: an OpenSuse VM that was so damn slow, that it still was waiting for SSH to become available

**Comment by simonguest** [comment] 2016-03-10 04:37
Any update on this? I'm having the same issue - random SSH disconnections (which seem pretty common) are forcing packer to skip on to the next script/provisioner. Would be great to have an option in the provisioner to prevent this from happening.

**Comment by mwhooker** [comment] 2017-02-03 08:02
We ended up implementing this as an "expect_disconnect" flag in the shell provisioner. Set this to `false` to fail build if you get a disconnect. We decided we couldn't make it default to false, since it would break so many builds

**Closed by mwhooker** 2017-02-03 08:02 UTC
Labels: core, enhancement
