### ISSUE TITLE
vmware-iso: Failed to build image using distributed switch (vSphere)

### ISSUE THREAD

**Issue by amitinfo2k** [mitchellh/packer#2715] opened 2015-09-07 07:01 UTC
Hi  All,

I am building a RHEL 7.1 image using the vmware-iso builder. 
ESXi version 5.5.  Here for network configuration ( VLAN ) i am passing the following vmxdata.

---

```
   "ethernet0.present": "TRUE",
    "ethernet0.startConnected": "TRUE",
    "ethernet0.virtualDev": "vmxnet3",
    "ethernet0.dvs.switchId": "9f ba 07 50 39 f7 34 79-b6 2e 07 1a 80 aa 82 46",
    "ethernet0.dvs.portgroupId": "dvportgroup-48",
    "ethernet0.dvs.portId": "1004",
    "ethernet0.addressType": "generated",
    "ethernet0.generatedAddressOffset": "0",
    "ethernet0.wakeOnPcktRcv": "FALSE"
```

---

Here, vm is getting botted but network is not in connected started. I have tried Editing VM setting on vmware vsphere where i see the nic is not connected. as a workaround i need to delete this Nic and re-add it manually from vcenter UI with the same configuration then it works.
I tried to compare the VMX data for the vm where i have manually configured n/w through vmware vcenter and found that i need to pass the connection id and port id as follows:

---

```
    "ethernet0.dvs.connectionId": "2040775856",
    "ethernet0.dvs.portId": "1004",
```

---

This information i need to take from the vmx file of a VM which was manually created on vmware vecenter.

Can anyone help me to figure out the exact the vmx data i need to pass which can remove this manual intervention of removing and re-adding the network.

Thanks,
Amit Wankhede

**Comment by Ancillas** [comment] 2015-11-11 20:51
I'm running into this issue as well, and haven't yet found a solution.  The 'dvs' settings may not be supported when deploying from a template.

http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1037675

**Comment by Ancillas** [comment] 2015-11-20 01:16
Here's what I've found out, for what it's worth.

Using a distributed switch and a port group that uses static binding is what causes the problem.  These kinds of ports can only be issued by vCenter.  When the VM is started on the ESX host, a network port can't be assigned, so the network never works.

If you run Packer in debug mode, just before the SSH step, you can power down the VM, delete the NIC.  Add another NIC, and re-start the VM through vCenter.  This will give the VM a network connection.  Unfortunately, the SSH step still fails.

Packer uses an ESX command to get a list of VMs on the host.  It send searches for the VM with a name matching the Packer VM, and gets the ID of the VM

After this, Packer then uses that VM ID to get a list of ports associated with the VM.  Because the port is a dvs port assigned by vCenter, the command fails (since the ESX host knows nothing about these ports).

A temporary solution would be to put a config flag in to indicate statically bound ports are used, and then use govmomi to query vcenter directly.  Of course, this would really just be a stop-gap.  The best solution would be a builder that uses the vCenter API.

**Comment by amitinfo2k** [comment] 2015-11-30 09:10
I am trying out the stop-gap solution to change the builder use the govami where i am trying to delete the existing network and recreating it using 
-----------------------------------------------------------------------------------------------------------------
govc vm.network.add -k -vm=<VM Name> -net=<VLAN Name> -dc=<Data Center> -net.adapter=vmxnet3
-----------------------------------------------------------------------------------------------------------------
but, here it is unable to find that VM even though i can see the same VM on vcenter UI. but, govc is not able to list it. I am not sure which api i can use to delete existing network and recreate it using vcenter api.

**Comment by Ancillas** [comment] 2015-12-09 02:27
I was experimenting with govc the other day, and my experience was that govc was not listing VMs within clusters.  I haven't found a solution for that yet, but I'll share if I do.

**Comment by amitinfo2k** [comment] 2015-12-09 12:30
yes @Ancillas  I also tried using govc it's not able to list the vm as it has network dependency  pyvmomi is able to list it but didn't explored it please share if you find a solution.

**Comment by amitinfo2k** [comment] 2015-12-21 13:26
working with stop gap solution using govomi (found pretty confusing to work with)

**Comment by Ancillas** [comment] 2016-01-06 20:24
Would you mind throwing up a quick gist of your code/config/process?  It doesn't have to be pretty.

**Comment by amitinfo2k** [comment] 2016-01-25 07:43
@Ancillas  sorry for the delay here's  https://github.com/amitinfo2k/packerfixdvsnw This is stop gap fix :)

**Comment by Ancillas** [comment] 2016-01-25 15:21
This looks very close to what I was currently building, thanks!  I was struggling with govmomi because I haven't worked much with Go.

I'll make the changes to the vmware-iso builder in my branch and build it with this step included and make sure it works.  I'm testing with vCenter 5.5 for what it's worth.

**Comment by Ancillas** [comment] 2016-02-16 08:22
I built this and got it to run, but for me Packer crashes when it tries to add the new NIC.  I haven't solved that yet, but am working on it as time allows.

**Comment by michaeltlombardi** [comment] 2016-08-22 19:48
@Ancillas, @amitinfo2k Any movement on this since early in the year? Just ran into this problem myself for a Windows build.

**Comment by amitinfo2k** [comment] 2016-08-23 06:43
@michaeltlombardi  Mine changes available at  https://github.com/amitinfo2k/packerfixdvsnw 
tested against packer v.0.8.*

**Comment by Ancillas** [comment] 2016-08-23 06:46
I patched this work around in for a test build back in March, and on my
system it caused Packer to crash hard.

I wasn't granted any time to troubleshoot, and instead went the route of
using VMWare Workstation on a physical host.

**Comment by rickard-von-essen** [comment] 2016-08-23 07:12
If there is a fix for this please open a PR. I just recently merged some fixes related to ESXi, it can be worth testing a build from master.

**Comment by michaeltlombardi** [comment] 2016-08-23 12:17
I've been running the builds on my desktop via Workstation but it isn't really a longterm solution. Not being able to execute builds on an ESXi host with (fairly standard) network settings is a pretty hefty blow.

Still researching available workarounds in my environment but if this can be patched with @amitinfo2k 's fixes (and without @Ancillas's reported failure modes), even better.

**Comment by rickard-von-essen** [comment] 2016-08-23 13:07
_I urge anyone seeing this to supply the information requested in the issue template_:
- Packer version (`packer version`)
- Host platform (`uname -a` etc.)
- Debug log output from `PACKER_LOG=1 packer build template.json`.
  Please paste this in a [gist](https://gist.github.com).
- The _simplest example template and scripts_ needed to reproduce the bug.
  Include these in your [gist](https://gist.github.com).

Without that it's extremely hard to replicate a issue like this and we will be forced to close this issue as not reproducible.

**Comment by michaeltlombardi** [comment] 2016-08-23 15:04
@rickard-von-essen: Generating data for repro now, will update this post once it's in a gist.

**Comment by michaeltlombardi** [comment] 2016-08-23 15:50
@rickard-von-essen:  My repro can be found [here](https://gist.github.com/michaeltlombardi/7c5c73669889cd3dd1461121cf190eac).

**Comment by michaeltlombardi** [comment] 2016-08-29 15:32
@rickard-von-essen: Just pinging to clarify that the repro information requested has been supplied.

**Comment by rickard-von-essen** [comment] 2016-08-29 18:49
@michaeltlombardi Thank you for the detailed report.

Currently I have a hard time getting Windows building at all on my ESXi 6.0 host that I'm running in a nested VMware Fusion 7 on OS X. The turn around time to test with building Windows (especially with scarce resources as a laptop) is horrible so it's progressing slowly.

My initial comment after reading up a bit on this is that distributed virtual switches - _dvs_ are not supported when not accessing through the vSphere API. And since we are not using the API this is unsupported.

The long term fix would be that someone would write and contribute a vSphere builder.

**Comment by michaeltlombardi** [comment] 2016-08-29 22:11
> My initial comment after reading up a bit on this is that distributed virtual switches - dvs are not supported when not accessing through the vSphere API. And since we are not using the API this is unsupported.
>
> The long term fix would be that someone would write and contribute a vSphere builder.

Fair enough! I'm wholly unqualified to write the builder today but since we're looking at using Packer it seems to behoove me to learn enough to at least help whoever does start running with the vSphere builder. I'm a reasonably competent documentarian and breaker-of-things as is.

Thanks for taking the time to review the issue. To anyone actually capable of writing the builder, hit me up, I'd love to take some of the weight off your shoulders.

**Comment by ripun** [comment] 2016-10-05 11:02
Hi Team,
we still have this issue 

Please suggest if there is any fix available for this issue , its blocking us from using packer for vmware 

I am building a CentOS-7-x86_64   image using the vmware-iso builder. 

ESXi version 5.5. Here for network configuration ( VLAN ) i am passing the following vmxdata.

      "vmx_data": {
        "memsize": "8192",
        "numvcpus": "2",
        "ethernet0.virtualDev": "vmxnet3",
        "ethernet0.dvs.portId": "632",
        "ethernet0.dvs.switchId": "9f 76 00 50 50 fb c7 aa-61 49 02 2c cb 95 90 7e",
        "ethernet0.dvs.portgroupId": "dvportgroup-141",
        "ethernet0.dvs.connectionId": "2040775856",
        "ethernet0.present": "TRUE",
        "ethernet0.startConnected": "TRUE",
        "ethernet0.virtualDev": "vmxnet3",
        "ethernet0.addressType": "generated",
        "ethernet0.generatedAddressOffset": "0",
        "ethernet0.wakeOnPcktRcv": "FALSE",
        "ethernet0.networkName": "{{user `packer_remote_network`}}",
        "virtualHW.version": "8"

      },
      "vmx_data_post": {
        "ide1:0.startConnected": "FALSE",
        "ide1:0.clientDevice": "TRUE",
        "ide1:0.fileName": "emptyBackingString",
        "ethernet0.virtualDev": "vmxnet3"
      },
      "boot_command": [
        "<tab> net.ifnames=0 biosdevname=0 netmask=XXX.XXX.XXX.X gateway=XX.XXX.XX.X ip=XX.XXX.XX.XX ks=http://XX.XXX.XX.XX/centos/centos-7-kickstart.cfg<enter><wait>"
      ]
Here, vm is getting botted but network is not in connected started. I have tried Editing VM setting on vmware vsphere where i see the nic is not connected. as a workaround i need to delete this Nic and re-add it manually from vcenter UI with the same configuration then it works.

Please suggest if there is any fix available for this issue , its blocking us from using packer for vmware

**Comment by michaeltlombardi** [comment] 2016-10-05 13:11
What we did in our environment was add a non-distributed switch to a particular host in our lab for building images and this has worked perfectly well for us. Since you have to specify a single host in the first place for the ESXi builder (and open SSH, etc) this doesn't pose _too_ much additional work for us.

It's the simplest work-around until an actual vSphere builder comes along.

**Comment by ripun** [comment] 2016-10-06 09:25
Thanks a lot @michaeltlombardi we will check and update you

**Comment by eegilbert** [comment] 2016-11-18 21:57
Unfortunately this is still an issue in vSphere 6. I will post a gist of the debut out put, but I'm afraid that michaeltlombardi has the best solution for the moment.

**Comment by LIV2** [comment] 2016-11-28 01:38
I had the same issue but have no free uplinks to assign a standard switch to.
Instead, I found that you can create a new portgroup with the port binding policy set to Ephemeral and not specify the "ethernet0.dvs.portid" in vmx_data and it works.

**Comment by rickard-von-essen** [comment] 2016-11-28 05:56
@LIV2 thanks for the work around!

**Comment by eegilbert** [comment] 2016-12-06 12:54
@LIV2 Would you mind sharing a gist of your vmx_data?

**Comment by LIV2** [comment] 2016-12-06 20:30
@eegilbert Yep. You can find it here: https://gist.github.com/LIV2/9e3179bb1ee1981bdc4f20345bba4a09

I got the portgroup id and switchid by attaching a VM to the network and inspecting its vmx file.

**Comment by mwhooker** [comment] 2017-02-10 02:58
Hi all,

I don't want to minimize the impact of this issue, but I'm afraid this isn't something we can support without switching to using the vSphere API. I would be very happy to review any PRs that are created for this, but currently this is not something we're targeting for 1.0, so I'm going to close this. We rely on the community to support this builder, so the best way to get this added would be to implement it. Please see the [mailing list](https://groups.google.com/forum/#!topic/packer-tool/XLrSoETUjWk) for more details on 1.0.

I will create a ticket to use the vSphere API for after 1.0 and reference this ticket.

**Closed by mwhooker** 2017-02-10 02:58 UTC
Labels: builder/vmware-esxi, enhancement, need-more-info

**Comment by shyam2j** [comment] 2017-02-10 09:39
Hi,

 I am in a similar situation trying to build in ESX machine. But using a normal switch I'm a getting error ed out waiting for network. Under Network Adapters I cant see any VLAN getting assigned for VM getting created. Can you please help me with the parameters to mention the VLAN ? I tried mentioning ethernet1.dvs.portgroupId = "" eventhough there is no distributed switch.

Thanks
Shyam

**Comment by rismoney** [comment] 2017-06-17 00:21
@rickard-von-essen do you have a link to substantiate:

 > My initial comment after reading up a bit on this is that distributed virtual switches - dvs are not supported when not accessing through the vSphere API.

**Comment by rickard-von-essen** [comment] 2017-06-17 04:17
@rismoney see this comment for a explanation https://github.com/hashicorp/packer/issues/2715#issuecomment-158249368. The solution to this is most likely a new `vSphere` builder see #4526.

**Comment by markayre** [comment] 2017-07-26 21:07
Just to add how i worked around this:

- Created a new distributed port group within the dvs (with the same vlanid)
- Changed port binding to ephemeral
- Made sure the json had the below information:
`               "ethernet0.present": "true",
                "ethernet0.startConnected": "true",
                "ethernet0.addressType": "generated",
                "ethernet0.addressType":"vpx",
                "ethernet0.dvs.switchId": "50 16 05 eb 86 41 62 30-72 0f d7 d8 ff 21 09",
                "ethernet0.dvs.portgroupId": "dvportgroup-369"
`

**Comment by sn00p** [comment] 2017-07-30 07:06
Workaround works perfectly good for me, thanks.

**Comment by mananpatel** [comment] 2017-08-11 15:23
This work around isn't working for me. the job stuck at writing vmx file.. I am using packer v1.0.3

**Comment by sn00p** [comment] 2017-08-12 14:36
@mananpatel ^^ 
This workaround is applied next steps after when image is uploaded and VM is started. 
 so I guess not a case. 
Check your vmware installation

**Comment by markayre** [comment] 2017-08-12 20:01
@mananpatel This post has good instructions on how to get the vmware installation section completed. Good luck!
https://nickcharlton.net/posts/using-packer-esxi-6.html

**Comment by mananpatel** [comment] 2017-08-14 14:38
Thanks @markayre and @sn00p 
My packer job finished without any issue if I connect to VM Network which is connected to a portGroup, I would like to connect. It installs windows, installing updates, other tools etc.

The issue I am facing is I can't connect to the portgroup directly.
I am providing all info like switchId, portgroupId.. Also tried with and without providing port number with no luck.

**Comment by sn00p** [comment] 2017-08-15 06:34
@mananpatel Add ephemeral portgroup, check out switchID where this PG is attached and this portgroupID  : 
```
...
     "vmx_data": {
      "ethernet0.addressType": "vpx",
      "ethernet0.present": "true",
      "ethernet0.addresstype": "generated",
      "ethernet0.dvs.switchId": "50 02 1c ae da 31 27 ee-bd 98 3c 6e 7b 03 e5 de",
      "ethernet0.dvs.portgroupId": "dvportgroup-110",
...
}

```

**Comment by mananpatel** [comment] 2017-08-15 10:26
thanks @sn00p 
I am adding all of these in vmx_data
"vmx_data": {   
                        "ethernet0.present": "TRUE",
        		"ethernet0.startConnected": "TRUE",
	                "ethernet0.dvs.switchId": "fa 9e 3c 50 c5 0e c3 57-fd ca 66 4d c5 09 e8 6b",
                        "ethernet0.dvs.portgroupId": "dvportgroup-31",
            	        "ethernet0.dvs.portId": "763",
		        "ethernet0.addressType": "generated",
                        "ethernet0.generatedAddressOffset": "0",
                        "virtualHW.version" : "11"
		   }
I have tried various keys in and out with no luck to connect to portgropup directly. I have a PG configured with static binding and elastic allocation and that's why I am mentioning PortId which is free. So I guess that should not make much difference. 
Any further ideas/recommendation ?

Thanks

**Comment by mananpatel** [comment] 2017-08-15 11:03
I think i need to create a new PG with ephemeral binding as can't manage static from host level.

**Comment by sn00p** [comment] 2017-08-15 17:34
@mananpatel yeah it's the main idea of this workaround - to use ephemeral PG bound to your switch.
As you can't replace port number because it's read-only.
