### ISSUE TITLE
Packer chef-solo provisioner not finding node_name

### ISSUE THREAD

**Issue by ed-sullivation** [mitchellh/packer#1648] opened 2014-11-01 18:08 UTC
I am using chef version 11.16.4 and packer v 0.7.1

I am having trouble getting chef-solo to run the chef-solo provisioner after it installs chef-solo.

I am getting the following error: 

**ERROR: Unable to determine node name: configure node_name or configure the system's hostname and fqdn**

I poked around on the internet trying to figure what was happening, and this error seems rare since node_name is usually given a default value by the system, or is assigned in solo.rb, which seemed to me can not be overwritten directly in the packer config template.

I am using the following packer config

```json
{
    "variables": {
         "version": "",
         "base-image-version": ""
    },
    "builders":[{
         "type": "docker",
         "image": "centos:latest",
         "pull": true,
         "export_path": "zookeeper-base-{{user `version`}}.tar"
    }],
    "provisioners":[
         {
         "type": "chef-solo",
         "cookbook_paths": ["../chef-simple/cookbooks"],
         "install_command":"curl -L https://www.opscode.com/chef/install.sh | bash",
         "execute_command":"chef-solo --no-color -c {{.ConfigPath}} -j {{.JsonPath}}",
         "run_list":["recipe[zookeeper::install]"],
         "json":{"node_name":"zookeeper-box","env_name":"dev","ip":"10.10.10.10"},
         "prevent_sudo":true
    }],
    "post-processors": [{
         "type": "docker-import",
         "repository": "ed-sullivan/zookeeper-base",
         "tag": "{{user `version`}}"
    }]
}
```

**Comment by hd-deman** [comment] 2015-01-16 18:02
@jmassara whats inside `install_chef.sh`?

**Comment by defunct73** [comment] 2015-01-16 22:11
@hd-deman A basic bash script that installs a specific version of chef:

```bash
#!/usr/bin/env bash
set -ex

# Chef version to install.
CHEF_VERSION='11.16.4'

# Install Chef using the Opscode omni installer.
curl -sSL https://www.opscode.com/chef/install.sh | bash -s -- -v $CHEF_VERSION

# Verify installation.
[ -f /opt/chef/bin/chef-zero ] || exit 1
```

**Comment by sethvargo** [comment] 2015-02-24 23:04
Hi there - this is a duplicate of https://github.com/mitchellh/packer/issues/1118. Sorry we didn't catch that sooner :smile:

**Closed by sethvargo** 2015-02-24 23:04 UTC
Labels: bug, provisioner/chef
