### ISSUE TITLE
The --version option shouldn't have a non-zero exit code 

### ISSUE THREAD

**Issue by joestump** [mitchellh/packer#4486] opened 2017-01-30 22:11 UTC
I ran across this because I added `set -e` to a shell script I use to install HashiCorp tooling into my build environments. Sadly, this resulted in my builds failing whenever `packer --version` is called. It's my understanding that [a non-zero exit code means an error occurred](http://www.tldp.org/LDP/abs/html/exitcodes.html), but I fail to see how printing out the version is an error or could be a problem.

I suspect all that needs to change is [this line here](https://github.com/mitchellh/packer/blob/d310de8cf5871354bd1d12996a87020803d373ea/vendor/github.com/mitchellh/cli/cli.go#L122) to return `0` instead of `1`.

* Packer = 0.12.1.
* Platform = Travis CI / Ubuntu 14.04

```shell
#!/bin/bash -x

set -e

APP=$1
VERSION=$2
PACKAGE="${APP}_${VERSION}_linux_amd64.zip"
SOURCE_URL="https://releases.hashicorp.com"

function install_app() {
    echo "Installing v$VERSION of $APP..."
    curl -O "$SOURCE_URL/$APP/$VERSION/$PACKAGE"
    unzip -o "./$PACKAGE"
    rm -f $PACKAGE
    $BIN_DIR/$APP --version
    exit 0
}

cd $BIN_DIR

if [ -f $APP ]
then
    CURRENT_VERSION=`$BIN_DIR/$APP --version | head -n 1 | awk '{print $2}'`
    if [ ! "$CURRENT_VERSION" ]
    then
        CURRENT_VERSION="v`$BIN_DIR/$APP --version`"
    fi

    if [ "$CURRENT_VERSION" != "v${VERSION}" ]
    then
        echo "Version mismatch found."
        install_app
    fi
else
    echo "$APP not found."
    install_app
fi
```

As a comparison with `awscli`:

```
(ops-goldstar-chef) josephstump[~/Dropbox/jstump/dev/goldstar/ops-goldstar-chef]
ops-goldstar-chef $ aws --version && echo TRUE || echo FALSE
aws-cli/1.11.29 Python/2.7.12 Darwin/16.3.0 botocore/1.4.86
TRUE
(ops-goldstar-chef) josephstump[~/Dropbox/jstump/dev/goldstar/ops-goldstar-chef]
ops-goldstar-chef $ packer --version && echo TRUE || echo FALSE
0.12.1
FALSE
```

**Comment by mwhooker** [comment] 2017-01-30 22:41
Hey Joe,

good catch, thanks! Tracking upstream here https://github.com/mitchellh/cli/pull/49

will update our dep when that gets merged

**Comment by mwhooker** [comment] 2017-02-01 19:32
@joestump in the meantime, if it's helpful, you can use the version subcommand

```
$ packer version; echo $?
Packer v0.12.2

0
```

**Comment by tb3088** [comment] 2017-02-02 00:40
interesting that 'packer version' and 'packer --version' return different strings and an extra carriage return in the case of 'version'.

**Comment by mwhooker** [comment] 2017-02-03 08:33
dupe of #3370

**Closed by mwhooker** 2017-02-03 08:33 UTC
Labels: core, enhancement
