### ISSUE TITLE
VMWARE ESXi - VM gets new ip after reboot so packer cannot connect

### ISSUE THREAD

**Issue by ghost** [mitchellh/packer#2185] opened 2015-06-08 03:53 UTC
Hi,
I want to deploy VMs in ESXi 5.5. Packer can create and deploy a vm but the issue is VM gets
new ip after reboot so packer cannot connect. It keeps trying to connect to the old ip.   

First- it gets correct ip - ssh is not up so it cannot connect
TCP connection to SSH ip/port failed: dial tcp 192.168.111.158:22: connection refused
Second- then machine reboot
TCP connection to SSH ip/port failed: dial tcp 192.168.111.158:22: i/o timeout
Third - It cannot connect as that ip is not valid
TCP connection to SSH ip/port failed: dial tcp 192.168.111.158:22: no route to host

```javascript
{
  "builders": [
    {
      "type": "vmware-iso",
      "vm_name": "centos-rhel-7",
      "iso_url": "/home/files/CentOS-7-x86_64-Minimal-1503-01.iso",
      "iso_checksum": "d07ab3e615c66a8b2e9a50f4852e6a77",
      "iso_checksum_type": "md5",
      "disk_size": "10240",
      "disk_type_id": "thin",
      "http_directory": "~/packertemplatebuilding",
      "remote_host": "192.168.111.111",
      "remote_datastore": "SSD_60",
      "remote_username": "root",
      "remote_password": "password",
      "remote_type": "esx5",
      "ssh_username": "root",
      "guest_os_type": "rhel6-64",
      "ssh_password": "abc@123",
      "ssh_port": 22,
      "ssh_wait_timeout": "20m",
      "shutdown_command": "shutdown -h now",
      "headless": "false",
      "boot_command": [
        "<tab> text ks=http://192.168.111.8/files/ksv3.cfg<enter><wait>"
      ],
      "boot_wait": "5s",
      "vmx_data": {
        "ethernet0.networkName": "VM Network",
        "config.version": 8,
        "virtualHW.version": 8,
        "ethernet0.present": "true",
        "ethernet0.virtualDev": "vmxnet3",
        "ethernet0.startConnected": "true",
        "ethernet0.addressType": "generated",
        "memsize": "2048",
        "numvcpus": "2",
        "cpuid.coresPerSocket": "1",
        "ide0:0.fileName": "disk.vmdk",
        "ide0:0.present": "TRUE",
        "ide0:0.redo": "",
        "scsi0:0.present": "FALSE",
        "RemoteDisplay.vnc.enabled": "TRUE",
        "RemoteDisplay.vnc.port":  "5900"
      }
    }
  ],
"provisioners": [
    {
      "type": "shell",
      "inline": [
        "sleep 30",
        "yum install -y httpd",
        "rm -f /etc/udev/rules.d/70-persistent-net.rules"
      ]
    }
  ]
}
```

I want packer to rerun 
esxcli --formatter csv network vm port list -w port 

after reboot (lets say after 8 min) so that it gets the new ip. Is it possible? Is there a better solution?

**Comment by shible2014** [comment] 2015-06-13 12:51
ssh_wait_timeout states "Note that this should be quite long since the timer begins as soon as the virtual machine is booted."

I was wondering why packer start to connect to ssh before it install the OS?

**Comment by israelshirk** [comment] 2015-06-25 21:11
If you want to use a static IP, here's a few snippets that may work for you.  In effect, you can specify variables in the boot command, pick them up in the kickstart (which is a little indirect due to chrooting during the process), and create the network configuration at the very end of the kickstart.  Also, this is RHEL - CentOS may have slight variations.  Subscription management stuff is stripped out.

Kickstart - obviously you'd want to change a lot of this:
```bash
# Base settings
install

# Zero everything out and partition the root disk
zerombr
clearpart  --all --initlabel

cdrom
lang en_US.UTF-8
keyboard 'us'

# Network setup
network --onboot yes --device eth0 --bootproto dhcp --noipv6 --hostname=localhost.localdomain
timezone --utc UTC

# Base settings
firewall --enabled --trust eth0 --ssh
authconfig --enableshadow --passalgo=sha512
selinux --permissive
timezone --utc UTC

# Install in text mode, no X11
text
skipx

part /boot --fstype ext4 --size=100 --asprimary
part pv.1  --size=0 --grow --asprimary --size=7000
volgroup   vg00 pv.1
logvol /             --name=lv_root         --fstype ext4 --vgname=vg00 --size=8192

# Install bootloader
bootloader --location=mbr --append="norhgb net.ifnames=0 biosdevname=0"

# Disable wonky stuff
firstboot --disabled

# Enable network and SSH
services --enabled network,sshd

# Reboot after setup
reboot

# Install stuff
%packages --excludedocs

# Core group - we use all of it currently; this makes it a little easier to strip stuff out
@core
-ecryptfs-utils
rsyslog

# Base group
# Base Mandatory Packages
@base

# Base Optional Packages
-openCryptoki
-tpm-tools
-trousers
authd
bridge-utils
hardlink
iscsi-initiator-utils


# Development Tools group, plus a few optional packages, minus some defaults
@development
@server-platform-devel
-cvs-inetd
-dejagnu
-doxygen
-ElectricFence
-libgfortran44
-nasm
-pexpect
-python-docs
-valgrind
cmake
expect

bzr
chrpath
cmake
compat-gcc-34
compat-gcc-34-c++
compat-gcc-34-g77
cvs-inetd
dejagnu
ElectricFence
expect
gcc-gnat
gcc-java
gcc-objc
gcc-objc++
imake
jpackage-utils
kdewebdev
ksc
libstdc++-docs
rpmdevtools
rpmlint


# Additional Development Libs group, minus some defaults
@additional-devel
-boost-devel
-coolkey-devel
-curl-devel
-cyrus-sasl-devel
-db4-devel
-dbus-devel
-expat-devel
-fuse-devel
-gdbm-devel
-gmp-devel
-gnome-desktop-devel
-gnome-keyring-devel
-gpm-devel
-hesiod-devel
-krb5-devel
-kudzu-devel
-libogg-devel
-libselinux-devel
-libusb-devel
-libvorbis-devel
-libxml2-devel
-lockdev-devel
-newt-devel
-newt-perl
-openldap-devel
-pcsc-lite-devel
-python-devel
-slang-devel
-sysfsutils
-xmlsec1-devel
-xulrunner-devel

# Assorted stuff
bzip2
man
man-pages
sudo
vim-enhanced
acpid
wget

# Make sure Virtualbox Guest Extensions can build
kernel-devel
kernel-headers
zlib-devel
openssl-devel
readline-devel
sqlite-devel
perl

# Things because 2015.  Just a bare minimum.  :/
rsyslog
-syslog

# Stuff for Puppet
libselinux-ruby
libX11
libXau
xorg-x11-filesystem
libXdmcp
tk

# Needed for vmxnet3
yum-kmod

%end

%post

# Install anything we were given with our kickstart
# (normally, network or disk drivers)
mkdir -p /floppy
mount /dev/fd0 /floppy
rpm -ivh /floppy/*rpm
umount /floppy
rm -rf /floppy

# Add Vagrant user and group.  501/20 matches the default user on OS X (in case you're thinking of using NFS in that context)
/usr/sbin/groupadd -g 501 vagrant
/usr/sbin/useradd -u 501 -g 501 -m vagrant

echo "vagrant"|passwd --stdin vagrant

# Give Vagrant user permission to sudo.
#echo 'Defaults:vagrant !requiretty' >> /etc/sudoers.d/vagrant
#echo '%vagrant ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/vagrant
#chmod 440 /etc/sudoers.d/vagrant

echo 'Defaults:vagrant !requiretty' >> /etc/sudoers
echo '%vagrant ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers


# Install vagrant authorized ssh key...
# This doesn't do the normal 'curl https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub > ...' because
# networking may not be online yet.
mkdir /home/vagrant/.ssh
cat <<THE_END > /home/vagrant/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
THE_END
chown vagrant:vagrant -R /home/vagrant/.ssh
chmod 700 /home/vagrant/.ssh
chmod 600 /home/vagrant/.ssh/authorized_keys

chcon -R unconfined_u:object_r:user_home_t:s0 /home/vagrant/.ssh

# Disable 'consistent network device naming' and make things act more or less reasonable in a VM-oriented context.
echo > /etc/udev/rules.d/70-persistent-net.rules
echo > /etc/udev/rules.d/75-persistent-net-generator.rules

sed -i'' -e '/UUID=/d' /etc/sysconfig/network-scripts/ifcfg-eth0
sed -i'' -e '/HWADDR=/d' /etc/sysconfig/network-scripts/ifcfg-eth0
sed -i'' -e '/DHCP_HOSTNAME=/d' /etc/sysconfig/network-scripts/ifcfg-eth0
sed -i'' -e 's/NM_CONTROLLED=.*/NM_CONTROLLED="no"/' /etc/sysconfig/network-scripts/ifcfg-eth0

# Disable rhnsd so we don't get automatic updates - needs discussion with The Operators.  This is aimed at immutable stuff.  YMMV.
service rhnsd stop || echo "ignore"
chkconfig rhnsd off
%end
```

template.json - this is probably broken from stripping things, but demonstrates the boot command well
```
{
	"variables": {
		"rhn_activation_key": "",
		"yum_caching_proxy_url": "",

		"redhat_repo_base_url": "http://256.256.256.218/yum",

		"ip_address": "256.256.256.163",
		"netmask": "255.255.255.0",
		"gateway": "256.256.256.5",
		"nameserver1": "256.256.256.10",
		"nameserver2": "256.256.256.36",

		"esxi_username": "",
		"esxi_password": "",
		"esxi_host": "",
		"esxi_datastore": "",

		"role": "base",
		"hiera": "hiera/null.yaml",
		"post_command": " || [[ \"$?\" == \"2\" || \"$?\" == \"0\" ]] || (sudo subscription-manager unregister; echo \"sleeping 9000 seconds due to failure; ctrl-Z to pause indefinitely\"; sleep 9000; exit 1)"
	},
	"builders": [
		{
			"type": "vmware-iso",
			"name": "rhel6-vsphere",

			"guest_os_type": "rhel6-64",

			"iso_url": "file:///{{ pwd }}/iso/rhel-server-6.6-x86_64-dvd.iso",
			"iso_checksum": "4907e3ee01b5455b98654b136ab9833b6e672067051417d269f5c896cc7f3cf4cc878deb923022784d51ba523de63f2ee2ea3633a833aab2667704bfb09baab3",
			"iso_checksum_type": "sha512",

			"remote_type": "esx5",
			"remote_username": "{{ user `esxi_username` }}",
			"remote_password": "{{ user `esxi_password` }}",
			"remote_host": "{{user `esxi_host` }}",
			"remote_datastore": "{{ user `esxi_datastore` }}",
			"remote_cache_directory": "/packer",

			"output_directory": "output-rhel6-vsphere-{{ user `role` }}",

			"vmx_data": {
				"ethernet0.virtualDev": "vmxnet3",
				"ethernet0.networkName": "VM Network",
				"ethernet0.displayName": "VM Network",
				"ethernet0.connectionType": "bridged",
				"memSize": 2048
			},

			"vmdk_name": "disk",
			"version": "9",

			"floppy_files": [
				"kickstarts/rhel-6.6/ks.cfg",
				"drivers/rhel6/x86_64/kmod-vmware-tools-vmxnet3-1.3.1.0-2.6.32.71.el6.x86_64.5.el6.x86_64.rpm",
				"drivers/rhel6/x86_64/vmware-tools-foundation-9.4.11-1.el6.x86_64.rpm",
				"drivers/rhel6/x86_64/vmware-tools-vmxnet3-common-9.4.11-5.el6.x86_64.rpm"
			],

			"disk_size": "40000",

			"ssh_username": "vagrant",
			"ssh_password": "vagrant",
			"ssh_wait_timeout": "1000s",
			"ssh_host": "{{ user `ip_address` }}",

			"tools_upload_flavor": "linux",
			"tools_upload_path": "/home/vagrant/linux.iso",
			"headless": true,
			"shutdown_command": "echo 'vagrant' | sudo -S /sbin/shutdown -h now",

			"boot_command": "<tab> text ks=floppy IP={{ user `ip_address` }} NM={{ user `netmask` }} GW={{ user `gateway` }} DNS1={{ user `nameserver1` }}<enter><wait>",
			"boot_wait": "5s"
		}
	],
	"provisioners": [
		{
			"type": "shell",
			"execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}' {{ user `post_command` }}",

			"environment_vars": [
				"YUM_CACHING_PROXY_URL={{ user `yum_caching_proxy_url` }}"
			],

			"scripts": [
				"scripts/bare.sh",
				"scripts/virtualbox.sh",
				"scripts/facter.sh",
				"scripts/sanity_check.sh"
			]
		},
		{
			"type": "file",
			"source": "provisioners/puppeteer/puppet",
			"destination": "/tmp/puppet"
		},
		{
			"type": "shell",
			"inline": "sudo cp -a /tmp/puppet/* /etc/puppet/; rm -rf /tmp/puppet"
		},
		{
			"type": "puppet-masterless",
			"execute_command": "{{.FacterVars}}{{if .Sudo}} sudo -E {{end}}puppet apply --verbose --debug --parser future --modulepath='/etc/puppet/modules' --hiera_config='/etc/puppet/{{ user `hiera` }}' --manifestdir='/etc/puppet/manifests' --detailed-exitcodes /etc/puppet/manifests/site.pp {{ user `post_command` }}",

			"facter": {
				"server_tags": "role:{{ user `role` }}=true"
			},

			"hiera_config_path": "provisioners/puppeteer/puppet/{{ user `hiera` }}",

			"manifest_file": "provisioners/puppeteer/puppet/manifests/site.pp",
			"module_paths": [
				"provisioners/puppeteer/puppet/modules/"
			],

			"staging_directory": "/tmp/packer-puppet-masterless/puppet"
		},
		{
			"type": "shell",
			"execute_command": "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}' {{ user `post_command` }}",

			"environment_vars": [
				"YUM_CACHING_PROXY_URL={{ user `yum_caching_proxy_url` }}"
			],

			"scripts": [
				"scripts/cleanup.sh"
			]
		},
		{
			"type": "shell",
			"inline": [
				"echo Sleeping 90 so you can interrupt - run pkill -f sleep to continue.",
				"sleep 90 || true"
			]
		}
	],
	"post-processors": [
		{
			"type": "vagrant",
			"output": "packer_{{.BuildName}}_{{ user `role` }}_{{.Provider}}.box",
			"only": ["rhel5-vagrant", "rhel6-vagrant", "centos6-vagrant"]
		}
	]
}
```

**Comment by epowell** [comment] 2015-09-16 16:26
I'm not having any luck specifying an IP address for SSH as you do here. It looks like it always tries to detect the address from the host, even if I specify a value for `ssh_host`.

Any advice?

```
2015/09/16 16:14:36 packer-builder-vmware-iso: 2015/09/16 16:14:36 opening new ssh session
2015/09/16 16:14:36 packer-builder-vmware-iso: 2015/09/16 16:14:36 starting remote command: esxcli --formatter csv network vm list
2015/09/16 16:14:36 packer-builder-vmware-iso: 2015/09/16 16:14:36 remote command exited with '0': esxcli --formatter csv network vm list
2015/09/16 16:14:36 packer-builder-vmware-iso: 2015/09/16 16:14:36 opening new ssh session
2015/09/16 16:14:36 packer-builder-vmware-iso: 2015/09/16 16:14:36 starting remote command: esxcli --formatter csv network vm port list -w 2490148
2015/09/16 16:14:37 packer-builder-vmware-iso: 2015/09/16 16:14:37 remote command exited with '0': esxcli --formatter csv network vm port list -w 2490148
2015/09/16 16:14:37 packer-builder-vmware-iso: 2015/09/16 16:14:37 [DEBUG] Error getting SSH address: VM network port found, but no IP address
2015/09/16 16:14:40 ui error: ==> hypprovisioning: Timeout waiting for SSH.
```

**Comment by israelshirk** [comment] 2015-09-16 17:13
@epowell probably the easiest way to troubleshoot is to VNC in and REPL on /etc/sysconfig/network-scripts/ifcfg-eth0 and service network restart.  Also, using e1000 and moving vmxnet3 to post_data simplifies things a bit

**Comment by shible2014** [comment] 2015-09-17 14:44
@epowell , most probably your DHCP server is not working. Make sure new VMs can automatically get ip. You can manually create a VM and check.

**Comment by epowell** [comment] 2015-09-17 14:50
@shible2014 If I had DHCP my life would be easier. :) Thanks, though.

I am specifically trying to create a VM with a static IP on an isolated network - SSH will not work in this case. I was hoping to use the `ssh_host`/`ssh_username`/`ssh_password` configuration to provide an alternate IP to get to the VM, but these parameters seem to be ignored entirely by the vmware-iso builder - it always tries to auto-detect and connects to that address.

**Comment by shible2014** [comment] 2015-09-17 14:56
As far as I know, you cannot install VMs without DHCP. Just run a DHCP temporally, one it is configured, use automation tools to reset the ip to static. You could use different IP range for DHCP.

**Comment by epowell** [comment] 2015-09-17 15:54
The VM I am building is the DHCP provider for the network it has access to. I'm not jumping through hoops unnecessarily. :)

**Comment by shible2014** [comment] 2015-09-17 23:32
For 1/2 VMs, one can do it manually!

**Comment by michaeltlombardi** [comment] 2016-09-21 18:14
Should this issue have been closed by #3617 or is it still a problem, @epowell/@ghost?

**Comment by rickard-von-essen** [comment] 2016-09-21 19:05
@michaeltlombardi #3617 is a fix for `virtualbox` builder this issue concerns `vmware` builder on ESXi. But I think this is fixed in #3738

**Comment by michaeltlombardi** [comment] 2016-09-21 19:25
Sorry, reading comprehension fail.

**Comment by rickard-von-essen** [comment] 2016-10-11 22:12
This should be working in (at least) the last release. Please reopen if not.

**Closed by rickard-von-essen** 2016-10-11 22:12 UTC
Labels: builder/vmware-esxi, question, waiting-reply

**Comment by epowell** [comment] 2016-11-01 18:42
I cannot reproduce this with the 0.11.0 release, so I think it's good to go.  I believe the change for #3347 has fixed this for my use case.

**Comment by rickard-von-essen** [comment] 2016-11-01 18:58
Thanks for reporting back.
