### ISSUE TITLE
packer validate crash - 0.8.1 - brew install  

### ISSUE THREAD

**Issue by NicolasMas** [mitchellh/packer#2390] opened 2015-07-06 13:51 UTC
2015/07/06 21:46:14 [INFO] Packer version: 0.8.1  872e78d5b0a387eb3b87ddeef210264c3199d178+CHANGES
2015/07/06 21:46:14 Packer Target OS/Arch: darwin amd64
2015/07/06 21:46:14 Built with Go Version: go1.4.2
2015/07/06 21:46:14 [DEBUG] Discovered plugin: amazon-chroot = /usr/local/bin/packer-builder-amazon-chroot
2015/07/06 21:46:14 [DEBUG] Discovered plugin: amazon-ebs = /usr/local/bin/packer-builder-amazon-ebs
2015/07/06 21:46:14 [DEBUG] Discovered plugin: amazon-instance = /usr/local/bin/packer-builder-amazon-instance
2015/07/06 21:46:14 [DEBUG] Discovered plugin: digitalocean = /usr/local/bin/packer-builder-digitalocean
2015/07/06 21:46:14 [DEBUG] Discovered plugin: docker = /usr/local/bin/packer-builder-docker
2015/07/06 21:46:14 [DEBUG] Discovered plugin: file = /usr/local/bin/packer-builder-file
2015/07/06 21:46:14 [DEBUG] Discovered plugin: googlecompute = /usr/local/bin/packer-builder-googlecompute
2015/07/06 21:46:14 [DEBUG] Discovered plugin: null = /usr/local/bin/packer-builder-null
2015/07/06 21:46:14 [DEBUG] Discovered plugin: openstack = /usr/local/bin/packer-builder-openstack
2015/07/06 21:46:14 [DEBUG] Discovered plugin: parallels-iso = /usr/local/bin/packer-builder-parallels-iso
2015/07/06 21:46:14 [DEBUG] Discovered plugin: parallels-pvm = /usr/local/bin/packer-builder-parallels-pvm
2015/07/06 21:46:14 [DEBUG] Discovered plugin: qemu = /usr/local/bin/packer-builder-qemu
2015/07/06 21:46:14 [DEBUG] Discovered plugin: virtualbox-iso = /usr/local/bin/packer-builder-virtualbox-iso
2015/07/06 21:46:14 [DEBUG] Discovered plugin: virtualbox-ovf = /usr/local/bin/packer-builder-virtualbox-ovf
2015/07/06 21:46:14 [DEBUG] Discovered plugin: vmware-iso = /usr/local/bin/packer-builder-vmware-iso
2015/07/06 21:46:14 [DEBUG] Discovered plugin: vmware-vmx = /usr/local/bin/packer-builder-vmware-vmx
2015/07/06 21:46:14 [DEBUG] Discovered plugin: atlas = /usr/local/bin/packer-post-processor-atlas
2015/07/06 21:46:14 [DEBUG] Discovered plugin: compress = /usr/local/bin/packer-post-processor-compress
2015/07/06 21:46:14 [DEBUG] Discovered plugin: docker-import = /usr/local/bin/packer-post-processor-docker-import
2015/07/06 21:46:14 [DEBUG] Discovered plugin: docker-push = /usr/local/bin/packer-post-processor-docker-push
2015/07/06 21:46:14 [DEBUG] Discovered plugin: docker-save = /usr/local/bin/packer-post-processor-docker-save
2015/07/06 21:46:14 [DEBUG] Discovered plugin: docker-tag = /usr/local/bin/packer-post-processor-docker-tag
2015/07/06 21:46:14 [DEBUG] Discovered plugin: vagrant = /usr/local/bin/packer-post-processor-vagrant
2015/07/06 21:46:14 [DEBUG] Discovered plugin: vagrant-cloud = /usr/local/bin/packer-post-processor-vagrant-cloud
2015/07/06 21:46:14 [DEBUG] Discovered plugin: vsphere = /usr/local/bin/packer-post-processor-vsphere
2015/07/06 21:46:14 [DEBUG] Discovered plugin: ansible-local = /usr/local/bin/packer-provisioner-ansible-local
2015/07/06 21:46:14 [DEBUG] Discovered plugin: chef-client = /usr/local/bin/packer-provisioner-chef-client
2015/07/06 21:46:14 [DEBUG] Discovered plugin: chef-solo = /usr/local/bin/packer-provisioner-chef-solo
2015/07/06 21:46:14 [DEBUG] Discovered plugin: file = /usr/local/bin/packer-provisioner-file
2015/07/06 21:46:14 [DEBUG] Discovered plugin: powershell = /usr/local/bin/packer-provisioner-powershell
2015/07/06 21:46:14 [DEBUG] Discovered plugin: puppet-masterless = /usr/local/bin/packer-provisioner-puppet-masterless
2015/07/06 21:46:14 [DEBUG] Discovered plugin: puppet-server = /usr/local/bin/packer-provisioner-puppet-server
2015/07/06 21:46:14 [DEBUG] Discovered plugin: salt-masterless = /usr/local/bin/packer-provisioner-salt-masterless
2015/07/06 21:46:14 [DEBUG] Discovered plugin: shell = /usr/local/bin/packer-provisioner-shell
2015/07/06 21:46:14 [DEBUG] Discovered plugin: shell-local = /usr/local/bin/packer-provisioner-shell-local
2015/07/06 21:46:14 [DEBUG] Discovered plugin: windows-restart = /usr/local/bin/packer-provisioner-windows-restart
2015/07/06 21:46:14 [DEBUG] Discovered plugin: windows-shell = /usr/local/bin/packer-provisioner-windows-shell
2015/07/06 21:46:14 Detected home directory from env var: /Users/nicolasmas
2015/07/06 21:46:14 Detected home directory from env var: /Users/nicolasmas
2015/07/06 21:46:14 Attempting to open config file: /Users/nicolasmas/.packerconfig
2015/07/06 21:46:14 [WARN] Config file doesn't exist: /Users/nicolasmas/.packerconfig
2015/07/06 21:46:14 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[amazon-instance:/usr/local/bin/packer-builder-amazon-instance digitalocean:/usr/local/bin/packer-builder-digitalocean vmware-vmx:/usr/local/bin/packer-builder-vmware-vmx vmware-iso:/usr/local/bin/packer-builder-vmware-iso amazon-chroot:/usr/local/bin/packer-builder-amazon-chroot amazon-ebs:/usr/local/bin/packer-builder-amazon-ebs googlecompute:/usr/local/bin/packer-builder-googlecompute null:/usr/local/bin/packer-builder-null qemu:/usr/local/bin/packer-builder-qemu docker:/usr/local/bin/packer-builder-docker file:/usr/local/bin/packer-builder-file parallels-iso:/usr/local/bin/packer-builder-parallels-iso virtualbox-iso:/usr/local/bin/packer-builder-virtualbox-iso virtualbox-ovf:/usr/local/bin/packer-builder-virtualbox-ovf openstack:/usr/local/bin/packer-builder-openstack parallels-pvm:/usr/local/bin/packer-builder-parallels-pvm] PostProcessors:map[compress:/usr/local/bin/packer-post-processor-compress docker-save:/usr/local/bin/packer-post-processor-docker-save docker-tag:/usr/local/bin/packer-post-processor-docker-tag vagrant:/usr/local/bin/packer-post-processor-vagrant vagrant-cloud:/usr/local/bin/packer-post-processor-vagrant-cloud atlas:/usr/local/bin/packer-post-processor-atlas docker-import:/usr/local/bin/packer-post-processor-docker-import docker-push:/usr/local/bin/packer-post-processor-docker-push vsphere:/usr/local/bin/packer-post-processor-vsphere] Provisioners:map[shell-local:/usr/local/bin/packer-provisioner-shell-local ansible-local:/usr/local/bin/packer-provisioner-ansible-local chef-client:/usr/local/bin/packer-provisioner-chef-client chef-solo:/usr/local/bin/packer-provisioner-chef-solo powershell:/usr/local/bin/packer-provisioner-powershell salt-masterless:/usr/local/bin/packer-provisioner-salt-masterless shell:/usr/local/bin/packer-provisioner-shell file:/usr/local/bin/packer-provisioner-file puppet-masterless:/usr/local/bin/packer-provisioner-puppet-masterless puppet-server:/usr/local/bin/packer-provisioner-puppet-server windows-restart:/usr/local/bin/packer-provisioner-windows-restart windows-shell:/usr/local/bin/packer-provisioner-windows-shell]}
2015/07/06 21:46:14 Setting cache directory: /Users/nicolasmas/Dropbox/Serv/devOps/packer/packer_cache
2015/07/06 21:46:14 Detected home directory from env var: /Users/nicolasmas
2015/07/06 21:46:14 waiting for all plugin processes to complete...
panic: Malformed version: 

goroutine 1 [running]:
github.com/mitchellh/packer/packer.(*Core).validate(0xc2080fc730, 0x0, 0x0)
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/packer/core.go:238 +0x100
github.com/mitchellh/packer/packer.NewCore(0xc208037f00, 0x0, 0x0, 0x0)
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/packer/core.go:63 +0x15b
github.com/mitchellh/packer/command.(*Meta).Core(0xc2080101c0, 0xc208062400, 0xc208062400, 0x0, 0x0)
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/command/meta.go:49 +0x10c
github.com/mitchellh/packer/command.(*ValidateCommand).Run(0xc2080101c0, 0xc20800a020, 0x1, 0x1, 0xc208035358)
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/command/validate.go:45 +0x458
github.com/mitchellh/cli.(*CLI).Run(0xc20802c000, 0x843dc0, 0x0, 0x0)
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/cli/cli.go:112 +0x5be
main.wrappedMain(0x0)
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/main.go:187 +0x13d5
main.realMain(0x0)
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/main.go:91 +0x923
main.main()
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/main.go:26 +0x1f

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 7 [syscall]:
syscall.Syscall(0x3, 0x0, 0xc2080e4000, 0x8000, 0x769101, 0x8000, 0x7691a8)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:20 +0x5
syscall.read(0x0, 0xc2080e4000, 0x8000, 0x8000, 0x7691a8, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:970 +0x6e
syscall.Read(0x0, 0xc2080e4000, 0x8000, 0x8000, 0x391a80, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc208038000, 0xc2080e4000, 0x8000, 0x8000, 0xc2080e4000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file_unix.go:191 +0x86
os.(*File).Read(0xc208038000, 0xc2080e4000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/os/file.go:95 +0x91
io.Copy(0x843dc0, 0xc2080380b8, 0x8445c0, 0xc208038000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/io.go:362 +0x1f6
main.func·013()
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/stdin.go:23 +0xc5
created by main.setupStdin
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/stdin.go:24 +0x11f

goroutine 8 [chan receive]:
main.func·014()
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/stdin.go:34 +0x99
created by main.setupStdin
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/stdin.go:36 +0x270

goroutine 10 [semacquire]:
sync.(*Cond).Wait(0xc2080fe0f0)
	/usr/local/Cellar/go/1.4.2/libexec/src/sync/cond.go:62 +0x9e
io.(*pipe).read(0xc2080fe0c0, 0xc208101000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/pipe.go:52 +0x303
io.(*PipeReader).Read(0xc208038080, 0xc208101000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/io/pipe.go:134 +0x5b
bufio.(*Scanner).Scan(0xc20806a000, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/bufio/scan.go:180 +0x688
github.com/mitchellh/packer/command.func·006()
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/command/meta.go:132 +0x3d
created by github.com/mitchellh/packer/command.(*Meta).FlagSet
	/private/tmp/packer20150704-1588-hf1jji/src/github.com/mitchellh/packer/command/meta.go:135 +0x553

**Comment by cbednarski** [comment] 2015-07-06 16:51
@NicolasMas Thanks for the report. Can you share the config you're using that causes the crash?

**Comment by cbednarski** [comment] 2015-07-06 20:23
I think this is a dupe of #2385 Will track in that issue. Please reopen if this is a different issue.

**Closed by cbednarski** 2015-07-06 20:23 UTC
Labels: core, crash

**Comment by NicolasMas** [comment] 2015-07-07 02:31
Yep, dupe of #2385
