### ISSUE TITLE
AWS EBS - packer does not use existing keypair

### ISSUE THREAD

**Issue by myoung34** [mitchellh/packer#1799] opened 2014-12-30 14:42 UTC
The base official CentOS AMI does not work with vagrant or packer.
To work with them, 1 thing needs to happen:  ``Defaults !requiretty`` in */etc/sudoers*

This change allows packer/vagrant to work, as it needs to run sudo commands via SSH. 
For packer, at this point, you cannot use dynamic keys. */etc/rc.local* sets */root/.ssh/authorized_keys* only when that file does not exist. It does, so it won't update, that public key is now bundled with the AMI.

To run packer against this, ``"ssh_private_key_file": "~/.ssh/mykey.pem",`` must be set in the packer JSON, where it is the private key to the bundled public. This does not work, and causes the same issue as #1697 , where a handshake fails. However, if I use ``-debug`` on build and ssh into the Packer builder agent, it succeeds.

The only other way that this works, and not related to this ticket, but for anyone who might need to know, is while making the initial !requiretty change, you must remove */root/.ssh/authorized_keys*. This allows the key to be dynamic. Removing ``ssh_private_key_file`` as a JSON key will allow packer to generate a temporary one that works with the instance.

The bug here, however, that I can't seem to figure out is why specifying a private key does not work.

**Comment by jantman** [comment] 2015-01-31 14:10
This also appears related to #1635

**Comment by sethvargo** [comment] 2015-02-24 23:56
This seems like a duplicate of #1635. If not an exact duplicate, it appears that solving #1635 will also solve this issue. Let's track that issue instead please :smile:

**Closed by sethvargo** 2015-02-24 23:56 UTC

**Comment by halmer1984** [comment] 2017-06-15 15:19
I have a question, I see that packer creates the  temporary keypair, however it deletes the keypair. So what key pair is used to access the Instance once it has launched

**Comment by myoung34** [comment] 2017-06-15 15:21
@halmer1984 it uses the keypair that it created before it deletes it

**Comment by rickard-von-essen** [comment] 2017-06-15 15:34
Don't zombie 👻  old issues.

---

Please only use _GitHub Issues_ for reporting bugs and feature requests. Do not ask for general help here. Use _IRC `#packer-tool` on Freenode_ or the [mailing list](https://groups.google.com/group/packer-tool) for that.

See https://www.packer.io/community/
