### ISSUE TITLE
packer Openstack provisioner fails to authenticate to Rackspace Cloud Identity v2

### ISSUE THREAD

**Issue by rickhull** [mitchellh/packer#3449] opened 2016-04-17 03:55 UTC
- Packer Version 0.10.0
- Host platform Debian 8.4 amd64

In our case, Rackspace Cloud identity v2.0 requires a username and a secret API key in order to authenticate.

Here is a cURL example from their [docs](https://developer.rackspace.com/docs/cloud-identity/v2/developer-guide/#generate-an-authentication-token):

```
$ curl https://identity.api.rackspacecloud.com/v2.0/tokens  \
 -X POST \
 -d '{"auth":{"RAX-KSKEY:apiKeyCredentials":{"username":"yourUserName","apiKey":"yourPassword"}}}' \
 -H "Content-type: application/json"
```

This works for me, using my credentials.  However, I can't get anything similar to work via packer's OpenStack provisioner, starting from the _Rackspace Public Cloud_ example here https://www.packer.io/docs/builders/openstack.html

```
    {
      "type": "openstack",
      "identity_endpoint": "https://identity.api.rackspacecloud.com/v2.0",
      "username": "yourUser",
      "password": "{{user `rackspace_api_key`}}",
      "region": "DFW",
      "source_image": "a84b1592-6817-42da-a57c-3c13f3cfc1da",
      "ssh_username": "root",
      "flavor": "general1-4",
      "image_name": "packer-example {{timestamp}}"
    }
```

```
$ packer validate -var 'rackspace_api_key=yourPassword' multi.json 
Template validation failed. Errors are shown below.

Errors validating build 'openstack'. 1 error(s) occurred:

* Expected HTTP response code [200 203] when accessing [POST https://identity.api.rackspacecloud.com/v2.0/tokens], but got 401 instead
{"unauthorized":{"code":401,"message":"Unable to authenticate user with credentials provided."}}
```

So I tried specifying my API key as `api_key` rather than `password`:

```
{
      ...
      "api_key": "{{user `rackspace_api_key`}}",
      ...
}
```

```
$ packer validate -var 'rackspace_api_key=yourPassword' multi.json 
Template validation failed. Errors are shown below.

Errors validating build 'openstack'. 1 error(s) occurred:

* The base Identity V2 API does not accept authentication by APIKey
```

Now this is strange!  Because we know from the cURL above that Identity v2.0 _does_ accept an APIKey.  We also know this from Rackspace's own gophercloud documentation:

https://developer.rackspace.com/docs/cloud-servers/getting-started/#authentication

(make sure to select the Go SDK -- not sure why it's not in the URL)

```
import (
  "github.com/rackspace/gophercloud"
  "github.com/rackspace/gophercloud/rackspace"
  "github.com/rackspace/gophercloud/rackspace/compute/v2/images"
  "github.com/rackspace/gophercloud/rackspace/compute/v2/flavors"
  "github.com/rackspace/gophercloud/rackspace/compute/v2/servers"
  "github.com/rackspace/gophercloud/rackspace/compute/v2/keypairs"

  oskeypairs "github.com/rackspace/gophercloud/openstack/compute/v2/extensions/keypairs"
)

ao := gophercloud.AuthOptions{
  Username: "{username}",
  APIKey: "{apiKey}",
}
provider, err := rackspace.AuthenticatedClient(ao)

serviceClient, err := rackspace.NewComputeV2(provider, gophercloud.EndpointOpts{
  Region: "{region}",
})
```

So, I'm not sure what's going on, honestly, and I'm not sure how this is supposed to be done on the Packer side.  I would think it should be straightforward to make GopherCloud authenticate to Rackspace Cloud.

I can gist a more extensive dump if need be.

_Note: this comment and others below have been edited in light of the discussion below.  Keep in mind that this may make the discussion seem absurd_

**Comment by rickhull** [comment] 2016-04-17 04:11
Here is my first ever go program, authenticating to Rackspace Identity v2.0 using gophercloud:

```
package main

import (
	"fmt"
	"log"
	"github.com/rackspace/gophercloud"
	"github.com/rackspace/gophercloud/rackspace"
	// "github.com/rackspace/gophercloud/openstack"
	// "github.com/rackspace/gophercloud/openstack/utils"
)

func main() {
	opts := gophercloud.AuthOptions{
		Username: "yourUser",
		APIKey: "yourPassword",
	}
	provider, err := rackspace.AuthenticatedClient(opts)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(provider.IdentityEndpoint)

	client, err := rackspace.NewComputeV2(provider, gophercloud.EndpointOpts{
		Region: "DFW",
	})
	fmt.Println(client.Endpoint)
}
```
```
$ bin/rackspace 
https://identity.api.rackspacecloud.com/v2.0/
https://dfw.servers.api.rackspacecloud.com/v2/xxxxxx/
```

**Comment by rickard-von-essen** [comment] 2016-04-17 05:57
See the docs under _Basic Example: Rackspace Public Cloud_. Password is the password you use to login, not your api key. Did you specify tenant via env vars? Be sure to double check you `OS_` env vars so they are correct.

**Comment by rickhull** [comment] 2016-04-17 07:41
A few things:

1. Rackspace Cloud is a bit of an odd duck, relative to the standard OpenStack auth
2. I believe Rackspace Cloud will allow using password auth, but they recommend using the API key.  To be clear, user value I am using is the account name (not my username), and the secret value I am using is an API key, and not a password.  This is shown with the cURL example and Rackspace's own gophercloud example.  This is how Rackspace says to do it, in contrast to the *Rackspace Public Cloud* Packer docs.
3. You can see from mine and Rackspace's gophercloud examples that tenant is not required (nor appropriate).  Also, gophercloud doesn't require anything (to my knowledge) to be set via env var -- this is just one way to get the data into the client.

See again their docs:

* https://developer.rackspace.com/docs/cloud-identity/v2/developer-guide/#generate-an-authentication-token -- search for `RAX-KSKEY:apiKeyCredentials`
* https://developer.rackspace.com/docs/cloud-servers/getting-started/#authentication -- search for `APIKey`

To reiterate, for authenticating to Rackspace's API, we are using account name and API key, not username and password.  This is fully supported (and recommended) by their Identity API v2.0.  Tenant ID is not required.  I can connect this way with gophercloud.  You can see in my original comment how packer's provisioner failed when trying to follow *Basic Example: Rackspace Public Cloud*.

**Comment by rickard-von-essen** [comment] 2016-04-17 08:12
I'm  traveling and don't have access to a computer until later today, I'll try to reproduce this then. 
The code for logging into OS is very simple, mostly passing things to gophercloud. See https://github.com/mitchellh/packer/blob/master/builder/openstack/access_config.go#L32

**Comment by rickhull** [comment] 2016-04-17 08:39
Thanks.  As best I can tell, it looks like API key was just overlooked as a use case.  There may also be some friction around possibly needing additional rackspace-specific libraries.  We've been using "API key" auth for well over a year now, confirmed via cURL and gophercloud, but generally using Ruby's Fog library.  We've never used user/password auth for Rackspace API, but we'd love to start using Packer in our devops pipeline.

**Comment by rickard-von-essen** [comment] 2016-04-17 19:10
I just did some quick testing without packer using the _OpenStack CLI_.

Setting env vars listed below allows me to run `openstack catalog list` but setting my API key as password I get _401 Unauthorized_. But both password and api key works for curl.

```shell
$ openstack catalog list
+-----------------------+-------------------+-----------------------------------------------------------------------------------+
| Name                  | Type              | Endpoints                                                                         |
+-----------------------+-------------------+-----------------------------------------------------------------------------------+
| cloudBlockStorage     | volume            | DFW                                                                               |
[...]
$ set | grep OS_
OS_AUTH_URL=https://identity.api.rackspacecloud.com/v2.0/
OS_PASSWORD=<PASSWORD>
OS_REGION_NAME=IAD
OS_TENANT_ID=994800
OS_USERNAME=rickardvonessen
$ export OS_PASSWORD=<API KEY>
$ openstack catalog list
Unauthorized (HTTP 401)
```

What happens if you try to do a catalog listing via curl? (I could test this my self but I'm very short on time, sorry)

**Comment by rickhull** [comment] 2016-04-22 05:37
I'll check this weekend if not tonight.  Thanks.

**Comment by rickhull** [comment] 2016-04-22 22:56
I can confirm that the token I get back from the identity API, providing only `username` and `apiKey`,  is sufficient to list images:

```
#!/bin/bash                                                                                                                                                         

ID_ENDPOINT=https://identity.api.rackspacecloud.com/v2.0/tokens

JSON=$(curl $ID_ENDPOINT -s \
            -X POST -H "Content-type: application/json" \
            -d '{"auth":{"RAX-KSKEY:apiKeyCredentials":{"username":"xxx","apiKey":"yyy"}}}')

TOKEN=$(echo $JSON | jq -r .access.token.id)

IMG_ENDPOINT=$(echo $JSON | jq -r '.access.serviceCatalog[] | select(.name == "cloudImages").endpoints[] | select(.region == "DFW").publicURL')/v2/images

JSON=$(curl $IMG_ENDPOINT -s \
            -H "X-Auth-Token: $TOKEN")

echo $JSON | jq '.images[] | select(.os_distro == "debian") | {(.id): .name}'
```

```
{
  "d4574d0c-5d1f-4156-a626-9ed75b401804": "Debian Testing (Stretch) (PVHVM)"
}
{
  "fd74c45f-c642-4e78-834d-c33391c70f64": "Debian 7 (Wheezy) (PVHVM)"
}
{
  "43b287ad-8c5f-4632-a7a3-05e17ce537a1": "OnMetal - Debian Unstable (Sid)"
}
{
  "6a2ce934-2c64-497d-9e8e-8d73070f47ee": "OnMetal - Debian Testing (Stretch)"
}
{
  "597376a4-fd00-406a-8148-4f007218a770": "OnMetal - Debian 8 (Jessie)"
}
```

**Comment by rickhull** [comment] 2016-04-25 19:27
Is this sufficient to conclude that packer should support authentication to Rackspace using just `username` and `apiKey`?  If packer already supports this, then I just need help with the proper invocation.

To recap: When I specify the API key using the `password` field in the packer template, Rackspace rejects the authentication attempt.  When I specify the API key using the `api_key` field, then packer / gophercloud reject the attempt as "unsupported": `The base Identity V2 API does not accept authentication by APIKey`

**Comment by rickhull** [comment] 2016-04-27 19:51
@rickard-von-essen thoughts?

**Comment by rickard-von-essen** [comment] 2016-05-08 09:55
Sorry for the delay. I'm not the original author of the OpenStack builder and don't know exactly what is needed for Rackspace auth to work. I'll try to do some more testing. I'll try your script.

**Comment by rickard-von-essen** [comment] 2016-05-08 10:09
Just realised from reading the Gophercloud code that your way of authenticating in the script is not a OpenStack standard. We use this code to authenticate:
https://github.com/rackspace/gophercloud/blob/master/openstack/client.go#L66

But you are using `RAX-KSKEY` which is Rackspace specific and seems to covered by the code in:
https://github.com/rackspace/gophercloud/blob/master/rackspace/identity/v2/tokens/delegate.go
Which we don't use.

**Comment by rickard-von-essen** [comment] 2016-05-08 10:15
Rackspace docs for this is available at:
https://developer.rackspace.com/docs/cloud-identity/v2/developer-guide/#document-general-api-info/extensions

**Comment by rickhull** [comment] 2016-05-10 06:53
Yep, this was more or less my initial diagnosis, if you start from the top.  So does packer plan to support Rackspace Cloud in this way?  Especially since gophercloud already supports it.

**Comment by rickard-von-essen** [comment] 2016-05-10 07:23
> So does packer plan to support Rackspace Cloud in this way

Most features are contributed from the community. If someone wants this PR's are more than welcome. I might take a stab at it but I don't expect to have much time to spend on Packer until the summer. But I think this is easy to fix so it is a great way to get into the Packer code base.

**Comment by rickhull** [comment] 2016-05-10 07:26
Dang, it probably won't come from me.  I am leaving the team that needs this and I was hoping to nail it down before I go.  I bet you could get some action on this direct from Rackspace.  They wrote gophercloud, AFAIK.

**Comment by devghai** [comment] 2016-10-12 17:59
This issue is duplicate of https://github.com/mitchellh/packer/issues/2457. I can confirm that making changes as mentioned by @tdooner while compiling with latest gophercloud (that contains rackspace customizations) fixes this issue.

**Comment by mwhooker** [comment] 2017-02-03 04:23
we've updated to `gophercloud/gophercloud` since this was opened. Please open a new issue if this is still a problem

**Closed by mwhooker** 2017-02-03 04:23 UTC
Labels: builder/openstack, enhancement, rackspace
