### ISSUE TITLE
packer -v returns non-zero exit code.

### ISSUE THREAD

**Issue by schubert** [mitchellh/packer#3412] opened 2016-04-01 21:55 UTC
I'm not sure why but `packer -v` returns a non-zero exit code. That seems pretty non-standard behavior for a unix tool. 1 is for failure but printing the version number is successful.

This makes it difficult in shell scripts where you want to chain the successful execution of printing out the version to another step since you can't tell the difference from an actual failure.

Darwin <host> 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

```
$ packer -v
0.10.0

$ echo $?
1
```

**Comment by cbednarski** [comment] 2016-04-01 22:46
Thanks for the report. This is a dupe of https://github.com/mitchellh/packer/issues/3370

**Closed by cbednarski** 2016-04-01 22:46 UTC
Labels: duplicate
