### ISSUE TITLE
packer push does not push variables

### ISSUE THREAD

**Issue by clstokes** [mitchellh/packer#2598] opened 2015-08-13 21:53 UTC
The [packer documentation](https://www.packer.io/docs/command-line/push.html#_var) says that users should be able to push variables with `packer push -var "var=val ...`, however this doesn't seem to work. Turning on Packer's log with `PACKER_LOG=1`, shows that no variable information is in the request payload to Atlas.

Log output and example Packer config are at https://gist.github.com/clstokes/148b682b196ff62643eb.

I've tested this with both Packer v0.8.1 and v0.8.5. Both exhibit the same behavior.

**Comment by cbednarski** [comment] 2015-08-13 23:52
Thanks for submitting this. I've run into this as well but I have not yet tracked down where the flags are getting lost.

**Comment by clstokes** [comment] 2015-08-29 17:55
It looks like this when trying to pass a variables file with the `-var-file` parameter too.

**Comment by cyberswat** [comment] 2015-10-06 21:00
I'm hitting this as well using packer 0.8.6 against Atlas.  Everything works as intended locally.

**Comment by clstokes** [comment] 2015-10-07 22:34
`terraform push` doesn't push AWS keys if they're being inherited from the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables. Packer should probably follow this behavior.

**Comment by bascht** [comment] 2015-10-08 06:21
At the moment I've worked my way around this by setting all required variables manually in the Atlas Build config and then just using {{ env }} - what's a bit confusing: The Build tab has a variables section that are entirely environment variables, while the Infrastructure tab combines both terraform variables *and* environment variables in that tab. :)

**Comment by AirbornePorcine** [comment] 2015-10-28 19:38
+1, this is basically preventing us from using Atlas with Packer as we have a number of dynamic variables that need to be pushed up for each build.

**Comment by domofactor** [comment] 2016-01-19 06:32
+1, just bumped into this issue as well. any updates on a fix for this?

**Comment by cybertk** [comment] 2016-02-19 20:12
Same issue here on Travis with packer 0.8.6

**Comment by gamename** [comment] 2016-03-26 12:50
+1
Still happening with packer 0.10.0

**Comment by gamename** [comment] 2016-03-26 13:11
Any ETA?  Been running into this for 6+ months. 

Guys, this is not an obscure use case. It is clearly documented functionality that simply does not work.  How can I convince my management to work with (and spend money on) Hashicorp when problems like this go unaddressed? 

@sethvargo @kikitux  @mitchellh @armon

**Comment by dynamike** [comment] 2016-05-04 18:15
Yet another request for this

**Comment by cbednarski** [comment] 2016-05-04 21:48
Hey folks, thanks for your interest in this feature. It is in progress but unfortunately I don't have an ETA to share with you.

**Comment by malaikah** [comment] 2016-05-08 07:39
+1

**Comment by dennis-bsi** [comment] 2016-05-28 00:45
Just hit this issue myself.

**Comment by kenfusion** [comment] 2016-06-23 11:21
In the mean time, can you take it out of documentation?  I was spinning wheels for days until I found this discussion.

**Comment by mo-mughrabi** [comment] 2016-09-12 10:14
+1

**Comment by mo-mughrabi** [comment] 2016-09-12 10:17
Hitting this issue too, is there an API or alternative we could use meanwhile to push environment variables to builds? as its unpractical in our case to run 20+ builds and have to go one by one and update environment variables :/

**Comment by cyberswat** [comment] 2016-09-12 12:04
@mo-mughrabi This issue is why we chose to never to use Hashicorp's enterprise offerings.  This has been a known issue for more than a year.  It's a big deal because it stops legitimate use, and the workarounds are not practical.

**Comment by mwhooker** [comment] 2016-11-22 18:59
should be fixed now

**Closed** 2016-11-22 18:58 UTC
Labels: bug, post-processor/atlas
