### ISSUE TITLE
Unexpected EOF after build

### ISSUE THREAD

**Issue by jarbaugh5** [mitchellh/packer#4407] opened 2017-01-17 03:39 UTC
The AMI is built successfully, but Packer crashes on an EOF right after trying to delete the temporary key pair (at least the log makes it look that way).

It is an amazon-ebs build with ansible remote provisioning.

- Packer version: 0.12.1
- Host platform: Mac OS Sierra 10.12.2
- [Crash.log](https://gist.github.com/jarbaugh5/3f54e0285cebff4adf66a6ae2d568e2b)
- packer.json and ansible playbook at bottom of [crash.log gist](https://gist.github.com/jarbaugh5/3f54e0285cebff4adf66a6ae2d568e2b)

**Comment by rickard-von-essen** [comment] 2017-01-17 07:53
Stack trace

```
017/01/16 22:24:28 packer: panic(0xfc4be0, 0xc4200120c0)
2017/01/16 22:24:28 packer: 	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
2017/01/16 22:24:28 packer: github.com/mitchellh/packer/builder/amazon/ebs.(*stepCreateAMI).Run(0xc4201522a8, 0x1a1b960, 0xc42034e570, 0x0)
2017/01/16 22:24:28 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/builder/amazon/ebs/step_create_ami.go:72 +0x917
2017/01/16 22:24:28 packer: github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep.(*BasicRunner).Run(0xc4202abec0, 0x1a1b960, 0xc42034e570)
2017/01/16 22:24:28 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/vendor/github.com/mitchellh/multistep/basic_runner.go:70 +0x207
2017/01/16 22:24:28 packer: github.com/mitchellh/packer/builder/amazon/ebs.(*Builder).Run(0xc42026af00, 0x1a1e200, 0xc42033adc0, 0x1a17260, 0xc42033ea70, 0x1a1cfe0, 0xc420152260, 0xc4202d8030, 0x0, 0x0, ...)
2017/01/16 22:24:28 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/builder/amazon/ebs/builder.go:196 +0x11cb
2017/01/16 22:24:28 packer: github.com/mitchellh/packer/packer/rpc.(*BuilderServer).Run(0xc42028a480, 0x1, 0xc4202c40d0, 0x0, 0x0)
2017/01/16 22:24:28 packer: 	/Users/mwhooker/go/src/github.com/mitchellh/packer/packer/rpc/builder.go:93 +0x218
2017/01/16 22:24:28 packer: reflect.Value.call(0xc4201635c0, 0xc4201521c8, 0x13, 0x12063f7, 0x4, 0xc420543ed0, 0x3, 0x3, 0x0, 0x0, ...)
2017/01/16 22:24:28 packer: 	/usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:434 +0x5c8
2017/01/16 22:24:28 packer: reflect.Value.Call(0xc4201635c0, 0xc4201521c8, 0x13, 0xc420543ed0, 0x3, 0x3, 0x16506, 0xc420302a78, 0x1)
2017/01/16 22:24:28 packer: 	/usr/local/Cellar/go/1.7.3/libexec/src/reflect/value.go:302 +0xa4
2017/01/16 22:24:28 packer: net/rpc.(*service).call(0xc4202aa040, 0xc4202aa000, 0xc42020db68, 0xc42016d880, 0xc42028a760, 0xf16a40, 0xc4202c40cc, 0x18a, 0xeeb640, 0xc4202c40d0, ...)
2017/01/16 22:24:28 packer: 	/usr/local/Cellar/go/1.7.3/libexec/src/net/rpc/server.go:383 +0x148
2017/01/16 22:24:28 packer: created by net/rpc.(*Server).ServeCodec
2017/01/16 22:24:28 packer: /usr/local/Cellar/go/1.7.3/libexec/src/net/rpc/server.go:477 +0x421
```

**Comment by rickard-von-essen** [comment] 2017-01-17 07:57
Thanks for reporting this. This is a duplicate of #4303, which have been fixed on master. The fix will be included in the next release.

**Closed by rickard-von-essen** 2017-01-17 07:57 UTC
Labels: bug, builder/amazon, crash
